DROP TABLE EW701.E_ENV_VAR_IDNF CASCADE CONSTRAINTS;

CREATE TABLE EW701.E_ENV_VAR_IDNF
(
  SEQ_ID                     NUMBER(22)         NOT NULL,
  ENV_SEQ_ID                 NUMBER(22)         NOT NULL,
  EOB_IDNF_RANGE_NM          NUMBER(10),
  CED_DEFAULT_LIB_TYPE       NUMBER(1),
  EOB_DEFAULT_LIB_TYPE       NUMBER(1),
  W_FRQ_RANGE                NUMBER(3),
  W_FRQ_EXP_RANGE            NUMBER(3),
  W_FRQ_MOD_PRD              NUMBER(3),
  W_FRQ_MOD_POS_CNT          NUMBER(3),
  W_FRQ_MOD_ELMT             NUMBER(3),
  W_FRQ_MAIN_OBS_VAL         NUMBER(3),
  W_PRI_RANGE                NUMBER(3),
  W_PRI_EXP_RANGE            NUMBER(3),
  W_PRI_MOD_PRD              NUMBER(3),
  W_PRI_MOD_POS_CNT          NUMBER(3),
  W_PRI_MOD_ELMT             NUMBER(3),
  W_PRI_DIFF_IN_GRP          NUMBER(3),
  W_PRI_MAIN_OBS_VAL         NUMBER(3),
  W_PA_DIFF_IN_GRP           NUMBER(3),
  W_SCAN_TYPE                NUMBER(3),
  W_SCAN_PRD                 NUMBER(3),
  W_INTRA_MOD_TYPE           NUMBER(3),
  M_FRQ_ERR                  NUMBER(3),
  M_PRI_ERR                  NUMBER(3),
  M_PW_ERR                   NUMBER(3),
  M_ERR_RTO_CMP_PW           NUMBER(3),
  M_FRQ_MOD_PRD_ERR_RTO      NUMBER(3),
  M_PRI_MOD_PRD_ERR_RTO      NUMBER(3),
  M_MIN_RQD_FRQ_RNG_NST_RTO  NUMBER(3),
  M_MIN_RQD_PRI_RNG_NST_RTO  NUMBER(3),
  M_PA_ERR_IN_PLS_GRP        NUMBER(3),
  M_SCAN_PRD_ERR_RTO         NUMBER(3)
)
TABLESPACE EW701
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE TRIGGER EW701.AUTO_TRG_E_ENV_VAR_IDNF 
BEFORE INSERT ON EW701.E_ENV_VAR_IDNF
FOR EACH ROW
BEGIN
    SELECT AUTO_E_ENV_VAR_IDNF.NEXTVAL
    INTO :NEW.SEQ_ID
    FROM DUAL;
END;
/
