DROP TABLE EW701.E_ENV_VAR_RPT CASCADE CONSTRAINTS;

CREATE TABLE EW701.E_ENV_VAR_RPT
(
  SEQ_ID         NUMBER(22)                     NOT NULL,
  ENV_SEQ_ID     NUMBER(22)                     NOT NULL,
  IS_USE         NUMBER(1),
  PIN_NUM        NUMBER(10),
  NATIONALITY    VARCHAR2(5 BYTE),
  SEND_PRIORITY  VARCHAR2(12 BYTE),
  ADDRESSEE      VARCHAR2(22 BYTE),
  DISTRIBUTOR    VARCHAR2(22 BYTE),
  RPT_TYPE       VARCHAR2(2 BYTE),
  ELNOT          VARCHAR2(7 BYTE)
)
TABLESPACE EW701
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE OR REPLACE TRIGGER EW701.AUTO_TRG_E_ENV_VAR_RPT 
BEFORE INSERT ON EW701.E_ENV_VAR_RPT
FOR EACH ROW
BEGIN
    SELECT AUTO_E_ENV_VAR_RPT.NEXTVAL
    INTO :NEW.SEQ_ID
    FROM DUAL;
END;
/
