ALTER TABLE EW701.E_PRF_STORE_DATA
 DROP PRIMARY KEY CASCADE;

DROP TABLE EW701.E_PRF_STORE_DATA CASCADE CONSTRAINTS;

CREATE TABLE EW701.E_PRF_STORE_DATA
(
  PRF_STORE_ID     NUMBER(10)                   NOT NULL,
  TASK_ID          VARCHAR2(22 BYTE),
  SEARCH_BAND_ID   NUMBER(5),
  STORETIME        TIMESTAMP(9),
  CREATE_TIME      TIMESTAMP(9),
  FILE_NAME        VARCHAR2(100 BYTE),
  FILE_LOCATION    VARCHAR2(300 BYTE),
  FILE_SIZE        NUMBER(10),
  START_FREQUENCY  NUMBER,
  END_FREQUENCY    NUMBER
)
TABLESPACE EW701
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE EW701.E_PRF_STORE_DATA IS 'PRF저장데이터';

COMMENT ON COLUMN EW701.E_PRF_STORE_DATA.PRF_STORE_ID IS 'PRF저장번호';

COMMENT ON COLUMN EW701.E_PRF_STORE_DATA.TASK_ID IS '과제ID';

COMMENT ON COLUMN EW701.E_PRF_STORE_DATA.SEARCH_BAND_ID IS '탐색밴드ID';

COMMENT ON COLUMN EW701.E_PRF_STORE_DATA.STORETIME IS '저장시각';

COMMENT ON COLUMN EW701.E_PRF_STORE_DATA.CREATE_TIME IS '생성시각';

COMMENT ON COLUMN EW701.E_PRF_STORE_DATA.FILE_NAME IS '저장파일명';

COMMENT ON COLUMN EW701.E_PRF_STORE_DATA.FILE_LOCATION IS '저장파일위치';

COMMENT ON COLUMN EW701.E_PRF_STORE_DATA.FILE_SIZE IS '파일크기';


CREATE UNIQUE INDEX EW701.PK_E_PRF_STORE_DATA ON EW701.E_PRF_STORE_DATA
(PRF_STORE_ID)
LOGGING
TABLESPACE EW701
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE TRIGGER EW701.AUTO_TRG_E_PRF_STORE_DATA 
BEFORE INSERT ON EW701.E_PRF_STORE_DATA
FOR EACH ROW
BEGIN
    SELECT AUTO_E_PRF_STORE_DATA.NEXTVAL
    INTO :NEW.PRF_STORE_ID
    FROM DUAL;
END;
/


ALTER TABLE EW701.E_PRF_STORE_DATA ADD (
  CONSTRAINT PK_E_PRF_STORE_DATA
  PRIMARY KEY
  (PRF_STORE_ID)
  USING INDEX EW701.PK_E_PRF_STORE_DATA
  ENABLE VALIDATE);
