DROP VIEW EW701.VEL_RADARMODE_LIST;

/* Formatted on 2018/11/28 09:47:59 (QP5 v5.269.14213.34769) */
CREATE OR REPLACE FORCE VIEW EW701.VEL_RADARMODE_LIST
(
   ELNOT,
   NICKNAME,
   RADAR_PRIORITY,
   STATUS,
   TIME_INACTIVATED,
   
   WEAPON_SYS,
   PLATFORM,
   
   RADAR_MODE_NAME,
   MODE_CODE,
   PLATFORM_TYPE,
  
   FUNCTION_CODE,
   MODULATION_CODE,
   SIGNAL_TYPE,
   POLARIZATION,
   
   RF_LEGACY_TYPE,
   PRI_LEGACY_TYPE,
   VALIDATION,
   RF_TYPICAL_MIN,
   RF_TYPICAL_MAX,
   PRI_TYPICAL_MIN,
   PRI_TYPICAL_MAX,
   PD_TYPICAL_MIN,
   PD_TYPICAL_MAX,
   SCAN_PRIMARY_TYPICAL_MIN,
   SCAN_PRIMARY_TYPICAL_MAX,
   SCAN_PRIMARY_TYPE,
   RF_CONTINUITY,
   /* ????v????    */
   RF_COHERENCY,
   RF_PATTERN,
   RF_PATTERN_PERIOD_MIN,
   RF_PATTERN_PERIOD_MAX,
   RF_NUM_ELEMENTS,
   RF_NUM_POSITIONS,
   RF_TYPE,
   
   PRI_CONTINUITY,
   /* PRI?v????    */
   PRI_PATTERN,
   PRI_NUM_POSITIONS,
   PRI_NUM_ELEMENTS,
   PRI_PATTERN_PERIOD_MIN,
   PRI_PATTERN_PERIOD_MAX,
   PRI_SUBFRAME_PERIOD_MIN,
   PRI_SUBFRAME_PERIOD_MAX,
   PRI_FRAME_PERIOD_MIN,
   PRI_FRAME_PERIOD_MAX,
   PRI_PPG_MIN,
   PRI_PPG_MAX,
   PRI_TYPE,
   
   PD_CONTINUITY,
   PD_PATTERN,
   PD_NUM_POSITIONS,
   PD_NUM_ELEMENTS,
   PD_PATTERN_PERIOD_MIN,
   PD_PATTERN_PERIOD_MAX,
   
   RADAR_INDEX,
   RADAR_MODE_INDEX,
   PRIORITY,
   
   MOP_CW_MODULATION_TYPE,
   MOP_CW_LEGACY_TYPE,
   MANUAL_REVISION,
   ACCEPTED
)
AS
   SELECT A.ELNOT,
          A.NICKNAME,
          A.PRIORITY,
          A.STATUS,
          A.TIME_INACTIVATED,
          
          E.WEAPON_SYS,
          G.PLATFORM,
          
          C.RADAR_MODE_NAME,
          C.MODE_CODE,
          B.PLATFORM,
          
          B.FUNCTION_CODE,
          B.MODULATION_CODE,
          B.SIGNAL_TYPE,
          B.POLARIZATION,
          
          B.RF_LEGACY_TYPE,
          B.PRI_LEGACY_TYPE,
          B.VALIDATION,
          B.RF_TYPICAL_MIN,
          B.RF_TYPICAL_MAX,
          B.PRI_TYPICAL_MIN,
          B.PRI_TYPICAL_MAX,
          B.PD_TYPICAL_MIN,
          B.PD_TYPICAL_MAX,
          B.SCAN_PRIMARY_TYPICAL_MIN,
          B.SCAN_PRIMARY_TYPICAL_MAX,
          B.SCAN_PRIMARY_TYPE,
          B.RF_CONTINUITY,
          B.RF_COHERENCY,
          B.RF_PATTERN,
          B.RF_PATTERN_PERIOD_MIN,
          B.RF_PATTERN_PERIOD_MAX,
          B.RF_NUM_ELEMENTS,
          B.RF_NUM_POSITIONS,
          B.RF_TYPE,
          
          B.PRI_CONTINUITY,
          B.PRI_PATTERN,
          B.PRI_NUM_POSITIONS,
          B.PRI_NUM_ELEMENTS,
          B.PRI_PATTERN_PERIOD_MIN,
          B.PRI_PATTERN_PERIOD_MAX,
          B.PRI_SUBFRAME_PERIOD_MIN,
          B.PRI_SUBFRAME_PERIOD_MAX,
          B.PRI_FRAME_PERIOD_MIN,
          B.PRI_FRAME_PERIOD_MAX,
          B.PRI_PPG_MIN,
          B.PRI_PPG_MAX,
          B.PRI_TYPE,
          
          B.PD_CONTINUITY,
          B.PD_PATTERN,
          B.PD_NUM_POSITIONS,
          B.PD_NUM_ELEMENTS,
          B.PD_PATTERN_PERIOD_MIN,
          B.PD_PATTERN_PERIOD_MAX,
          
          A.RADAR_INDEX,
          B.RADAR_MODE_INDEX,
          B.PRIORITY,
          
          H.MOP_CW_MODULATION_TYPE,
          H.MOP_CW_LEGACY_TYPE,
          B.MANUAL_REVISION,
          B.ACCEPTED
     FROM RADAR A,
          RADAR_MODE B,
          RADAR_MODE_LIFECYCLE C,
          ASSOC_WEAP_SYS D,
          WEAPON_SYSTEM E,
          ASSOC_PLATFORM F,
          PLATFORM G,
          RADAR_MOP_CW H
                    
    WHERE     A.RADAR_INDEX = C.RADAR_INDEX(+)
          AND C.RADAR_MODE_INDEX = B.RADAR_MODE_INDEX
          AND A.RADAR_INDEX = D.RADAR_INDEX(+)
          AND D.WEAPON_INDEX = E.WEAPON_INDEX(+)
          AND A.RADAR_INDEX = F.RADAR_INDEX(+)
          AND F.PLATFORM_INDEX = G.PLATFORM_INDEX(+)
          AND H.RADAR_MODE_INDEX(+) = B.RADAR_MODE_INDEX
          AND H.MOP_CW_INDEX(+) = 1;
