DECLARE
    nCnt NUMBER;
BEGIN

    SELECT COUNT(*) INTO nCnt FROM ALL_TABLES WHERE TABLE_NAME = 'E_AA_MSG_LOB';
    if nCnt > 0 then execute immediate 'DROP TABLE EW701.E_AA_MSG_LOB';
    end if;
   

       
END;

DROP TABLE EW701.CEF_META_INFO CASCADE CONSTRAINTS;

CREATE TABLE EW701.CEF_META_INFO
(
  MISSION_ID        VARCHAR2(22 BYTE),
  CEQUIPMENTTYPE    NUMBER(5),
  SZTASKID          VARCHAR2(22 BYTE)           NOT NULL,
  UCNUMLIST         NUMBER(5)                   NOT NULL,
  UCRECVID          NUMBER(5)                   NOT NULL,
  UIMETADATACLASS   NUMBER(20),
  UCFREQSTART       NUMBER(20),
  USTYPEMODULATION  NUMBER(10),
  UIRATESYMBOL      NUMBER(20),
  CSIGLEVEL         NUMBER(5),
  UISEARCHBW        NUMBER(10),
  CGAIN             NUMBER(10),
  STRFILENAME       VARCHAR2(200 BYTE),
  UCENDIAN          NUMBER(5),
  UCSAMPLERATE      NUMBER(5),
  UCBYTESIZE        NUMBER(5),
  UISTORAGEKINDS    NUMBER(10),
  IACQSTARTTIME     TIMESTAMP(9),
  IACQENDTIME       TIMESTAMP(9),
  UIFILECOUNT       NUMBER(30),
  SZFILESIZE        VARCHAR2(30 BYTE),
  UCONOFFSTATUS     NUMBER(1),
  UCLOCALSAVE       NUMBER(1),
  SZEXTRAINFO       VARCHAR2(30 BYTE),
  UCLINKNO          NUMBER(1),
  TASK_NAME	    VARCHAR2(32 BYTE)

)
TABLESPACE EW701
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;
