DECLARE
    nCnt NUMBER;
BEGIN

    SELECT COUNT(*) INTO nCnt FROM ALL_TABLES WHERE TABLE_NAME = 'CEF_FILE_PATH';
    if nCnt > 0 then execute immediate 'DROP TABLE EW701.CEF_FILE_PATH';
    end if;
   

       
END;


CREATE TABLE EW701.CEF_FILE_PATH
(
  EQUIP_TYPE  VARCHAR2(10 BYTE),
  ITEM_INFO   VARCHAR2(20 BYTE),
  FILE_PATH   VARCHAR2(60 BYTE),
  ITEM_NAME   VARCHAR2(65 BYTE)
);


Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMMON', '2525B', '\\192.168.0.60\Files\COMMON\2525B');
   
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('PDE', 'RAW_IMAGE', '\\192.168.0.60\Files\PDE\RAW');  
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('ELINT', 'EL_DOWNLOAD', '\\192.168.0.60\Files\ELINT\DOWNLOAD');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMINT', 'CM_NB_SPTR', '\\192.168.0.60\Files\COMINT\NB_SPTR');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMINT', 'CM_DMODE_IQ', '\\192.168.0.60\Files\COMINT\DMODE_IQ');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMINT', 'CM_DMODE_DIG', '\\192.168.0.60\Files\COMINT\DMODE_DIG');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMINT', 'CM_DMODE_AUDIO', '\\192.168.0.60\Files\COMINT\DMODE_AUDIO');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMINT', 'CM_WB_FH', '\\192.168.0.60\Files\COMINT\WB_FH');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMINT', 'CM_WB_REC', '\\192.168.0.60\Files\COMINT\WB_REC');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMINT', 'CM_WB_ACQ', '\\192.168.0.60\Files\COMINT\WB_ACQ');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMINT', 'CM_WB_SPTR', '\\192.168.0.60\Files\COMINT\WB_SPTR');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('ELINT', 'EL_PRF_AUDIO', '\\192.168.0.60\Files\ELINT\PRF_AUDIO');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('ELINT', 'EL_PRF', '\\192.168.0.60\Files\ELINT\PRF');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('ELINT', 'EL_WB_PDW', '\\192.168.0.60\Files\ELINT\WB_PDW');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('ELINT', 'EL_PDW', '\\192.168.0.60\Files\ELINT\PDW');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('ELINT', 'EL_IQ', '\\192.168.0.60\Files\ELINT\IQ');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('ELINT', 'EL_IF', '\\192.168.0.60\Files\ELINT\IF');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('ELINT', 'EL_SPTR', '\\192.168.0.60\Files\ELINT\SPTR');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('FISINT', 'FS_DMODE_DIG', '\\192.168.0.60\Files\FISINT\DMODE_DIG');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('FISINT', 'FS_TONE', '\\192.168.0.60\Files\FISINT\TONE');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('FISINT', 'FS_WB_SPTR', '\\192.168.0.60\Files\FISINT\WB_SPTR');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('FISINT', 'FS_NB_SPTR', '\\192.168.0.60\Files\FISINT\NB_SPTR');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMINT', 'CM_NB_OFFLINE_IQ', '\\192.168.0.60\Files\COMINT\NB_OFFLINE_IQ');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('ELINT', 'EL_REPORT', '\\192.168.0.60\Files\ELINT\REPORT');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMINT', 'CM_REPORT', '\\192.168.0.60\Files\COMINT\REPORT');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('FISINT', 'FS_OFFLINE', '\\192.168.0.60\Files\FISINT\OffLineIF');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('FISINT', 'FS_ONLINE_IF', '\\192.168.0.60\Files\FISINT\IF');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('FISINT', 'FS_REPORT', '\\192.168.0.60\Files\FISINT\REPORT');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMINT', 'CM_SELF_ACQ_MODE2', '\\192.168.0.60\Files\StandAlone2');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('PDE', 'JP2_IMAGE', '\\192.168.0.60\Files\PDE\JP2');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('COMINT', 'CM_SELF_ACQ_MODE', '\\192.168.0.60\Files\StandAlone');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('FISINT', 'FS_ONLINE_IF_FOLDER', '\\192.168.0.60\Files\FISINT\IF');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('PDE', 'RAW_IMAGE_FOLDER', '\\192.168.0.60\Files\PDE\RAW');
Insert into EW701.CEF_FILE_PATH
   (EQUIP_TYPE, ITEM_INFO, FILE_PATH)
 Values
   ('PDE', 'JP2_IMAGE_FOLDER', '\\192.168.0.60\Files\PDE\JP2');
COMMIT;

