DROP VIEW EW701.VEL_RADAR_LIST;

CREATE OR REPLACE FORCE VIEW EW701.VEL_RADAR_LIST
(
   ELNOT,
   NICKNAME,
   FUNCTION_CODE,
   RADAR_PRIORITY,
   STATUS,
   
   RF_TYPICAL_MIN,
   RF_TYPICAL_MAX,
   PRI_TYPICAL_MIN,
   PRI_TYPICAL_MAX,
   WEAPON_SYS,
   PLATFORM,
   RADAR_INDEX
)
AS
   SELECT A.ELNOT,
          A.NICKNAME,
          A.FUNCTION_CODE,
          A.PRIORITY,
          A.STATUS,
          
          B.RF_TYPICAL_MIN,
          B.RF_TYPICAL_MAX,
          B.PRI_TYPICAL_MIN,
          B.PRI_TYPICAL_MAX,
          E.WEAPON_SYS,
          G.PLATFORM,
          A.RADAR_INDEX
     FROM RADAR A,
          RADAR_MODE B,
          RADAR_MODE_LIFECYCLE C,
          ASSOC_WEAP_SYS D,
          WEAPON_SYSTEM E,
          ASSOC_PLATFORM F,
          PLATFORM G
    WHERE     A.RADAR_INDEX = C.RADAR_INDEX(+)
          AND C.RADAR_MODE_INDEX = B.RADAR_MODE_INDEX(+)
          AND A.RADAR_INDEX = D.RADAR_INDEX(+)
          AND D.WEAPON_INDEX = E.WEAPON_INDEX(+)
          AND A.RADAR_INDEX = F.RADAR_INDEX(+)
          AND F.PLATFORM_INDEX = G.PLATFORM_INDEX(+);
