DECLARE
    nCnt NUMBER;
BEGIN

    SELECT COUNT(*) INTO nCnt FROM ALL_TABLES WHERE TABLE_NAME = 'E_MSG_PDW_DATA';
    if nCnt > 0 then execute immediate 'DROP TABLE EW701.E_MSG_PDW_DATA';
    end if;
		
    SELECT COUNT(*) INTO nCnt FROM ALL_TABLES WHERE TABLE_NAME = 'E_PDW_IQ_IF_LIST';
    if nCnt > 0 then execute immediate 'DROP TABLE EW701.E_PDW_IQ_IF_LIST';
    end if;
  		
  
       
END;


CREATE TABLE EW701.E_MSG_PDW_DATA
(
    PDW_SET_ID          NUMBER(22)                  NOT NULL,
    MSG_AET_ID          VARCHAR2(22 BYTE),
    DTCT_SIG_ID         VARCHAR2(22 BYTE),
    TASK_ID             VARCHAR2(22 BYTE)           NOT NULL,
    SEARCH_BAND_ID      NUMBER(5)                   NOT NULL,
    CREATE_TIME         TIMESTAMP(9),
    NUM_PDW             NUMBER(15),
    FILE_NAME           VARCHAR2(100 BYTE),
    FILE_LOCATION       VARCHAR2(300 BYTE),
    FILE_SIZE           NUMBER(10),
    LINK_NUM            NUMBER(1),
    TRIAL_NUM           NUMBER,
    AET_ID              NUMBER,
    LOB_ID              NUMBER,
    LOB_ACQ_TIME        TIMESTAMP(9),

    FRQ_AVG         	NUMBER,
    TASK_NAME       	VARCHAR2(40 BYTE),
    MISSION_ID      	VARCHAR2(22 BYTE),
    MISSION_NAME    	VARCHAR2(40 BYTE),
    ABT_ID         	    NUMBER

    /* FATHER_FILE_NAME    VARCHAR2(100 BYTE) */
  
);


COMMENT ON TABLE EW701.E_MSG_PDW_DATA IS 'PDW데이터전송메시지';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.PDW_SET_ID IS 'PDW세트번호,,,,,,,';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.MSG_AET_ID IS 'AET메시지ID,,,,,,MSG_AET_ID';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.DTCT_SIG_ID IS '탐지신호ID,,,,,,DTCT_SIG_ID';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.TASK_ID IS '과제ID,,,,,o,TASK_ID';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.SEARCH_BAND_ID IS '탐색대역ID,,0,0,65534,,';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.CREATE_TIME IS '저장시각,,,,,,';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.NUM_PDW IS 'PDW개수,,1,1,1000000,,';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.FILE_NAME IS '저장파일명,,,,,,';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.FILE_LOCATION IS '저장파일위치,,,,,,';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.FILE_SIZE IS '파일크기(Bytes),,10,1,1000000,,';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.LINK_NUM IS '링크번호,,1,1,2,,';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.TRIAL_NUM IS '시험수,,,,,,,,';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.AET_ID IS 'AETID,,,,,,,,,';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.LOB_ID IS 'LOBID,,,,,,,,,';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.LOB_ACQ_TIME IS '신호수집시간';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.FRQ_AVG IS '평균 주파수';

COMMENT ON COLUMN EW701.E_MSG_PDW_DATA.TASK_NAME IS '과제명';


CREATE INDEX EW701.IDX_E_MSG_PDW_DATA ON EW701.E_MSG_PDW_DATA
(SEARCH_BAND_ID)
LOGGING
TABLESPACE EW701
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;








CREATE TABLE EW701.E_PDW_IQ_IF_LIST
(
  PDW_SET_ID          VARCHAR2(22 BYTE),
  TASK_ID             VARCHAR2(22 BYTE),
  SEARCH_BAND_ID      VARCHAR2(22 BYTE),
  LINK_NUM            VARCHAR2(22 BYTE),
  AET_ID              VARCHAR2(22 BYTE),
  LOB_ID              VARCHAR2(22 BYTE),
  NUM_OF_DATA         VARCHAR2(22 BYTE),
  PDW_ID              VARCHAR2(22 BYTE),
  DATA_TYPE           VARCHAR2(22 BYTE),
  AVR_DTOA            VARCHAR2(22 BYTE),
  SIG_TYPE            VARCHAR2(22 BYTE),
  BIT_FLAG            VARCHAR2(22 BYTE),
  FMOP_FLAG           VARCHAR2(22 BYTE),
  PMOP_FLAG           VARCHAR2(22 BYTE),
  BLANKING_TAG        VARCHAR2(22 BYTE),
  CH_CHANGE_POP       VARCHAR2(22 BYTE),
  BLK                 VARCHAR2(22 BYTE),
  DI_VALID            VARCHAR2(22 BYTE),
  FOV_FLAG            VARCHAR2(22 BYTE),
  CH_NO               VARCHAR2(22 BYTE),
  PA_MEAN             VARCHAR2(22 BYTE),
  FRQ_MEAN            VARCHAR2(22 BYTE),
  DOA_MEAN            VARCHAR2(22 BYTE),
  POLARIZATION        VARCHAR2(22 BYTE),
  PPT_TAG             VARCHAR2(22 BYTE),
  PW_MEAN             VARCHAR2(22 BYTE),
  I_DATA              VARCHAR2(22 BYTE),
  Q_DATA              VARCHAR2(22 BYTE),
  PRF_SET_ID          VARCHAR2(22 BYTE),
  SPECTRUM_SET_ID     VARCHAR2(22 BYTE),
  RAW_DATA_ID         VARCHAR2(22 BYTE)         NOT NULL,
  PULSE_ARRIVAL_TIME  VARCHAR2(23 BYTE),
  DTCT_ID             VARCHAR2(22 BYTE),
  FILE_NAME           VARCHAR2(250 BYTE),
  MISSION_ID          VARCHAR2(22 BYTE),
  TASK_NAME           VARCHAR2(60 BYTE),
  SEQ_NUM             NUMBER,
  ABT_ID              NUMBER
);

COMMENT ON TABLE EW701.E_PDW_IQ_IF_LIST IS 'PDW/IQ/IF목록창';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.PDW_SET_ID IS 'PDWSetID';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.TASK_ID IS '과제ID';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.SEARCH_BAND_ID IS '탐색밴드ID';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.LINK_NUM IS 'SDFID';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.NUM_OF_DATA IS '데이터개수';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.PDW_ID IS 'PDWID';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.DATA_TYPE IS '데이터형식';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.AVR_DTOA IS 'TOA';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.BIT_FLAG IS 'BITFlag';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.FMOP_FLAG IS 'FMOPFlag';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.PMOP_FLAG IS 'PMOPFlag';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.BLANKING_TAG IS 'BlankingTag';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.CH_CHANGE_POP IS '채널변경여부';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.BLK IS '채널변경방향';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.DI_VALID IS 'DI';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.FOV_FLAG IS 'FOV Flag';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.CH_NO IS 'CH번호';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.POLARIZATION IS '신호극성';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.PPT_TAG IS 'PPFTag';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.I_DATA IS 'I데이터';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.Q_DATA IS 'Q데이터';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.PRF_SET_ID IS 'PRFSetID';

COMMENT ON COLUMN EW701.E_PDW_IQ_IF_LIST.SPECTRUM_SET_ID IS 'SptrSetID';

CREATE UNIQUE INDEX EW701.PK_E_PDW_IQ_IF_LIST ON EW701.E_PDW_IQ_IF_LIST
(RAW_DATA_ID)
LOGGING
TABLESPACE EW701
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE TRIGGER EW701.AUTO_E_PDWIQ    
BEFORE INSERT ON EW701.E_PDW_IQ_IF_LIST
FOR EACH ROW
BEGIN
    SELECT AUTO_E_PDW_IQ_IF_LIST.NEXTVAL
    INTO :NEW.SEQ_NUM
    FROM DUAL;
END;
/


ALTER TABLE EW701.E_PDW_IQ_IF_LIST ADD (
  CONSTRAINT PK_E_PDW_IQ_IF_LIST
  PRIMARY KEY
  (RAW_DATA_ID)
  USING INDEX EW701.PK_E_PDW_IQ_IF_LIST
  ENABLE VALIDATE);