set timing on

drop index INDEX_RADAR_MODE;
CREATE INDEX EW701.INDEX_RADAR_MODE ON EW701.RADAR_MODE(RADAR_MODE_INDEX);

drop index INDEX_RADAR_MODE_P;
CREATE INDEX EW701.INDEX_RADAR_MODE_P ON EW701.RADAR_MODE_P(RADAR_MODE_INDEX);
