set timing on

drop index INDEX_E_AA_MSG_LOB;
drop index INDEX_E_AA_MSG_LOB2;
create index INDEX_E_AA_MSG_LOB on E_AA_MSG_LOB(MISSION_ID,SEQ_NUM,LOB_ID);
/*create index INDEX_E_AA_MSG_LOB2 on E_AA_MSG_LOB(MISSION_ID,ABT_ID);   */

/*
CREATE INDEX EW701.INDEX_E_AA_MSG_LOB ON EW701.E_AA_MSG_LOB
(SEQ_NUM, LOB_ID)
LOGGING
TABLESPACE EW701
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX EW701.INDEX_E_AA_MSG_LOB2 ON EW701.E_AA_MSG_LOB
(MISSION_ID, ABT_ID)
LOGGING
TABLESPACE EW701
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
*/


drop index INDEX_E_AA_MSG_LOB_ELMT_LIST;
create index INDEX_E_AA_MSG_LOB_ELMT_LIST on E_AA_MSG_LOB_ELMT_LIST(MISSION_ID,SEQ_NUM,LOB_ID);

/*
drop index INDEX_E_AA_MSG_LOB_LINK2;
drop index INDEX_E_AA_MSG_LOB2_LINK2;
create index INDEX_E_AA_MSG_LOB_LINK2 on E_AA_MSG_LOB_LINK2(SEQ_NUM,LOB_ID);
create index INDEX_E_AA_MSG_LOB2_LINK2 on E_AA_MSG_LOB_LINK2(MISSION_ID,ABT_ID);
*/

/*
drop index INDEX_E_AA_GMI_BEAM;
create index INDEX_E_AA_GMI_BEAM on E_AA_GMI_BEAM(SEQ_NUM,ABT_ID);

drop index INDEX_E_AA_GMI_EMITTER;
create index INDEX_E_AA_GMI_EMITTER on E_AA_GMI_EMITTER(SEQ_NUM,AET_ID);	*/


drop index INDEX_E_AA_GMI_BEAM;
drop index INDEX_E_AA_GMI_BEAM2;
CREATE INDEX EW701.INDEX_E_AA_GMI_BEAM ON EW701.E_AA_GMI_BEAM(SEQ_NUM, MISSION_ID);
CREATE INDEX EW701.INDEX_E_AA_GMI_BEAM2 ON EW701.E_AA_GMI_BEAM(AET_ID, ABT_ID, MISSION_ID);

/*
CREATE INDEX EW701.INDEX_E_AA_GMI_BEAM ON EW701.E_AA_GMI_BEAM
(SEQ_NUM, AET_ID, ABT_ID, MISSION_ID)
LOGGING
TABLESPACE EW701
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
*/

drop index INDEX_E_AA_GMI_BEAM_ELMT_LIST;
drop index INDEX_E_AA_GMI_BEAM_ELMT_LIST2;
CREATE INDEX EW701.INDEX_E_AA_GMI_BEAM_ELMT_LIST ON E_AA_GMI_BEAM_ELMT_LIST(SEQ_NUM, MISSION_ID);
CREATE INDEX EW701.INDEX_E_AA_GMI_BEAM_ELMT_LIST2 ON E_AA_GMI_BEAM_ELMT_LIST(AET_ID, ABT_ID, MISSION_ID);

/*
CREATE INDEX EW701.INDEX_E_AA_GMI_BEAM_ELMT_LIST ON EW701.E_AA_GMI_BEAM_ELMT_LIST
(AET_ID, ABT_ID, MISSION_ID)
LOGGING
TABLESPACE EW701
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );
*/		   

drop index INDEX_E_AA_GMI_EMITTER;
drop index INDEX_E_AA_GMI_EMITTER2;
CREATE INDEX EW701.INDEX_E_AA_GMI_EMITTER ON EW701.E_AA_GMI_EMITTER(SEQ_NUM, MISSION_ID);
CREATE INDEX EW701.INDEX_E_AA_GMI_EMITTER2 ON EW701.E_AA_GMI_EMITTER(AET_ID, MISSION_ID);

/*

CREATE INDEX EW701.INDEX_E_AA_GMI_EMITTER ON EW701.E_AA_GMI_EMITTER
(SEQ_NUM, AET_ID, MISSION_ID)
LOGGING
TABLESPACE EW701
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

*/		   


