DECLARE
    nCnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO nCnt FROM ALL_TABLES WHERE TABLE_NAME = 'THREAT';
    if nCnt > 0 then execute immediate 'DROP TABLE EW701.THREAT';
    end if;
    SELECT COUNT(*) INTO nCnt FROM ALL_TABLES WHERE TABLE_NAME = 'THREAT_P';
    if nCnt > 0 then execute immediate 'DROP TABLE EW701.THREAT_P';
    end if;
    SELECT COUNT(*) INTO nCnt FROM ALL_TABLES WHERE TABLE_NAME = 'DEVICE';
    if nCnt > 0 then execute immediate 'DROP TABLE EW701.DEVICE';
    end if;
    SELECT COUNT(*) INTO nCnt FROM ALL_TABLES WHERE TABLE_NAME = 'DEVICE_P';
    if nCnt > 0 then execute immediate 'DROP TABLE EW701.DEVICE_P';
    end if;
END;
CREATE TABLE EW701.THREAT
(
  THREAT_INDEX      NUMBER                      NOT NULL,
  PIN               NUMBER UNIQUE               NOT NULL,
  BE_NUMBER         CHAR(10 BYTE),
  FACILITY_NAME     VARCHAR2(50 BYTE),
  PLACE_NAME_KOR    VARCHAR2(50 BYTE),
  PLACE_NAME_ENG    VARCHAR2(50 BYTE),
  USER_COUNTRY      CHAR(2 BYTE),
  PRIMARY_FUNCTION  CHAR(2 BYTE),
  FRIEND_OR_FOE     VARCHAR2(10 BYTE),
  PRIORITY          NUMBER,
  ADA               CHAR(6 BYTE),
  CATEGORY          NUMBER,
  STATUS            CHAR(1 BYTE),
  DTC               TIMESTAMP(6),
  DTLI              TIMESTAMP(6),
  DTFI              TIMESTAMP(6),
  PLATFORM          NUMBER,
  DISTINCTION       VARCHAR2(10 BYTE),
  SYMBOL_CODE       VARCHAR2(30 BYTE),
  LATITUDE          CHAR(7 BYTE),
  LONGITUDE         CHAR(8 BYTE),
  PRIMARY KEY (THREAT_INDEX)
);
CREATE TABLE EW701.THREAT_P
(
  THREAT_INDEX      NUMBER                      NOT NULL,
  PIN               NUMBER UNIQUE               NOT NULL,
  BE_NUMBER         CHAR(10 BYTE),
  FACILITY_NAME     VARCHAR2(50 BYTE),
  PLACE_NAME_KOR    VARCHAR2(50 BYTE),
  PLACE_NAME_ENG    VARCHAR2(50 BYTE),
  USER_COUNTRY      CHAR(2 BYTE),
  PRIMARY_FUNCTION  CHAR(2 BYTE),
  FRIEND_OR_FOE     VARCHAR2(10 BYTE),
  PRIORITY          NUMBER,
  ADA               CHAR(6 BYTE),
  CATEGORY          NUMBER,
  STATUS            CHAR(1 BYTE),
  DTC               TIMESTAMP(6),
  DTLI              TIMESTAMP(6),
  DTFI              TIMESTAMP(6),
  PLATFORM          NUMBER,
  DISTINCTION       VARCHAR2(10 BYTE),
  SYMBOL_CODE       VARCHAR2(30 BYTE),
  LATITUDE          CHAR(7 BYTE),
  LONGITUDE         CHAR(8 BYTE),
  PRIMARY KEY (THREAT_INDEX)
);
CREATE TABLE EW701.DEVICE
(
  THREAT_INDEX          NUMBER                      NOT NULL,
  DEVICE_INDEX          NUMBER                      NOT NULL,
  ELNOT                 VARCHAR2(15 BYTE),
  DEVICE_NAME           VARCHAR2(50 BYTE),
  STATUS                CHAR(1 BYTE),
  IDENTIFICATION_RANGE  NUMBER,
  LATITUDE              VARCHAR2(13 BYTE),
  LONGITUDE             VARCHAR2(14 BYTE),
  ELEVATION             NUMBER,
  
  LATITUDE_NUM          NUMBER,
  LONGITUDE_NUM         NUMBER,  
  PRIMARY KEY (THREAT_INDEX, DEVICE_INDEX)
);
CREATE TABLE EW701.DEVICE_P
(
  THREAT_INDEX          NUMBER                      NOT NULL,
  DEVICE_INDEX          NUMBER                      NOT NULL,
  ELNOT                 CHAR(5 BYTE),
  DEVICE_NAME           VARCHAR2(50 BYTE),
  STATUS                CHAR(1 BYTE),
  IDENTIFICATION_RANGE  NUMBER,
  LATITUDE              VARCHAR2(13 BYTE),
  LONGITUDE             VARCHAR2(14 BYTE),
  ELEVATION             NUMBER,
  
  LATITUDE_NUM          NUMBER,
  LONGITUDE_NUM         NUMBER,    
  PRIMARY KEY (THREAT_INDEX, DEVICE_INDEX)
);