TRUNCATE TABLE EW701.RADAR;

TRUNCATE TABLE EW701.RADAR_COMMENTS;

TRUNCATE TABLE EW701.WEAPON_SYSTEM;
TRUNCATE TABLE EW701.ASSOC_WEAP_SYS;
TRUNCATE TABLE EW701.PLATFORM;
TRUNCATE TABLE EW701.ASSOC_PLATFORM;
TRUNCATE TABLE EW701.ASSOC_ELNOT;
TRUNCATE TABLE EW701.PARAM_SET_ASSOCIATIONS;
TRUNCATE TABLE EW701.RADAR_MODE;
TRUNCATE TABLE EW701.RADAR_MODE_COMMENTS;
TRUNCATE TABLE EW701.RADAR_MODE_LIFECYCLE;
TRUNCATE TABLE EW701.RADAR_PD_VALUES;
TRUNCATE TABLE EW701.RADAR_PD_SEQUENCE_NAME;
TRUNCATE TABLE EW701.RADAR_PD_SEQUENCE;
TRUNCATE TABLE EW701.RADAR_PD_SPOT_VALUES;
TRUNCATE TABLE EW701.RADAR_RF_VALUES;
TRUNCATE TABLE EW701.RADAR_RF_SEQUENCE_NAME;
TRUNCATE TABLE EW701.RADAR_RF_SEQUENCE;
TRUNCATE TABLE EW701.RADAR_RF_SPOT_VALUES;

TRUNCATE TABLE EW701.RADAR_PRI_VALUES;
TRUNCATE TABLE EW701.RADAR_PRI_SEQUENCE_NAME;

TRUNCATE TABLE EW701.RADAR_PRI_SEQUENCE;
TRUNCATE TABLE EW701.RADAR_PRI_SPOT_VALUES;
TRUNCATE TABLE EW701.RADAR_PRI_GROUP_SPACING;
TRUNCATE TABLE EW701.RADAR_MOP_CW;
TRUNCATE TABLE EW701.RADAR_MOP_CW_VALUES;
TRUNCATE TABLE EW701.RADAR_MOP_CW_SEQ_NAME;
TRUNCATE TABLE EW701.RADAR_MOP_CW_SEQUENCE;
TRUNCATE TABLE EW701.RADAR_MODE_PA_DIFF_IN_GROUP;

