/* Copyright (c) 2014-2016 Wind River Systems, Inc.
 *
 * The right to copy, distribute, modify or otherwise make use
 * of this software may be licensed only pursuant to the terms
 * of an applicable Wind River license agreement.
 */

/* This file has been autogenerated by cafe-type2h(1). */

#ifndef CAFE_TYPE2H_USER_EVENT_TYPE_autogenerated_h
#define CAFE_TYPE2H_USER_EVENT_TYPE_autogenerated_h

#include <cafe/autogenerated/cafe.type.h>

#ifdef __cplusplus
extern "C" {
#endif

#define category_user_events_VT_DEF "N[category.user_events,,n[cafe.METRIC_CATEGORY,\"user_events\",\"User Events\"]]"
#define category_user_events_VT_REF "t[category.user_events]"
#define category_user_events_VT_NAT "n[category.user_events]"

#define user_event_CONTEXT_VT_DEF "N[user_event.CONTEXT]"
#define user_event_CONTEXT_VT_REF "t[user_event.CONTEXT]"
#define user_event_CONTEXT_VT_NAT "n[user_event.CONTEXT]"

#define user_event_float_VT_DEF "S[user_event.float,v[label,s,n[user_event.CONTEXT]]v[value,d,n[cafe.SUM_METRIC_CLASS]n[category.user_events]n[cafe.LABEL,\"Float Value\"]],n[cafe.LABEL,\"Float Simple User Event\"]n[cafe.COUNTER_METRIC_CLASS]n[category.user_events]]"
#define user_event_float_VT_REF "t[user_event.float]"

#define user_event_signed_VT_DEF "S[user_event.signed,v[label,s,n[user_event.CONTEXT]]v[value,q,n[cafe.SUM_METRIC_CLASS]n[category.user_events]n[cafe.LABEL,\"Signed Value\"]],n[cafe.LABEL,\"Signed Simple User Event\"]n[cafe.COUNTER_METRIC_CLASS]n[category.user_events]]"
#define user_event_signed_VT_REF "t[user_event.signed]"

#define user_event_string_VT_DEF "S[user_event.string,v[label,s,n[user_event.CONTEXT]]v[value,s,n[cafe.SET_METRIC_CLASS]n[category.user_events]n[cafe.LABEL,\"String Value\"]],n[cafe.LABEL,\"String Simple User Event\"]n[cafe.COUNTER_METRIC_CLASS]n[category.user_events]]"
#define user_event_string_VT_REF "t[user_event.string]"

#define user_event_unsigned_VT_DEF "S[user_event.unsigned,v[label,s,n[user_event.CONTEXT]]v[value,Q,n[cafe.SUM_METRIC_CLASS]n[category.user_events]n[cafe.LABEL,\"Unsigned Value\"]],n[cafe.LABEL,\"Unsigned Simple User Event\"]n[cafe.COUNTER_METRIC_CLASS]n[category.user_events]]"
#define user_event_unsigned_VT_REF "t[user_event.unsigned]"

#define USER_EVENT_TYPE_ALL_VT_DEFS \
	category_user_events_VT_DEF \
	user_event_CONTEXT_VT_DEF \
	user_event_float_VT_DEF \
	user_event_signed_VT_DEF \
	user_event_string_VT_DEF \
	user_event_unsigned_VT_DEF \

struct user_event_float {
	char *label;
	double value;
};

struct user_event_signed {
	char *label;
	long long value;
};

struct user_event_string {
	char *label;
	char *value;
};

struct user_event_unsigned {
	char *label;
	unsigned long long value;
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
