# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_IPNET_FTP  {}
set _VSB_LAYER_CDFPATH_IPNET_FTP [concat  $_VSB_LAYER_CDFPATH_IPNET_FTP D:/vxWorks7/vxworks-7/pkgs/net/ipnet-1.1.1.2/app/ftp-1.0.4.5/cdf]
