# this file is automatically generated by mk/krnl/rules.layers.mk
VSBL_CDFPATH_SYSTEMVIEWER_AGENT =
VSBL_CDFPATH_SYSTEMVIEWER_AGENT += D:/vxWorks7/vxworks-7/pkgs/rttools/systemviewer-1.0.0.12/src/osconfig/vxworks/cdf
