# this file is automatically generated by mk/krnl/rules.layers.mk
VSBL_CDFPATH_LANG_LIB_LIBC_LIBC_KERNEL =
VSBL_CDFPATH_LANG_LIB_LIBC_LIBC_KERNEL += D:/vxWorks7/vxworks-7/pkgs/os/lang-lib/libc-1.0.0.1/libc-kernel-1.0.6.2/cdf
