# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_FS_ROMFS  {}
set _VSB_LAYER_CDFPATH_FS_ROMFS [concat  $_VSB_LAYER_CDFPATH_FS_ROMFS D:/vxWorks7/vxworks-7/pkgs/storage/fs-1.0.0.2/romfs-1.1.2.0/cdf]
