# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_DIAB Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_DIAB
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_DIAB_20_0_4_2
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_SRC += LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_DIAB_USER
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_SRC += LANG_LIB_TOOL_TOOLSRC_DIAB_USER
endif
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_SRC += LANG_LIB_TOOL_TOOLSRC_DIAB
LANG_LIB_TOOL_TOOLSRC_DIAB_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_diab-20.0.4.2
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_DIAB_20_0_4_2
endif
endif

