# Automatically generated file: do not edit

##########################
# IPNET_PPP Section
##########################


ifdef _WRS_CONFIG_IPNET_PPP
VSBL_IPNET_PPP_SRC = 
VSBL_IPNET_PPP_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_LINKPROTO_1_0_1_2_PPP_1_2_1_4
VSBL_IPNET_PPP_SRC += IPNET_PPP
VSBL_IPNET_PPP_DEPEND += IPNET_COREIP
VSBL_IPNET_PPP_DEPEND += SEC_HASH
VSBL_IPNET_PPP_DEPEND += IPNET_COREIP
VSBL_IPNET_PPP_DEPEND += CORE_KERNEL
IPNET_PPP_FASTBUILD = YES
VSBL_IPNET_PPP_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4
VSBL_IPNET_PPP_VERSION = IPNET_1_1_1_2_LINKPROTO_1_0_1_2_PPP_1_2_1_4
endif
endif

