# Automatically generated file: do not edit

##########################
# RTNET Section
##########################


ifdef _WRS_CONFIG_RTNET
VSBL_RTNET_SRC = 
VSBL_RTNET_DEPEND = 

ifdef _WRS_CONFIG_RTNET_1_0_2_3
VSBL_RTNET_SRC += RTNET
VSBL_RTNET_DEPEND += JSON
VSBL_RTNET_DEPEND += SOCKET
VSBL_RTNET_DEPEND += NET_BASE
VSBL_RTNET_DEPEND += NET_BASE
VSBL_RTNET_DEPEND += JOBQUEUE
VSBL_RTNET_DEPEND += VXBUS_CORE
VSBL_RTNET_DEPEND += END
VSBL_RTNET_DEPEND += NET_BASE
RTNET_FASTBUILD = YES
VSBL_RTNET_PATH = $(WIND_BASE)/pkgs/net/rtnet-1.0.2.3
VSBL_RTNET_VERSION = RTNET_1_0_2_3
endif
endif

