# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_DIAB_USER Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_DIAB_USER
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_USER_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_USER_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_DIAB_20_0_4_2_TOOLSRC_DIAB_USER_20_0_1_8
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_USER_SRC += LANG_LIB_TOOL_TOOLSRC_DIAB_USER
LANG_LIB_TOOL_TOOLSRC_DIAB_USER_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_USER_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_diab-20.0.4.2/usr
VSBL_LANG_LIB_TOOL_TOOLSRC_DIAB_USER_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_DIAB_20_0_4_2_TOOLSRC_DIAB_USER_20_0_1_8
endif
endif

