# Automatically generated file: do not edit

##########################
# IPNET_COREIP Section
##########################


ifdef _WRS_CONFIG_IPNET_COREIP
VSBL_IPNET_COREIP_SRC = 
VSBL_IPNET_COREIP_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_COREIP_1_4_2_0
VSBL_IPNET_COREIP_SRC += IPNET_COREIP
VSBL_IPNET_COREIP_DEPEND += JOBQUEUE
VSBL_IPNET_COREIP_DEPEND += SEC_HASH
VSBL_IPNET_COREIP_DEPEND += SOCKET
VSBL_IPNET_COREIP_DEPEND += CORE_KERNEL
VSBL_IPNET_COREIP_DEPEND += CORE_KERNEL
VSBL_IPNET_COREIP_DEPEND += CORE_KERNEL
VSBL_IPNET_COREIP_DEPEND += CORE_KERNEL
VSBL_IPNET_COREIP_DEPEND += CORE_KERNEL
VSBL_IPNET_COREIP_DEPEND += CORE_KERNEL
ifdef _WRS_CONFIG_USER_MANAGEMENT
VSBL_IPNET_COREIP_DEPEND += USER_MANAGEMENT
endif
ifdef _WRS_CONFIG_USER_MANAGEMENT
VSBL_IPNET_COREIP_DEPEND += USER_MANAGEMENT
endif
ifdef _WRS_CONFIG_USER_MANAGEMENT*
VSBL_IPNET_COREIP_DEPEND += USER_MANAGEMENT
endif
VSBL_IPNET_COREIP_DEPEND += NET_BASE
VSBL_IPNET_COREIP_DEPEND += NET_BASE
VSBL_IPNET_COREIP_DEPEND += NET_BASE
VSBL_IPNET_COREIP_DEPEND += END
IPNET_COREIP_FASTBUILD = YES
VSBL_IPNET_COREIP_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/coreip-1.4.2.0
VSBL_IPNET_COREIP_VERSION = IPNET_1_1_1_2_COREIP_1_4_2_0
endif
endif

