# Automatically generated file: do not edit

##########################
# AUDIO Section
##########################


ifdef _WRS_CONFIG_AUDIO
VSBL_AUDIO_SRC = 
VSBL_AUDIO_DEPEND = 

ifdef _WRS_CONFIG_AUDIO_1_0_0_2
ifdef _WRS_CONFIG_AUDIO_DEMO
VSBL_AUDIO_SRC += AUDIO_DEMO
endif
ifdef _WRS_CONFIG_AUDIO_DRV
VSBL_AUDIO_SRC += AUDIO_DRV
endif
ifdef _WRS_CONFIG_AUDIO_FSL_SGTL5000
VSBL_AUDIO_SRC += AUDIO_FSL_SGTL5000
endif
ifdef _WRS_CONFIG_AUDIO_FSL_SSI
VSBL_AUDIO_SRC += AUDIO_FSL_SSI
endif
ifdef _WRS_CONFIG_AUDIO_TI_AIC3106
VSBL_AUDIO_SRC += AUDIO_TI_AIC3106
endif
ifdef _WRS_CONFIG_AUDIO_TI_MCASP
VSBL_AUDIO_SRC += AUDIO_TI_MCASP
endif
ifdef _WRS_CONFIG_AUDIO_WM8962
VSBL_AUDIO_SRC += AUDIO_WM8962
endif
ifdef _WRS_CONFIG_AUDIO_LIB
VSBL_AUDIO_SRC += AUDIO_LIB
endif
VSBL_AUDIO_SRC += AUDIO
AUDIO_FASTBUILD = YES
VSBL_AUDIO_PATH = $(WIND_BASE)/pkgs/ui/audio-1.0.0.2
VSBL_AUDIO_VERSION = AUDIO_1_0_0_2
endif
endif

