# Automatically generated file: do not edit

##########################
# TIPC_TIPC_KERNEL_INVENTORYSIM_DEMO Section
##########################


ifdef _WRS_CONFIG_TIPC_TIPC_KERNEL_INVENTORYSIM_DEMO
VSBL_TIPC_TIPC_KERNEL_INVENTORYSIM_DEMO_SRC = 
VSBL_TIPC_TIPC_KERNEL_INVENTORYSIM_DEMO_DEPEND = 

ifdef _WRS_CONFIG_TIPC_1_0_0_1_TIPC_KERNEL_INVENTORYSIM_DEMO_1_0_0_3
VSBL_TIPC_TIPC_KERNEL_INVENTORYSIM_DEMO_SRC += TIPC_TIPC_KERNEL_INVENTORYSIM_DEMO
VSBL_TIPC_TIPC_KERNEL_INVENTORYSIM_DEMO_DEPEND += TIPC_TIPC_KERNEL
TIPC_TIPC_KERNEL_INVENTORYSIM_DEMO_FASTBUILD = YES
VSBL_TIPC_TIPC_KERNEL_INVENTORYSIM_DEMO_PATH = $(WIND_BASE)/pkgs/ipc/tipc-1.0.0.1/tipcInventorySim_demo-1.0.0.3
VSBL_TIPC_TIPC_KERNEL_INVENTORYSIM_DEMO_VERSION = TIPC_1_0_0_1_TIPC_KERNEL_INVENTORYSIM_DEMO_1_0_0_3
endif
endif

