# Automatically generated file: do not edit

##########################
# DEBUG_AGENT Section
##########################


ifdef _WRS_CONFIG_DEBUG_AGENT
VSBL_DEBUG_AGENT_SRC = 
VSBL_DEBUG_AGENT_DEPEND = 

ifdef _WRS_CONFIG_DEBUG_AGENT_1_2_5_1
VSBL_DEBUG_AGENT_SRC += DEBUG_AGENT
VSBL_DEBUG_AGENT_DEPEND += FSAPI_UTIL
VSBL_DEBUG_AGENT_DEPEND += IPNET
VSBL_DEBUG_AGENT_DEPEND += IPNET_COREIP
VSBL_DEBUG_AGENT_DEPEND += LOADER
VSBL_DEBUG_AGENT_DEPEND += VXDBG
VSBL_DEBUG_AGENT_DEPEND += VXDBG
VSBL_DEBUG_AGENT_DEPEND += VXDBG
DEBUG_AGENT_FASTBUILD = YES
VSBL_DEBUG_AGENT_PATH = $(WIND_BASE)/pkgs/rttools/agent-1.2.5.1
VSBL_DEBUG_AGENT_VERSION = DEBUG_AGENT_1_2_5_1
endif
endif

