# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_ICC Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_ICC
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_ICC_20_0_0_5
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_SRC += LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_ICC_USER
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_SRC += LANG_LIB_TOOL_TOOLSRC_ICC_USER
endif
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_SRC += LANG_LIB_TOOL_TOOLSRC_ICC
LANG_LIB_TOOL_TOOLSRC_ICC_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_icc-20.0.0.5
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_ICC_20_0_0_5
endif
endif

