# Automatically generated file: do not edit

##########################
# VXBUS_BUSLIB Section
##########################


ifdef _WRS_CONFIG_VXBUS_BUSLIB
VSBL_VXBUS_BUSLIB_SRC = 
VSBL_VXBUS_BUSLIB_DEPEND = 

ifdef _WRS_CONFIG_VXBUS_1_0_5_0_BUSLIB_2_1_3_4
VSBL_VXBUS_BUSLIB_SRC += VXBUS_BUSLIB
VSBL_VXBUS_BUSLIB_DEPEND += VXBUS_SUBSYSTEM
VSBL_VXBUS_BUSLIB_DEPEND += VXBUS_SUBSYSTEM
VSBL_VXBUS_BUSLIB_DEPEND += VXBUS_CORE
VSBL_VXBUS_BUSLIB_DEPEND += VXBUS_SUBSYSTEM
VSBL_VXBUS_BUSLIB_DEPEND += VXBUS_CORE
VSBL_VXBUS_BUSLIB_DEPEND += VXBUS_CORE
VXBUS_BUSLIB_FASTBUILD = YES
VSBL_VXBUS_BUSLIB_PATH = $(WIND_BASE)/pkgs/os/drv/vxbus-1.0.5.0/buslib-2.1.3.4
VSBL_VXBUS_BUSLIB_VERSION = VXBUS_1_0_5_0_BUSLIB_2_1_3_4
endif
endif

