# Automatically generated file: do not edit

##########################
# FBDEV_SAMPLEFB Section
##########################


ifdef _WRS_CONFIG_FBDEV_SAMPLEFB
VSBL_FBDEV_SAMPLEFB_SRC = 
VSBL_FBDEV_SAMPLEFB_DEPEND = 

ifdef _WRS_CONFIG_FBDEV_1_0_0_2_SAMPLEFB_1_0_2_0
VSBL_FBDEV_SAMPLEFB_SRC += FBDEV_SAMPLEFB
VSBL_FBDEV_SAMPLEFB_DEPEND += FBDEV_COMMON
FBDEV_SAMPLEFB_FASTBUILD = YES
VSBL_FBDEV_SAMPLEFB_PATH = $(WIND_BASE)/pkgs/ui/fbdev-1.0.0.2/sample-1.0.2.0
VSBL_FBDEV_SAMPLEFB_VERSION = FBDEV_1_0_0_2_SAMPLEFB_1_0_2_0
endif
endif

