# Automatically generated file: do not edit

##########################
# IPNET_BRIDGE Section
##########################


ifdef _WRS_CONFIG_IPNET_BRIDGE
VSBL_IPNET_BRIDGE_SRC = 
VSBL_IPNET_BRIDGE_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_LINKPROTO_1_0_1_2_BRIDGE_1_0_1_3
VSBL_IPNET_BRIDGE_SRC += IPNET_BRIDGE
VSBL_IPNET_BRIDGE_DEPEND += END_LIB
VSBL_IPNET_BRIDGE_DEPEND += IPNET_COREIP
IPNET_BRIDGE_FASTBUILD = YES
VSBL_IPNET_BRIDGE_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/bridge-1.0.1.3
VSBL_IPNET_BRIDGE_VERSION = IPNET_1_1_1_2_LINKPROTO_1_0_1_2_BRIDGE_1_0_1_3
endif
endif

