# Automatically generated file: do not edit

##########################
# IPNET_LINKPROTO Section
##########################


ifdef _WRS_CONFIG_IPNET_LINKPROTO
VSBL_IPNET_LINKPROTO_SRC = 
VSBL_IPNET_LINKPROTO_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_LINKPROTO_1_0_1_2
ifdef _WRS_CONFIG_IPNET_BRIDGE
VSBL_IPNET_LINKPROTO_SRC += IPNET_BRIDGE
endif
ifdef _WRS_CONFIG_IPNET_L2TP
VSBL_IPNET_LINKPROTO_SRC += IPNET_L2TP
endif
ifdef _WRS_CONFIG_IPNET_PPP
VSBL_IPNET_LINKPROTO_SRC += IPNET_PPP
endif
ifdef _WRS_CONFIG_IPNET_ROHC
VSBL_IPNET_LINKPROTO_SRC += IPNET_ROHC
endif
VSBL_IPNET_LINKPROTO_SRC += IPNET_LINKPROTO
VSBL_IPNET_LINKPROTO_DEPEND += IPNET_COREIP
IPNET_LINKPROTO_FASTBUILD = YES
VSBL_IPNET_LINKPROTO_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto
VSBL_IPNET_LINKPROTO_VERSION = IPNET_1_1_1_2_LINKPROTO_1_0_1_2
endif
endif

