# Automatically generated file: do not edit

##########################
# WEBCLI Section
##########################


ifdef _WRS_CONFIG_WEBCLI
VSBL_WEBCLI_SRC = 
VSBL_WEBCLI_DEPEND = 

ifdef _WRS_CONFIG_WEBCLI_1_0_0_3
ifdef _WRS_CONFIG_WEBCLI_BACKPLANE
VSBL_WEBCLI_SRC += WEBCLI_BACKPLANE
endif
ifdef _WRS_CONFIG_WEBCLI_CLI
VSBL_WEBCLI_SRC += WEBCLI_CLI
endif
ifdef _WRS_CONFIG_WEBCLI_CLIDEMO
VSBL_WEBCLI_SRC += WEBCLI_CLIDEMO
endif
ifdef _WRS_CONFIG_WEBCLI_COMMON
VSBL_WEBCLI_SRC += WEBCLI_COMMON
endif
ifdef _WRS_CONFIG_WEBCLI_CURL
VSBL_WEBCLI_SRC += WEBCLI_CURL
endif
ifdef _WRS_CONFIG_WEBCLI_HTTP
VSBL_WEBCLI_SRC += WEBCLI_HTTP
endif
ifdef _WRS_CONFIG_WEBCLI_MIBWAY
VSBL_WEBCLI_SRC += WEBCLI_MIBWAY
endif
ifdef _WRS_CONFIG_WEBCLI_WEBCLIDEMO
VSBL_WEBCLI_SRC += WEBCLI_WEBCLIDEMO
endif
ifdef _WRS_CONFIG_WEBCLI_WEBDEMO
VSBL_WEBCLI_SRC += WEBCLI_WEBDEMO
endif
VSBL_WEBCLI_SRC += WEBCLI
WEBCLI_FASTBUILD = YES
VSBL_WEBCLI_PATH = $(WIND_BASE)/pkgs/app/webcli-1.0.0.3
VSBL_WEBCLI_VERSION = WEBCLI_1_0_0_3
endif
endif

