# Automatically generated file: do not edit

##########################
# IPNET_DHCPS6 Section
##########################


ifdef _WRS_CONFIG_IPNET_DHCPS6
VSBL_IPNET_DHCPS6_SRC = 
VSBL_IPNET_DHCPS6_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_DHCPS6_1_0_0_9
VSBL_IPNET_DHCPS6_SRC += IPNET_DHCPS6
VSBL_IPNET_DHCPS6_DEPEND += IPNET_COREIP
VSBL_IPNET_DHCPS6_DEPEND += IPNET_DNSC
VSBL_IPNET_DHCPS6_DEPEND += SEC_HASH
IPNET_DHCPS6_FASTBUILD = YES
VSBL_IPNET_DHCPS6_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/app/dhcps6-1.0.0.9
VSBL_IPNET_DHCPS6_VERSION = IPNET_1_1_1_2_DHCPS6_1_0_0_9
endif
endif

