# Automatically generated file: do not edit

##########################
# GPUDEV_FSLVIVGPU Section
##########################


ifdef _WRS_CONFIG_GPUDEV_FSLVIVGPU
VSBL_GPUDEV_FSLVIVGPU_SRC = 
VSBL_GPUDEV_FSLVIVGPU_DEPEND = 

ifdef _WRS_CONFIG_GPUDEV_1_0_0_2_FSLVIVGPU_5_0_11_8_3
VSBL_GPUDEV_FSLVIVGPU_SRC += GPUDEV_FSLVIVGPU
VSBL_GPUDEV_FSLVIVGPU_DEPEND += GPUDEV_COMMON
VSBL_GPUDEV_FSLVIVGPU_DEPEND += FBDEV_FSLIPUFB
VSBL_GPUDEV_FSLVIVGPU_DEPEND += KHRONOS
VSBL_GPUDEV_FSLVIVGPU_DEPEND += CORE_KERNEL
GPUDEV_FSLVIVGPU_FASTBUILD = YES
VSBL_GPUDEV_FSLVIVGPU_PATH = $(WIND_BASE)/pkgs/ui/gpudev-1.0.0.2/fslviv-5.0.11.8.3
VSBL_GPUDEV_FSLVIVGPU_VERSION = GPUDEV_1_0_0_2_FSLVIVGPU_5_0_11_8_3
endif
endif

