# Automatically generated file: do not edit

##########################
# GPUDEV_SAMPLEDRM Section
##########################


ifdef _WRS_CONFIG_GPUDEV_SAMPLEDRM
VSBL_GPUDEV_SAMPLEDRM_SRC = 
VSBL_GPUDEV_SAMPLEDRM_DEPEND = 

ifdef _WRS_CONFIG_GPUDEV_1_0_0_2_SAMPLEDRM_1_0_1_0
VSBL_GPUDEV_SAMPLEDRM_SRC += GPUDEV_SAMPLEDRM
VSBL_GPUDEV_SAMPLEDRM_DEPEND += GPUDEV_DRM
GPUDEV_SAMPLEDRM_FASTBUILD = YES
VSBL_GPUDEV_SAMPLEDRM_PATH = $(WIND_BASE)/pkgs/ui/gpudev-1.0.0.2/sample-1.0.1.0
VSBL_GPUDEV_SAMPLEDRM_VERSION = GPUDEV_1_0_0_2_SAMPLEDRM_1_0_1_0
endif
endif

