# Automatically generated file: do not edit

##########################
# IPNET_TSN Section
##########################


ifdef _WRS_CONFIG_IPNET_TSN
VSBL_IPNET_TSN_SRC = 
VSBL_IPNET_TSN_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_TSN_1_0_3_0
ifdef _WRS_CONFIG_IPNET_CLOCK
VSBL_IPNET_TSN_SRC += IPNET_CLOCK
endif
ifdef _WRS_CONFIG_IPNET_QAVQBV
VSBL_IPNET_TSN_SRC += IPNET_QAVQBV
endif
ifdef _WRS_CONFIG_IPNET_STREAM
VSBL_IPNET_TSN_SRC += IPNET_STREAM
endif
VSBL_IPNET_TSN_SRC += IPNET_TSN
VSBL_IPNET_TSN_DEPEND += END
VSBL_IPNET_TSN_DEPEND += IPNET_COREIP
VSBL_IPNET_TSN_DEPEND += IPNET_PTP
IPNET_TSN_FASTBUILD = YES
VSBL_IPNET_TSN_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/tsn-1.0.3.0
VSBL_IPNET_TSN_VERSION = IPNET_1_1_1_2_TSN_1_0_3_0
endif
endif

