# Automatically generated file: do not edit

##########################
# IPNET_DOT1X Section
##########################


ifdef _WRS_CONFIG_IPNET_DOT1X
VSBL_IPNET_DOT1X_SRC = 
VSBL_IPNET_DOT1X_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_MOBILITY_1_0_1_0_DOT1X_1_0_1_0
VSBL_IPNET_DOT1X_SRC += IPNET_DOT1X
VSBL_IPNET_DOT1X_DEPEND += END_LIB
VSBL_IPNET_DOT1X_DEPEND += IPNET_COREIP
VSBL_IPNET_DOT1X_DEPEND += IPNET_RADIUS
IPNET_DOT1X_FASTBUILD = YES
VSBL_IPNET_DOT1X_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/mobility-1.0.1.0/dot1x
VSBL_IPNET_DOT1X_VERSION = IPNET_1_1_1_2_MOBILITY_1_0_1_0_DOT1X_1_0_1_0
endif
endif

