# Automatically generated file: do not edit

##########################
# RASTER_VG Section
##########################


ifdef _WRS_CONFIG_RASTER_VG
VSBL_RASTER_VG_SRC = 
VSBL_RASTER_VG_DEPEND = 

ifdef _WRS_CONFIG_RASTER_1_0_0_2_VG_1_0_4_2
VSBL_RASTER_VG_SRC += RASTER_VG
VSBL_RASTER_VG_DEPEND += IMAGE_JPEG
VSBL_RASTER_VG_DEPEND += IMAGE_PNG
VSBL_RASTER_VG_DEPEND += KHRONOS
VSBL_RASTER_VG_DEPEND += RASTER_COMMON
VSBL_RASTER_VG_DEPEND += FBDEV_COMMON
RASTER_VG_FASTBUILD = YES
VSBL_RASTER_VG_PATH = $(WIND_BASE)/pkgs/ui/raster-1.0.0.2/vg-1.0.4.2
VSBL_RASTER_VG_VERSION = RASTER_1_0_0_2_VG_1_0_4_2
endif
endif

