# Automatically generated file: do not edit

##########################
# IPNET_SSH Section
##########################


ifdef _WRS_CONFIG_IPNET_SSH
VSBL_IPNET_SSH_SRC = 
VSBL_IPNET_SSH_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_SSH_1_0_3_0
VSBL_IPNET_SSH_SRC += IPNET_SSH
VSBL_IPNET_SSH_DEPEND += IPNET_COREIP
VSBL_IPNET_SSH_DEPEND += CORE_KERNEL
VSBL_IPNET_SSH_DEPEND += CORE_KERNEL
VSBL_IPNET_SSH_DEPEND += OPENSSL
VSBL_IPNET_SSH_DEPEND += IPNET_COREIP
ifdef _WRS_CONFIG_USER_MANAGEMENT
VSBL_IPNET_SSH_DEPEND += USER_MANAGEMENT
endif
ifdef _WRS_CONFIG_USER_MANAGEMENT*
VSBL_IPNET_SSH_DEPEND += USER_MANAGEMENT
endif
VSBL_IPNET_SSH_DEPEND += SEC_CRYPTO
IPNET_SSH_FASTBUILD = YES
IPNET_SSH_FRIEND = SSH_CLIENT
VSBL_IPNET_SSH_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/ssh-1.0.3.0
VSBL_IPNET_SSH_VERSION = IPNET_1_1_1_2_SSH_1_0_3_0
endif
endif

