# Automatically generated file: do not edit

##########################
# EVDEV Section
##########################


ifdef _WRS_CONFIG_EVDEV
VSBL_EVDEV_SRC = 
VSBL_EVDEV_DEPEND = 

ifdef _WRS_CONFIG_EVDEV_1_0_0_3
ifdef _WRS_CONFIG_EVDEV_DEMO
VSBL_EVDEV_SRC += EVDEV_DEMO
endif
ifdef _WRS_CONFIG_EVDEV_DRV
VSBL_EVDEV_SRC += EVDEV_DRV
endif
ifdef _WRS_CONFIG_EVDEV_EETI_EXC7200_TS
VSBL_EVDEV_SRC += EVDEV_EETI_EXC7200_TS
endif
ifdef _WRS_CONFIG_EVDEV_FSL_CRTOUCH_TS
VSBL_EVDEV_SRC += EVDEV_FSL_CRTOUCH_TS
endif
ifdef _WRS_CONFIG_EVDEV_FT_5X06_TS
VSBL_EVDEV_SRC += EVDEV_FT_5X06_TS
endif
ifdef _WRS_CONFIG_EVDEV_TI_AM335X_TS
VSBL_EVDEV_SRC += EVDEV_TI_AM335X_TS
endif
ifdef _WRS_CONFIG_EVDEV_TI_TSC2004_TS
VSBL_EVDEV_SRC += EVDEV_TI_TSC2004_TS
endif
ifdef _WRS_CONFIG_EVDEV_VIRTUAL_KBD
VSBL_EVDEV_SRC += EVDEV_VIRTUAL_KBD
endif
ifdef _WRS_CONFIG_EVDEV_VIRTUAL_PTR
VSBL_EVDEV_SRC += EVDEV_VIRTUAL_PTR
endif
ifdef _WRS_CONFIG_EVDEV_VXSIM_KBD
VSBL_EVDEV_SRC += EVDEV_VXSIM_KBD
endif
ifdef _WRS_CONFIG_EVDEV_VXSIM_PTR
VSBL_EVDEV_SRC += EVDEV_VXSIM_PTR
endif
ifdef _WRS_CONFIG_EVDEV_LIB
VSBL_EVDEV_SRC += EVDEV_LIB
endif
VSBL_EVDEV_SRC += EVDEV
EVDEV_FASTBUILD = YES
VSBL_EVDEV_PATH = $(WIND_BASE)/pkgs/ui/evdev-1.0.0.3
VSBL_EVDEV_VERSION = EVDEV_1_0_0_3
endif
endif

