# Automatically generated file: do not edit

##########################
# WEBCLI_CURL Section
##########################


ifdef _WRS_CONFIG_WEBCLI_CURL
VSBL_WEBCLI_CURL_SRC = 
VSBL_WEBCLI_CURL_DEPEND = 

ifdef _WRS_CONFIG_WEBCLI_1_0_0_3_CURL_7_55_1_0
VSBL_WEBCLI_CURL_SRC += WEBCLI_CURL
VSBL_WEBCLI_CURL_DEPEND += IPNET_COREIP
VSBL_WEBCLI_CURL_DEPEND += OPENSSL
VSBL_WEBCLI_CURL_DEPEND += SEC_CRYPTO
VSBL_WEBCLI_CURL_DEPEND += ZLIB
WEBCLI_CURL_FASTBUILD = YES
VSBL_WEBCLI_CURL_PATH = $(WIND_BASE)/pkgs/app/webcli-1.0.0.3/curl-7.55.1.0
VSBL_WEBCLI_CURL_VERSION = WEBCLI_1_0_0_3_CURL_7_55_1_0
endif
endif

