# Automatically generated file: do not edit

##########################
# WEBCLI_BACKPLANE Section
##########################


ifdef _WRS_CONFIG_WEBCLI_BACKPLANE
VSBL_WEBCLI_BACKPLANE_SRC = 
VSBL_WEBCLI_BACKPLANE_DEPEND = 

ifdef _WRS_CONFIG_WEBCLI_1_0_0_3_BACKPLANE_1_0_0_8
VSBL_WEBCLI_BACKPLANE_SRC += WEBCLI_BACKPLANE
VSBL_WEBCLI_BACKPLANE_DEPEND += WEBCLI_COMMON
WEBCLI_BACKPLANE_FASTBUILD = YES
VSBL_WEBCLI_BACKPLANE_PATH = $(WIND_BASE)/pkgs/app/webcli-1.0.0.3/backplane-1.0.0.8
VSBL_WEBCLI_BACKPLANE_VERSION = WEBCLI_1_0_0_3_BACKPLANE_1_0_0_8
endif
endif

