# Automatically generated file: do not edit

##########################
# KHRONOS Section
##########################


ifdef _WRS_CONFIG_KHRONOS
VSBL_KHRONOS_SRC = 
VSBL_KHRONOS_DEPEND = 

ifdef _WRS_CONFIG_KHRONOS_1_4_0_0
VSBL_KHRONOS_SRC += KHRONOS
KHRONOS_FASTBUILD = YES
VSBL_KHRONOS_PATH = $(WIND_BASE)/pkgs/ui/khronos-1.4.0.0
VSBL_KHRONOS_VERSION = KHRONOS_1_4_0_0
endif

ifdef _WRS_CONFIG_KHRONOS_1_4_0_1
VSBL_KHRONOS_SRC += KHRONOS
KHRONOS_FASTBUILD = YES
VSBL_KHRONOS_PATH = $(WIND_BASE)/pkgs/ui/khronos-1.4.0.1
VSBL_KHRONOS_VERSION = KHRONOS_1_4_0_1
endif
endif

