# Automatically generated file: do not edit

##########################
# RASTER_SDL Section
##########################


ifdef _WRS_CONFIG_RASTER_SDL
VSBL_RASTER_SDL_SRC = 
VSBL_RASTER_SDL_DEPEND = 

ifdef _WRS_CONFIG_RASTER_1_0_0_2_SDL_2_0_5_1
VSBL_RASTER_SDL_SRC += RASTER_SDL
VSBL_RASTER_SDL_DEPEND += RASTER_COMMON
VSBL_RASTER_SDL_DEPEND += KHRONOS
VSBL_RASTER_SDL_DEPEND += FBDEV_COMMON
ifdef _WRS_CONFIG_RASTER_MESA
VSBL_RASTER_SDL_DEPEND += RASTER_MESA
endif
ifdef _WRS_CONFIG_ARCH_i86*
VSBL_RASTER_SDL_DEPEND += RASTER_MESA
endif
ifdef _WRS_CONFIG_GPUDEV_FSLVIVGPU
VSBL_RASTER_SDL_DEPEND += GPUDEV_FSLVIVGPU
endif
ifdef _WRS_CONFIG_FSL_IMX*
VSBL_RASTER_SDL_DEPEND += GPUDEV_FSLVIVGPU
endif
RASTER_SDL_FASTBUILD = YES
VSBL_RASTER_SDL_PATH = $(WIND_BASE)/pkgs/ui/raster-1.0.0.2/sdl-2.0.5.1
VSBL_RASTER_SDL_VERSION = RASTER_1_0_0_2_SDL_2_0_5_1
endif
endif

