# Automatically generated file: do not edit

##########################
# AUDIO_DRV Section
##########################


ifdef _WRS_CONFIG_AUDIO_DRV
VSBL_AUDIO_DRV_SRC = 
VSBL_AUDIO_DRV_DEPEND = 

ifdef _WRS_CONFIG_AUDIO_1_0_0_2_DRV_1_0_0_1
ifdef _WRS_CONFIG_AUDIO_FSL_SGTL5000
VSBL_AUDIO_DRV_SRC += AUDIO_FSL_SGTL5000
endif
ifdef _WRS_CONFIG_AUDIO_FSL_SSI
VSBL_AUDIO_DRV_SRC += AUDIO_FSL_SSI
endif
ifdef _WRS_CONFIG_AUDIO_TI_AIC3106
VSBL_AUDIO_DRV_SRC += AUDIO_TI_AIC3106
endif
ifdef _WRS_CONFIG_AUDIO_TI_MCASP
VSBL_AUDIO_DRV_SRC += AUDIO_TI_MCASP
endif
ifdef _WRS_CONFIG_AUDIO_WM8962
VSBL_AUDIO_DRV_SRC += AUDIO_WM8962
endif
VSBL_AUDIO_DRV_SRC += AUDIO_DRV
VSBL_AUDIO_DRV_DEPEND += AUDIO_LIB
AUDIO_DRV_FASTBUILD = YES
VSBL_AUDIO_DRV_PATH = $(WIND_BASE)/pkgs/ui/audio-1.0.0.2/drv
VSBL_AUDIO_DRV_VERSION = AUDIO_1_0_0_2_DRV_1_0_0_1
endif
endif

