# Automatically generated file: do not edit

##########################
# EVDEV_VXSIM_KBD Section
##########################


ifdef _WRS_CONFIG_EVDEV_VXSIM_KBD
VSBL_EVDEV_VXSIM_KBD_SRC = 
VSBL_EVDEV_VXSIM_KBD_DEPEND = 

ifdef _WRS_CONFIG_EVDEV_1_0_0_3_DRV_1_0_0_1_VXSIM_KBD_1_0_1_1
VSBL_EVDEV_VXSIM_KBD_SRC += EVDEV_VXSIM_KBD
VSBL_EVDEV_VXSIM_KBD_DEPEND += FBDEV_VXSIMFB
EVDEV_VXSIM_KBD_FASTBUILD = YES
VSBL_EVDEV_VXSIM_KBD_PATH = $(WIND_BASE)/pkgs/ui/evdev-1.0.0.3/drv/vxSimKbd-1.0.1.1
VSBL_EVDEV_VXSIM_KBD_VERSION = EVDEV_1_0_0_3_DRV_1_0_0_1_VXSIM_KBD_1_0_1_1
endif
endif

