# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_COMMON Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_COMMON
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_COMMON_1_0_3_5
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_SRC += LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_COMMON_USER
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_SRC += LANG_LIB_TOOL_TOOLSRC_COMMON_USER
endif
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_SRC += LANG_LIB_TOOL_TOOLSRC_COMMON
LANG_LIB_TOOL_TOOLSRC_COMMON_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/common-1.0.3.5
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_COMMON_1_0_3_5
endif
endif

