# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_COMMON_USER Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_COMMON_USER
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_USER_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_USER_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_COMMON_1_0_3_5_TOOLSRC_COMMON_USER_1_0_1_1
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_USER_SRC += LANG_LIB_TOOL_TOOLSRC_COMMON_USER
LANG_LIB_TOOL_TOOLSRC_COMMON_USER_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_USER_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/common-1.0.3.5/usr
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_USER_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_COMMON_1_0_3_5_TOOLSRC_COMMON_USER_1_0_1_1
endif
endif

