# Automatically generated file: do not edit

##########################
# VXDBG Section
##########################


ifdef _WRS_CONFIG_VXDBG
VSBL_VXDBG_SRC = 
VSBL_VXDBG_DEPEND = 

ifdef _WRS_CONFIG_VXDBG_1_0_7_1
ifdef _WRS_CONFIG_VXDBG_VXTEST
VSBL_VXDBG_SRC += VXDBG_VXTEST
endif
VSBL_VXDBG_SRC += VXDBG
ifdef _WRS_CONFIG_IA_KERNEL
VSBL_VXDBG_DEPEND += IA_KERNEL
endif
ifdef _WRS_CONFIG_ARCH_i86*
VSBL_VXDBG_DEPEND += IA_KERNEL
endif
ifdef _WRS_CONFIG_IA_KERNEL
VSBL_VXDBG_DEPEND += IA_KERNEL
endif
ifdef _WRS_CONFIG_ARCH_i86*
VSBL_VXDBG_DEPEND += IA_KERNEL
endif
ifdef _WRS_CONFIG_ARM_KERNEL
VSBL_VXDBG_DEPEND += ARM_KERNEL
endif
ifdef _WRS_CONFIG_ARCH_arm*
VSBL_VXDBG_DEPEND += ARM_KERNEL
endif
ifdef _WRS_CONFIG_PPC_KERNEL
VSBL_VXDBG_DEPEND += PPC_KERNEL
endif
ifdef _WRS_CONFIG_ARCH_ppc*
VSBL_VXDBG_DEPEND += PPC_KERNEL
endif
ifdef _WRS_CONFIG_PPC_KERNEL
VSBL_VXDBG_DEPEND += PPC_KERNEL
endif
ifdef _WRS_CONFIG_ARCH_ppc*
VSBL_VXDBG_DEPEND += PPC_KERNEL
endif
ifdef _WRS_CONFIG_VXSIM_KERNEL
VSBL_VXDBG_DEPEND += VXSIM_KERNEL
endif
ifdef _WRS_CONFIG_ARCH_simlinux*
VSBL_VXDBG_DEPEND += VXSIM_KERNEL
endif
ifdef _WRS_CONFIG_VXSIM_KERNEL
VSBL_VXDBG_DEPEND += VXSIM_KERNEL
endif
ifdef _WRS_CONFIG_ARCH_simpc*
VSBL_VXDBG_DEPEND += VXSIM_KERNEL
endif
VSBL_VXDBG_DEPEND += CORE_KERNEL
VSBL_VXDBG_DEPEND += CORE_KERNEL
ifdef _WRS_CONFIG_IA_KERNEL
VSBL_VXDBG_DEPEND += IA_KERNEL
endif
ifdef _WRS_CONFIG_ARCH_i86*
VSBL_VXDBG_DEPEND += IA_KERNEL
endif
VXDBG_FASTBUILD = YES
VSBL_VXDBG_PATH = $(WIND_BASE)/pkgs/os/debug/vxdbg-1.0.7.1
VSBL_VXDBG_VERSION = VXDBG_1_0_7_1
endif
endif

