# Automatically generated file: do not edit

##########################
# IA_KERNEL Section
##########################


ifdef _WRS_CONFIG_IA_KERNEL
VSBL_IA_KERNEL_SRC = 
VSBL_IA_KERNEL_DEPEND = 

ifdef _WRS_CONFIG_IA_1_2_4_1_KERNEL_1_1_4_1
VSBL_IA_KERNEL_SRC += IA_KERNEL
VSBL_IA_KERNEL_DEPEND += CORE_KERNEL
VSBL_IA_KERNEL_DEPEND += CORE_KERNEL
VSBL_IA_KERNEL_DEPEND += CORE_KERNEL
VSBL_IA_KERNEL_DEPEND += CORE_KERNEL
VSBL_IA_KERNEL_DEPEND += CORE_KERNEL
IA_KERNEL_FASTBUILD = YES
VSBL_IA_KERNEL_PATH = $(WIND_BASE)/pkgs/os/arch/ia-1.2.4.1/kernel
VSBL_IA_KERNEL_VERSION = IA_1_2_4_1_KERNEL_1_1_4_1
endif
endif

