# Automatically generated file: do not edit

##########################
# BOOTAPP Section
##########################


ifdef _WRS_CONFIG_BOOTAPP
VSBL_BOOTAPP_SRC = 
VSBL_BOOTAPP_DEPEND = 

ifdef _WRS_CONFIG_BOOTAPP_1_0_6_0
VSBL_BOOTAPP_SRC += BOOTAPP
VSBL_BOOTAPP_DEPEND += END_LIB
VSBL_BOOTAPP_DEPEND += FS
VSBL_BOOTAPP_DEPEND += FSAPI_UTIL
VSBL_BOOTAPP_DEPEND += IPNET_COREIP
VSBL_BOOTAPP_DEPEND += IPNET_DHCPC
VSBL_BOOTAPP_DEPEND += LOADER
VSBL_BOOTAPP_DEPEND += CORE_KERNEL
BOOTAPP_FASTBUILD = YES
VSBL_BOOTAPP_PATH = $(WIND_BASE)/pkgs/os/utils/bootapp-1.0.6.0
VSBL_BOOTAPP_VERSION = BOOTAPP_1_0_6_0
endif
endif

