# Automatically generated file: do not edit

##########################
# TI_AM3XXX Section
##########################


ifdef _WRS_CONFIG_TI_AM3XXX
VSBL_TI_AM3XXX_SRC = 
VSBL_TI_AM3XXX_DEPEND = 

ifdef _WRS_CONFIG_TI_AM3XXX_1_1_4_3
VSBL_TI_AM3XXX_SRC += TI_AM3XXX
VSBL_TI_AM3XXX_DEPEND += BOARDLIB
VSBL_TI_AM3XXX_DEPEND += CORE_KERNEL
VSBL_TI_AM3XXX_DEPEND += FDT
VSBL_TI_AM3XXX_DEPEND += VXBUS
VSBL_TI_AM3XXX_DEPEND += VXBUS_SUBSYSTEM
VSBL_TI_AM3XXX_DEPEND += VXBUS_BUSLIB
VSBL_TI_AM3XXX_DEPEND += BOARDLIB
VSBL_TI_AM3XXX_DEPEND += ARM_KERNEL
TI_AM3XXX_FASTBUILD = YES
VSBL_TI_AM3XXX_PATH = $(WIND_BASE)/pkgs/os/platform/ti_am3xxx-1.1.4.3
VSBL_TI_AM3XXX_VERSION = TI_AM3XXX_1_1_4_3
endif
endif

