# Automatically generated file: do not edit

##########################
# GPUDEV_FSLVIVGPU_DEMOS Section
##########################


ifdef _WRS_CONFIG_GPUDEV_FSLVIVGPU_DEMOS
VSBL_GPUDEV_FSLVIVGPU_DEMOS_SRC = 
VSBL_GPUDEV_FSLVIVGPU_DEMOS_DEPEND = 

ifdef _WRS_CONFIG_GPUDEV_1_0_0_2_FSLVIVGPU_DEMOS_1_0_6_1
VSBL_GPUDEV_FSLVIVGPU_DEMOS_SRC += GPUDEV_FSLVIVGPU_DEMOS
VSBL_GPUDEV_FSLVIVGPU_DEMOS_DEPEND += GPUDEV_FSLVIVGPU
GPUDEV_FSLVIVGPU_DEMOS_FASTBUILD = YES
VSBL_GPUDEV_FSLVIVGPU_DEMOS_PATH = $(WIND_BASE)/pkgs/ui/gpudev-1.0.0.2/fslviv_demos-1.0.6.1
VSBL_GPUDEV_FSLVIVGPU_DEMOS_VERSION = GPUDEV_1_0_0_2_FSLVIVGPU_DEMOS_1_0_6_1
endif
endif

