# Automatically generated file: do not edit

##########################
# IPNET_RIPNG Section
##########################


ifdef _WRS_CONFIG_IPNET_RIPNG
VSBL_IPNET_RIPNG_SRC = 
VSBL_IPNET_RIPNG_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_ROUTEPROTO_1_0_1_6_RIPNG_1_0_0_5
VSBL_IPNET_RIPNG_SRC += IPNET_RIPNG
VSBL_IPNET_RIPNG_DEPEND += HASH
VSBL_IPNET_RIPNG_DEPEND += IPNET_COREIP
IPNET_RIPNG_FASTBUILD = YES
VSBL_IPNET_RIPNG_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/routeproto-1.0.1.6/ripng
VSBL_IPNET_RIPNG_VERSION = IPNET_1_1_1_2_ROUTEPROTO_1_0_1_6_RIPNG_1_0_0_5
endif
endif

