# Automatically generated file: do not edit

##########################
# VXBUS Section
##########################


ifdef _WRS_CONFIG_VXBUS
VSBL_VXBUS_SRC = 
VSBL_VXBUS_DEPEND = 

ifdef _WRS_CONFIG_VXBUS_1_0_5_0
ifdef _WRS_CONFIG_VXBUS_BUSLIB
VSBL_VXBUS_SRC += VXBUS_BUSLIB
endif
ifdef _WRS_CONFIG_VXBUS_CORE
VSBL_VXBUS_SRC += VXBUS_CORE
endif
ifdef _WRS_CONFIG_VXBUS_VXTEST
VSBL_VXBUS_SRC += VXBUS_VXTEST
endif
ifdef _WRS_CONFIG_VXBUS_DRV
VSBL_VXBUS_SRC += VXBUS_DRV
endif
ifdef _WRS_CONFIG_VXBUS_SUBSYSTEM
VSBL_VXBUS_SRC += VXBUS_SUBSYSTEM
endif
ifdef _WRS_CONFIG_VXBUS_VXTEST_SUBSYSTEM
VSBL_VXBUS_SRC += VXBUS_VXTEST_SUBSYSTEM
endif
VSBL_VXBUS_SRC += VXBUS
VSBL_VXBUS_DEPEND += CORE_IO
VXBUS_FASTBUILD = YES
VSBL_VXBUS_PATH = $(WIND_BASE)/pkgs/os/drv/vxbus-1.0.5.0
VSBL_VXBUS_VERSION = VXBUS_1_0_5_0
endif
endif

