# Automatically generated file: do not edit

##########################
# SYSCALLS_VXWORKS Section
##########################


ifdef _WRS_CONFIG_SYSCALLS_VXWORKS
VSBL_SYSCALLS_VXWORKS_SRC = 
VSBL_SYSCALLS_VXWORKS_DEPEND = 

ifdef _WRS_CONFIG_SYSCALLS_1_0_14_0_VXWORKS_1_0_13_0
VSBL_SYSCALLS_VXWORKS_SRC += SYSCALLS_VXWORKS
SYSCALLS_VXWORKS_FASTBUILD = YES
VSBL_SYSCALLS_VXWORKS_PATH = $(WIND_BASE)/pkgs/os/core/syscalls-1.0.14.0/vxworks
VSBL_SYSCALLS_VXWORKS_VERSION = SYSCALLS_1_0_14_0_VXWORKS_1_0_13_0
endif
endif

