# Automatically generated file: do not edit

##########################
# IPNET_DIAMETER Section
##########################


ifdef _WRS_CONFIG_IPNET_DIAMETER
VSBL_IPNET_DIAMETER_SRC = 
VSBL_IPNET_DIAMETER_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_AAA_1_0_1_10_DIAMETER_1_0_0_8
VSBL_IPNET_DIAMETER_SRC += IPNET_DIAMETER
VSBL_IPNET_DIAMETER_DEPEND += IPNET_COREIP
VSBL_IPNET_DIAMETER_DEPEND += SEC_HASH
VSBL_IPNET_DIAMETER_DEPEND += OPENSSL
ifdef _WRS_CONFIG_SEC_CRYPTO
VSBL_IPNET_DIAMETER_DEPEND += SEC_CRYPTO
endif
ifdef _WRS_CONFIG_SEC_CRYPTO*
VSBL_IPNET_DIAMETER_DEPEND += SEC_CRYPTO
endif
IPNET_DIAMETER_FASTBUILD = YES
VSBL_IPNET_DIAMETER_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/aaa-1.0.1.10/diameter
VSBL_IPNET_DIAMETER_VERSION = IPNET_1_1_1_2_AAA_1_0_1_10_DIAMETER_1_0_0_8
endif
endif

