# Automatically generated file: do not edit

##########################
# VXBUS_SUBSYSTEM Section
##########################


ifdef _WRS_CONFIG_VXBUS_SUBSYSTEM
VSBL_VXBUS_SUBSYSTEM_SRC = 
VSBL_VXBUS_SUBSYSTEM_DEPEND = 

ifdef _WRS_CONFIG_VXBUS_1_0_5_0_SUBSYSTEM_1_0_12_1
ifdef _WRS_CONFIG_VXBUS_VXTEST_SUBSYSTEM
VSBL_VXBUS_SUBSYSTEM_SRC += VXBUS_VXTEST_SUBSYSTEM
endif
VSBL_VXBUS_SUBSYSTEM_SRC += VXBUS_SUBSYSTEM
VSBL_VXBUS_SUBSYSTEM_DEPEND += JOBQUEUE
ifdef _WRS_CONFIG_BOARDLIB
VSBL_VXBUS_SUBSYSTEM_DEPEND += BOARDLIB
endif
ifdef _WRS_CONFIG_BOARDLIB
VSBL_VXBUS_SUBSYSTEM_DEPEND += BOARDLIB
endif
ifdef _WRS_CONFIG_BOARDLIB
VSBL_VXBUS_SUBSYSTEM_DEPEND += BOARDLIB
endif
ifdef _WRS_CONFIG_BOARDLIB*
VSBL_VXBUS_SUBSYSTEM_DEPEND += BOARDLIB
endif
VSBL_VXBUS_SUBSYSTEM_DEPEND += VXBUS_CORE
VXBUS_SUBSYSTEM_FASTBUILD = YES
VSBL_VXBUS_SUBSYSTEM_PATH = $(WIND_BASE)/pkgs/os/drv/vxbus-1.0.5.0/subsystem-1.0.12.1
VSBL_VXBUS_SUBSYSTEM_VERSION = VXBUS_1_0_5_0_SUBSYSTEM_1_0_12_1
endif
endif

