# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_GNU Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_GNU
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_GNU_20_0_2_6
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_SRC += LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_GNU_USER
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_SRC += LANG_LIB_TOOL_TOOLSRC_GNU_USER
endif
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_SRC += LANG_LIB_TOOL_TOOLSRC_GNU
LANG_LIB_TOOL_TOOLSRC_GNU_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_gnu-20.0.2.6
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_GNU_20_0_2_6
endif
endif

