# Automatically generated file: do not edit

##########################
# EVDEV_FSL_CRTOUCH_TS Section
##########################


ifdef _WRS_CONFIG_EVDEV_FSL_CRTOUCH_TS
VSBL_EVDEV_FSL_CRTOUCH_TS_SRC = 
VSBL_EVDEV_FSL_CRTOUCH_TS_DEPEND = 

ifdef _WRS_CONFIG_EVDEV_1_0_0_3_DRV_1_0_0_1_FSL_CRTOUCH_TS_1_0_0_3
VSBL_EVDEV_FSL_CRTOUCH_TS_SRC += EVDEV_FSL_CRTOUCH_TS
VSBL_EVDEV_FSL_CRTOUCH_TS_DEPEND += FDT
VSBL_EVDEV_FSL_CRTOUCH_TS_DEPEND += VXBUS_BUSLIB
VSBL_EVDEV_FSL_CRTOUCH_TS_DEPEND += VXBUS_CORE
EVDEV_FSL_CRTOUCH_TS_FASTBUILD = YES
VSBL_EVDEV_FSL_CRTOUCH_TS_PATH = $(WIND_BASE)/pkgs/ui/evdev-1.0.0.3/drv/fslCRTouchTs-1.0.0.3
VSBL_EVDEV_FSL_CRTOUCH_TS_VERSION = EVDEV_1_0_0_3_DRV_1_0_0_1_FSL_CRTOUCH_TS_1_0_0_3
endif
endif

