# Automatically generated file: do not edit

##########################
# RASTER Section
##########################


ifdef _WRS_CONFIG_RASTER
VSBL_RASTER_SRC = 
VSBL_RASTER_DEPEND = 

ifdef _WRS_CONFIG_RASTER_1_0_0_2
ifdef _WRS_CONFIG_RASTER_COMMON
VSBL_RASTER_SRC += RASTER_COMMON
endif
ifdef _WRS_CONFIG_RASTER_MESA
VSBL_RASTER_SRC += RASTER_MESA
endif
ifdef _WRS_CONFIG_RASTER_MESA_DEMOS
VSBL_RASTER_SRC += RASTER_MESA_DEMOS
endif
ifdef _WRS_CONFIG_RASTER_QTPRE
VSBL_RASTER_SRC += RASTER_QTPRE
endif
ifdef _WRS_CONFIG_RASTER_SDL
VSBL_RASTER_SRC += RASTER_SDL
endif
ifdef _WRS_CONFIG_RASTER_SDL_DEMOS
VSBL_RASTER_SRC += RASTER_SDL_DEMOS
endif
ifdef _WRS_CONFIG_RASTER_VG
VSBL_RASTER_SRC += RASTER_VG
endif
ifdef _WRS_CONFIG_RASTER_VG_DEMOS
VSBL_RASTER_SRC += RASTER_VG_DEMOS
endif
VSBL_RASTER_SRC += RASTER
RASTER_FASTBUILD = YES
VSBL_RASTER_PATH = $(WIND_BASE)/pkgs/ui/raster-1.0.0.2
VSBL_RASTER_VERSION = RASTER_1_0_0_2
endif
endif

