# Automatically generated file: do not edit

##########################
# RUNTIME_ANALYSIS Section
##########################


ifdef _WRS_CONFIG_RUNTIME_ANALYSIS
VSBL_RUNTIME_ANALYSIS_SRC = 
VSBL_RUNTIME_ANALYSIS_DEPEND = 

ifdef _WRS_CONFIG_RUNTIME_ANALYSIS_1_1_4_2
VSBL_RUNTIME_ANALYSIS_SRC += RUNTIME_ANALYSIS
ifndef _WRS_CONFIG_RTP
VSBL_RUNTIME_ANALYSIS_DEPEND += SYSTEMVIEWER
endif
VSBL_RUNTIME_ANALYSIS_DEPEND += CORE_KERNEL
VSBL_RUNTIME_ANALYSIS_DEPEND += DEBUG_AGENT
ifdef _WRS_CONFIG_SYSTEMVIEWER
VSBL_RUNTIME_ANALYSIS_DEPEND += SYSTEMVIEWER
endif
ifdef _WRS_CONFIG_RTP*
VSBL_RUNTIME_ANALYSIS_DEPEND += SYSTEMVIEWER
endif
VSBL_RUNTIME_ANALYSIS_DEPEND += STACKTRACE
VSBL_RUNTIME_ANALYSIS_DEPEND += LANG_LIB_LIBC_LIBC_KERNEL
RUNTIME_ANALYSIS_FASTBUILD = YES
VSBL_RUNTIME_ANALYSIS_PATH = $(WIND_BASE)/pkgs/rttools/cafe-1.1.4.2
VSBL_RUNTIME_ANALYSIS_VERSION = RUNTIME_ANALYSIS_1_1_4_2
endif
endif

