# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_CERT Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_CERT
VSBL_LANG_LIB_TOOL_TOOLSRC_CERT_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_CERT_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_CERT_1_0_0_0
VSBL_LANG_LIB_TOOL_TOOLSRC_CERT_SRC += LANG_LIB_TOOL_TOOLSRC_CERT
LANG_LIB_TOOL_TOOLSRC_CERT_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_CERT_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_cert-1.0.0.0
VSBL_LANG_LIB_TOOL_TOOLSRC_CERT_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_CERT_1_0_0_0
endif
endif

