# Automatically generated file: do not edit

##########################
# CORE_RTP_VXTEST Section
##########################


ifdef _WRS_CONFIG_CORE_RTP_VXTEST
VSBL_CORE_RTP_VXTEST_SRC = 
VSBL_CORE_RTP_VXTEST_DEPEND = 

ifdef _WRS_CONFIG_CORE_RTP_1_1_4_1_VXTEST_1_0_0_1
VSBL_CORE_RTP_VXTEST_SRC += CORE_RTP_VXTEST
VSBL_CORE_RTP_VXTEST_DEPEND += CORE_KERNEL_VXTEST
CORE_RTP_VXTEST_FASTBUILD = YES
VSBL_CORE_RTP_VXTEST_PATH = $(WIND_BASE)/pkgs/os/core/rtp-1.1.4.1/vxTest
VSBL_CORE_RTP_VXTEST_VERSION = CORE_RTP_1_1_4_1_VXTEST_1_0_0_1
endif
endif

