# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_COMMON_1_0_3_5_TOOLSRC_COMMON_KERNEL_1_0_1_0
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL_SRC += LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL
LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/common-1.0.3.5/kernel
VSBL_LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_COMMON_1_0_3_5_TOOLSRC_COMMON_KERNEL_1_0_1_0
endif
endif

