# Automatically generated file: do not edit

##########################
# IPNET_FIREWALL Section
##########################


ifdef _WRS_CONFIG_IPNET_FIREWALL
VSBL_IPNET_FIREWALL_SRC = 
VSBL_IPNET_FIREWALL_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_FIREWALL_1_0_1_6
VSBL_IPNET_FIREWALL_SRC += IPNET_FIREWALL
VSBL_IPNET_FIREWALL_DEPEND += IPNET_COREIP
IPNET_FIREWALL_FASTBUILD = YES
VSBL_IPNET_FIREWALL_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/firewall-1.0.1.6
VSBL_IPNET_FIREWALL_VERSION = IPNET_1_1_1_2_FIREWALL_1_0_1_6
endif
endif

