# Automatically generated file: do not edit

##########################
# LANG_LIB_LIBC_VXTEST_KERNEL Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_LIBC_VXTEST_KERNEL
VSBL_LANG_LIB_LIBC_VXTEST_KERNEL_SRC = 
VSBL_LANG_LIB_LIBC_VXTEST_KERNEL_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_LIBC_1_0_0_1_LIBC_KERNEL_1_0_6_2_VXTEST_KERNEL_1_0_0_3
VSBL_LANG_LIB_LIBC_VXTEST_KERNEL_SRC += LANG_LIB_LIBC_VXTEST_KERNEL
VSBL_LANG_LIB_LIBC_VXTEST_KERNEL_DEPEND += CORE_KERNEL_VXTEST
LANG_LIB_LIBC_VXTEST_KERNEL_FASTBUILD = YES
VSBL_LANG_LIB_LIBC_VXTEST_KERNEL_PATH = $(WIND_BASE)/pkgs/os/lang-lib/libc-1.0.0.1/libc-kernel-1.0.6.2/vxTest
VSBL_LANG_LIB_LIBC_VXTEST_KERNEL_VERSION = LANG_LIB_LIBC_1_0_0_1_LIBC_KERNEL_1_0_6_2_VXTEST_KERNEL_1_0_0_3
endif
endif

