# Automatically generated file: do not edit

##########################
# MOSQUITTO Section
##########################


ifdef _WRS_CONFIG_MOSQUITTO
VSBL_MOSQUITTO_SRC = 
VSBL_MOSQUITTO_DEPEND = 

ifdef _WRS_CONFIG_MOSQUITTO_1_4_8_1
VSBL_MOSQUITTO_SRC += MOSQUITTO
VSBL_MOSQUITTO_DEPEND += JSON
VSBL_MOSQUITTO_DEPEND += OPENSSL
VSBL_MOSQUITTO_DEPEND += UNIX
VSBL_MOSQUITTO_DEPEND += LANG_LIB_LIBC_LIBC_KERNEL
VSBL_MOSQUITTO_DEPEND += UNIX
MOSQUITTO_FASTBUILD = YES
MOSQUITTO_SUBSCRIBE = UNIX
VSBL_MOSQUITTO_PATH = $(WIND_BASE)/pkgs/app/mosquitto-1.4.8.1
VSBL_MOSQUITTO_VERSION = MOSQUITTO_1_4_8_1
endif
endif

