# Automatically generated file: do not edit

##########################
# ARM_ARMV7A Section
##########################


ifdef _WRS_CONFIG_ARM_ARMV7A
VSBL_ARM_ARMV7A_SRC = 
VSBL_ARM_ARMV7A_DEPEND = 

ifdef _WRS_CONFIG_ARM_1_1_10_2_KERNEL_1_0_13_2_ARMV7A_1_0_10_2
VSBL_ARM_ARMV7A_SRC += ARM_ARMV7A
VSBL_ARM_ARMV7A_DEPEND += CORE_KERNEL
VSBL_ARM_ARMV7A_DEPEND += CORE_KERNEL
VSBL_ARM_ARMV7A_DEPEND += ARM_ARMBASE
ARM_ARMV7A_FASTBUILD = YES
VSBL_ARM_ARMV7A_PATH = $(WIND_BASE)/pkgs/os/arch/arm-1.1.10.2/kernel/armv7a
VSBL_ARM_ARMV7A_VERSION = ARM_1_1_10_2_KERNEL_1_0_13_2_ARMV7A_1_0_10_2
endif
endif

