# Automatically generated file: do not edit

##########################
# VXSIM_KERNEL Section
##########################


ifdef _WRS_CONFIG_VXSIM_KERNEL
VSBL_VXSIM_KERNEL_SRC = 
VSBL_VXSIM_KERNEL_DEPEND = 

ifdef _WRS_CONFIG_VXSIM_1_0_7_9_KERNEL_1_0_5_1
VSBL_VXSIM_KERNEL_SRC += VXSIM_KERNEL
ifndef _WRS_CONFIG_COMPAT69
VSBL_VXSIM_KERNEL_DEPEND += FDT
endif
ifndef _WRS_CONFIG_COMPAT69
VSBL_VXSIM_KERNEL_DEPEND += VXBUS
endif
ifndef _WRS_CONFIG_COMPAT69
VSBL_VXSIM_KERNEL_DEPEND += BOARDLIB
endif
VSBL_VXSIM_KERNEL_DEPEND += CORE_KERNEL
VSBL_VXSIM_KERNEL_DEPEND += CORE_KERNEL
VSBL_VXSIM_KERNEL_DEPEND += CORE_KERNEL
VSBL_VXSIM_KERNEL_DEPEND += CORE_KERNEL
ifdef _WRS_CONFIG_VXBUS_LEGACY
VSBL_VXSIM_KERNEL_DEPEND += VXBUS_LEGACY
endif
ifndef _WRS_CONFIG_VXBUS_CORE
VSBL_VXSIM_KERNEL_DEPEND += VXBUS_CORE
endif
VXSIM_KERNEL_FASTBUILD = YES
VSBL_VXSIM_KERNEL_PATH = $(WIND_BASE)/pkgs/os/arch/simulator-1.0.7.9/kernel
VSBL_VXSIM_KERNEL_VERSION = VXSIM_1_0_7_9_KERNEL_1_0_5_1
endif
endif

