# Automatically generated file: do not edit

##########################
# IPNET_USRSPACE Section
##########################


ifdef _WRS_CONFIG_IPNET_USRSPACE
VSBL_IPNET_USRSPACE_SRC = 
VSBL_IPNET_USRSPACE_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_USRSPACE_2_0_2_5
VSBL_IPNET_USRSPACE_SRC += IPNET_USRSPACE
VSBL_IPNET_USRSPACE_DEPEND += NET_BASE
VSBL_IPNET_USRSPACE_DEPEND += IPNET_COREIP
IPNET_USRSPACE_FASTBUILD = YES
VSBL_IPNET_USRSPACE_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/usrspace-2.0.2.5
VSBL_IPNET_USRSPACE_VERSION = IPNET_1_1_1_2_USRSPACE_2_0_2_5
endif
endif

