# Automatically generated file: do not edit

##########################
# LANG_LIB_CPLUS Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_CPLUS
VSBL_LANG_LIB_CPLUS_SRC = 
VSBL_LANG_LIB_CPLUS_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_CPLUS_1_0_0_1
ifdef _WRS_CONFIG_LANG_LIB_CPLUS_CPLUS_USER_2011
VSBL_LANG_LIB_CPLUS_SRC += LANG_LIB_CPLUS_CPLUS_USER_2011
endif
ifdef _WRS_CONFIG_LANG_LIB_CPLUS_CPLUS_KERNEL
VSBL_LANG_LIB_CPLUS_SRC += LANG_LIB_CPLUS_CPLUS_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_CPLUS_CPLUS_USER
VSBL_LANG_LIB_CPLUS_SRC += LANG_LIB_CPLUS_CPLUS_USER
endif
VSBL_LANG_LIB_CPLUS_SRC += LANG_LIB_CPLUS
LANG_LIB_CPLUS_FASTBUILD = YES
VSBL_LANG_LIB_CPLUS_PATH = $(WIND_BASE)/pkgs/os/lang-lib/cplus-1.0.0.1
VSBL_LANG_LIB_CPLUS_VERSION = LANG_LIB_CPLUS_1_0_0_1
endif
endif

