# Automatically generated file: do not edit

##########################
# USB_FUNCTION Section
##########################


ifdef _WRS_CONFIG_USB_FUNCTION
VSBL_USB_FUNCTION_SRC = 
VSBL_USB_FUNCTION_DEPEND = 

ifdef _WRS_CONFIG_USB_1_1_0_6_TARGET_1_1_0_1_FUNCTION_1_1_0_1
ifdef _WRS_CONFIG_USB_HLP
VSBL_USB_FUNCTION_SRC += USB_HLP
endif
ifdef _WRS_CONFIG_USB_KBD
VSBL_USB_FUNCTION_SRC += USB_KBD
endif
ifdef _WRS_CONFIG_USB_MSC
VSBL_USB_FUNCTION_SRC += USB_MSC
endif
ifdef _WRS_CONFIG_USB_NET
VSBL_USB_FUNCTION_SRC += USB_NET
endif
ifdef _WRS_CONFIG_USB_PRNT
VSBL_USB_FUNCTION_SRC += USB_PRNT
endif
ifdef _WRS_CONFIG_USB_SER
VSBL_USB_FUNCTION_SRC += USB_SER
endif
VSBL_USB_FUNCTION_SRC += USB_FUNCTION
USB_FUNCTION_FASTBUILD = YES
VSBL_USB_FUNCTION_PATH = $(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/target/function
VSBL_USB_FUNCTION_VERSION = USB_1_1_0_6_TARGET_1_1_0_1_FUNCTION_1_1_0_1
endif
endif

