# Automatically generated file: do not edit

##########################
# IPNET_MOBILITY Section
##########################


ifdef _WRS_CONFIG_IPNET_MOBILITY
VSBL_IPNET_MOBILITY_SRC = 
VSBL_IPNET_MOBILITY_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_MOBILITY_1_0_1_0
ifdef _WRS_CONFIG_IPNET_8021X
VSBL_IPNET_MOBILITY_SRC += IPNET_8021X
endif
ifdef _WRS_CONFIG_IPNET_DOT1X
VSBL_IPNET_MOBILITY_SRC += IPNET_DOT1X
endif
ifdef _WRS_CONFIG_IPNET_WLAN
VSBL_IPNET_MOBILITY_SRC += IPNET_WLAN
endif
ifdef _WRS_CONFIG_IPNET_WLANDRV
VSBL_IPNET_MOBILITY_SRC += IPNET_WLANDRV
endif
ifdef _WRS_CONFIG_IPNET_WLANMLME
VSBL_IPNET_MOBILITY_SRC += IPNET_WLANMLME
endif
ifdef _WRS_CONFIG_IPNET_WPS
VSBL_IPNET_MOBILITY_SRC += IPNET_WPS
endif
VSBL_IPNET_MOBILITY_SRC += IPNET_MOBILITY
VSBL_IPNET_MOBILITY_DEPEND += IPNET_COREIP
IPNET_MOBILITY_FASTBUILD = YES
VSBL_IPNET_MOBILITY_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/mobility-1.0.1.0
VSBL_IPNET_MOBILITY_VERSION = IPNET_1_1_1_2_MOBILITY_1_0_1_0
endif
endif

