# Automatically generated file: do not edit

##########################
# VXBUS_LEGACY Section
##########################


ifdef _WRS_CONFIG_VXBUS_LEGACY
VSBL_VXBUS_LEGACY_SRC = 
VSBL_VXBUS_LEGACY_DEPEND = 

ifdef _WRS_CONFIG_VXBUS_LEGACY_1_1_4_0
ifdef _WRS_CONFIG_VXBUS_LEGACY_VXTEST
VSBL_VXBUS_LEGACY_SRC += VXBUS_LEGACY_VXTEST
endif
VSBL_VXBUS_LEGACY_SRC += VXBUS_LEGACY
VSBL_VXBUS_LEGACY_DEPEND += ERF
VSBL_VXBUS_LEGACY_DEPEND += CORE_KERNEL
ifdef _WRS_CONFIG_CONFIG_LEGACY
VSBL_VXBUS_LEGACY_DEPEND += CONFIG_LEGACY
endif
ifdef _WRS_CONFIG_CONFIG_LEGACY*
VSBL_VXBUS_LEGACY_DEPEND += CONFIG_LEGACY
endif
VSBL_VXBUS_LEGACY_DEPEND += CORE_IO
VXBUS_LEGACY_FASTBUILD = YES
VSBL_VXBUS_LEGACY_PATH = $(WIND_BASE)/pkgs/os/drv/vxbus_legacy-1.1.4.0
VSBL_VXBUS_LEGACY_VERSION = VXBUS_LEGACY_1_1_4_0
endif
endif

