# Automatically generated file: do not edit

##########################
# USB Section
##########################


ifdef _WRS_CONFIG_USB
VSBL_USB_SRC = 
VSBL_USB_DEPEND = 

ifdef _WRS_CONFIG_USB_1_1_0_6
ifdef _WRS_CONFIG_USB_CORE
VSBL_USB_SRC += USB_CORE
endif
ifdef _WRS_CONFIG_USB_CTLR
VSBL_USB_SRC += USB_CTLR
endif
ifdef _WRS_CONFIG_USB_CCORE
VSBL_USB_SRC += USB_CCORE
endif
ifdef _WRS_CONFIG_USB_DWC2DR
VSBL_USB_SRC += USB_DWC2DR
endif
ifdef _WRS_CONFIG_USB_EHCI
VSBL_USB_SRC += USB_EHCI
endif
ifdef _WRS_CONFIG_USB_FSLDR
VSBL_USB_SRC += USB_FSLDR
endif
ifdef _WRS_CONFIG_USB_MHDRC
VSBL_USB_SRC += USB_MHDRC
endif
ifdef _WRS_CONFIG_USB_OHCI
VSBL_USB_SRC += USB_OHCI
endif
ifdef _WRS_CONFIG_USB_PCHUDC
VSBL_USB_SRC += USB_PCHUDC
endif
ifdef _WRS_CONFIG_USB_PLX
VSBL_USB_SRC += USB_PLX
endif
ifdef _WRS_CONFIG_USB_UHCI
VSBL_USB_SRC += USB_UHCI
endif
ifdef _WRS_CONFIG_USB_XHCI
VSBL_USB_SRC += USB_XHCI
endif
ifdef _WRS_CONFIG_USB_HOST
VSBL_USB_SRC += USB_HOST
endif
ifdef _WRS_CONFIG_USB_CLASS
VSBL_USB_SRC += USB_CLASS
endif
ifdef _WRS_CONFIG_USB_HELPER
VSBL_USB_SRC += USB_HELPER
endif
ifdef _WRS_CONFIG_USB_HID
VSBL_USB_SRC += USB_HID
endif
ifdef _WRS_CONFIG_USB_KEYBOARD
VSBL_USB_SRC += USB_KEYBOARD
endif
ifdef _WRS_CONFIG_USB_MOUSE
VSBL_USB_SRC += USB_MOUSE
endif
ifdef _WRS_CONFIG_USB_NETWORK
VSBL_USB_SRC += USB_NETWORK
endif
ifdef _WRS_CONFIG_USB_PRINTER
VSBL_USB_SRC += USB_PRINTER
endif
ifdef _WRS_CONFIG_USB_SERIAL
VSBL_USB_SRC += USB_SERIAL
endif
ifdef _WRS_CONFIG_USB_STORAGE
VSBL_USB_SRC += USB_STORAGE
endif
ifdef _WRS_CONFIG_USB_TOUCHSCREEN
VSBL_USB_SRC += USB_TOUCHSCREEN
endif
ifdef _WRS_CONFIG_USB_UVC
VSBL_USB_SRC += USB_UVC
endif
ifdef _WRS_CONFIG_USB_HCORE
VSBL_USB_SRC += USB_HCORE
endif
ifdef _WRS_CONFIG_USB_OTG
VSBL_USB_SRC += USB_OTG
endif
ifdef _WRS_CONFIG_USB_PHY
VSBL_USB_SRC += USB_PHY
endif
ifdef _WRS_CONFIG_USB_TARGET
VSBL_USB_SRC += USB_TARGET
endif
ifdef _WRS_CONFIG_USB_TCORE
VSBL_USB_SRC += USB_TCORE
endif
ifdef _WRS_CONFIG_USB_FUNCTION
VSBL_USB_SRC += USB_FUNCTION
endif
ifdef _WRS_CONFIG_USB_HLP
VSBL_USB_SRC += USB_HLP
endif
ifdef _WRS_CONFIG_USB_KBD
VSBL_USB_SRC += USB_KBD
endif
ifdef _WRS_CONFIG_USB_MSC
VSBL_USB_SRC += USB_MSC
endif
ifdef _WRS_CONFIG_USB_NET
VSBL_USB_SRC += USB_NET
endif
ifdef _WRS_CONFIG_USB_PRNT
VSBL_USB_SRC += USB_PRNT
endif
ifdef _WRS_CONFIG_USB_SER
VSBL_USB_SRC += USB_SER
endif
VSBL_USB_SRC += USB
USB_FASTBUILD = YES
VSBL_USB_PATH = $(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6
VSBL_USB_VERSION = USB_1_1_0_6
endif
endif

