# Automatically generated file: do not edit

##########################
# FBDEV_FSLIPUFB Section
##########################


ifdef _WRS_CONFIG_FBDEV_FSLIPUFB
VSBL_FBDEV_FSLIPUFB_SRC = 
VSBL_FBDEV_FSLIPUFB_DEPEND = 

ifdef _WRS_CONFIG_FBDEV_1_0_0_2_FSLIPUFB_1_0_5_1
VSBL_FBDEV_FSLIPUFB_SRC += FBDEV_FSLIPUFB
VSBL_FBDEV_FSLIPUFB_DEPEND += FBDEV_COMMON
FBDEV_FSLIPUFB_FASTBUILD = YES
VSBL_FBDEV_FSLIPUFB_PATH = $(WIND_BASE)/pkgs/ui/fbdev-1.0.0.2/fslipu-1.0.5.1
VSBL_FBDEV_FSLIPUFB_VERSION = FBDEV_1_0_0_2_FSLIPUFB_1_0_5_1
endif
endif

