# Automatically generated file: do not edit

##########################
# USER_MANAGEMENT Section
##########################


ifdef _WRS_CONFIG_USER_MANAGEMENT
VSBL_USER_MANAGEMENT_SRC = 
VSBL_USER_MANAGEMENT_DEPEND = 

ifdef _WRS_CONFIG_USER_MANAGEMENT_1_1_0_2
VSBL_USER_MANAGEMENT_SRC += USER_MANAGEMENT
VSBL_USER_MANAGEMENT_DEPEND += CORE_KERNEL
VSBL_USER_MANAGEMENT_DEPEND += SEC_HASH
VSBL_USER_MANAGEMENT_DEPEND += CORE_KERNEL
VSBL_USER_MANAGEMENT_DEPEND += CORE_KERNEL
VSBL_USER_MANAGEMENT_DEPEND += CORE_KERNEL
USER_MANAGEMENT_FASTBUILD = YES
VSBL_USER_MANAGEMENT_PATH = $(WIND_BASE)/pkgs/security/user_management-1.1.0.2
VSBL_USER_MANAGEMENT_VERSION = USER_MANAGEMENT_1_1_0_2
endif
endif

