# Automatically generated file: do not edit

##########################
# FBDEV_ITLGMCFB Section
##########################


ifdef _WRS_CONFIG_FBDEV_ITLGMCFB
VSBL_FBDEV_ITLGMCFB_SRC = 
VSBL_FBDEV_ITLGMCFB_DEPEND = 

ifdef _WRS_CONFIG_FBDEV_1_0_0_2_ITLGMCFB_1_0_3_0
VSBL_FBDEV_ITLGMCFB_SRC += FBDEV_ITLGMCFB
VSBL_FBDEV_ITLGMCFB_DEPEND += FBDEV_COMMON
VSBL_FBDEV_ITLGMCFB_DEPEND += GPUDEV_ITLI915
VSBL_FBDEV_ITLGMCFB_DEPEND += GPUDEV_LIBDRM
FBDEV_ITLGMCFB_FASTBUILD = YES
VSBL_FBDEV_ITLGMCFB_PATH = $(WIND_BASE)/pkgs/ui/fbdev-1.0.0.2/itlgmc-1.0.3.0
VSBL_FBDEV_ITLGMCFB_VERSION = FBDEV_1_0_0_2_ITLGMCFB_1_0_3_0
endif
endif

