BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "RADAR" (
	"RADAR_INDEX"	INTEGER NOT NULL DEFAULT -1,
	"SECLAB"	INTEGER NOT NULL DEFAULT -1,
	"ELNOT"	VARCHAR2(5) NOT NULL UNIQUE,
	"NICKNAME"	VARCHAR2(30),
	"FUNCTION_CODE"	VARCHAR2(2),
	"PRIORITY"	INTEGER NOT NULL DEFAULT 0,
	"STATUS"	VARCHAR2(20) NOT NULL DEFAULT 'ACTIVE',
	"DATE_LAST_UPDATED"	TIMESTAMP(6),
	"DATE_LAST_REVIEWED"	TIMESTAMP(6),
	"LAST_REVIEWED_BY"	INTEGER DEFAULT -1,
	"LAST_UPDATED_BY"	INTEGER DEFAULT -1,
	"DATE_ACTIVATED"	TIMESTAMP(6),
	"DATE_INACTIVATED"	TIMESTAMP(6),
	"SRT_REVIEWED"	INTEGER NOT NULL DEFAULT 0,
	"TIME_INACTIVATED"	INTEGER DEFAULT -1,
	"AOR_INDEX"	INTEGER DEFAULT -1,
	"DATE_CADCN"	TIMESTAMP(6),
	"ACCEPTED"	INTEGER NOT NULL DEFAULT 1,
	"PRIMARY_WEAP_SYS"	INTEGER DEFAULT -1,
	"PRIMARY_PLATFORM"	INTEGER DEFAULT -1,
	"SECURITY_REVIEW_DATE"	TIMESTAMP(6),
	"COMBINED_DATE_LAST_UPDATED"	TIMESTAMP(6),
	PRIMARY KEY("RADAR_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_P" (
	"RADAR_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"ELNOT"	VARCHAR2(5) NOT NULL UNIQUE,
	"NICKNAME"	VARCHAR2(30),
	"FUNCTION_CODE"	VARCHAR2(2),
	"PRIORITY"	INTEGER NOT NULL DEFAULT 0,
	"STATUS"	VARCHAR2(20) NOT NULL DEFAULT 'ACTIVE',
	"DATE_LAST_UPDATED"	TIMESTAMP(6),
	"DATE_LAST_REVIEWED"	TIMESTAMP(6),
	"LAST_REVIEWED_BY"	INTEGER,
	"LAST_UPDATED_BY"	INTEGER,
	"DATE_ACTIVATED"	TIMESTAMP(6),
	"DATE_INACTIVATED"	TIMESTAMP(6),
	"SRT_REVIEWED"	INTEGER NOT NULL DEFAULT 0,
	"TIME_INACTIVATED"	INTEGER,
	"AOR_INDEX"	INTEGER,
	"DATE_CADCN"	TIMESTAMP(6),
	"ACCEPTED"	INTEGER NOT NULL DEFAULT 1,
	"PRIMARY_WEAP_SYS"	INTEGER,
	"PRIMARY_PLATFORM"	INTEGER,
	"SECURITY_REVIEW_DATE"	TIMESTAMP(6),
	"COMBINED_DATE_LAST_UPDATED"	TIMESTAMP(6),
	PRIMARY KEY("RADAR_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_COMMENTS" (
	"RADAR_COMMENT_INDEX"	INTEGER NOT NULL,
	"RADAR_INDEX"	INTEGER NOT NULL,
	"TITLE"	VARCHAR2(30) NOT NULL,
	"DATE_CREATED"	TIMESTAMP(6) NOT NULL,
	"DATE_LAST_UPDATED"	TIMESTAMP(6) NOT NULL,
	"TYPE"	VARCHAR2(10) NOT NULL,
	"COMMENTS"	CLOB,
	"THIRD_PARTY_RELEASABLE"	INTEGER,
	"SECURITY_REVIEW_DATE"	TIMESTAMP(6),
	"COMMENT_ORDER"	INTEGER,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_INDEX","RADAR_COMMENT_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_COMMENTS_P" (
	"RADAR_COMMENT_INDEX"	INTEGER NOT NULL,
	"RADAR_INDEX"	INTEGER NOT NULL,
	"TITLE"	VARCHAR2(30) NOT NULL,
	"DATE_CREATED"	TIMESTAMP(6) NOT NULL,
	"DATE_LAST_UPDATED"	TIMESTAMP(6) NOT NULL,
	"TYPE"	VARCHAR2(10) NOT NULL,
	"COMMENTS"	CLOB,
	"THIRD_PARTY_RELEASABLE"	INTEGER,
	"SECURITY_REVIEW_DATE"	TIMESTAMP(6),
	"COMMENT_ORDER"	INTEGER,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_INDEX","RADAR_COMMENT_INDEX")
);
CREATE TABLE IF NOT EXISTS "WEAPON_SYSTEM" (
	"WEAPON_SYS"	VARCHAR2(40) NOT NULL,
	"WEAPON_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"SUPPORT_CNT"	INTEGER NOT NULL DEFAULT 0,
	"SECURITY_REVIEW_DATE"	TIMESTAMP(6),
	"DATE_LAST_UPDATED"	TIMESTAMP(6),
	PRIMARY KEY("WEAPON_INDEX")
);
CREATE TABLE IF NOT EXISTS "WEAPON_SYSTEM_P" (
	"WEAPON_SYS"	VARCHAR2(40) NOT NULL,
	"WEAPON_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"SUPPORT_CNT"	INTEGER NOT NULL DEFAULT 0,
	"SECURITY_REVIEW_DATE"	TIMESTAMP(6),
	"DATE_LAST_UPDATED"	TIMESTAMP(6),
	PRIMARY KEY("WEAPON_INDEX")
);
CREATE TABLE IF NOT EXISTS "ASSOC_WEAP_SYS" (
	"RADAR_INDEX"	INTEGER NOT NULL,
	"WEAPON_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_INDEX","WEAPON_INDEX")
);
CREATE TABLE IF NOT EXISTS "ASSOC_WEAP_SYS_P" (
	"RADAR_INDEX"	INTEGER NOT NULL,
	"WEAPON_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_INDEX","WEAPON_INDEX")
);
CREATE TABLE IF NOT EXISTS "PLATFORM" (
	"PLATFORM_INDEX"	INTEGER NOT NULL,
	"PLATFORM"	VARCHAR2(40) NOT NULL,
	"SECURITY_REVIEW_DATE"	TIMESTAMP(6),
	"DATE_LAST_UPDATED"	TIMESTAMP(6),
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("PLATFORM_INDEX")
);
CREATE TABLE IF NOT EXISTS "PLATFORM_P" (
	"PLATFORM_INDEX"	INTEGER NOT NULL,
	"PLATFORM"	VARCHAR2(40) NOT NULL,
	"SECURITY_REVIEW_DATE"	TIMESTAMP(6),
	"DATE_LAST_UPDATED"	TIMESTAMP(6),
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("PLATFORM_INDEX")
);
CREATE TABLE IF NOT EXISTS "ASSOC_PLATFORM" (
	"RADAR_INDEX"	INTEGER NOT NULL,
	"PLATFORM_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_INDEX","PLATFORM_INDEX")
);
CREATE TABLE IF NOT EXISTS "ASSOC_PLATFORM_P" (
	"RADAR_INDEX"	INTEGER NOT NULL,
	"PLATFORM_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_INDEX","PLATFORM_INDEX")
);
CREATE TABLE IF NOT EXISTS "ASSOC_ELNOT" (
	"RADAR_INDEX"	INTEGER NOT NULL,
	"ASSOC_RADAR_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_INDEX","ASSOC_RADAR_INDEX")
);
CREATE TABLE IF NOT EXISTS "ASSOC_ELNOT_P" (
	"RADAR_INDEX"	INTEGER NOT NULL,
	"ASSOC_RADAR_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_INDEX","ASSOC_RADAR_INDEX")
);
CREATE TABLE IF NOT EXISTS "PARAM_SET_ASSOCIATIONS" (
	"ASSOC_INDEX"	INTEGER NOT NULL,
	"RADAR_INDEX"	INTEGER NOT NULL,
	"SET_CODE"	VARCHAR2(2) NOT NULL,
	"ASSOC_TYPE"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL DEFAULT NULL,
	PRIMARY KEY("ASSOC_INDEX")
);
CREATE TABLE IF NOT EXISTS "PARAM_SET_ASSOCIATIONS_P" (
	"ASSOC_INDEX"	INTEGER NOT NULL,
	"RADAR_INDEX"	INTEGER NOT NULL,
	"SET_CODE"	VARCHAR2(2) NOT NULL,
	"ASSOC_TYPE"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL DEFAULT NULL,
	PRIMARY KEY("ASSOC_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_MODE" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"FUNCTION_CODE"	VARCHAR2(2),
	"DATE_CREATED"	TIMESTAMP(6) DEFAULT '1970/01/01 0:00:00.000',
	"DATE_LAST_UPDATED"	TIMESTAMP(6) DEFAULT '1970/01/01 0:00:00.000',
	"DATE_LAST_REVIEWED"	TIMESTAMP(6) DEFAULT '1970/01/01 0:00:00.000',
	"DATE_FIRST_SEEN"	TIMESTAMP(6) DEFAULT '1970/01/01 0:00:00.000',
	"DATE_LAST_SEEN"	TIMESTAMP(6) DEFAULT '1970/01/01 0:00:00.000',
	"LAST_UPDATED_BY"	INTEGER DEFAULT -1,
	"SIGNAL_TYPE"	VARCHAR2(10) NOT NULL,
	"ERP_CONTINUITY"	INTEGER DEFAULT -1,
	"ERP_DWELL_TIME_MIN"	FLOAT(52) DEFAULT -1,
	"ERP_DWELL_TIME_MAX"	FLOAT(52) DEFAULT -1,
	"ERP_EXTREME_MIN"	FLOAT(52) DEFAULT -1,
	"ERP_EXTREME_MAX"	FLOAT(52) DEFAULT -1,
	"ERP_MEAN_MIN"	FLOAT(52) DEFAULT -1,
	"ERP_MEAN_MAX"	FLOAT(52) DEFAULT -1,
	"ERP_NUM_ELEMENTS"	INTEGER DEFAULT -1,
	"ERP_NUM_POSITIONS"	INTEGER DEFAULT -1,
	"ERP_PATTERN"	INTEGER DEFAULT -1,
	"ERP_PATTERN_DRIVER"	VARCHAR2(400) DEFAULT 'X',
	"ERP_PATTERN_RULE"	VARCHAR2(400) DEFAULT 'X',
	"ERP_PATTERN_PERIOD_MIN"	FLOAT(52) DEFAULT -1,
	"ERP_PATTERN_PERIOD_MAX"	FLOAT(52) DEFAULT -1,
	"ERP_RANGE_MIN"	FLOAT(52) DEFAULT -1,
	"ERP_RANGE_MAX"	FLOAT(52) DEFAULT -1,
	"ERP_RATE_MIN"	FLOAT(52) DEFAULT -1,
	"ERP_RATE_MAX"	FLOAT(52) DEFAULT -1,
	"ERP_STANDARD_DEVIATION"	FLOAT(52) DEFAULT -1,
	"ERP_STEP_MIN"	FLOAT(52) DEFAULT -1,
	"ERP_STEP_MAX"	FLOAT(52) DEFAULT -1,
	"ERP_TYPICAL_MIN"	FLOAT(52) DEFAULT -1,
	"ERP_TYPICAL_MAX"	FLOAT(52) DEFAULT -1,
	"POLARIZATION"	INTEGER DEFAULT -1,
	"POL_AXIAL_RATIO_MIN"	FLOAT(52) DEFAULT -1,
	"POL_AXIAL_RATIO_MAX"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_PATTERN_DRIVER"	VARCHAR2(400) DEFAULT 'X',
	"POL_TILT_ANGLE_PATTERN_RULE"	VARCHAR2(400) DEFAULT 'X',
	"POL_TILT_ANGLE_RATE_MIN"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_RATE_MAX"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_CONTINUITY"	INTEGER DEFAULT -1,
	"POL_TILT_ANGLE_DWELL_TIME_MIN"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_DWELL_TIME_MAX"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_EXTREME_MIN"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_EXTREME_MAX"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_MEAN_MIN"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_MEAN_MAX"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_NUM_ELEMENTS"	INTEGER DEFAULT -1,
	"POL_TILT_ANGLE_NUM_POSITIONS"	INTEGER DEFAULT -1,
	"POL_TILT_ANGLE_PATTERN"	INTEGER DEFAULT -1,
	"POL_TILT_ANGLE_PAT_PERIOD_MIN"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_PAT_PERIOD_MAX"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_RANGE_MIN"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_RANGE_MAX"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_STEP_MIN"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_STEP_MAX"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_TYPICAL_MIN"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_TYPICAL_MAX"	FLOAT(52) DEFAULT -1,
	"POL_TILT_ANGLE_STAND_DEVIATION"	FLOAT(52) DEFAULT -1,
	"POL_ROTATION_DIRECTION"	INTEGER DEFAULT -1,
	"POL_ROTATION_FREQUENCY_MIN"	FLOAT(52) DEFAULT -1,
	"POL_ROTATION_FREQUENCY_MAX"	FLOAT(52) DEFAULT -1,
	"POL_SENSE"	INTEGER DEFAULT -1,
	"PLATFORM"	INTEGER DEFAULT -1,
	"RF_EXTREME_MIN"	FLOAT(52) DEFAULT -1,
	"RF_EXTREME_MAX"	FLOAT(52) DEFAULT -1,
	"RF_TYPICAL_MIN"	FLOAT(52) DEFAULT -1,
	"RF_TYPICAL_MAX"	FLOAT(52) DEFAULT -1,
	"BANDWIDTH_OPER_MIN"	FLOAT(52) DEFAULT -1,
	"BANDWIDTH_OPER_MAX"	FLOAT(52) DEFAULT -1,
	"RF_CHANNEL_SPACING_MIN"	FLOAT(52) DEFAULT -1,
	"RF_CHANNEL_SPACING_MAX"	FLOAT(52) DEFAULT -1,
	"RF_CHIP_RATE"	FLOAT(52) DEFAULT -1,
	"RF_CONTINUITY"	INTEGER DEFAULT -1,
	"RF_DWELL_TIME_MIN"	FLOAT(52) DEFAULT -1,
	"RF_DWELL_TIME_MAX"	FLOAT(52) DEFAULT -1,
	"RF_GUARD_BAND"	FLOAT(52) DEFAULT -1,
	"RF_NUM_SIMULTANEOUS"	INTEGER DEFAULT -1,
	"RF_REST_MIN"	FLOAT(52) DEFAULT -1,
	"RF_REST_MAX"	FLOAT(52) DEFAULT -1,
	"RF_SLOT_DURATION"	FLOAT(52) DEFAULT -1,
	"RF_PATTERN"	INTEGER DEFAULT -1,
	"RF_NUM_CHANNELS"	INTEGER DEFAULT -1,
	"RF_NUM_ELEMENTS"	INTEGER DEFAULT -1,
	"RF_NUM_POSITIONS"	INTEGER DEFAULT -1,
	"RF_PATTERN_PERIOD_MIN"	FLOAT(52) DEFAULT -1,
	"RF_PATTERN_PERIOD_MAX"	FLOAT(52) DEFAULT -1,
	"RF_STANDARD_DEVIATION"	FLOAT(52) DEFAULT -1,
	"RF_RANGE_MIN"	FLOAT(52) DEFAULT -1,
	"RF_RANGE_MAX"	FLOAT(52) DEFAULT -1,
	"RF_RATE_MIN"	FLOAT(52) DEFAULT -1,
	"RF_RATE_MAX"	FLOAT(52) DEFAULT -1,
	"RF_STEP_MIN"	FLOAT(52) DEFAULT -1,
	"RF_STEP_MAX"	FLOAT(52) DEFAULT -1,
	"RF_PATTERN_DRIVER"	VARCHAR2(400) DEFAULT 'X',
	"RF_PATTERN_RULE"	VARCHAR2(400) DEFAULT 'X',
	"RF_STABILITY"	FLOAT(52) DEFAULT -1,
	"RF_STAB_PERIOD"	FLOAT(52) DEFAULT -1,
	"RF_COHERENCY"	INTEGER DEFAULT -1,
	"RF_MEAN_MIN"	FLOAT(52) DEFAULT -1,
	"RF_MEAN_MAX"	FLOAT(52) DEFAULT -1,
	"RF_XTAL_MIN"	FLOAT(52) DEFAULT -1,
	"RF_XTAL_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_CONTINUITY"	INTEGER DEFAULT -1,
	"PRI_DWELL_TIME_MIN"	FLOAT(52) DEFAULT -1,
	"PRI_DWELL_TIME_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_EXTREME_MIN"	FLOAT(52) DEFAULT -1,
	"PRI_EXTREME_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_FRAME_PERIOD_MIN"	FLOAT(52) DEFAULT -1,
	"PRI_FRAME_PERIOD_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_GROUP_FORM"	INTEGER DEFAULT -1,
	"PRI_GROUP_DWELL"	FLOAT(52) DEFAULT -1,
	"PRI_GROUP_TRANS_MIN"	FLOAT(52) DEFAULT -1,
	"PRI_GROUP_TRANS_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_MEAN_MIN"	FLOAT(52) DEFAULT -1,
	"PRI_MEAN_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_NUM_ELEMENTS"	INTEGER DEFAULT -1,
	"PRI_NUM_POSITIONS"	INTEGER DEFAULT -1,
	"PRI_PATTERN"	INTEGER DEFAULT -1,
	"PRI_PATTERN_DRIVER"	VARCHAR2(400) DEFAULT 'X',
	"PRI_PATTERN_RULE"	VARCHAR2(400) DEFAULT 'X',
	"PRI_PATTERN_PERIOD_MIN"	FLOAT(52) DEFAULT -1,
	"PRI_PATTERN_PERIOD_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_PATTERN_PERIOD_COUNT_MIN"	INTEGER DEFAULT -1,
	"PRI_PATTERN_PERIOD_COUNT_MAX"	INTEGER DEFAULT -1,
	"PRI_PPG_MIN"	INTEGER DEFAULT -1,
	"PRI_PPG_MAX"	INTEGER DEFAULT -1,
	"PRI_RANGE_MIN"	FLOAT(52) DEFAULT -1,
	"PRI_RANGE_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_RATE_MIN"	FLOAT(52) DEFAULT -1,
	"PRI_RATE_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_SHIFT_VAL"	FLOAT(52) DEFAULT -1,
	"PRI_STABILITY"	FLOAT(52) DEFAULT -1,
	"PRI_STAB_PERIOD"	FLOAT(52) DEFAULT -1,
	"PRI_STANDARD_DEVIATION"	FLOAT(52) DEFAULT -1,
	"PRI_STEP_MIN"	FLOAT(52) DEFAULT -1,
	"PRI_STEP_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_SUBFRAME_PERIOD_MIN"	FLOAT(52) DEFAULT -1,
	"PRI_SUBFRAME_PERIOD_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_TYPICAL_MIN"	FLOAT(52) DEFAULT -1,
	"PRI_TYPICAL_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_XTAL_MIN"	FLOAT(52) DEFAULT -1,
	"PRI_XTAL_MAX"	FLOAT(52) DEFAULT -1,
	"PRI_XTAL_COUNT_MIN"	INTEGER DEFAULT -1,
	"PRI_XTAL_COUNT_MAX"	INTEGER DEFAULT -1,
	"PD_CONTINUITY"	INTEGER DEFAULT -1,
	"PD_DWELL_TIME_MIN"	FLOAT(52) DEFAULT -1,
	"PD_DWELL_TIME_MAX"	FLOAT(52) DEFAULT -1,
	"PD_EXTREME_MIN"	FLOAT(52) DEFAULT -1,
	"PD_EXTREME_MAX"	FLOAT(52) DEFAULT -1,
	"PD_TYPICAL_MIN"	FLOAT(52) DEFAULT -1,
	"PD_TYPICAL_MAX"	FLOAT(52) DEFAULT -1,
	"PD_NUM_ELEMENTS"	INTEGER DEFAULT -1,
	"PD_NUM_POSITIONS"	INTEGER DEFAULT -1,
	"PD_PATTERN"	INTEGER DEFAULT -1,
	"PD_PATTERN_PERIOD_MIN"	FLOAT(52) DEFAULT -1,
	"PD_PATTERN_PERIOD_MAX"	FLOAT(52) DEFAULT -1,
	"PD_PATTERN_DRIVER"	VARCHAR2(400) DEFAULT 'X',
	"PD_PATTERN_RULE"	VARCHAR2(400) DEFAULT 'X',
	"PD_RANGE_MIN"	FLOAT(52) DEFAULT -1,
	"PD_RANGE_MAX"	FLOAT(52) DEFAULT -1,
	"PD_RATE_MIN"	FLOAT(52) DEFAULT -1,
	"PD_RATE_MAX"	FLOAT(52) DEFAULT -1,
	"PD_STANDARD_DEVIATION"	FLOAT(52) DEFAULT -1,
	"PD_STEP_MIN"	FLOAT(52) DEFAULT -1,
	"PD_STEP_MAX"	FLOAT(52) DEFAULT -1,
	"PD_MEAN_MIN"	FLOAT(52) DEFAULT -1,
	"PD_MEAN_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_EXTENT_ELEVATION_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_EXTENT_ELEVATION_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_EXTENT_AZIMUTH_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_EXTENT_AZIMUTH_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_SLEW_RATE_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_SLEW_RATE_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_PATTERN_DRIVER"	VARCHAR2(400) DEFAULT 'X',
	"SCAN_PRIMARY_PATTERN_RULE"	VARCHAR2(400) DEFAULT 'X',
	"SCAN_PRIMARY_CONTINUITY"	INTEGER DEFAULT -1,
	"SCAN_PRIMARY_DWELL_TIME_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_DWELL_TIME_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_EXTREME_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_EXTREME_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_MEAN_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_MEAN_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_NUM_ELEMENTS"	INTEGER DEFAULT -1,
	"SCAN_PRIMARY_NUM_POSITIONS"	INTEGER DEFAULT -1,
	"SCAN_PRIMARY_PATTERN"	INTEGER DEFAULT -1,
	"SCAN_PRIMARY_PAT_PERIOD_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_PAT_PERIOD_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_RANGE_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_RANGE_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_RATE_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_RATE_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_STAND_DEVIATION"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_STEP_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_STEP_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_TYPICAL_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_PRIMARY_TYPICAL_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_PATTERN_DRIVER"	VARCHAR2(400) DEFAULT 'X',
	"SCAN_SECONDARY_PATTERN_RULE"	VARCHAR2(400) DEFAULT 'X',
	"SCAN_SECONDARY_CONTINUITY"	INTEGER DEFAULT -1,
	"SCAN_SECONDARY_DWELL_TIME_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_DWELL_TIME_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_EXTREME_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_EXTREME_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_MEAN_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_MEAN_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_NUM_ELEMENTS"	INTEGER DEFAULT -1,
	"SCAN_SECONDARY_NUM_POSITIONS"	INTEGER DEFAULT -1,
	"SCAN_SECONDARY_PATTERN"	INTEGER DEFAULT -1,
	"SCAN_SECONDARY_PAT_PERIOD_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_PAT_PERIOD_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_RANGE_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_RANGE_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_RATE_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_RATE_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_STAND_DEVIATION"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_STEP_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_STEP_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_TYPE"	INTEGER DEFAULT -1,
	"SCAN_SECONDARY_TYPICAL_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_SECONDARY_TYPICAL_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_UNIQUE_BEAM_POSITIONS"	INTEGER DEFAULT -1,
	"SCAN_START_POINT_ELEVATION_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_START_POINT_ELEVATION_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_START_POINT_AZIMUTH_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_START_POINT_AZIMUTH_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_END_POINT_ELEVATION_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_END_POINT_ELEVATION_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_END_POINT_AZIMUTH_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_END_POINT_AZIMUTH_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_SECT_BEAMWIDTH_RATIO_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_SECT_BEAMWIDTH_RATIO_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_BEAM_POS_PER_RASTER_MIN"	INTEGER DEFAULT -1,
	"SCAN_BEAM_POS_PER_RASTER_MAX"	INTEGER DEFAULT -1,
	"SCAN_BARS_PER_RASTER_MIN"	INTEGER DEFAULT -1,
	"SCAN_BARS_PER_RASTER_MAX"	INTEGER DEFAULT -1,
	"SCAN_AZIMUTH_COVERAGE"	FLOAT(52) DEFAULT -1,
	"SCAN_AZIMUTH_CENTER"	FLOAT(52) DEFAULT -1,
	"SCAN_HORIZONTAL_BEAMWIDTH_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_HORIZONTAL_BEAMWIDTH_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_VERTICAL_BEAMWIDTH_MIN"	FLOAT(52) DEFAULT -1,
	"SCAN_VERTICAL_BEAMWIDTH_MAX"	FLOAT(52) DEFAULT -1,
	"SCAN_DWELLS"	INTEGER DEFAULT -1,
	"SCAN_ELEVATION_STEP_TYPE"	INTEGER DEFAULT -1,
	"SCAN_ELEVATION_WIDTH"	FLOAT(52) DEFAULT -1,
	"SCAN_NUM_TURNS"	INTEGER DEFAULT -1,
	"HORIZON_AVG_SIDELOBE_LEVEL_MIN"	FLOAT(52) DEFAULT -1,
	"HORIZON_AVG_SIDELOBE_LEVEL_MAX"	FLOAT(52) DEFAULT -1,
	"VERT_AVG_SIDELOBE_LEVEL_MIN"	FLOAT(52) DEFAULT -1,
	"VERT_AVG_SIDELOBE_LEVEL_MAX"	FLOAT(52) DEFAULT -1,
	"COMMS_MULTIP_SCHEME"	VARCHAR2(20) DEFAULT 'X',
	"COMMS_MULTIP_TYPE"	VARCHAR2(20) DEFAULT 'X',
	"COMMS_MULTIP_LEVEL"	VARCHAR2(20) DEFAULT 'X',
	"COMMS_SUBCARRIER_MODULATION"	VARCHAR2(20) DEFAULT 'X',
	"COMMS_SUBCARRIER_RF"	FLOAT(52) DEFAULT -1,
	"COMMS_TONE"	FLOAT(52) DEFAULT -1,
	"COMMS_TONE_DURATION"	FLOAT(52) DEFAULT -1,
	"COMMS_SUBCARRIER_REST_RF"	FLOAT(52) DEFAULT -1,
	"COMMS_KEYING_RATE"	FLOAT(52) DEFAULT -1,
	"VALIDATION"	INTEGER NOT NULL DEFAULT 0,
	"MANUAL_REVISION"	INTEGER NOT NULL DEFAULT 0,
	"ACCEPTED"	INTEGER NOT NULL DEFAULT 1,
	"SRT_REVIEWED"	INTEGER NOT NULL DEFAULT 0,
	"PARENT_INDEX"	INTEGER DEFAULT -1,
	"DATE_CADCN"	TIMESTAMP(6) DEFAULT '1970/01/01 0:00:00.000',
	"HOR_FIRST_SIDELOBE_LEVEL_MIN"	FLOAT(52) DEFAULT -1,
	"HOR_FIRST_SIDELOBE_LEVEL_MAX"	FLOAT(52) DEFAULT -1,
	"HOR_SECOND_SIDELOBE_LEVEL_MIN"	FLOAT(52) DEFAULT -1,
	"HOR_SECOND_SIDELOBE_LEVEL_MAX"	FLOAT(52) DEFAULT -1,
	"HOR_THIRD_SIDELOBE_LEVEL_MIN"	FLOAT(52) DEFAULT -1,
	"HOR_THIRD_SIDELOBE_LEVEL_MAX"	FLOAT(52) DEFAULT -1,
	"VERT_FIRST_SIDELOBE_LEVEL_MIN"	FLOAT(52) DEFAULT -1,
	"VERT_FIRST_SIDELOBE_LEVEL_MAX"	FLOAT(52) DEFAULT -1,
	"VERT_SECOND_SIDELOBE_LEVEL_MIN"	FLOAT(52) DEFAULT -1,
	"VERT_SECOND_SIDELOBE_LEVEL_MAX"	FLOAT(52) DEFAULT -1,
	"VERT_THIRD_SIDELOBE_LEVEL_MIN"	FLOAT(52) DEFAULT -1,
	"VERT_THIRD_SIDELOBE_LEVEL_MAX"	FLOAT(52) DEFAULT -1,
	"RF_LEGACY_TYPE"	INTEGER DEFAULT -1,
	"PRI_LEGACY_TYPE"	INTEGER DEFAULT -1,
	"PD_LEGACY_TYPE"	INTEGER DEFAULT -1,
	"PD_RISE_MIN"	FLOAT(52) DEFAULT -1,
	"PD_RISE_MAX"	FLOAT(52) DEFAULT -1,
	"PD_FALL_MIN"	FLOAT(52) DEFAULT -1,
	"PD_FALL_MAX"	FLOAT(52) DEFAULT -1,
	"BLANKING_DURATION_MIN"	FLOAT(52) DEFAULT -1,
	"BLANKING_DURATION_MAX"	FLOAT(52) DEFAULT -1,
	"BLANKING_PERIOD_MIN"	FLOAT(52) DEFAULT -1,
	"BLANKING_PERIOD_MAX"	FLOAT(52) DEFAULT -1,
	"POWER_DIFFERENCE_MIN"	FLOAT(52) DEFAULT -1,
	"POWER_DIFFERENCE_MAX"	FLOAT(52) DEFAULT -1,
	"BANDWIDTH_INST_THREE_MIN"	FLOAT(52) DEFAULT -1,
	"BANDWIDTH_INST_THREE_MAX"	FLOAT(52) DEFAULT -1,
	"BANDWIDTH_INST_SIX_MIN"	FLOAT(52) DEFAULT -1,
	"BANDWIDTH_INST_SIX_MAX"	FLOAT(52) DEFAULT -1,
	"BANDWIDTH_INST_TEN_MIN"	FLOAT(52) DEFAULT -1,
	"BANDWIDTH_INST_TEN_MAX"	FLOAT(52) DEFAULT -1,
	"BANDWIDTH_INST_TWENTY_MIN"	FLOAT(52) DEFAULT -1,
	"BANDWIDTH_INST_TWENTY_MAX"	FLOAT(52) DEFAULT -1,
	"PARAM_ASSOC"	VARCHAR2(390) DEFAULT 'X',
	"SCAN_PRIMARY_TYPE"	INTEGER DEFAULT -1,
	"HOR_FIRST_SIDELOBE_POS_MIN"	FLOAT(52) DEFAULT -1,
	"HOR_FIRST_SIDELOBE_POS_MAX"	FLOAT(52) DEFAULT -1,
	"HOR_SECOND_SIDELOBE_POS_MIN"	FLOAT(52) DEFAULT -1,
	"HOR_SECOND_SIDELOBE_POS_MAX"	FLOAT(52) DEFAULT -1,
	"HOR_THIRD_SIDELOBE_POS_MIN"	FLOAT(52) DEFAULT -1,
	"HOR_THIRD_SIDELOBE_POS_MAX"	FLOAT(52) DEFAULT -1,
	"VERT_FIRST_SIDELOBE_POS_MIN"	FLOAT(52) DEFAULT -1,
	"VERT_FIRST_SIDELOBE_POS_MAX"	FLOAT(52) DEFAULT -1,
	"VERT_SECOND_SIDELOBE_POS_MIN"	FLOAT(52) DEFAULT -1,
	"VERT_SECOND_SIDELOBE_POS_MAX"	FLOAT(52) DEFAULT -1,
	"VERT_THIRD_SIDELOBE_POS_MIN"	FLOAT(52) DEFAULT -1,
	"VERT_THIRD_SIDELOBE_POS_MAX"	FLOAT(52) DEFAULT -1,
	"SECURITY_REVIEW_DATE"	TIMESTAMP(6) DEFAULT '1970/01/01 0:00:00.000',
	"ASSOC_INDEX"	INTEGER DEFAULT -1,
	"MODULATION_CODE"	VARCHAR2(2) DEFAULT 'ZZ',
	"PRIORITY"	INTEGER DEFAULT -1,
	"RF_TYPE"	INTEGER,
	"PRI_TYPE"	INTEGER,
	PRIMARY KEY("RADAR_MODE_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_MODE_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"FUNCTION_CODE"	VARCHAR2(2),
	"DATE_CREATED"	TIMESTAMP(6),
	"DATE_LAST_UPDATED"	TIMESTAMP(6),
	"DATE_LAST_REVIEWED"	TIMESTAMP(6),
	"DATE_FIRST_SEEN"	TIMESTAMP(6),
	"DATE_LAST_SEEN"	TIMESTAMP(6),
	"LAST_UPDATED_BY"	INTEGER,
	"SIGNAL_TYPE"	VARCHAR2(10) NOT NULL,
	"ERP_CONTINUITY"	INTEGER,
	"ERP_DWELL_TIME_MIN"	FLOAT(52),
	"ERP_DWELL_TIME_MAX"	FLOAT(52),
	"ERP_EXTREME_MIN"	FLOAT(52),
	"ERP_EXTREME_MAX"	FLOAT(52),
	"ERP_MEAN_MIN"	FLOAT(52),
	"ERP_MEAN_MAX"	FLOAT(52),
	"ERP_NUM_ELEMENTS"	INTEGER,
	"ERP_NUM_POSITIONS"	INTEGER,
	"ERP_PATTERN"	INTEGER,
	"ERP_PATTERN_DRIVER"	VARCHAR2(400),
	"ERP_PATTERN_RULE"	VARCHAR2(400),
	"ERP_PATTERN_PERIOD_MIN"	FLOAT(52),
	"ERP_PATTERN_PERIOD_MAX"	FLOAT(52),
	"ERP_RANGE_MIN"	FLOAT(52),
	"ERP_RANGE_MAX"	FLOAT(52),
	"ERP_RATE_MIN"	FLOAT(52),
	"ERP_RATE_MAX"	FLOAT(52),
	"ERP_STANDARD_DEVIATION"	FLOAT(52),
	"ERP_STEP_MIN"	FLOAT(52),
	"ERP_STEP_MAX"	FLOAT(52),
	"ERP_TYPICAL_MIN"	FLOAT(52),
	"ERP_TYPICAL_MAX"	FLOAT(52),
	"POLARIZATION"	INTEGER,
	"POL_AXIAL_RATIO_MIN"	FLOAT(52),
	"POL_AXIAL_RATIO_MAX"	FLOAT(52),
	"POL_TILT_ANGLE_PATTERN_DRIVER"	VARCHAR2(400),
	"POL_TILT_ANGLE_PATTERN_RULE"	VARCHAR2(400),
	"POL_TILT_ANGLE_RATE_MIN"	FLOAT(52),
	"POL_TILT_ANGLE_RATE_MAX"	FLOAT(52),
	"POL_TILT_ANGLE_CONTINUITY"	INTEGER,
	"POL_TILT_ANGLE_DWELL_TIME_MIN"	FLOAT(52),
	"POL_TILT_ANGLE_DWELL_TIME_MAX"	FLOAT(52),
	"POL_TILT_ANGLE_EXTREME_MIN"	FLOAT(52),
	"POL_TILT_ANGLE_EXTREME_MAX"	FLOAT(52),
	"POL_TILT_ANGLE_MEAN_MIN"	FLOAT(52),
	"POL_TILT_ANGLE_MEAN_MAX"	FLOAT(52),
	"POL_TILT_ANGLE_NUM_ELEMENTS"	INTEGER,
	"POL_TILT_ANGLE_NUM_POSITIONS"	INTEGER,
	"POL_TILT_ANGLE_PATTERN"	INTEGER,
	"POL_TILT_ANGLE_PAT_PERIOD_MIN"	FLOAT(52),
	"POL_TILT_ANGLE_PAT_PERIOD_MAX"	FLOAT(52),
	"POL_TILT_ANGLE_RANGE_MIN"	FLOAT(52),
	"POL_TILT_ANGLE_RANGE_MAX"	FLOAT(52),
	"POL_TILT_ANGLE_STEP_MIN"	FLOAT(52),
	"POL_TILT_ANGLE_STEP_MAX"	FLOAT(52),
	"POL_TILT_ANGLE_TYPICAL_MIN"	FLOAT(52),
	"POL_TILT_ANGLE_TYPICAL_MAX"	FLOAT(52),
	"POL_TILT_ANGLE_STAND_DEVIATION"	FLOAT(52),
	"POL_ROTATION_DIRECTION"	INTEGER,
	"POL_ROTATION_FREQUENCY_MIN"	FLOAT(52),
	"POL_ROTATION_FREQUENCY_MAX"	FLOAT(52),
	"POL_SENSE"	INTEGER,
	"PLATFORM"	INTEGER,
	"RF_EXTREME_MIN"	FLOAT(52),
	"RF_EXTREME_MAX"	FLOAT(52),
	"RF_TYPICAL_MIN"	FLOAT(52),
	"RF_TYPICAL_MAX"	FLOAT(52),
	"BANDWIDTH_OPER_MIN"	FLOAT(52),
	"BANDWIDTH_OPER_MAX"	FLOAT(52),
	"RF_CHANNEL_SPACING_MIN"	FLOAT(52),
	"RF_CHANNEL_SPACING_MAX"	FLOAT(52),
	"RF_CHIP_RATE"	FLOAT(52),
	"RF_CONTINUITY"	INTEGER,
	"RF_DWELL_TIME_MIN"	FLOAT(52),
	"RF_DWELL_TIME_MAX"	FLOAT(52),
	"RF_GUARD_BAND"	FLOAT(52),
	"RF_NUM_SIMULTANEOUS"	INTEGER,
	"RF_REST_MIN"	FLOAT(52),
	"RF_REST_MAX"	FLOAT(52),
	"RF_SLOT_DURATION"	FLOAT(52),
	"RF_PATTERN"	INTEGER DEFAULT -1,
	"RF_NUM_CHANNELS"	INTEGER,
	"RF_NUM_ELEMENTS"	INTEGER,
	"RF_NUM_POSITIONS"	INTEGER,
	"RF_PATTERN_PERIOD_MIN"	FLOAT(52),
	"RF_PATTERN_PERIOD_MAX"	FLOAT(52),
	"RF_STANDARD_DEVIATION"	FLOAT(52),
	"RF_RANGE_MIN"	FLOAT(52),
	"RF_RANGE_MAX"	FLOAT(52),
	"RF_RATE_MIN"	FLOAT(52),
	"RF_RATE_MAX"	FLOAT(52),
	"RF_STEP_MIN"	FLOAT(52),
	"RF_STEP_MAX"	FLOAT(52),
	"RF_PATTERN_DRIVER"	VARCHAR2(400),
	"RF_PATTERN_RULE"	VARCHAR2(400),
	"RF_STABILITY"	FLOAT(52),
	"RF_STAB_PERIOD"	FLOAT(52),
	"RF_COHERENCY"	INTEGER,
	"RF_MEAN_MIN"	FLOAT(52),
	"RF_MEAN_MAX"	FLOAT(52),
	"RF_XTAL_MIN"	FLOAT(52),
	"RF_XTAL_MAX"	FLOAT(52),
	"PRI_CONTINUITY"	INTEGER,
	"PRI_DWELL_TIME_MIN"	FLOAT(52),
	"PRI_DWELL_TIME_MAX"	FLOAT(52),
	"PRI_EXTREME_MIN"	FLOAT(52),
	"PRI_EXTREME_MAX"	FLOAT(52),
	"PRI_FRAME_PERIOD_MIN"	FLOAT(52),
	"PRI_FRAME_PERIOD_MAX"	FLOAT(52),
	"PRI_GROUP_FORM"	INTEGER,
	"PRI_GROUP_DWELL"	FLOAT(52),
	"PRI_GROUP_TRANS_MIN"	FLOAT(52),
	"PRI_GROUP_TRANS_MAX"	FLOAT(52),
	"PRI_MEAN_MIN"	FLOAT(52),
	"PRI_MEAN_MAX"	FLOAT(52),
	"PRI_NUM_ELEMENTS"	INTEGER,
	"PRI_NUM_POSITIONS"	INTEGER,
	"PRI_PATTERN"	INTEGER DEFAULT -1,
	"PRI_PATTERN_DRIVER"	VARCHAR2(400),
	"PRI_PATTERN_RULE"	VARCHAR2(400),
	"PRI_PATTERN_PERIOD_MIN"	FLOAT(52),
	"PRI_PATTERN_PERIOD_MAX"	FLOAT(52),
	"PRI_PATTERN_PERIOD_COUNT_MIN"	INTEGER,
	"PRI_PATTERN_PERIOD_COUNT_MAX"	INTEGER,
	"PRI_PPG_MIN"	INTEGER,
	"PRI_PPG_MAX"	INTEGER,
	"PRI_RANGE_MIN"	FLOAT(52),
	"PRI_RANGE_MAX"	FLOAT(52),
	"PRI_RATE_MIN"	FLOAT(52),
	"PRI_RATE_MAX"	FLOAT(52),
	"PRI_SHIFT_VAL"	FLOAT(52),
	"PRI_STABILITY"	FLOAT(52),
	"PRI_STAB_PERIOD"	FLOAT(52),
	"PRI_STANDARD_DEVIATION"	FLOAT(52),
	"PRI_STEP_MIN"	FLOAT(52),
	"PRI_STEP_MAX"	FLOAT(52),
	"PRI_SUBFRAME_PERIOD_MIN"	FLOAT(52),
	"PRI_SUBFRAME_PERIOD_MAX"	FLOAT(52),
	"PRI_TYPICAL_MIN"	FLOAT(52),
	"PRI_TYPICAL_MAX"	FLOAT(52),
	"PRI_XTAL_MIN"	FLOAT(52),
	"PRI_XTAL_MAX"	FLOAT(52),
	"PRI_XTAL_COUNT_MIN"	INTEGER,
	"PRI_XTAL_COUNT_MAX"	INTEGER,
	"PD_CONTINUITY"	INTEGER,
	"PD_DWELL_TIME_MIN"	FLOAT(52),
	"PD_DWELL_TIME_MAX"	FLOAT(52),
	"PD_EXTREME_MIN"	FLOAT(52),
	"PD_EXTREME_MAX"	FLOAT(52),
	"PD_TYPICAL_MIN"	FLOAT(52),
	"PD_TYPICAL_MAX"	FLOAT(52),
	"PD_NUM_ELEMENTS"	INTEGER,
	"PD_NUM_POSITIONS"	INTEGER,
	"PD_PATTERN"	INTEGER,
	"PD_PATTERN_PERIOD_MIN"	FLOAT(52),
	"PD_PATTERN_PERIOD_MAX"	FLOAT(52),
	"PD_PATTERN_DRIVER"	VARCHAR2(400),
	"PD_PATTERN_RULE"	VARCHAR2(400),
	"PD_RANGE_MIN"	FLOAT(52),
	"PD_RANGE_MAX"	FLOAT(52),
	"PD_RATE_MIN"	FLOAT(52),
	"PD_RATE_MAX"	FLOAT(52),
	"PD_STANDARD_DEVIATION"	FLOAT(52),
	"PD_STEP_MIN"	FLOAT(52),
	"PD_STEP_MAX"	FLOAT(52),
	"PD_MEAN_MIN"	FLOAT(52),
	"PD_MEAN_MAX"	FLOAT(52),
	"SCAN_EXTENT_ELEVATION_MIN"	FLOAT(52),
	"SCAN_EXTENT_ELEVATION_MAX"	FLOAT(52),
	"SCAN_EXTENT_AZIMUTH_MIN"	FLOAT(52),
	"SCAN_EXTENT_AZIMUTH_MAX"	FLOAT(52),
	"SCAN_SLEW_RATE_MIN"	FLOAT(52),
	"SCAN_SLEW_RATE_MAX"	FLOAT(52),
	"SCAN_PRIMARY_PATTERN_DRIVER"	VARCHAR2(400),
	"SCAN_PRIMARY_PATTERN_RULE"	VARCHAR2(400),
	"SCAN_PRIMARY_CONTINUITY"	INTEGER,
	"SCAN_PRIMARY_DWELL_TIME_MIN"	FLOAT(52),
	"SCAN_PRIMARY_DWELL_TIME_MAX"	FLOAT(52),
	"SCAN_PRIMARY_EXTREME_MIN"	FLOAT(52),
	"SCAN_PRIMARY_EXTREME_MAX"	FLOAT(52),
	"SCAN_PRIMARY_MEAN_MIN"	FLOAT(52),
	"SCAN_PRIMARY_MEAN_MAX"	FLOAT(52),
	"SCAN_PRIMARY_NUM_ELEMENTS"	INTEGER,
	"SCAN_PRIMARY_NUM_POSITIONS"	INTEGER,
	"SCAN_PRIMARY_PATTERN"	INTEGER,
	"SCAN_PRIMARY_PAT_PERIOD_MIN"	FLOAT(52),
	"SCAN_PRIMARY_PAT_PERIOD_MAX"	FLOAT(52),
	"SCAN_PRIMARY_RANGE_MIN"	FLOAT(52),
	"SCAN_PRIMARY_RANGE_MAX"	FLOAT(52),
	"SCAN_PRIMARY_RATE_MIN"	FLOAT(52),
	"SCAN_PRIMARY_RATE_MAX"	FLOAT(52),
	"SCAN_PRIMARY_STAND_DEVIATION"	FLOAT(52),
	"SCAN_PRIMARY_STEP_MIN"	FLOAT(52),
	"SCAN_PRIMARY_STEP_MAX"	FLOAT(52),
	"SCAN_PRIMARY_TYPICAL_MIN"	FLOAT(52),
	"SCAN_PRIMARY_TYPICAL_MAX"	FLOAT(52),
	"SCAN_SECONDARY_PATTERN_DRIVER"	VARCHAR2(400),
	"SCAN_SECONDARY_PATTERN_RULE"	VARCHAR2(400),
	"SCAN_SECONDARY_CONTINUITY"	INTEGER,
	"SCAN_SECONDARY_DWELL_TIME_MIN"	FLOAT(52),
	"SCAN_SECONDARY_DWELL_TIME_MAX"	FLOAT(52),
	"SCAN_SECONDARY_EXTREME_MIN"	FLOAT(52),
	"SCAN_SECONDARY_EXTREME_MAX"	FLOAT(52),
	"SCAN_SECONDARY_MEAN_MIN"	FLOAT(52),
	"SCAN_SECONDARY_MEAN_MAX"	FLOAT(52),
	"SCAN_SECONDARY_NUM_ELEMENTS"	INTEGER,
	"SCAN_SECONDARY_NUM_POSITIONS"	INTEGER,
	"SCAN_SECONDARY_PATTERN"	INTEGER,
	"SCAN_SECONDARY_PAT_PERIOD_MIN"	FLOAT(52),
	"SCAN_SECONDARY_PAT_PERIOD_MAX"	FLOAT(52),
	"SCAN_SECONDARY_RANGE_MIN"	FLOAT(52),
	"SCAN_SECONDARY_RANGE_MAX"	FLOAT(52),
	"SCAN_SECONDARY_RATE_MIN"	FLOAT(52),
	"SCAN_SECONDARY_RATE_MAX"	FLOAT(52),
	"SCAN_SECONDARY_STAND_DEVIATION"	FLOAT(52),
	"SCAN_SECONDARY_STEP_MIN"	FLOAT(52),
	"SCAN_SECONDARY_STEP_MAX"	FLOAT(52),
	"SCAN_SECONDARY_TYPE"	INTEGER,
	"SCAN_SECONDARY_TYPICAL_MIN"	FLOAT(52),
	"SCAN_SECONDARY_TYPICAL_MAX"	FLOAT(52),
	"SCAN_UNIQUE_BEAM_POSITIONS"	INTEGER,
	"SCAN_START_POINT_ELEVATION_MIN"	FLOAT(52),
	"SCAN_START_POINT_ELEVATION_MAX"	FLOAT(52),
	"SCAN_START_POINT_AZIMUTH_MIN"	FLOAT(52),
	"SCAN_START_POINT_AZIMUTH_MAX"	FLOAT(52),
	"SCAN_END_POINT_ELEVATION_MIN"	FLOAT(52),
	"SCAN_END_POINT_ELEVATION_MAX"	FLOAT(52),
	"SCAN_END_POINT_AZIMUTH_MIN"	FLOAT(52),
	"SCAN_END_POINT_AZIMUTH_MAX"	FLOAT(52),
	"SCAN_SECT_BEAMWIDTH_RATIO_MIN"	FLOAT(52),
	"SCAN_SECT_BEAMWIDTH_RATIO_MAX"	FLOAT(52),
	"SCAN_BEAM_POS_PER_RASTER_MIN"	INTEGER,
	"SCAN_BEAM_POS_PER_RASTER_MAX"	INTEGER,
	"SCAN_BARS_PER_RASTER_MIN"	INTEGER,
	"SCAN_BARS_PER_RASTER_MAX"	INTEGER,
	"SCAN_AZIMUTH_COVERAGE"	FLOAT(52),
	"SCAN_AZIMUTH_CENTER"	FLOAT(52),
	"SCAN_HORIZONTAL_BEAMWIDTH_MIN"	FLOAT(52),
	"SCAN_HORIZONTAL_BEAMWIDTH_MAX"	FLOAT(52),
	"SCAN_VERTICAL_BEAMWIDTH_MIN"	FLOAT(52),
	"SCAN_VERTICAL_BEAMWIDTH_MAX"	FLOAT(52),
	"SCAN_DWELLS"	INTEGER,
	"SCAN_ELEVATION_STEP_TYPE"	INTEGER,
	"SCAN_ELEVATION_WIDTH"	FLOAT(52),
	"SCAN_NUM_TURNS"	INTEGER,
	"HORIZON_AVG_SIDELOBE_LEVEL_MIN"	FLOAT(52),
	"HORIZON_AVG_SIDELOBE_LEVEL_MAX"	FLOAT(52),
	"VERT_AVG_SIDELOBE_LEVEL_MIN"	FLOAT(52),
	"VERT_AVG_SIDELOBE_LEVEL_MAX"	FLOAT(52),
	"COMMS_MULTIP_SCHEME"	VARCHAR2(20),
	"COMMS_MULTIP_TYPE"	VARCHAR2(20),
	"COMMS_MULTIP_LEVEL"	VARCHAR2(20),
	"COMMS_SUBCARRIER_MODULATION"	VARCHAR2(20),
	"COMMS_SUBCARRIER_RF"	FLOAT(52),
	"COMMS_TONE"	FLOAT(52),
	"COMMS_TONE_DURATION"	FLOAT(52),
	"COMMS_SUBCARRIER_REST_RF"	FLOAT(52),
	"COMMS_KEYING_RATE"	FLOAT(52),
	"VALIDATION"	INTEGER NOT NULL DEFAULT 0,
	"MANUAL_REVISION"	INTEGER NOT NULL DEFAULT 0,
	"ACCEPTED"	INTEGER NOT NULL DEFAULT 1,
	"SRT_REVIEWED"	INTEGER NOT NULL DEFAULT 0,
	"PARENT_INDEX"	INTEGER,
	"DATE_CADCN"	TIMESTAMP(6),
	"HOR_FIRST_SIDELOBE_LEVEL_MIN"	FLOAT(52),
	"HOR_FIRST_SIDELOBE_LEVEL_MAX"	FLOAT(52),
	"HOR_SECOND_SIDELOBE_LEVEL_MIN"	FLOAT(52),
	"HOR_SECOND_SIDELOBE_LEVEL_MAX"	FLOAT(52),
	"HOR_THIRD_SIDELOBE_LEVEL_MIN"	FLOAT(52),
	"HOR_THIRD_SIDELOBE_LEVEL_MAX"	FLOAT(52),
	"VERT_FIRST_SIDELOBE_LEVEL_MIN"	FLOAT(52),
	"VERT_FIRST_SIDELOBE_LEVEL_MAX"	FLOAT(52),
	"VERT_SECOND_SIDELOBE_LEVEL_MIN"	FLOAT(52),
	"VERT_SECOND_SIDELOBE_LEVEL_MAX"	FLOAT(52),
	"VERT_THIRD_SIDELOBE_LEVEL_MIN"	FLOAT(52),
	"VERT_THIRD_SIDELOBE_LEVEL_MAX"	FLOAT(52),
	"RF_LEGACY_TYPE"	INTEGER DEFAULT -1,
	"PRI_LEGACY_TYPE"	INTEGER DEFAULT -1,
	"PD_LEGACY_TYPE"	INTEGER DEFAULT -1,
	"PD_RISE_MIN"	FLOAT(52),
	"PD_RISE_MAX"	FLOAT(52),
	"PD_FALL_MIN"	FLOAT(52),
	"PD_FALL_MAX"	FLOAT(52),
	"BLANKING_DURATION_MIN"	FLOAT(52),
	"BLANKING_DURATION_MAX"	FLOAT(52),
	"BLANKING_PERIOD_MIN"	FLOAT(52),
	"BLANKING_PERIOD_MAX"	FLOAT(52),
	"POWER_DIFFERENCE_MIN"	FLOAT(52),
	"POWER_DIFFERENCE_MAX"	FLOAT(52),
	"BANDWIDTH_INST_THREE_MIN"	FLOAT(52),
	"BANDWIDTH_INST_THREE_MAX"	FLOAT(52),
	"BANDWIDTH_INST_SIX_MIN"	FLOAT(52),
	"BANDWIDTH_INST_SIX_MAX"	FLOAT(52),
	"BANDWIDTH_INST_TEN_MIN"	FLOAT(52),
	"BANDWIDTH_INST_TEN_MAX"	FLOAT(52),
	"BANDWIDTH_INST_TWENTY_MIN"	FLOAT(52),
	"BANDWIDTH_INST_TWENTY_MAX"	FLOAT(52),
	"PARAM_ASSOC"	VARCHAR2(390),
	"SCAN_PRIMARY_TYPE"	INTEGER,
	"HOR_FIRST_SIDELOBE_POS_MIN"	FLOAT(52),
	"HOR_FIRST_SIDELOBE_POS_MAX"	FLOAT(52),
	"HOR_SECOND_SIDELOBE_POS_MIN"	FLOAT(52),
	"HOR_SECOND_SIDELOBE_POS_MAX"	FLOAT(52),
	"HOR_THIRD_SIDELOBE_POS_MIN"	FLOAT(52),
	"HOR_THIRD_SIDELOBE_POS_MAX"	FLOAT(52),
	"VERT_FIRST_SIDELOBE_POS_MIN"	FLOAT(52),
	"VERT_FIRST_SIDELOBE_POS_MAX"	FLOAT(52),
	"VERT_SECOND_SIDELOBE_POS_MIN"	FLOAT(52),
	"VERT_SECOND_SIDELOBE_POS_MAX"	FLOAT(52),
	"VERT_THIRD_SIDELOBE_POS_MIN"	FLOAT(52),
	"VERT_THIRD_SIDELOBE_POS_MAX"	FLOAT(52),
	"SECURITY_REVIEW_DATE"	TIMESTAMP(6),
	"ASSOC_INDEX"	INTEGER,
	"MODULATION_CODE"	VARCHAR2(2),
	"PRIORITY"	INTEGER,
	"RF_TYPE"	INTEGER,
	"PRI_TYPE"	INTEGER,
	PRIMARY KEY("RADAR_MODE_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_MODE_COMMENTS" (
	"RADAR_MODE_COMMENT_INDEX"	INTEGER NOT NULL,
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"TITLE"	VARCHAR2(30) NOT NULL,
	"DATE_CREATED"	TIMESTAMP(6) NOT NULL,
	"DATE_LAST_UPDATED"	TIMESTAMP(6) NOT NULL,
	"TYPE"	VARCHAR2(10) NOT NULL,
	"COMMENTS"	CLOB,
	"THIRD_PARTY_RELEASABLE"	INTEGER,
	"SECURITY_REVIEW_DATE"	TIMESTAMP(6),
	"COMMENT_ORDER"	INTEGER,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","RADAR_MODE_COMMENT_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_MODE_COMMENTS_P" (
	"RADAR_MODE_COMMENT_INDEX"	INTEGER NOT NULL,
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"TITLE"	VARCHAR2(30) NOT NULL,
	"DATE_CREATED"	TIMESTAMP(6) NOT NULL,
	"DATE_LAST_UPDATED"	TIMESTAMP(6) NOT NULL,
	"TYPE"	VARCHAR2(10) NOT NULL,
	"COMMENTS"	CLOB,
	"THIRD_PARTY_RELEASABLE"	INTEGER,
	"SECURITY_REVIEW_DATE"	TIMESTAMP(6),
	"COMMENT_ORDER"	INTEGER,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","RADAR_MODE_COMMENT_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_MODE_LIFECYCLE" (
	"RADAR_INDEX"	INTEGER NOT NULL,
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"RADAR_MODE_NAME"	VARCHAR2(30) NOT NULL,
	"MODE_CODE"	VARCHAR2(5) NOT NULL,
	"SECLAB"	INTEGER NOT NULL DEFAULT NULL,
	PRIMARY KEY("RADAR_INDEX","RADAR_MODE_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_MODE_LIFECYCLE_P" (
	"RADAR_INDEX"	INTEGER NOT NULL,
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"RADAR_MODE_NAME"	VARCHAR2(30) NOT NULL,
	"MODE_CODE"	VARCHAR2(5) NOT NULL,
	"SECLAB"	INTEGER NOT NULL DEFAULT NULL,
	PRIMARY KEY("RADAR_INDEX","RADAR_MODE_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_PD_VALUES" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PD_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"PD_MIN"	FLOAT(52) NOT NULL,
	"PD_MAX"	FLOAT(52) NOT NULL,
	"PD_RISE_MIN"	FLOAT(52),
	"PD_RISE_MAX"	FLOAT(52),
	"PD_FALL_MIN"	FLOAT(52),
	"PD_FALL_MAX"	FLOAT(52),
	PRIMARY KEY("RADAR_MODE_INDEX","PD_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_PD_VALUES_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PD_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"PD_MIN"	FLOAT(52) NOT NULL,
	"PD_MAX"	FLOAT(52) NOT NULL,
	"PD_RISE_MIN"	FLOAT(52),
	"PD_RISE_MAX"	FLOAT(52),
	"PD_FALL_MIN"	FLOAT(52),
	"PD_FALL_MAX"	FLOAT(52),
	PRIMARY KEY("RADAR_MODE_INDEX","PD_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_PD_SEQUENCE_NAME" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PD_SEQ_ID"	INTEGER NOT NULL,
	"PD_SEQ_NAME"	VARCHAR2(32),
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","PD_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_PD_SEQUENCE_NAME_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PD_SEQ_ID"	INTEGER NOT NULL,
	"PD_SEQ_NAME"	VARCHAR2(32),
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","PD_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_PD_SEQUENCE" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PD_SEQUENCE_NUM"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"PD_INDEX"	INTEGER NOT NULL,
	"PD_SEQ_ID"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("RADAR_MODE_INDEX","PD_SEQUENCE_NUM","PD_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_PD_SEQUENCE_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PD_SEQUENCE_NUM"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"PD_INDEX"	INTEGER NOT NULL,
	"PD_SEQ_ID"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("RADAR_MODE_INDEX","PD_SEQUENCE_NUM","PD_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_PD_SPOT_VALUES" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PD_MIN"	FLOAT(52) NOT NULL,
	"PD_MAX"	FLOAT(52) NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","PD_MIN","PD_MAX")
);
CREATE TABLE IF NOT EXISTS "RADAR_PD_SPOT_VALUES_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PD_MIN"	FLOAT(52) NOT NULL,
	"PD_MAX"	FLOAT(52) NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","PD_MIN","PD_MAX")
);
CREATE TABLE IF NOT EXISTS "RADAR_RF_VALUES" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"RF_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"RF_MIN"	FLOAT(52) NOT NULL,
	"RF_MAX"	FLOAT(52) NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","RF_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_RF_VALUES_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"RF_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"RF_MIN"	FLOAT(52) NOT NULL,
	"RF_MAX"	FLOAT(52) NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","RF_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_RF_SEQUENCE_NAME" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"RF_SEQ_ID"	INTEGER NOT NULL,
	"RF_SEQ_NAME"	VARCHAR2(32),
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","RF_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_RF_SEQUENCE_NAME_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"RF_SEQ_ID"	INTEGER NOT NULL,
	"RF_SEQ_NAME"	VARCHAR2(32),
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","RF_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_RF_SEQUENCE" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"RF_SEQUENCE_NUM"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"RF_INDEX"	INTEGER NOT NULL,
	"RF_SEQ_ID"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("RADAR_MODE_INDEX","RF_SEQUENCE_NUM","RF_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_RF_SEQUENCE_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"RF_SEQUENCE_NUM"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"RF_INDEX"	INTEGER NOT NULL,
	"RF_SEQ_ID"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("RADAR_MODE_INDEX","RF_SEQUENCE_NUM","RF_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_RF_SPOT_VALUES" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"RF_MIN"	FLOAT(52) NOT NULL,
	"RF_MAX"	FLOAT(52) NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","RF_MIN","RF_MAX")
);
CREATE TABLE IF NOT EXISTS "RADAR_RF_SPOT_VALUES_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"RF_MIN"	FLOAT(52) NOT NULL,
	"RF_MAX"	FLOAT(52) NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","RF_MIN","RF_MAX")
);
CREATE TABLE IF NOT EXISTS "RADAR_PRI_VALUES" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PRI_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"PRI_MIN"	FLOAT(52) NOT NULL,
	"PRI_MAX"	FLOAT(52) NOT NULL,
	"DWELL_DURATION_MIN"	FLOAT(52),
	"DWELL_DURATION_MAX"	FLOAT(52),
	"PULSES_PER_DWELL"	INTEGER,
	"TRANSITION_MIN"	FLOAT(52),
	"TRANSITION_MAX"	FLOAT(52),
	PRIMARY KEY("RADAR_MODE_INDEX","PRI_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_PRI_VALUES_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PRI_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"PRI_MIN"	FLOAT(52) NOT NULL,
	"PRI_MAX"	FLOAT(52) NOT NULL,
	"DWELL_DURATION_MIN"	FLOAT(52),
	"DWELL_DURATION_MAX"	FLOAT(52),
	"PULSES_PER_DWELL"	INTEGER,
	"TRANSITION_MIN"	FLOAT(52),
	"TRANSITION_MAX"	FLOAT(52),
	PRIMARY KEY("RADAR_MODE_INDEX","PRI_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_PRI_SEQUENCE_NAME" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PRI_SEQ_ID"	INTEGER NOT NULL,
	"PRI_SEQ_NAME"	VARCHAR2(32),
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","PRI_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_PRI_SEQUENCE_NAME_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PRI_SEQ_ID"	INTEGER NOT NULL,
	"PRI_SEQ_NAME"	VARCHAR2(32),
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","PRI_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_PRI_SEQUENCE" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PRI_SEQUENCE_NUM"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"PRI_INDEX"	INTEGER NOT NULL,
	"PULSES_PER_DWELL"	INTEGER,
	"PRI_SEQ_ID"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("RADAR_MODE_INDEX","PRI_SEQUENCE_NUM","PRI_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_PRI_SEQUENCE_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PRI_SEQUENCE_NUM"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"PRI_INDEX"	INTEGER NOT NULL,
	"PULSES_PER_DWELL"	INTEGER,
	"PRI_SEQ_ID"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("RADAR_MODE_INDEX","PRI_SEQUENCE_NUM","PRI_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_PRI_SPOT_VALUES" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PRI_MIN"	FLOAT(52) NOT NULL,
	"PRI_MAX"	FLOAT(52) NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","PRI_MIN","PRI_MAX")
);
CREATE TABLE IF NOT EXISTS "RADAR_PRI_SPOT_VALUES_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"PRI_MIN"	FLOAT(52) NOT NULL,
	"PRI_MAX"	FLOAT(52) NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","PRI_MIN","PRI_MAX")
);
CREATE TABLE IF NOT EXISTS "RADAR_PRI_GROUP_SPACING" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"SEQUENCE_NUM"	INTEGER NOT NULL,
	"GROUP_SPACING"	FLOAT(52) NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","SEQUENCE_NUM")
);
CREATE TABLE IF NOT EXISTS "RADAR_PRI_GROUP_SPACING_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"SEQUENCE_NUM"	INTEGER NOT NULL,
	"GROUP_SPACING"	FLOAT(52) NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","SEQUENCE_NUM")
);
CREATE TABLE IF NOT EXISTS "RADAR_MOP_CW" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"MOP_CW_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"MOP_CW_MODULATION_TYPE"	INTEGER,
	"MOP_CW_BIT_DURATION_MIN"	FLOAT(52),
	"MOP_CW_BIT_DURATION_MAX"	FLOAT(52),
	"MOP_CW_CONTINUITY"	INTEGER,
	"MOP_CW_NUM_ELEMENTS"	INTEGER,
	"MOP_CW_NUM_POSITIONS"	INTEGER,
	"MOP_CW_PATTERN"	INTEGER,
	"MOP_CW_PATTERN_DRIVER"	VARCHAR2(400),
	"MOP_CW_PATTERN_PERIOD_MIN"	FLOAT(52),
	"MOP_CW_PATTERN_PERIOD_MAX"	FLOAT(52),
	"MOP_CW_PATTERN_RULE"	VARCHAR2(400),
	"MOP_CW_RANGE_MIN"	FLOAT(52),
	"MOP_CW_RANGE_MAX"	FLOAT(52),
	"MOP_CW_RATE_MIN"	FLOAT(52),
	"MOP_CW_RATE_MAX"	FLOAT(52),
	"MOP_CW_STANDARD_DEVIATION"	FLOAT(52),
	"MOP_CW_STEP_MIN"	FLOAT(52),
	"MOP_CW_STEP_MAX"	FLOAT(52),
	"MOP_CW_MEAN_MIN"	FLOAT(52),
	"MOP_CW_MEAN_MAX"	FLOAT(52),
	"PD_INDEX"	INTEGER,
	"MOP_CW_LEGACY_TYPE"	INTEGER,
	"MOP_CW_PATTERN_NAME"	VARCHAR2(20),
	"MOP_CW_ON_TIME_MIN"	FLOAT(52),
	"MOP_CW_ON_TIME_MAX"	FLOAT(52),
	"MOP_CW_OFF_TIME_MIN"	FLOAT(52),
	"MOP_CW_OFF_TIME_MAX"	FLOAT(52),
	"MOP_CW_BIT_SEQ_LENGTH_MIN"	INTEGER,
	"MOP_CW_BIT_SEQ_LENGTH_MAX"	INTEGER,
	"MOP_CW_DUTY_CYCLE_MIN"	FLOAT(52),
	"MOP_CW_DUTY_CYCLE_MAX"	FLOAT(52),
	"SPECTRAL_COMPONENTS_MIN"	FLOAT(52),
	"SPECTRAL_COMPONENTS_MAX"	FLOAT(52),
	"LOOK_THROUGH_DURATION_MIN"	FLOAT(52),
	"LOOK_THROUGH_DURATION_MAX"	FLOAT(52),
	"LOOK_THROUGH_PERIOD_MIN"	FLOAT(52),
	"LOOK_THROUGH_PERIOD_MAX"	FLOAT(52),
	"MOP_CW_TIME_BANDWIDTH_PRODUCT"	INTEGER,
	PRIMARY KEY("RADAR_MODE_INDEX","MOP_CW_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_MOP_CW_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"MOP_CW_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"MOP_CW_MODULATION_TYPE"	INTEGER,
	"MOP_CW_BIT_DURATION_MIN"	FLOAT(52),
	"MOP_CW_BIT_DURATION_MAX"	FLOAT(52),
	"MOP_CW_CONTINUITY"	INTEGER,
	"MOP_CW_NUM_ELEMENTS"	INTEGER,
	"MOP_CW_NUM_POSITIONS"	INTEGER,
	"MOP_CW_PATTERN"	INTEGER,
	"MOP_CW_PATTERN_DRIVER"	VARCHAR2(400),
	"MOP_CW_PATTERN_PERIOD_MIN"	FLOAT(52),
	"MOP_CW_PATTERN_PERIOD_MAX"	FLOAT(52),
	"MOP_CW_PATTERN_RULE"	VARCHAR2(400),
	"MOP_CW_RANGE_MIN"	FLOAT(52),
	"MOP_CW_RANGE_MAX"	FLOAT(52),
	"MOP_CW_RATE_MIN"	FLOAT(52),
	"MOP_CW_RATE_MAX"	FLOAT(52),
	"MOP_CW_STANDARD_DEVIATION"	FLOAT(52),
	"MOP_CW_STEP_MIN"	FLOAT(52),
	"MOP_CW_STEP_MAX"	FLOAT(52),
	"MOP_CW_MEAN_MIN"	FLOAT(52),
	"MOP_CW_MEAN_MAX"	FLOAT(52),
	"PD_INDEX"	INTEGER,
	"MOP_CW_LEGACY_TYPE"	INTEGER,
	"MOP_CW_PATTERN_NAME"	VARCHAR2(20),
	"MOP_CW_ON_TIME_MIN"	FLOAT(52),
	"MOP_CW_ON_TIME_MAX"	FLOAT(52),
	"MOP_CW_OFF_TIME_MIN"	FLOAT(52),
	"MOP_CW_OFF_TIME_MAX"	FLOAT(52),
	"MOP_CW_BIT_SEQ_LENGTH_MIN"	INTEGER,
	"MOP_CW_BIT_SEQ_LENGTH_MAX"	INTEGER,
	"MOP_CW_DUTY_CYCLE_MIN"	FLOAT(52),
	"MOP_CW_DUTY_CYCLE_MAX"	FLOAT(52),
	"SPECTRAL_COMPONENTS_MIN"	FLOAT(52),
	"SPECTRAL_COMPONENTS_MAX"	FLOAT(52),
	"LOOK_THROUGH_DURATION_MIN"	FLOAT(52),
	"LOOK_THROUGH_DURATION_MAX"	FLOAT(52),
	"LOOK_THROUGH_PERIOD_MIN"	FLOAT(52),
	"LOOK_THROUGH_PERIOD_MAX"	FLOAT(52),
	"MOP_CW_TIME_BANDWIDTH_PRODUCT"	INTEGER,
	PRIMARY KEY("RADAR_MODE_INDEX","MOP_CW_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_MOP_CW_VALUES" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"MOP_CW_INDEX"	INTEGER NOT NULL,
	"MOP_CW_VALUE_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"MOP_CW_MIN"	FLOAT(52) NOT NULL,
	"MOP_CW_MAX"	FLOAT(52) NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","MOP_CW_INDEX","MOP_CW_VALUE_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_MOP_CW_VALUES_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"MOP_CW_INDEX"	INTEGER NOT NULL,
	"MOP_CW_VALUE_INDEX"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"MOP_CW_MIN"	FLOAT(52) NOT NULL,
	"MOP_CW_MAX"	FLOAT(52) NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","MOP_CW_INDEX","MOP_CW_VALUE_INDEX")
);
CREATE TABLE IF NOT EXISTS "RADAR_MOP_CW_SEQ_NAME" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"MOP_CW_INDEX"	INTEGER NOT NULL,
	"MOP_CW_SEQ_ID"	INTEGER NOT NULL,
	"MOP_CW_SEQ_NAME"	VARCHAR2(32),
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","MOP_CW_INDEX","MOP_CW_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_MOP_CW_SEQ_NAME_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"MOP_CW_INDEX"	INTEGER NOT NULL,
	"MOP_CW_SEQ_ID"	INTEGER NOT NULL,
	"MOP_CW_SEQ_NAME"	VARCHAR2(32),
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","MOP_CW_INDEX","MOP_CW_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_MOP_CW_SEQUENCE" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"MOP_CW_INDEX"	INTEGER NOT NULL,
	"MOP_CW_SEQUENCE_NUM"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"MOP_CW_VALUE_INDEX"	INTEGER NOT NULL,
	"MOP_CW_DURATION"	FLOAT(52),
	"MOP_CW_SEQ_ID"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("RADAR_MODE_INDEX","MOP_CW_SEQUENCE_NUM","MOP_CW_INDEX","MOP_CW_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_MOP_CW_SEQUENCE_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"MOP_CW_INDEX"	INTEGER NOT NULL,
	"MOP_CW_SEQUENCE_NUM"	INTEGER NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	"MOP_CW_VALUE_INDEX"	INTEGER NOT NULL,
	"MOP_CW_DURATION"	FLOAT(52),
	"MOP_CW_SEQ_ID"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("RADAR_MODE_INDEX","MOP_CW_SEQUENCE_NUM","MOP_CW_INDEX","MOP_CW_SEQ_ID")
);
CREATE TABLE IF NOT EXISTS "RADAR_MODE_PA_DIFF_IN_GROUP" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"SEQUENCE_NUM"	INTEGER NOT NULL,
	"PA_DIFF"	FLOAT(52) NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","SEQUENCE_NUM")
);
CREATE TABLE IF NOT EXISTS "RADAR_MODE_PA_DIFF_IN_GROUP_P" (
	"RADAR_MODE_INDEX"	INTEGER NOT NULL,
	"SEQUENCE_NUM"	INTEGER NOT NULL,
	"PA_DIFF"	FLOAT(52) NOT NULL,
	"SECLAB"	INTEGER NOT NULL,
	PRIMARY KEY("RADAR_MODE_INDEX","SEQUENCE_NUM")
);
CREATE TABLE IF NOT EXISTS "THREAT" (
	"THREAT_INDEX"	NUMBER NOT NULL,
	"PIN"	NUMBER NOT NULL UNIQUE,
	"BE_NUMBER"	CHAR(10),
	"FACILITY_NAME"	VARCHAR2(50),
	"PLACE_NAME_KOR"	VARCHAR2(50),
	"PLACE_NAME_ENG"	VARCHAR2(50),
	"USER_COUNTRY"	CHAR(2),
	"PRIMARY_FUNCTION"	CHAR(2),
	"FRIEND_OR_FOE"	VARCHAR2(10),
	"PRIORITY"	NUMBER,
	"ADA"	CHAR(6),
	"CATEGORY"	NUMBER,
	"STATUS"	CHAR(1),
	"DTC"	TIMESTAMP(6),
	"DTLI"	TIMESTAMP(6),
	"DTFI"	TIMESTAMP(6),
	"PLATFORM"	NUMBER,
	"DISTINCTION"	VARCHAR2(10),
	"SYMBOL_CODE"	VARCHAR2(30),
	"LATITUDE"	CHAR(7),
	"LONGITUDE"	CHAR(8),
	PRIMARY KEY("THREAT_INDEX")
);
CREATE TABLE IF NOT EXISTS "THREAT_P" (
	"THREAT_INDEX"	NUMBER NOT NULL,
	"PIN"	NUMBER NOT NULL UNIQUE,
	"BE_NUMBER"	CHAR(10),
	"FACILITY_NAME"	VARCHAR2(50),
	"PLACE_NAME_KOR"	VARCHAR2(50),
	"PLACE_NAME_ENG"	VARCHAR2(50),
	"USER_COUNTRY"	CHAR(2),
	"PRIMARY_FUNCTION"	CHAR(2),
	"FRIEND_OR_FOE"	VARCHAR2(10),
	"PRIORITY"	NUMBER,
	"ADA"	CHAR(6),
	"CATEGORY"	NUMBER,
	"STATUS"	CHAR(1),
	"DTC"	TIMESTAMP(6),
	"DTLI"	TIMESTAMP(6),
	"DTFI"	TIMESTAMP(6),
	"PLATFORM"	NUMBER,
	"DISTINCTION"	VARCHAR2(10),
	"SYMBOL_CODE"	VARCHAR2(30),
	"LATITUDE"	CHAR(7),
	"LONGITUDE"	CHAR(8),
	PRIMARY KEY("THREAT_INDEX")
);
CREATE TABLE IF NOT EXISTS "DEVICE" (
	"THREAT_INDEX"	NUMBER NOT NULL,
	"DEVICE_INDEX"	NUMBER NOT NULL,
	"ELNOT"	VARCHAR2(15),
	"DEVICE_NAME"	VARCHAR2(50),
	"STATUS"	CHAR(1),
	"IDENTIFICATION_RANGE"	NUMBER,
	"LATITUDE"	VARCHAR2(13),
	"LONGITUDE"	VARCHAR2(14),
	"ELEVATION"	NUMBER,
	"LATITUDE_NUM"	NUMBER,
	"LONGITUDE_NUM"	NUMBER,
	PRIMARY KEY("THREAT_INDEX","DEVICE_INDEX")
);
CREATE TABLE IF NOT EXISTS "DEVICE_P" (
	"THREAT_INDEX"	NUMBER NOT NULL,
	"DEVICE_INDEX"	NUMBER NOT NULL,
	"ELNOT"	CHAR(5),
	"DEVICE_NAME"	VARCHAR2(50),
	"STATUS"	CHAR(1),
	"IDENTIFICATION_RANGE"	NUMBER,
	"LATITUDE"	VARCHAR2(13),
	"LONGITUDE"	VARCHAR2(14),
	"ELEVATION"	NUMBER,
	"LATITUDE_NUM"	NUMBER,
	"LONGITUDE_NUM"	NUMBER,
	PRIMARY KEY("THREAT_INDEX","DEVICE_INDEX")
);
CREATE TABLE IF NOT EXISTS "COHERENCY_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(25),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "CONTINUITY_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(25),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "MOP_CW_LEGACY_TYPE_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(25),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "MOP_CW_MOD_TYPE_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(25),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "PARAM_SET_ASSOC_TYPE_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(30),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "PATTERN_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(25),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "PLATFORM_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(25),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "POLARIZATION_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(50),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "PRI_LEGACY_TYPE_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(50),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "RF_LEGACY_TYPE_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(50),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "RF_MOP_TYPE_CODE" (
	"RF_MOP_TYPE_CODE"	VARCHAR2(2) NOT NULL,
	"SECLAB"	NUMBER NOT NULL,
	"RF_MOP_TYPE_DEF"	VARCHAR2(30) NOT NULL,
	PRIMARY KEY("RF_MOP_TYPE_CODE")
);
CREATE TABLE IF NOT EXISTS "ROTATION_DIR_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(25),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "SCAN_TYPE_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(25),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "THREAT_STATUS_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(25),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "VALIDATION_CODE" (
	"CODE_VAL"	NUMBER NOT NULL,
	"ABBREVIATION"	VARCHAR2(25),
	"NAME"	VARCHAR2(100),
	PRIMARY KEY("CODE_VAL")
);
CREATE TABLE IF NOT EXISTS "COUNTRY" (
	"COUNTRY_CODE"	VARCHAR2(2) NOT NULL,
	"COUNTRY_NAME"	VARCHAR2(80) NOT NULL,
	"TRIGRAPH"	VARCHAR2(3),
	"SECLAB"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("COUNTRY_CODE")
);
CREATE TABLE IF NOT EXISTS "FUNCTION_CODES" (
	"ABBREVIATION"	VARCHAR2(20) NOT NULL,
	"NAME"	VARCHAR2(45) NOT NULL,
	"DESCRIPTION"	CLOB,
	"SYSTEM"	INTEGER,
	"SECLAB"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("ABBREVIATION")
);
INSERT INTO "RADAR_MODE" VALUES (1,0,'AA','2010/01/01 0:00:00.000','1970/01/01 0:00:00.000','1970/01/01 0:00:00.000','1970/01/01 0:00:00.000','1970/01/01 0:00:00.000',-1,'Pulsed',-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,'X','X',-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,2,-1.0,-1.0,'X','X',-1.0,-1.0,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,8000.0,8000.9,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1.0,-1.0,-1,-1.0,-1.0,-1.0,2,-1,10,11,9000.0,9010.0,9010.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,'X','X',-1.0,-1.0,-1,500.0,501.0,-1.0,-1.0,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1.0,-1.0,19.0,21.0,4,5,-1,'X','X',5000.0,5001.0,-1,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1000.0,2000.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,100.0,200.0,-1,-1,-1,-1.0,-1.0,'X','X',-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,'X','X',-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,0.1,1.0,'X','X',-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1,100.0,110.0,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1,-1.0,-1.0,-1.0,-1.0,'X','X','X','X',-1.0,-1.0,-1.0,-1.0,-1.0,1,0,1,0,-1,'1970/01/01 0:00:00.000',-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,'X',1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,'1970/01/01 0:00:00.000',-1,'ZZ',0,1,1);
INSERT INTO "RADAR_MODE" VALUES (2,0,'AB','1970/01/01 0:00:00.000','1970/01/01 0:00:00.000','1970/01/01 0:00:00.000','1970/01/01 0:00:00.000','1970/01/01 0:00:00.000',-1,'CW',-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,'X','X',-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,3,-1.0,-1.0,'X','X',-1.0,-1.0,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,500.0,505.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1.0,-1.0,-1,-1.0,-1.0,-1.0,3,-1,5,22,100.0,110.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,'X','X',-1.0,-1.0,-1,600.0,601.0,-1.0,-1.0,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1.0,-1.0,500.0,501.0,6,7,-1,'X','X',10000.0,10100.0,-1,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1000.0,2000.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,1000.0,2000.0,-1,-1,-1,-1.0,-1.0,'X','X',-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,'X','X',-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,100.0,110.0,'X','X',-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,2,500.0,510.0,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1,-1.0,-1.0,-1.0,-1.0,'X','X','X','X',-1.0,-1.0,-1.0,-1.0,-1.0,1,0,1,0,-1,'1970/01/01 0:00:00.000',-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,'X',2,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,'1970/01/01 0:00:00.000',-1,'ZZ',11,1,1);
INSERT INTO "RADAR_MODE" VALUES (3,0,'AI','1970/01/01 0:00:00.000','1970/01/01 0:00:00.000','1970/01/01 0:00:00.000','1970/01/01 0:00:00.000','1970/01/01 0:00:00.000',-1,'EA',-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,'X','X',-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,5,-1.0,-1.0,'X','X',-1.0,-1.0,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1.0,-1,-1,-1.0,-1.0,499.0,510.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1.0,-1.0,-1,-1.0,-1.0,-1.0,1,-1,4,2,5000.0,5010.0,5010.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,'X','X',-1.0,-1.0,-1,800.0,801.0,-1.0,-1.0,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1.0,-1.0,-1.0,1000.0,1001.0,8,9,-1,'X','X',5000.0,5010.0,-1,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1000.0,2000.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,10000.0,20000.0,-1,-1,-1,-1.0,-1.0,'X','X',-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,'X','X',-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,6000.0,6010.0,'X','X',-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,3,1000.0,1010.0,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1.0,-1,-1.0,-1.0,-1.0,-1.0,'X','X','X','X',-1.0,-1.0,-1.0,-1.0,-1.0,0,0,1,0,-1,'1970/01/01 0:00:00.000',-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1,-1,-1,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,'X',3,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,'1970/01/01 0:00:00.000',-1,'ZZ',12,1,1);
INSERT INTO "RADAR_RF_VALUES" VALUES (1,0,0,500.0,1500.0);
INSERT INTO "RADAR_RF_VALUES" VALUES (1,1,0,1500.0,1600.0);
INSERT INTO "RADAR_RF_VALUES" VALUES (1,2,0,3000.0,3010.0);
INSERT INTO "RADAR_RF_SEQUENCE" VALUES (1,0,0,0,0);
INSERT INTO "RADAR_RF_SEQUENCE" VALUES (1,1,0,1,0);
INSERT INTO "RADAR_RF_SEQUENCE" VALUES (1,0,0,0,1);
INSERT INTO "RADAR_RF_SEQUENCE" VALUES (1,1,0,1,1);
INSERT INTO "RADAR_RF_SEQUENCE" VALUES (1,2,0,2,1);
INSERT INTO "RADAR_PRI_VALUES" VALUES (1,0,0,100.0,110.0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RADAR_PRI_VALUES" VALUES (1,1,0,200.0,200.0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RADAR_PRI_VALUES" VALUES (1,2,0,300.0,310.0,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "RADAR_PRI_SEQUENCE" VALUES (1,0,0,0,NULL,0);
INSERT INTO "RADAR_PRI_SEQUENCE" VALUES (1,1,0,1,'',1);
INSERT INTO "RADAR_PRI_SEQUENCE" VALUES (1,2,0,0,NULL,2);
INSERT INTO "COHERENCY_CODE" VALUES (0,'COHERENT','COHERENT');
INSERT INTO "COHERENCY_CODE" VALUES (1,'NON_COHERENT','NON_COHERENT');
INSERT INTO "COHERENCY_CODE" VALUES (3,'UNKNOWN','UNKNOWN');
INSERT INTO "CONTINUITY_CODE" VALUES (0,'UNKNOWN','UNKNOWN');
INSERT INTO "CONTINUITY_CODE" VALUES (1,'DISCRETE','DISCRETE');
INSERT INTO "CONTINUITY_CODE" VALUES (2,'COUNTINUOUS','COUNTINUOUS');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (40,'FMOP','FMOP');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (41,'FMOP_LINEAR','FMOP_LINEAR');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (42,'FMOP_NONLINEAR','FMOP_NONLINEAR');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (43,'FMOP_STEPPED','FMOP_STEPPED');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (44,'PMOP','PMOP');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (45,'PMOP_BPSK','PMOP_BPSK');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (46,'PMOP_QPSK','PMOP_QPSK');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (47,'PMOP_MSK','PMOP_MSK');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (49,'PMOP_POLY_TIME','PMOP_POLY_TIME');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (50,'AMOP','AMOP');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (51,'PCM','PCM');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (53,'FM_TRIANGULAR','FM_TRIANGULAR');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (55,'FM_SINUSOIDAL','FM_SINUSOIDAL');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (62,'AM_TONES','AM_TONES');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (63,'ON_OFF_KEYING','ON_OFF_KEYING');
INSERT INTO "MOP_CW_LEGACY_TYPE_CODE" VALUES (64,'OOK_SRW','OOK_SRW');
INSERT INTO "MOP_CW_MOD_TYPE_CODE" VALUES (0,'UNKNOWN','UNKNOWN');
INSERT INTO "MOP_CW_MOD_TYPE_CODE" VALUES (1,'FREQUENCY','FREQUENCY');
INSERT INTO "MOP_CW_MOD_TYPE_CODE" VALUES (2,'PHASE','PHASE');
INSERT INTO "MOP_CW_MOD_TYPE_CODE" VALUES (3,'AMPLITUDE','AMPLITUDE');
INSERT INTO "MOP_CW_MOD_TYPE_CODE" VALUES (4,'UNMODULATED','UNMODULATED');
INSERT INTO "PARAM_SET_ASSOC_TYPE_CODE" VALUES (1,'Simultaneous','Simultaneous');
INSERT INTO "PARAM_SET_ASSOC_TYPE_CODE" VALUES (2,'Sequential','Sequential');
INSERT INTO "PARAM_SET_ASSOC_TYPE_CODE" VALUES (3,'Independent-simultaneous','Independent-simultaneous');
INSERT INTO "PATTERN_CODE" VALUES (0,'UNKNOWN','UNKNOWN');
INSERT INTO "PATTERN_CODE" VALUES (1,'PATTERNED','PATTERNED');
INSERT INTO "PATTERN_CODE" VALUES (2,'NON_PATTERNED','NON_PATTERNED');
INSERT INTO "PATTERN_CODE" VALUES (3,'ADAPTIVE','ADAPTIVE');
INSERT INTO "PATTERN_CODE" VALUES (5,'UNMODULATED','UNMODULATED');
INSERT INTO "PLATFORM_CODE" VALUES (0,'UNKNOWN','UNKNOWN');
INSERT INTO "PLATFORM_CODE" VALUES (1,'LAND','LAND');
INSERT INTO "PLATFORM_CODE" VALUES (2,'SEA','SEA');
INSERT INTO "PLATFORM_CODE" VALUES (3,'LAND_SEA_AND_AIR','LAND_SEA_AND_AIR');
INSERT INTO "PLATFORM_CODE" VALUES (4,'COASTAL','COASTAL');
INSERT INTO "PLATFORM_CODE" VALUES (5,'AIR','AIR');
INSERT INTO "POLARIZATION_CODE" VALUES (0,'C','Diverse (Agile or adaptive). Capable of pulse-to-pulse agility.');
INSERT INTO "POLARIZATION_CODE" VALUES (1,'D','Diverse.Option of operating with any of several polarizations.');
INSERT INTO "POLARIZATION_CODE" VALUES (2,'G','Linear with no reference to plane (unknown whether H or V).');
INSERT INTO "POLARIZATION_CODE" VALUES (3,'H','Linear - horizontal as compared with earth horizon or platform.');
INSERT INTO "POLARIZATION_CODE" VALUES (4,'J','Circular, with right hand sense.');
INSERT INTO "POLARIZATION_CODE" VALUES (5,'K','Circular, with left hand sense.');
INSERT INTO "POLARIZATION_CODE" VALUES (6,'L','Circular, undetermined sense.');
INSERT INTO "POLARIZATION_CODE" VALUES (7,'M','Elliptical.');
INSERT INTO "POLARIZATION_CODE" VALUES (8,'R','Rotating.');
INSERT INTO "POLARIZATION_CODE" VALUES (9,'S','Linear - slant, undetermined angle.');
INSERT INTO "POLARIZATION_CODE" VALUES (10,'T','Linear - slant, right of vertical as compared with earth horizon or platform');
INSERT INTO "POLARIZATION_CODE" VALUES (11,'U','Linear - slant, leeft of vertical as compared with earth horizon or platform');
INSERT INTO "POLARIZATION_CODE" VALUES (12,'V','Linear - vertical as compared with earth horizon or platform');
INSERT INTO "POLARIZATION_CODE" VALUES (13,'W','Unpolarized - modulated or spinning linear polarization');
INSERT INTO "POLARIZATION_CODE" VALUES (14,'Y','Polarization fixed but type unknown');
INSERT INTO "POLARIZATION_CODE" VALUES (15,'Z','Undetermined');
INSERT INTO "PRI_LEGACY_TYPE_CODE" VALUES (20,'PULSE_CONSTANT','PULSE_CONSTANT');
INSERT INTO "PRI_LEGACY_TYPE_CODE" VALUES (21,'STAGGER','STAGGER');
INSERT INTO "PRI_LEGACY_TYPE_CODE" VALUES (22,'JITTER','JITTER');
INSERT INTO "PRI_LEGACY_TYPE_CODE" VALUES (23,'DWELL_AND_SWITCH','DWELL_AND_SWITCH');
INSERT INTO "PRI_LEGACY_TYPE_CODE" VALUES (24,'PULSE_POSITION_MODULATION','PULSE_POSITION_MODULATION');
INSERT INTO "PRI_LEGACY_TYPE_CODE" VALUES (25,'PULSE_FREQUENCY_MODULATION','PULSE_FREQUENCY_MODULATION');
INSERT INTO "PRI_LEGACY_TYPE_CODE" VALUES (26,'PRI_SLIDING','PRI_SLIDING');
INSERT INTO "PRI_LEGACY_TYPE_CODE" VALUES (27,'PRI_PHASE_MODULATION_OR_SHIFTING','PRI_PHASE_MODULATION_OR_SHIFTING');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (0,'RF_AGILE','RF_AGILE');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (1,'RF_AGILE_PULSE_TO_PULSE','RF_AGILE_PULSE_TO_PULSE');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (2,'RF_AGILE_GROUP_TO_GROUP','RF_AGILE_GROUP_TO_GROUP');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (3,'RF_AGILE_SUB_PULSE','RF_AGILE_SUB_PULSE');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (4,'MULTIPLE_RF','MULTIPLE_RF');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (5,'MULTIPLE_RF_SIMULTANEOUS','MULTIPLE_RF_SIMULTANEOUS');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (6,'MULTIPLE_RF_SEQUENTIAL','MULTIPLE_RF_SEQUENTIAL');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (7,'LIMITED_RF_CHANGE_CAPABLE','LIMITED_RF_CHANGE_CAPABLE');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (8,'RF_SWEEPING','RF_SWEEPING');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (9,'RF_SWEEPING_LINEAR','RF_SWEEPING_LINEAR');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (10,'RF_SWEEPING_SINUSOIDAL','RF_SWEEPING_SINUSOIDAL');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (11,'RF_SWEEPING_TRIANGULAR','RF_SWEEPING_TRIANGULAR');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (12,'RF_SLIDING','RF_SLIDING');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (13,'ON_OFF_KEYED','ON_OFF_KEYED');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (14,'CONSTANT_SINGLE_RF','CONSTANT_SINGLE_RF');
INSERT INTO "RF_LEGACY_TYPE_CODE" VALUES (15,'LINEAR_RF_STEPPING','LINEAR_RF_STEPPING');
INSERT INTO "ROTATION_DIR_CODE" VALUES (0,'Counter Clockwise','Clockwise');
INSERT INTO "ROTATION_DIR_CODE" VALUES (1,'Clockwise','Clockwise');
INSERT INTO "SCAN_TYPE_CODE" VALUES (0,'A','Circular');
INSERT INTO "SCAN_TYPE_CODE" VALUES (1,'B','Horizontal Sector (Bi-directional)');
INSERT INTO "SCAN_TYPE_CODE" VALUES (2,'C','Vertical Sector (Bi-directional)');
INSERT INTO "SCAN_TYPE_CODE" VALUES (3,'D','Non-Scanning');
INSERT INTO "SCAN_TYPE_CODE" VALUES (4,'E','Irregular');
INSERT INTO "SCAN_TYPE_CODE" VALUES (5,'F','Conical');
INSERT INTO "SCAN_TYPE_CODE" VALUES (6,'G','Lobe Switching');
INSERT INTO "SCAN_TYPE_CODE" VALUES (7,'H','Orthogonal or Interleaved Sectors');
INSERT INTO "SCAN_TYPE_CODE" VALUES (8,'J','Raster');
INSERT INTO "SCAN_TYPE_CODE" VALUES (9,'K','Spiral');
INSERT INTO "SCAN_TYPE_CODE" VALUES (10,'L','Helical');
INSERT INTO "SCAN_TYPE_CODE" VALUES (11,'O','Sector Uni or Bi-Directional');
INSERT INTO "SCAN_TYPE_CODE" VALUES (12,'P','Agile Beam');
INSERT INTO "SCAN_TYPE_CODE" VALUES (13,'R','Other Combination/Patterns');
INSERT INTO "SCAN_TYPE_CODE" VALUES (14,'S','Vertical Sector (Uni-Directional)');
INSERT INTO "SCAN_TYPE_CODE" VALUES (15,'T','Horizontal Sector (Uni-Directional)');
INSERT INTO "SCAN_TYPE_CODE" VALUES (16,'U','Uni-Directional Sector (Plane Undertermined)');
INSERT INTO "SCAN_TYPE_CODE" VALUES (17,'V','Bi-Directional Sector (Plane Undetermined)');
INSERT INTO "SCAN_TYPE_CODE" VALUES (18,'Z','Undetermined');
INSERT INTO "THREAT_STATUS_CODE" VALUES (0,'C','C');
INSERT INTO "THREAT_STATUS_CODE" VALUES (1,'P','P');
INSERT INTO "THREAT_STATUS_CODE" VALUES (2,'N','N');
INSERT INTO "THREAT_STATUS_CODE" VALUES (3,'X','X');
INSERT INTO "THREAT_STATUS_CODE" VALUES (4,'D','D');
INSERT INTO "THREAT_STATUS_CODE" VALUES (5,'U','U');
INSERT INTO "THREAT_STATUS_CODE" VALUES (6,'I','I');
INSERT INTO "THREAT_STATUS_CODE" VALUES (7,'A','A');
INSERT INTO "VALIDATION_CODE" VALUES (0,'UNVALIDATED','UNVALIDATED');
INSERT INTO "VALIDATION_CODE" VALUES (1,'VALIDATED','VALIDATED');
INSERT INTO "VALIDATION_CODE" VALUES (2,'POSTULATED','POSTULATED');
INSERT INTO "COUNTRY" VALUES ('AF','Afghanistan','AFG',0);
INSERT INTO "COUNTRY" VALUES ('AX','Akrotiri','',0);
INSERT INTO "COUNTRY" VALUES ('AL','Albania','ALB',0);
INSERT INTO "COUNTRY" VALUES ('AG','Algeria','DZA',0);
INSERT INTO "COUNTRY" VALUES ('AQ','American Samoa','ASM',0);
INSERT INTO "COUNTRY" VALUES ('AN','Andorra','AND',0);
INSERT INTO "COUNTRY" VALUES ('AO','Angola','AGO',0);
INSERT INTO "COUNTRY" VALUES ('AV','Anguilla','',0);
INSERT INTO "COUNTRY" VALUES ('AY','Antarctica','ATA',0);
INSERT INTO "COUNTRY" VALUES ('AC','Antigua and Barbuda','ATG',0);
INSERT INTO "COUNTRY" VALUES ('AR','Argentina','ARG',0);
INSERT INTO "COUNTRY" VALUES ('AM','Armenia','ARM',0);
INSERT INTO "COUNTRY" VALUES ('AA','Aruba','ABW',0);
INSERT INTO "COUNTRY" VALUES ('AT','Ashmore and Cartier Islands','',0);
INSERT INTO "COUNTRY" VALUES ('AS','Australia','',0);
INSERT INTO "COUNTRY" VALUES ('AU','Austria','AUS',0);
INSERT INTO "COUNTRY" VALUES ('AJ','Azerbaijan','AZE',0);
INSERT INTO "COUNTRY" VALUES ('BF','Bahamas','BHS',0);
INSERT INTO "COUNTRY" VALUES ('BA','Bahrain','BHR',0);
INSERT INTO "COUNTRY" VALUES ('FQ','Baker Island','',0);
INSERT INTO "COUNTRY" VALUES ('BG','Bangladesh','BGD',0);
INSERT INTO "COUNTRY" VALUES ('BB','Barbados','BRB',0);
INSERT INTO "COUNTRY" VALUES ('BS','Bassas da India','',0);
INSERT INTO "COUNTRY" VALUES ('BO','Belarus','BLR',0);
INSERT INTO "COUNTRY" VALUES ('BE','Belgium','BEL',0);
INSERT INTO "COUNTRY" VALUES ('BH','Belize','BLZ',0);
INSERT INTO "COUNTRY" VALUES ('BN','Benin','BEN',0);
INSERT INTO "COUNTRY" VALUES ('BD','Bermuda','BMU',0);
INSERT INTO "COUNTRY" VALUES ('BT','Bhutan','BTN',0);
INSERT INTO "COUNTRY" VALUES ('BL','Bolivia','BOL',0);
INSERT INTO "COUNTRY" VALUES ('BK','Bosnia and Herzegovina','BIH',0);
INSERT INTO "COUNTRY" VALUES ('BC','Botswana','BWA',0);
INSERT INTO "COUNTRY" VALUES ('BV','Bouvet Island','BVT',0);
INSERT INTO "COUNTRY" VALUES ('BR','Brazil','BRA',0);
INSERT INTO "COUNTRY" VALUES ('IO','British Indian Ocean Territory','IOT',0);
INSERT INTO "COUNTRY" VALUES ('VI','British Virgin Islands','VGB',0);
INSERT INTO "COUNTRY" VALUES ('BX','Brunei','BRN',0);
INSERT INTO "COUNTRY" VALUES ('BU','Bulgaria','BGR',0);
INSERT INTO "COUNTRY" VALUES ('UV','Burkina Faso','BFA',0);
INSERT INTO "COUNTRY" VALUES ('BM','Burma / Myanmar','MMR',0);
INSERT INTO "COUNTRY" VALUES ('BY','Burundi','BDI',0);
INSERT INTO "COUNTRY" VALUES ('CB','Cambodia','KHM',0);
INSERT INTO "COUNTRY" VALUES ('CM','Cameroon','CMR',0);
INSERT INTO "COUNTRY" VALUES ('CA','Canada','CAN',0);
INSERT INTO "COUNTRY" VALUES ('CV','Cape Verde','CPV',0);
INSERT INTO "COUNTRY" VALUES ('CJ','Cayman Islands','',0);
INSERT INTO "COUNTRY" VALUES ('CT','Central African Republic','CAF',0);
INSERT INTO "COUNTRY" VALUES ('CD','Chad','TCD',0);
INSERT INTO "COUNTRY" VALUES ('CI','Chile','CHL',0);
INSERT INTO "COUNTRY" VALUES ('KT','Christmas Island','CXR',0);
INSERT INTO "COUNTRY" VALUES ('IP','Clipperton Island','',0);
INSERT INTO "COUNTRY" VALUES ('CK','Cocos (Keeling) Islands','CCK',0);
INSERT INTO "COUNTRY" VALUES ('CO','Colombia','COL',0);
INSERT INTO "COUNTRY" VALUES ('CN','Comoros','COM',0);
INSERT INTO "COUNTRY" VALUES ('CW','Cook Islands','COK',0);
INSERT INTO "COUNTRY" VALUES ('CR','Coral Sea Islands','',0);
INSERT INTO "COUNTRY" VALUES ('CS','Costa Rica','CRI',0);
INSERT INTO "COUNTRY" VALUES ('IV','Cote d-lvoire','CIV',0);
INSERT INTO "COUNTRY" VALUES ('HR','Croatia','HRV',0);
INSERT INTO "COUNTRY" VALUES ('CU','Cuba','CUB',0);
INSERT INTO "COUNTRY" VALUES ('CY','Cyprus','CYP',0);
INSERT INTO "COUNTRY" VALUES ('EZ','Czech Republic','CZE',0);
INSERT INTO "COUNTRY" VALUES ('CG','Democratic Republic of the Congo','COD',0);
INSERT INTO "COUNTRY" VALUES ('DA','Denmark','DNK',0);
INSERT INTO "COUNTRY" VALUES ('DX','Dhekelia','',0);
INSERT INTO "COUNTRY" VALUES ('DJ','Djibouti','DJI',0);
INSERT INTO "COUNTRY" VALUES ('DO','Dominica','DMA',0);
INSERT INTO "COUNTRY" VALUES ('DR','Dominican Republic','DOM',0);
INSERT INTO "COUNTRY" VALUES ('EC','Ecuador','ECU',0);
INSERT INTO "COUNTRY" VALUES ('EG','Egypt','EGY',0);
INSERT INTO "COUNTRY" VALUES ('ES','El Salvador','SLV',0);
INSERT INTO "COUNTRY" VALUES ('EK','Equatorial Guinea','GNQ',0);
INSERT INTO "COUNTRY" VALUES ('ER','Eritrea','ERI',0);
INSERT INTO "COUNTRY" VALUES ('EN','Estonia','EST',0);
INSERT INTO "COUNTRY" VALUES ('ET','Ethiopia','ETH',0);
INSERT INTO "COUNTRY" VALUES ('EU','Europa Island','',0);
INSERT INTO "COUNTRY" VALUES ('FK','Falkland Islands/Islas Malvinas','FLK',0);
INSERT INTO "COUNTRY" VALUES ('FO','Faroe Islands','FRO',0);
INSERT INTO "COUNTRY" VALUES ('FM','Federated States of Micronesia','FSM',0);
INSERT INTO "COUNTRY" VALUES ('FJ','Fiji','FJI',0);
INSERT INTO "COUNTRY" VALUES ('FI','Finland','FIN',0);
INSERT INTO "COUNTRY" VALUES ('FR','France','FRA',0);
INSERT INTO "COUNTRY" VALUES ('FG','French Guiana','GUF',0);
INSERT INTO "COUNTRY" VALUES ('FP','French Polynesia','PYF',0);
INSERT INTO "COUNTRY" VALUES ('FS','French Southern Territories','',0);
INSERT INTO "COUNTRY" VALUES ('GB','Gabon','GAB',0);
INSERT INTO "COUNTRY" VALUES ('GZ','Gaza Strip','',0);
INSERT INTO "COUNTRY" VALUES ('GG','Georgia','GEO',0);
INSERT INTO "COUNTRY" VALUES ('GM','Germany','DEU',0);
INSERT INTO "COUNTRY" VALUES ('GH','Ghana','GHA',0);
INSERT INTO "COUNTRY" VALUES ('GI','Gibraltar','GIB',0);
INSERT INTO "COUNTRY" VALUES ('GO','Glorioso Islands','',0);
INSERT INTO "COUNTRY" VALUES ('GR','Greece','GRC',0);
INSERT INTO "COUNTRY" VALUES ('GL','Greenland','GRL',0);
INSERT INTO "COUNTRY" VALUES ('GJ','Grenada','GRD',0);
INSERT INTO "COUNTRY" VALUES ('GP','Guadeloupe','GLP',0);
INSERT INTO "COUNTRY" VALUES ('GQ','Guam','GUM',0);
INSERT INTO "COUNTRY" VALUES ('GT','Guatemala','GTM',0);
INSERT INTO "COUNTRY" VALUES ('GK','Guernsey','GGY',0);
INSERT INTO "COUNTRY" VALUES ('GV','Guinea','GIN',0);
INSERT INTO "COUNTRY" VALUES ('PU','Guinea-Bissau','GNB',0);
INSERT INTO "COUNTRY" VALUES ('GY','Guyana','GUY',0);
INSERT INTO "COUNTRY" VALUES ('HA','Haiti','HTI',0);
INSERT INTO "COUNTRY" VALUES ('HM','Heard Island and McDonald Islands','HMD',0);
INSERT INTO "COUNTRY" VALUES ('HO','Honduras','HND',0);
INSERT INTO "COUNTRY" VALUES ('HK','Hong Kong','HKG',0);
INSERT INTO "COUNTRY" VALUES ('HU','Hungary','HUN',0);
INSERT INTO "COUNTRY" VALUES ('IC','Iceland','ISL',0);
INSERT INTO "COUNTRY" VALUES ('IN','India','IND',0);
INSERT INTO "COUNTRY" VALUES ('ID','Indonesia','IDN',0);
INSERT INTO "COUNTRY" VALUES ('IR','Iran','IRN',0);
INSERT INTO "COUNTRY" VALUES ('IZ','Iraq','IRQ',0);
INSERT INTO "COUNTRY" VALUES ('IM','Isle of Man','IMN',0);
INSERT INTO "COUNTRY" VALUES ('IS','Israel','ISR',0);
INSERT INTO "COUNTRY" VALUES ('IT','Italy','ITA',0);
INSERT INTO "COUNTRY" VALUES ('JM','Jamaica','JAM',0);
INSERT INTO "COUNTRY" VALUES ('JN','Jan Mayen','',0);
INSERT INTO "COUNTRY" VALUES ('JA','Japan','JPN',0);
INSERT INTO "COUNTRY" VALUES ('JE','Jersey','JEY',0);
INSERT INTO "COUNTRY" VALUES ('JQ','Johnston Atoll','',0);
INSERT INTO "COUNTRY" VALUES ('JO','Jordan','JOR',0);
INSERT INTO "COUNTRY" VALUES ('JU','Juan de Nova Island','',0);
INSERT INTO "COUNTRY" VALUES ('KZ','Kazakhstan','KAZ',0);
INSERT INTO "COUNTRY" VALUES ('KE','Kenya','KEN',0);
INSERT INTO "COUNTRY" VALUES ('KQ','Kingman Reef','',0);
INSERT INTO "COUNTRY" VALUES ('KR','Kiribati','KIR',0);
INSERT INTO "COUNTRY" VALUES ('KU','Kuwait','KWT',0);
INSERT INTO "COUNTRY" VALUES ('KG','Kyrgyzstan','KGZ',0);
INSERT INTO "COUNTRY" VALUES ('LA','Laos','LAO',0);
INSERT INTO "COUNTRY" VALUES ('LG','Latvia','LVA',0);
INSERT INTO "COUNTRY" VALUES ('LE','Lebanon','LBN',0);
INSERT INTO "COUNTRY" VALUES ('LT','Lesotho','LSO',0);
INSERT INTO "COUNTRY" VALUES ('LI','Liberia','LBR',0);
INSERT INTO "COUNTRY" VALUES ('LY','Libya','',0);
INSERT INTO "COUNTRY" VALUES ('LS','Liechtenstein','LIE',0);
INSERT INTO "COUNTRY" VALUES ('LH','Lithuania','LTU',0);
INSERT INTO "COUNTRY" VALUES ('LU','Luxembourg','LUX',0);
INSERT INTO "COUNTRY" VALUES ('MC','Macau','MAC',0);
INSERT INTO "COUNTRY" VALUES ('MA','Madagascar','MDG',0);
INSERT INTO "COUNTRY" VALUES ('MI','Malawi','MWI',0);
INSERT INTO "COUNTRY" VALUES ('MY','Malaysia','MYS',0);
INSERT INTO "COUNTRY" VALUES ('MV','Maldives','MDV',0);
INSERT INTO "COUNTRY" VALUES ('ML','Mali','MLI',0);
INSERT INTO "COUNTRY" VALUES ('MT','Malta','MLT',0);
INSERT INTO "COUNTRY" VALUES ('RM','Marshall Islands','MHL',0);
INSERT INTO "COUNTRY" VALUES ('MB','Martinique','MTQ',0);
INSERT INTO "COUNTRY" VALUES ('MR','Mauritania','MRT',0);
INSERT INTO "COUNTRY" VALUES ('MP','Mauritius','MUS',0);
INSERT INTO "COUNTRY" VALUES ('MF','Mayotte','MYT',0);
INSERT INTO "COUNTRY" VALUES ('MX','Mexico','MEX',0);
INSERT INTO "COUNTRY" VALUES ('MQ','Midway Islands','',0);
INSERT INTO "COUNTRY" VALUES ('MD','Moldova','MDA',0);
INSERT INTO "COUNTRY" VALUES ('MN','Monaco','MCO',0);
INSERT INTO "COUNTRY" VALUES ('MG','Mongolia','MNG',0);
INSERT INTO "COUNTRY" VALUES ('MJ','Montenegro','MNE',0);
INSERT INTO "COUNTRY" VALUES ('MH','Montserrat','MSR',0);
INSERT INTO "COUNTRY" VALUES ('MO','Morocco','MAR',0);
INSERT INTO "COUNTRY" VALUES ('MZ','Mozambique','MOZ',0);
INSERT INTO "COUNTRY" VALUES ('WA','Namibia','NAM',0);
INSERT INTO "COUNTRY" VALUES ('NR','Nauru','NRU',0);
INSERT INTO "COUNTRY" VALUES ('BQ','Navassa Island','',0);
INSERT INTO "COUNTRY" VALUES ('NP','Nepal','NPL',0);
INSERT INTO "COUNTRY" VALUES ('NL','Netherlands','NLD',0);
INSERT INTO "COUNTRY" VALUES ('NT','Netherlands Antilles','',0);
INSERT INTO "COUNTRY" VALUES ('NC','New Caledonia','NCL',0);
INSERT INTO "COUNTRY" VALUES ('NZ','New Zealand','NZL',0);
INSERT INTO "COUNTRY" VALUES ('NU','Nicaragua','NIC',0);
INSERT INTO "COUNTRY" VALUES ('NG','Niger','NER',0);
INSERT INTO "COUNTRY" VALUES ('NI','Nigeria','NGA',0);
INSERT INTO "COUNTRY" VALUES ('NE','Niue','NIU',0);
INSERT INTO "COUNTRY" VALUES ('NF','Norfolk Island','NFK',0);
INSERT INTO "COUNTRY" VALUES ('KN','North Korea','PRK',0);
INSERT INTO "COUNTRY" VALUES ('CQ','Northern Mariana Islands','MNP',0);
INSERT INTO "COUNTRY" VALUES ('NO','Norway','NOR',0);
INSERT INTO "COUNTRY" VALUES ('MU','Oman','OMN',0);
INSERT INTO "COUNTRY" VALUES ('PK','Pakistan','PAK',0);
INSERT INTO "COUNTRY" VALUES ('PS','Palau','PLW',0);
INSERT INTO "COUNTRY" VALUES ('PM','Panama','PAN',0);
INSERT INTO "COUNTRY" VALUES ('PP','Papua New Guinea','PNG',0);
INSERT INTO "COUNTRY" VALUES ('PF','Paracel Islands','',0);
INSERT INTO "COUNTRY" VALUES ('PA','Paraguay','PRY',0);
INSERT INTO "COUNTRY" VALUES ('CH','People-s Republic of China','CHN',0);
INSERT INTO "COUNTRY" VALUES ('PE','Peru','PER',0);
INSERT INTO "COUNTRY" VALUES ('RP','Philippines','PHL',0);
INSERT INTO "COUNTRY" VALUES ('PC','Pitcairn Islands','PCN',0);
INSERT INTO "COUNTRY" VALUES ('PL','Poland','POL',0);
INSERT INTO "COUNTRY" VALUES ('PO','Portugal','PRT',0);
INSERT INTO "COUNTRY" VALUES ('RQ','Puerto Rico','PRI',0);
INSERT INTO "COUNTRY" VALUES ('QA','Qatar','QAT',0);
INSERT INTO "COUNTRY" VALUES ('TW','Republic of China (Taiwan)','TWN',0);
INSERT INTO "COUNTRY" VALUES ('EI','Republic of Ireland','IRL',0);
INSERT INTO "COUNTRY" VALUES ('MK','Republic of Macedonia','MKD',0);
INSERT INTO "COUNTRY" VALUES ('UG','Republic of Uganda','UGA',0);
INSERT INTO "COUNTRY" VALUES ('CF','Republic of the Congo','COG',0);
INSERT INTO "COUNTRY" VALUES ('RE','Reunion','REU',0);
INSERT INTO "COUNTRY" VALUES ('RO','Romania','ROU',0);
INSERT INTO "COUNTRY" VALUES ('RS','Russia','RUS',0);
INSERT INTO "COUNTRY" VALUES ('RW','Rwanda','RWA',0);
INSERT INTO "COUNTRY" VALUES ('SH','Saint Helena','SHN',0);
INSERT INTO "COUNTRY" VALUES ('SC','Saint Kitts and Nevis','KNA',0);
INSERT INTO "COUNTRY" VALUES ('ST','Saint Lucia','LCA',0);
INSERT INTO "COUNTRY" VALUES ('SB','Saint Pierre and Miquelon','SPM',0);
INSERT INTO "COUNTRY" VALUES ('VC','Saint Vincent and the Grenadines','VCT',0);
INSERT INTO "COUNTRY" VALUES ('WS','Samoa','WSM',0);
INSERT INTO "COUNTRY" VALUES ('SM','San Marino','SMR',0);
INSERT INTO "COUNTRY" VALUES ('TP','Sao Tome and Principe','STP',0);
INSERT INTO "COUNTRY" VALUES ('SA','Saudi Arabia','SAU',0);
INSERT INTO "COUNTRY" VALUES ('SG','Senegal','SEN',0);
INSERT INTO "COUNTRY" VALUES ('RB','Serbia','SRB',0);
INSERT INTO "COUNTRY" VALUES ('SE','Seychelles','SYC',0);
INSERT INTO "COUNTRY" VALUES ('SL','Sierra Leone','SLE',0);
INSERT INTO "COUNTRY" VALUES ('SN','Singapore','SGP',0);
INSERT INTO "COUNTRY" VALUES ('LO','Slovakia','SVK',0);
INSERT INTO "COUNTRY" VALUES ('SI','Slovenia','SVN',0);
INSERT INTO "COUNTRY" VALUES ('BP','Solomon Islands','SLB',0);
INSERT INTO "COUNTRY" VALUES ('SO','Somalia','SOM',0);
INSERT INTO "COUNTRY" VALUES ('SF','South Africa','ZAF',0);
INSERT INTO "COUNTRY" VALUES ('SX','South Georgia and the South Sandwich Islands','SGS',0);
INSERT INTO "COUNTRY" VALUES ('KS','South Korea','KOR',0);
INSERT INTO "COUNTRY" VALUES ('OD','South Sudan','SSD',0);
INSERT INTO "COUNTRY" VALUES ('SP','Spain','ESP',0);
INSERT INTO "COUNTRY" VALUES ('PG','Spratly Islands','',0);
INSERT INTO "COUNTRY" VALUES ('CE','Sri Lanka','LKA',0);
INSERT INTO "COUNTRY" VALUES ('SU','Sudan','SDN',0);
INSERT INTO "COUNTRY" VALUES ('NS','Suriname','SUR',0);
INSERT INTO "COUNTRY" VALUES ('SV','Svalbard','SJM',0);
INSERT INTO "COUNTRY" VALUES ('WZ','Swaziland','SWZ',0);
INSERT INTO "COUNTRY" VALUES ('SW','Sweden','SWE',0);
INSERT INTO "COUNTRY" VALUES ('SZ','Switzerland','CHE',0);
INSERT INTO "COUNTRY" VALUES ('SY','Syria','SYR',0);
INSERT INTO "COUNTRY" VALUES ('TI','Tajikistan','TJK',0);
INSERT INTO "COUNTRY" VALUES ('TZ','Tanzania','TZA',0);
INSERT INTO "COUNTRY" VALUES ('TH','Thailand','THA',0);
INSERT INTO "COUNTRY" VALUES ('GA','The Gambia','GMB',0);
INSERT INTO "COUNTRY" VALUES ('TT','Timor-Leste/EastTimor','TLS',0);
INSERT INTO "COUNTRY" VALUES ('TO','Togo','TGO',0);
INSERT INTO "COUNTRY" VALUES ('TL','Tokelau','TKL',0);
INSERT INTO "COUNTRY" VALUES ('TN','Tonga','TON',0);
INSERT INTO "COUNTRY" VALUES ('TD','Trinidad and Tobago','TTO',0);
INSERT INTO "COUNTRY" VALUES ('TE','Tromelin Island','',0);
INSERT INTO "COUNTRY" VALUES ('TS','Tunisia','TUN',0);
INSERT INTO "COUNTRY" VALUES ('TU','Turkey','TUR',0);
INSERT INTO "COUNTRY" VALUES ('TX','Turkmenistan','TKM',0);
INSERT INTO "COUNTRY" VALUES ('TK','Turks and Caicos Islands','TCA',0);
INSERT INTO "COUNTRY" VALUES ('TV','Tuvalu','TUV',0);
INSERT INTO "COUNTRY" VALUES ('VQ','U.S. Virgin Islands','VIR',0);
INSERT INTO "COUNTRY" VALUES ('UP','Ukraine','UKR',0);
INSERT INTO "COUNTRY" VALUES ('AE','United Arab Emirates','ARE',0);
INSERT INTO "COUNTRY" VALUES ('UK','United Kingdom','GBR',0);
INSERT INTO "COUNTRY" VALUES ('US','United States','USA',0);
INSERT INTO "COUNTRY" VALUES ('UY','Uruguay','URY',0);
INSERT INTO "COUNTRY" VALUES ('UZ','Uzbekistan','UZB',0);
INSERT INTO "COUNTRY" VALUES ('NH','Vanuatu','VUT',0);
INSERT INTO "COUNTRY" VALUES ('VT','Vatican City','VAT',0);
INSERT INTO "COUNTRY" VALUES ('VE','Venezuela','VEN',0);
INSERT INTO "COUNTRY" VALUES ('VM','Vietnam','VNM',0);
INSERT INTO "COUNTRY" VALUES ('WQ','Wake Island','',0);
INSERT INTO "COUNTRY" VALUES ('WF','Wallis and Futuna','WLF',0);
INSERT INTO "COUNTRY" VALUES ('WE','West Bank','',0);
INSERT INTO "COUNTRY" VALUES ('WI','Western Sahara','ESH',0);
INSERT INTO "COUNTRY" VALUES ('YM','Yemen','YEM',0);
INSERT INTO "COUNTRY" VALUES ('ZA','Zambia','ZMB',0);
INSERT INTO "COUNTRY" VALUES ('ZI','Zimbabwe','ZWE',0);
INSERT INTO "FUNCTION_CODES" VALUES ('AA','Anti Aircraft Fire Control','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('AB','Airborne Search and Bomb','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('AI','Airborne Intercept','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('AL','Altimeter','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('AM','Airborne Recon Mapping','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('AT','Air Traffic Control','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('AV','Avian Control','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('BN','Beacon Transponder','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('BS','Battlefield Surveillance','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('CA','Controlled Approach G S','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('CI ','Controlled Intercept A G S','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('CS','Coastal Surveillance','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('DC','Decoy Mimic','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('DT','Data Transmission','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('ES','Earth Surveillance','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('EW','Early Warning','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('FC','Fire Control','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('GB','Gun Laying Beacon','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('GI','Ground I','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('GM','Ground Mapping','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('GT','Ground Traffic Control','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('HF','Height Finder','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('HS','Harbor Surveillance','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('IF','IFF Interrogator','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('IL','Instrument Landing System','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('IS','Ionospheric Sounding','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('IT','IFF Transponder','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('JB','Barrage Jamming','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('JC','Click Jamming','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('JD','Deceptive Jamming','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('JF','Frequency Swept Jamming','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('JG','Jamming  General','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('JN','Noise Jamming','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('JP','Pulsed Jamming','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('JR','Repeater Jamming','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('JS','Spot Noise Jamming','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('JT','Transponder Jamming','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('MA','Missile Acquisition','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('MC','Missile Control','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('MD','Missile Downlink','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('ME','Meteorological','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('MF','Multi Function','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('MG','Missile Guidance','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('MH','Missile Homing','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('MT','Missile Tracking','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('NA','Navigation General','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('ND','Navigation DME','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('NT','Navigation Terrain Following','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('NW','Navigation Weather Avoidance','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('PF','Proximity Fuse','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('RI','Instrumentation','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('RO','Range Only','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('RS','Radiosonde','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('SB','Sonobuoy','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('SP','Space','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('SS','Surface Search','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('ST','Shell Tracking','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('TA','Target Acquisition','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('TI','Target Illumination','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('TT','Target Tracking','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('TV','Television','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('UN','Unknown','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('VR','Video Remoting','','',0);
INSERT INTO "FUNCTION_CODES" VALUES ('XP','Experimental or Trainer','','',0);
CREATE VIEW VEL_RADAR_LIST AS
	SELECT A.ELNOT,
          A.NICKNAME,
          A.FUNCTION_CODE,
          A.PRIORITY,
          A.STATUS,
          
          B.RF_TYPICAL_MIN,
          B.RF_TYPICAL_MAX,
          B.PRI_TYPICAL_MIN,
          B.PRI_TYPICAL_MAX,
          E.WEAPON_SYS,
          G.PLATFORM,
          A.RADAR_INDEX
		  
    FROM RADAR AS A, RADAR_MODE AS B, RADAR_MODE_LIFECYCLE AS C, ASSOC_WEAP_SYS AS D, WEAPON_SYSTEM AS E, ASSOC_PLATFORM AS F, PLATFORM AS G
    WHERE     A.RADAR_INDEX = C.RADAR_INDEX
          AND C.RADAR_MODE_INDEX = B.RADAR_MODE_INDEX
          AND A.RADAR_INDEX = D.RADAR_INDEX
          AND D.WEAPON_INDEX = E.WEAPON_INDEX
          AND A.RADAR_INDEX = F.RADAR_INDEX
          AND F.PLATFORM_INDEX = G.PLATFORM_INDEX;
CREATE VIEW VEL_RADAR_RF_SEQENCE AS
	SELECT A.RADAR_MODE_INDEX,
					 A.RF_SEQ_ID,
					 A.RF_INDEX,
           B.RF_MIN,
           B.RF_MAX
		  
    FROM RADAR_RF_SEQUENCE AS A, RADAR_RF_VALUES AS B
    WHERE     A.RADAR_MODE_INDEX = B.RADAR_MODE_INDEX and 
	A.RF_INDEX = B.RF_INDEX;
CREATE VIEW VEL_RADAR_PRI_SEQENCE AS
	SELECT 	A.RADAR_MODE_INDEX,
			A.PRI_SEQ_ID,
			A.PRI_INDEX,
			
			B.PRI_MIN,
			B.PRI_MAX
			
    FROM RADAR_PRI_SEQUENCE AS A, RADAR_PRI_VALUES AS B
    WHERE 		A.RADAR_MODE_INDEX = B.RADAR_MODE_INDEX
			AND A.PRI_INDEX = B.PRI_INDEX;
COMMIT;
