# Automatically generated file from prj_vsb.tcl: do not edit


__VSB_CHANGES_TO_CLEAN_OBJS = _WRS_CONFIG_CPU _WRS_CONFIG_VSB_DATAMODEL _WRS_CONFIG_SMP _WRS_CONFIG_FP _WRS_CONFIG_ENDIAN _WRS_CONFIG_CORE_KERNEL_1_2_5_1


