# 2020-08-26 오후 3:22:26

# 에미터 관련 테이블을 삭제합니다.
DROP TABLE if exists "LOBDATA";
DROP TABLE if exists "LOB_POSITION";
DROP TABLE if exists "ABTDATA";
DROP TABLE if exists "ABT_POSITION";
DROP TABLE if exists "AETDATA";


# 에미터 관련 테이블을 생성합니다.
CREATE TABLE "LOBDATA" (
	"SEQ_NUM"	integer PRIMARY KEY AUTOINCREMENT,
	"LOBID"	INTEGER NOT NULL,
	"ABTID"	int NOT NULL,
	"AETID"	int NOT NULL,
	"CONTACT_TIME"	datetime,
	"CONTACT_TIME_MS"	int,
	"SIGNAL_TYPE"	tinyint,
	"DOA_MEAN"	float,
	"DOA_MIN"	float,
	"DOA_MAX"	float,
	"DI_RATIO"	int,
	"FREQ_TYPE"	tinyint,
	"FREQ_PATTERN_TYPE"	tinyint,
	"FREQ_PATTERN_PERIOD"	float,
	"FREQ_MEAN"	float,
	"FREQ_MIN"	float,
	"FREQ_MAX"	float,
	"FREQ_POSITION_COUNT"	tinyint,
	"PRI_TYPE"	tinyint,
	"PRI_PATTERN_TYPE"	tinyint,
	"PRI_PATTERN_PERIOD"	float,
	"PRI_MEAN"	float,
	"PRI_MIN"	float,
	"PRI_MAX"	float,
	"PRI_JITTER_RATIO"	float,
	"PRI_POSITION_COUNT"	tinyint,
	"PW_MEAN"	float,
	"PW_MIN"	float,
	"PW_MAX"	float,
	"PA_MEAN"	float,
	"PA_MIN"	float,
	"PA_MAX"	float,
	"IS_STORED_PDW"	tinyint,
	"NUM_PDW"	smallint,
	"COLLECTOR_ID"	tinyint,
	"RADAR_LATITUDE"	float,
	"RADAR_LONGGITUDE"	float,
	"RADAR_NAME"	varchar(20),
	"RADARMODE_INDEX"	smallint,
	"THREAT_INDEX"	smallint
);

CREATE TABLE "LOB_POSITION" (
	"SEQ_NUM"	integer PRIMARY KEY AUTOINCREMENT,
	"LOBID"	int NOT NULL,
	"ABTID"	int NOT NULL,
	"AETID"	int NOT NULL,
	"TASK_ID"	varchar(30) NOT NULL,
	"POSITION_COUNT"	tinyint,
	"SEQ_01"	float,
	"SEQ_02"	float,
	"SEQ_03"	float,
	"SEQ_04"	float,
	"SEQ_05"	float,
	"SEQ_06"	float,
	"SEQ_07"	float,
	"SEQ_08"	float,
	"SEQ_09"	float,
	"SEQ_10"	float,
	"SEQ_11"	float,
	"SEQ_12"	float,
	"SEQ_13"	float,
	"SEQ_14"	float,
	"SEQ_15"	float,
	"SEQ_16"	float,
	"SEQ_17"	float,
	"SEQ_18"	float,
	"SEQ_19"	float,
	"SEQ_20"	float,
	"SEQ_21"	float,
	"SEQ_22"	float,
	"SEQ_23"	float,
	"SEQ_24"	float,
	"SEQ_25"	float,
	"SEQ_26"	float,
	"SEQ_27"	float,
	"SEQ_28"	float,
	"SEQ_29"	float,
	"SEQ_30"	float,
	"SEQ_31"	float,
	"SEQ_32"	float	
);

CREATE TABLE "ABTDATA" (
	"SEQ_NUM"	integer PRIMARY KEY AUTOINCREMENT,
	"ABTID"	int NOT NULL,
	"AETID"	int NOT NULL,
	"FIRST_TIME"	datetime,
	"LAST_TIME"	datetime,
	"SIGNAL_TYPE"	tinyint,
	"NUM_LOB"	int,
	"BEAM_VALIDITY"	int,
	"FREQ_TYPE"	tinyint,
	"FREQ_PATTERN_TYPE"	tinyint,
	"FREQ_PATTERN_PERIOD_MEAN"	float,
	"FREQ_PATTERN_PERIOD_MIN"	float,
	"FREQ_PATTERN_PERIOD_MAX"	float,
	"FREQ_MEAN"	float,
	"FREQ_MIN"	float,
	"FREQ_MAX"	float,
	"FREQ_POSITION_COUNT"	tinyint,
	"PRI_TYPE"	tinyint,
	"PRI_PATTERN_TYPE"	tinyint,
	"PRI_PATTERN_PERIOD_MEAN"	float,
	"PRI_PATTERN_PERIOD_MIN"	float,
	"PRI_PATTERN_PERIOD_MAX"	float,
	"PRI_MEAN"	float,
	"PRI_MIN"	float,
	"PRI_MAX"	float,
	"PRI_JITTER_RATIO"	float,
	"PRI_POSITION_COUNT"	tinyint,
	"PW_MEAN"	float,
	"PW_MIN"	float,
	"PW_MAX"	float,
	"PA_MEAN"	float,
	"PA_MIN"	float,
	"PA_MAX"	float,
	"TOTAL_PDW"	int,
	"RADAR_NAME"	varchar(20),
	"RADARMODE_INDEX"	smallint,
	"THREAT_INDEX"	smallint,
	"PE_VALID"	smallint,
	"PE_LATITUDE"	float,
	"PE_LONGGITUDE"	float,
	"PE_CEP"	float,
	"PE_MAJOR_AXIS"	float,
	"PE_MINOR_AXIS"	float,
	"PE_THETA"	float,
	"PE_DISTANCE"	float,
	"ALARM_TIME"	datetime,
	"STAT"	tinyint
);

CREATE TABLE "ABT_POSITION" (
	"SEQ_NUM"	integer PRIMARY KEY AUTOINCREMENT,
	"LOBID"	int NOT NULL,
	"ABTID"	int NOT NULL,
	"AETID"	int NOT NULL,
	"TASK_ID"	varchar(30) NOT NULL,
	"POSITION_COUNT"	tinyint,
	"SEQ_01"	float,
	"SEQ_02"	float,
	"SEQ_03"	float,
	"SEQ_04"	float,
	"SEQ_05"	float,
	"SEQ_06"	float,
	"SEQ_07"	float,
	"SEQ_08"	float,
	"SEQ_09"	float,
	"SEQ_10"	float,
	"SEQ_11"	float,
	"SEQ_12"	float,
	"SEQ_13"	float,
	"SEQ_14"	float,
	"SEQ_15"	float,
	"SEQ_16"	float,
	"SEQ_17"	float,
	"SEQ_18"	float,
	"SEQ_19"	float,
	"SEQ_20"	float,
	"SEQ_21"	float,
	"SEQ_22"	float,
	"SEQ_23"	float,
	"SEQ_24"	float,
	"SEQ_25"	float,
	"SEQ_26"	float,
	"SEQ_27"	float,
	"SEQ_28"	float,
	"SEQ_29"	float,
	"SEQ_30"	float,
	"SEQ_31"	float,
	"SEQ_32"	float	
);

CREATE TABLE "AETDATA" (
	"SEQ_NUM"	integer PRIMARY KEY AUTOINCREMENT,
	"AETID"	NUMBER NOT NULL,
	"RADARMODE_INDEX"	NUMBER NOT NULL,
	"THREAT_INDEX"	NUMBER NOT NULL,
	"IDINFO"	VARCHAR2(12),
	"ELNOT_PRIM"	VARCHAR2(12),
	"MODE_CODE_PRIM"	VARCHAR2(12),
	"NICK_NAME"	VARCHAR2(64),
	"PRIM_FUNC_CODE"	VARCHAR2(12),
	"RADAR_PRIORITY"	NUMBER,
	"PIN_NUM"	NUMBER,
	"SITE_NAME"	VARCHAR2(64),
	"BE_NUM"	VARCHAR2(64),
	"THREAT_FUNC_CODE"	VARCHAR2(64),
	"THREAT_PRIORITY"	NUMBER,
	"DISTANCE_ERR_FROM_THREAT"	NUMBER,
	"EQUIP_NUM"	NUMBER,
	"NUM_OF_LOBS"	NUMBER NOT NULL,
	"NUM_OF_BEAMS"	NUMBER NOT NULL,
	"RECORD_TIME_STA"	TIMESTAMP(9) NOT NULL,
	"RECORD_TIME_FIN"	TIMESTAMP(9) NOT NULL,
	"VALIDITY"	NUMBER(1) NOT NULL,
	"FRQ_MEAN"	NUMBER(8) NOT NULL,
	"FRQ_MAX"	NUMBER(8) NOT NULL,
	"FRQ_MIN"	NUMBER(8) NOT NULL,
	"FRQ_DEV"	NUMBER(8) NOT NULL,
	"PRI_MEAN"	NUMBER NOT NULL,
	"PRI_MAX"	NUMBER NOT NULL,
	"PRI_MIN"	NUMBER NOT NULL,
	"PRI_DEV"	NUMBER NOT NULL,
	"PW_MEAN"	NUMBER NOT NULL,
	"PW_MAX"	NUMBER NOT NULL,
	"PW_MIN"	NUMBER NOT NULL,
	"PW_DEV"	NUMBER NOT NULL,
	"PA_MEAN"	NUMBER NOT NULL,
	"PA_MAX"	NUMBER NOT NULL,
	"PA_MIN"	NUMBER NOT NULL,
	"PA_DEV"	NUMBER NOT NULL,
	"POS_EST_VALID"	NUMBER(2) NOT NULL,
	"POS_EST_LAT"	NUMBER NOT NULL,
	"POS_EST_LONG"	NUMBER NOT NULL,
	"POS_EST_HEIGHT"	NUMBER NOT NULL,
	"POS_EST_CEP"	NUMBER NOT NULL,
	"POS_EST_MAJOR_AXIS"	NUMBER NOT NULL,
	"POS_EST_MINOR_AXIS"	NUMBER NOT NULL,
	"EEP_MAJOR_TILT_ANGLE"	NUMBER NOT NULL,
	"FINAL_ALARM_TIME"	TIMESTAMP(9),
	"IS_MANUAL_INPUT"	NUMBER(2) NOT NULL,
	"MANUALPOSESTPREFERRED"	NUMBER(2) NOT NULL,
	"MANUAL_POS_EST_LAT"	NUMBER,
	"MANUAL_POS_EST_LONG"	NUMBER,
	"STAT"	NUMBER
);

