#!/bin/bash

echo "LOB 테이블을 생성합니다..."
sqlite3 emitter.sqlite3 ".read LOBDATA.sql"
sqlite3 emitter.sqlite3 ".read LOB_POSITION.sql"

echo "ABT 테이블을 생성합니다..."
sqlite3 emitter.sqlite3 ".read ABTDATA.sql"
sqlite3 emitter.sqlite3 ".read ABT_POSITION.sql"

echo "AET 테이블을 생성합니다..."
sqlite3 emitter.sqlite3 ".read AETDATA.sql"

echo "생성한 DB 를 복사합니다..."
cp emitter.sqlite3 ../../files/SQLite3.DB/.
cp emitter.sqlite3 ~/SQLite3.DB/.
