
	
# this file is automatically generated by mk/krnl/defs.layers.mk. Please do not edit

__FILE_COPIED += $(__FILES_COPIED_MY_QSPI_FLASH_LAYER)




	
	

	
# copying directory h to D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/h/public




PRENOBUILD : D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/h/public/vxbMySpiFlash.h

__FILES_TO_COPY_MY_QSPI_FLASH_LAYER += D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/h/public/vxbMySpiFlash.h





 

D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/h/public/vxbMySpiFlash.h : D:/vxWorks7/vxworks-7/pkgs/custom/myQspiFlash/h/vxbMySpiFlash.h | D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/h/public
ifdef __LAYER_DEPENDENCY_TEST
	cp -rfLs $< $@
else
	cp -rfL $< $@
endif




	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	


	
	
	
	
	
	
	
BUILD : MY_QSPI_FLASH_LAYER_src_diab__BUILD

.PHONY : MY_QSPI_FLASH_LAYER_src_diab__BUILD

__BUILD_FB_IDS += kernel_top_MY_QSPI_FLASH_LAYER_src_diab

MY_QSPI_FLASH_LAYER_src_diab__BUILD : 
	@ echo building MY_QSPI_FLASH_LAYER directory src
	+ @ cd D:/vxWorks7/vxworks-7/pkgs/custom/myQspiFlash/src && D:/vxWorks7/vxworks-7/host/binutils/x86-win32/bin/make _mk CPU=PPCE6500 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_5 SPACE=kernel _VSB_CONFIG_ADDEDCFLAGS="" _WRS_CONFIG_APP_TOOL=diab VSBL_NAME=MY_QSPI_FLASH_LAYER VSB_DIR=D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64 _WRS_CONFIG_FP=hard _WRS_CLI_CFLAGS="-I. " _FB_ID=kernel_top_MY_QSPI_FLASH_LAYER_src_diab BSPNAME=hmt_t2080vpx3u_1_0_0_0 BUILDSTAGE=BUILD


	
	
	

	
	
	

	

	


	
# copying directory cdf to D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/cdf





	
cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER_FILES = 

cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER_DIR = D:/vxWorks7/vxworks-7/pkgs/custom/myQspiFlash

PRENOBUILD_FILES += $(addprefix $(cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER_DIR)/,$(cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER_FILES))

PRENOBUILD : PRENOBUILD_MY_QSPI_FLASH_LAYER

PRENOBUILD_MY_QSPI_FLASH_LAYER : cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER

cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER : D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/cdf/cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER.cdf

D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/cdf/cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER.cdf : | D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/cdf
	$(file >D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/cdf/cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER.tmp,$(call __vsb_tmpl_cdf_inter,$(addprefix $(cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER_DIR)/,$(sort $(cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER_FILES))),MY_QSPI_FLASH_LAYER))
	$(CDFCOMP) -i D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/cdf/cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER.tmp -o $@ -cpp "$(CPP) $(__OPTION_LANG_CDF)" -cpu PPCE6500 -layer MY_QSPI_FLASH_LAYER -vsb D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64
	rm -f D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/cdf/cdf_PRENOBUILD_MY_QSPI_FLASH_LAYER.tmp

	

	
# copying directory cfg to D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/configlette






	
__DIR_TARGETS += $(__DIR_TARGETS_MY_QSPI_FLASH_LAYER)

__DIR_TARGETS_MY_QSPI_FLASH_LAYER += D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/cdf D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/configlette D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/h D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/krnl/h/public D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/share/h D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/usr/h D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild64/vsblCdf

