
ifndef __HEADER_ACCESS_EVDEV_INCLUDED
__HEADER_ACCESS_EVDEV_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_EVDEV = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/EVDEV),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), EVDEV))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/EVDEV
endif
endif

endif

endif

