
ifndef __HEADER_ACCESS_BDM_TFFS_INCLUDED
__HEADER_ACCESS_BDM_TFFS_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BDM_TFFS = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/BDM_TFFS),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BDM_TFFS))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/BDM_TFFS
endif
endif

endif

endif

