
ifndef __HEADER_ACCESS_IPNET_DNSC_INCLUDED
__HEADER_ACCESS_IPNET_DNSC_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_IPNET_DNSC = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET_DNSC),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), IPNET_DNSC))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET_DNSC
endif
endif

endif

endif

