
ifndef __HEADER_ACCESS_CORE_IO_INCLUDED
__HEADER_ACCESS_CORE_IO_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_CORE_IO = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/CORE_IO),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), CORE_IO))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/CORE_IO
endif
endif

endif

endif

