
ifndef __HEADER_ACCESS_SYSTEMVIEWER_AGENT_INCLUDED
__HEADER_ACCESS_SYSTEMVIEWER_AGENT_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_SYSTEMVIEWER_AGENT = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/SYSTEMVIEWER_AGENT),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), SYSTEMVIEWER_AGENT))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/SYSTEMVIEWER_AGENT
endif
endif

endif

endif

