
ifndef __HEADER_ACCESS_FS_COMMON_INCLUDED
__HEADER_ACCESS_FS_COMMON_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_FS_COMMON = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FS_COMMON),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), FS_COMMON))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FS_COMMON
endif
endif

endif

endif

