
ifndef __HEADER_ACCESS_NET_BASE_INCLUDED
__HEADER_ACCESS_NET_BASE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_NET_BASE = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/NET_BASE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), NET_BASE))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/NET_BASE
endif
endif

endif

endif

