
ifndef __HEADER_ACCESS_IPNET_BRIDGE_INCLUDED
__HEADER_ACCESS_IPNET_BRIDGE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_IPNET_BRIDGE = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET_BRIDGE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), IPNET_BRIDGE))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET_BRIDGE
endif
endif

endif

endif

