
ifndef __HEADER_ACCESS_SOCKET_INCLUDED
__HEADER_ACCESS_SOCKET_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_SOCKET = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/SOCKET),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), SOCKET))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/SOCKET
endif
endif

endif

endif

