
ifndef __HEADER_ACCESS_BDM_SIM_INCLUDED
__HEADER_ACCESS_BDM_SIM_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BDM_SIM = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/BDM_SIM),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BDM_SIM))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/BDM_SIM
endif
endif

endif

endif

