
ifndef __HEADER_ACCESS_PPC_BASE_INCLUDED
__HEADER_ACCESS_PPC_BASE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_PPC_BASE = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/PPC_BASE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), PPC_BASE))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/PPC_BASE
endif
endif

endif

endif

