
ifndef __HEADER_ACCESS_SYSCALLS_INCLUDED
__HEADER_ACCESS_SYSCALLS_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_SYSCALLS = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/SYSCALLS),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), SYSCALLS))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/SYSCALLS
endif
endif

endif

endif

