
ifndef __HEADER_ACCESS_IPNET_INCLUDED
__HEADER_ACCESS_IPNET_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_IPNET = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), IPNET))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET
endif
endif

endif

endif

