
ifndef __HEADER_ACCESS_BOARDLIB_INCLUDED
__HEADER_ACCESS_BOARDLIB_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BOARDLIB = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/BOARDLIB),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BOARDLIB))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/BOARDLIB
endif
endif

endif

endif

