
ifndef __HEADER_ACCESS_IPNET_SNTP_INCLUDED
__HEADER_ACCESS_IPNET_SNTP_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_IPNET_SNTP = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/IPNET_SNTP),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), IPNET_SNTP))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/IPNET_SNTP
endif
endif

endif

endif

