
ifndef __HEADER_ACCESS_PPC_USER_INCLUDED
__HEADER_ACCESS_PPC_USER_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_PPC_USER = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/PPC_USER),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), PPC_USER))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/PPC_USER
endif
endif

endif

endif

