
ifndef __HEADER_ACCESS_IPNET_DHCPC_INCLUDED
__HEADER_ACCESS_IPNET_DHCPC_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_IPNET_DHCPC = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/IPNET_DHCPC),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), IPNET_DHCPC))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/IPNET_DHCPC
endif
endif

endif

endif

