
ifndef __HEADER_ACCESS_END_LIB_INCLUDED
__HEADER_ACCESS_END_LIB_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_END_LIB = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/END_LIB),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), END_LIB))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/END_LIB
endif
endif

endif

endif

