
ifndef __HEADER_ACCESS_IPNET_LINKPROTO_INCLUDED
__HEADER_ACCESS_IPNET_LINKPROTO_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_IPNET_LINKPROTO = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/IPNET_LINKPROTO),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), IPNET_LINKPROTO))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/IPNET_LINKPROTO
endif
endif

endif

endif

