
ifndef __HEADER_ACCESS_STOP_MODE_DEBUG_AGENT_INCLUDED
__HEADER_ACCESS_STOP_MODE_DEBUG_AGENT_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_STOP_MODE_DEBUG_AGENT = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/STOP_MODE_DEBUG_AGENT),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), STOP_MODE_DEBUG_AGENT))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/STOP_MODE_DEBUG_AGENT
endif
endif

endif

endif

