
ifndef __HEADER_ACCESS_LANG_LIB_TOOL_TOOLSRC_DIAB_INCLUDED
__HEADER_ACCESS_LANG_LIB_TOOL_TOOLSRC_DIAB_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_LANG_LIB_TOOL_TOOLSRC_DIAB = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/LANG_LIB_TOOL_TOOLSRC_DIAB),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), LANG_LIB_TOOL_TOOLSRC_DIAB))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/LANG_LIB_TOOL_TOOLSRC_DIAB
endif
endif

endif

endif

