
ifndef __HEADER_ACCESS_BDM_XBD_INCLUDED
__HEADER_ACCESS_BDM_XBD_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BDM_XBD = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/BDM_XBD),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BDM_XBD))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/BDM_XBD
endif
endif

endif

endif

