

/* this file is automatically generated */


Layer Layer::FS_NFS {
}




/*********************************
 Component INCLUDE_NFS2_CLIENT 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Component	INCLUDE_NFS2_CLIENT {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Component INCLUDE_CORE_NFS_CLIENT 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Component	INCLUDE_CORE_NFS_CLIENT {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Component INCLUDE_NFS3_CLIENT 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Component	INCLUDE_NFS3_CLIENT {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Component INCLUDE_NFS_CLIENT_ALL 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Component	INCLUDE_NFS_CLIENT_ALL {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Component INCLUDE_NFS_MOUNT_ALL 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Component	INCLUDE_NFS_MOUNT_ALL {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Component INCLUDE_NFS2_SERVER 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Component	INCLUDE_NFS2_SERVER {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Component INCLUDE_CORE_NFS_SERVER 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Component	INCLUDE_CORE_NFS_SERVER {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Component INCLUDE_NFS_SERVER_INSTALL 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Component	INCLUDE_NFS_SERVER_INSTALL {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Component INCLUDE_NFS3_SERVER 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Component	INCLUDE_NFS3_SERVER {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Component INCLUDE_NFS_SERVER_ALL 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Component	INCLUDE_NFS_SERVER_ALL {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Component INCLUDE_NFS_DEBUG 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Component	INCLUDE_NFS_DEBUG {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Folder FOLDER_NFS 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Folder	FOLDER_NFS {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Layer Layer::FS_NFS 
 original object sources located at 
 $(VSB_DIR) 
**********************************/
Layer	Layer::FS_NFS {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(VSB_DIR)}
}


/*********************************
 Parameter NFS2_CLIENT_CACHE_DEFAULT_NUM_LINES 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Parameter	NFS2_CLIENT_CACHE_DEFAULT_NUM_LINES {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Parameter NFS2_CLIENT_CACHE_DEFAULT_LINE_SIZE 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Parameter	NFS2_CLIENT_CACHE_DEFAULT_LINE_SIZE {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Parameter NFS2_CLIENT_CACHE_DEFAULT_OPTIONS 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Parameter	NFS2_CLIENT_CACHE_DEFAULT_OPTIONS {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Parameter NFS3_CLIENT_CACHE_DEFAULT_NUM_LINES 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Parameter	NFS3_CLIENT_CACHE_DEFAULT_NUM_LINES {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Parameter NFS3_CLIENT_CACHE_DEFAULT_LINE_SIZE 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Parameter	NFS3_CLIENT_CACHE_DEFAULT_LINE_SIZE {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Parameter NFS3_CLIENT_CACHE_DEFAULT_OPTIONS 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Parameter	NFS3_CLIENT_CACHE_DEFAULT_OPTIONS {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Parameter NFS_USER_ID 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Parameter	NFS_USER_ID {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Parameter NFS_GROUP_ID 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Parameter	NFS_GROUP_ID {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Parameter NFS_MAXPATH 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Parameter	NFS_MAXPATH {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Parameter GROUP_EXPORTS 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Parameter	GROUP_EXPORTS {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Parameter NFS_MAXFILENAME 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Parameter	NFS_MAXFILENAME {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}


/*********************************
 Parameter NFS_DEBUG_LEVEL 
 original object sources located at 
 $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf 
**********************************/
Parameter	NFS_DEBUG_LEVEL {
		LAYER += Layer::FS_NFS
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/storage/fs-1.0.0.2/nfs-1.0.2.1/cdf/01comp_nfs.cdf}
}
