USE [ELINT];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[RADARMODE] (
[RADAR_MODE_INDEX] int NOT NULL,
[RADAR_MODE_NAME] varchar(10) NOT NULL,
[DATE_CREATED] datetime NULL,
[DATE_LAST_UPDATED] datetime NULL,
[DATE_FIRST_SEEN] datetime NULL,
[DATE_LAST_SEEN] datetime NULL,
[PLATFORM] tinyint NULL,
[SIGNAL_TYPE] tinyint NULL,
[RF_TYPE] tinyint NOT NULL,
[RF_TYPICAL_MIN] float NULL,
[RF_TYPICAL_MAX] float NULL,
[RF_PATTERN_TYPE] tinyint NULL,
[RF_NUM_POSITIONS] tinyint NULL,
[RF_PATTERN_PERIOD_MIN] float NULL,
[RF_PATTERN_PERIOD_MAX] float NULL,
[PRI_TYPE] tinyint NOT NULL,
[PRI_TYPICAL_MIN] float NULL,
[PRI_TYPICAL_MAX] float NULL,
[PRI_PATTERN_TYPE] tinyint NULL,
[PRI_NUM_POSITIONS] tinyint NULL,
[PRI_PATTERN_PERIOD_MIN] float NULL,
[PRI_PATTERN_PERIOD_MAX] float NULL,
[PW_TYPICAL_MIN] float NULL,
[PW_TYPICAL_MAX] float NULL,
[VALIDATION] tinyint NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[RADARMODE] SET (LOCK_ESCALATION = TABLE);
GO

