/****** Object: Table [dbo].[RADARMODE_RF_SEQUENCE]   Script Date: 2022-01-10 ¿ÀÈÄ 5:34:20 ******/
USE [ELINT];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[RADARMODE_RF_SEQUENCE] (
[RADAR_MODE_INDEX] int NOT NULL,
[RF_SEQ_ID] int NOT NULL,
[RF_SEQ_NAME] varchar(20) NULL,
[RF_MIN] float NULL,
[RF_MAX] float NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[RADARMODE_RF_SEQUENCE] SET (LOCK_ESCALATION = TABLE);
GO

