USE [ELINT];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[RADARMODE_PRI_SEQUENCE] (
[RADAR_MODE_INDEX] int NOT NULL,
[PRI_SEQ_ID] int NOT NULL,
[PRI_SEQ_NAME] varchar(20) NULL,
[PRI_MIN] float NULL,
[PRI_MAX] float NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[RADARMODE_PRI_SEQUENCE] SET (LOCK_ESCALATION = TABLE);
GO

