USE [ELINT];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[RAWDATA] (
[SEQ_NUM] int NOT NULL,
[OP_INIT_ID] tinyint NULL,
[PDW_ID] int NULL,
[TASK_ID] char(30) NULL,
[CREATE_TIME] datetime NULL,
[CREATE_TIME_MS] tinyint NULL,
[COUNTOFDATA] tinyint NULL,
[FILENAME] char(100) NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[RAWDATA] SET (LOCK_ESCALATION = TABLE);
GO

