USE [ELINT];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
CREATE TABLE [dbo].[THREAT] (
[THREAT_INDEX] int NOT NULL,
[RADAR_MODE_NAME] varchar(10) NOT NULL,
[THREAT_NAME] varchar(10) NULL,
[LATITUDE] float NULL,
[LONGITUDE] float NULL,
[SITE_NAME] varchar(10) NULL,
[THREAT_PLATFORM] tinyint NULL,
[DATE_CREATED] datetime NULL,
[DATE_FIRST_SEEN] datetime NULL,
[DATE_LAST_SEEN] datetime NULL,
[ID_RANGE] float NULL)
ON [PRIMARY]
WITH (DATA_COMPRESSION = NONE);
GO
ALTER TABLE [dbo].[THREAT] SET (LOCK_ESCALATION = TABLE);
GO

