USE [ELINT];
GO
SET ANSI_NULLS ON;
GO
SET QUOTED_IDENTIFIER ON;
GO
ALTER VIEW [dbo].[VIEW_RADARMODE]
AS
SELECT
	A.RADAR_INDEX, 
  A.RADARMODE_INDEX,
  A.RADARMODE_NAME,
  A.MODECODE,
  
  B.DATE_CREATED,
  B.DATE_LAST_UPDATED,
  B.DATE_FIRST_SEEN,
  B.DATE_LAST_SEEN,
  B.PLATFORM,
  B.SIGNAL_TYPE,
  B.RF_TYPE,
  B.RF_TYPICAL_MIN,
  B.RF_TYPICAL_MAX,
  B.RF_PATTERN_TYPE,
  B.RF_NUM_POSITIONS,
  B.RF_PATTERN_PERIOD_MIN,
  B.RF_PATTERN_PERIOD_MAX,
  B.PRI_TYPE,
  B.PRI_TYPICAL_MIN,
  B.PRI_TYPICAL_MAX,
  B.PRI_PATTERN_TYPE,
  B.PRI_POSITION_COUNT,
  B.PRI_PATTERN_PERIOD_MIN,
  B.PRI_PATTERN_PERIOD_MAX,
  B.PW_TYPICAL_MIN,
  B.PW_TYPICAL_MAX,
  B.PRIORITY,
  
  C.PRIORITY AS R_PRIORITY,
  C.ELNOT,  
  C.NICK_NAME,
  C.FUNC_CODE
FROM
	RADAR AS C
  INNER JOIN RADARMODE_LIFECYCLE A ON C.RADAR_INDEX=A.RADAR_INDEX 
  INNER JOIN RADARMODE B ON B.RADARMODE_INDEX=A.RADARMODE_INDEX 
WHERE B.VALIDATION='1' 

GO