#!/bin/sh

start()
{
	echo "bootscript:start 수행합니다 ----------------------------------------------"
	echo "1. 압축된 WEB 파일을 풉니다."
	cd /srv/www
	tar -xf web.tar.gz
	chown -R root:root .
	rm web.tar.gz
	
	echo "2. 폴더를 공유 합니다."
	
	
	echo "bootscript:start 종료합니다 ----------------------------------------------"
}

stop()
{
	echo "bootscript:stop 수행합니다 -----------------------------------------------"
	ls
	
	echo "bootscript:stop 종료합니다 -----------------------------------------------"
}


restart()
{
	echo "bootscript:restart 수행합니다 --------------------------------------------"
	stop
	start
	
	echo "bootscript:restart 종료합니다 --------------------------------------------"
}


[ -e $DAEMON ] || exit 1
	case "$1" in
		start)
			start; ;;
		stop)
			stop; ;;
		restart)
			restart; ;;
		*)
			echo "사용법: $0 {start|stop|restart}"
			exit 1
	esac
exit $?
