//GIT-VS-VERSION-GEN.bat generated resource header.
#define GEN_VER_VERSION_STRING   "EST.284.g8821d.dirty\0" 
#define GEN_VER_DIGITAL_VERSION  EST,284,g8821d,0 
#define GEN_VER_VERSION_HEX      0x0000011C00000000 
#define GEN_VER_COMMENT_STRING   "Major Version Release\0" 
#define GEN_VER_PRIVATE_FLAG     VS_FF_PRIVATEBUILD 
#define GEN_VER_PRIVATE_STRING   "Custom Build\0" 
#define GEN_VER_PATCHED_FLAG     VS_FF_PATCHED 
#define GEN_VER_PRERELEASE_FLAG  0 
