APP = apppocketsonata
APP2 = apptest

SYSTEM_CGI = system.cgi

FETCH_CGI = fetch.cgi

UPLOAD_CGI = upload.cgi

DOWNLOAD_CGI = download.cgi

BIT_CGI = bit.cgi

LISTALLCHANNEL_CGI = listallchannel.cgi

# Add any other object files to this list below
APP_OBJS  = Anal/EmitterMerge/CInverseMethod.o
APP_OBJS += Anal/EmitterMerge/DistanceLeastSquare/DistanceLeastSquare.o
APP_OBJS += Anal/EmitterMerge/ELEmitterMergeMngr.o
APP_OBJS += Anal/EmitterMerge/ELEnvironVariableMngr.o
APP_OBJS += Anal/EmitterMerge/ELThreat.o
APP_OBJS += Anal/EmitterMerge/GeoCoordConv.o
APP_OBJS += Anal/EmitterMerge/LOBClustering.o
APP_OBJS += Anal/EmitterMerge/Matrix/Matrix.o
APP_OBJS += Anal/EmitterMerge/PositionEstimationAlg.o
APP_OBJS += Anal/EmitterMerge/Quadratic/Quadratic.o
APP_OBJS += Anal/EmitterMerge/UTM.o
APP_OBJS += Anal/Identify/ELUtil.o
APP_OBJS += Anal/Identify/Identify.o
APP_OBJS += Anal/Identify/cipl.o
APP_OBJS += Anal/KnownSigAnal/KAnalPRI.o
APP_OBJS += Anal/KnownSigAnal/KGroup.o
APP_OBJS += Anal/KnownSigAnal/KMakeAET.o
APP_OBJS += Anal/KnownSigAnal/KPulExt.o
APP_OBJS += Anal/KnownSigAnal/KnownSigAnal.o
APP_OBJS += Anal/NewSigAnal/NGroup.o
APP_OBJS += Anal/NewSigAnal/NPulExt.o
APP_OBJS += Anal/NewSigAnal/NAnalPRI.o
APP_OBJS += Anal/NewSigAnal/NMakeAET.o
APP_OBJS += Anal/NewSigAnal/NewSigAnal.o
APP_OBJS += Anal/ScanSigAnal/SAnalSCN.o
APP_OBJS += Anal/ScanSigAnal/SGroup.o
APP_OBJS += Anal/ScanSigAnal/SPulExt.o
APP_OBJS += Anal/ScanSigAnal/ScanSigAnal.o
APP_OBJS += Anal/ParamMngr.o
APP_OBJS += Anal/SigAnal/Group.o
APP_OBJS += Anal/SigAnal/PulExt.o
APP_OBJS += Anal/SigAnal/AnalPRI.o
APP_OBJS += Anal/SigAnal/MakeAET.o
APP_OBJS += Anal/SigAnal/SysPara.o
APP_OBJS += Anal/SigAnal/stdafx.o
APP_OBJS += Anal/SigAnal/cencdec.o
APP_OBJS += Anal/MIDAS/Midas.o
APP_OBJS += Anal/MIDAS/RawFile.o
APP_OBJS += Anal/Collect/DataFile/DataFile.o
APP_OBJS += Anal/Collect/ccollectbank/ccollectbank.o
APP_OBJS += MinIni/minIni.o
APP_OBJS += SQLite/Backup.o
APP_OBJS += SQLite/Column.o
APP_OBJS += SQLite/Database.o
APP_OBJS += SQLite/Exception.o
APP_OBJS += SQLite/Statement.o
APP_OBJS += SQLite/Transaction.o
APP_OBJS += System/csysconfig.o
APP_OBJS += System/csharedmemory.o
APP_OBJS += Thread/ccgi.o
APP_OBJS += Thread/cdetectanalysis.o
APP_OBJS += Thread/cemittermerge.o
APP_OBJS += Thread/cjamtech.o
APP_OBJS += Thread/cprompt.o
APP_OBJS += Thread/cpulsetrk.o
APP_OBJS += Thread/cscananalysis.o
APP_OBJS += Thread/csignalcollect.o
APP_OBJS += Thread/ctaskmngr.o
APP_OBJS += Thread/ctrackanalysis.o
APP_OBJS += Thread/curbit.o
APP_OBJS += Thread/creclan.o
APP_OBJS += Thread/cusercollect.o
APP_OBJS += Utils/carraymsgdata.o
APP_OBJS += Utils/ccommonutils.o
APP_OBJS += Utils/cfile.o
APP_OBJS += Utils/clog.o
APP_OBJS += Utils/cmultiserver.o
APP_OBJS += Utils/csingleserver.o
APP_OBJS += Utils/csingleclient.o
APP_OBJS += Utils/cthread.o
APP_OBJS += Utils/cgpio.o
APP_OBJS += Utils/programrev.o
APP_OBJS += Utils/chwio.o
APP_OBJS += Utils/DMA/dma.o
#APP_OBJS += Test/hw_interface.o
#APP_OBJS += Test/api/dma.o
APP_OBJS += cmain.o

# Add any other object files to this list below
APP2_OBJS  = Test/helloworld.o
APP2_OBJS += Test/hw_interface.o
APP2_OBJS += Test/api/dma.o

###########################################################################
# CGI-BIN
# system.cgi
SYSTEM_CGI_OBJS = System/csharedmemory.o
SYSTEM_CGI_OBJS += CGI-BIN/system_cgi/system_cgi.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/md5/md5c.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/mkstemp.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qArg.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qAwk.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qCount.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qDecoder.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qDownload.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qEncode.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qEnv.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qError.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qFile.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qHttpHeader.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qInternalCommon.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qInternalEntry.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qMisc.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qSed.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qSession.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qString.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qTime.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qValid.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qfDecoder.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/qsDecoder.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/snprintf.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/strcasecmp.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/strptime.o
SYSTEM_CGI_OBJS += CGI-BIN/Qdecoder/timegm.o
SYSTEM_CGI_OBJS += MinIni/minIni.o


# upload.cgi
UPLOAD_CGI_OBJS = CGI-BIN/Qdecoder/md5/md5c.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/mkstemp.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qArg.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qAwk.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qCount.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qDecoder.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qDownload.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qEncode.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qEnv.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qError.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qFile.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qHttpHeader.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qInternalCommon.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qInternalEntry.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qMisc.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qSed.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qSession.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qString.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qTime.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qValid.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qfDecoder.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qsDecoder.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/snprintf.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/strcasecmp.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/strptime.o
UPLOAD_CGI_OBJS += CGI-BIN/Qdecoder/timegm.o
UPLOAD_CGI_OBJS += CGI-BIN/upload_cgi/main.o

# download.cgi
DOWNLOAD_CGI_OBJS = CGI-BIN/Qdecoder/md5/md5c.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/mkstemp.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qArg.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qAwk.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qCount.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qDecoder.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qDownload.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qEncode.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qEnv.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qError.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qFile.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qHttpHeader.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qInternalCommon.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qInternalEntry.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qMisc.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qSed.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qSession.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qString.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qTime.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qValid.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qfDecoder.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/qsDecoder.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/snprintf.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/strcasecmp.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/strptime.o
DOWNLOAD_CGI_OBJS += CGI-BIN/Qdecoder/timegm.o
DOWNLOAD_CGI_OBJS += CGI-BIN/download_cgi/download_cgi.o

# fetch.cgi
FETCH_CGI_OBJS = CGI-BIN/Qdecoder/md5/md5c.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/mkstemp.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qArg.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qAwk.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qCount.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qDecoder.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qDownload.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qEncode.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qEnv.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qError.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qFile.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qHttpHeader.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qInternalCommon.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qInternalEntry.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qMisc.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qSed.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qSession.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qString.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qTime.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qValid.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qfDecoder.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/qsDecoder.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/snprintf.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/strcasecmp.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/strptime.o
FETCH_CGI_OBJS += CGI-BIN/Qdecoder/timegm.o
FETCH_CGI_OBJS += MinIni/minIni.o
FETCH_CGI_OBJS += CGI-BIN/fetch_cgi/main.o
FETCH_CGI_OBJS += System/csharedmemory.o


# bit.cgi
BIT_CGI_OBJS = CGI-BIN/Qdecoder/md5/md5c.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/mkstemp.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qArg.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qAwk.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qCount.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qDecoder.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qDownload.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qEncode.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qEnv.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qError.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qFile.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qHttpHeader.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qInternalCommon.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qInternalEntry.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qMisc.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qSed.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qSession.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qString.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qTime.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qValid.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qfDecoder.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/qsDecoder.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/snprintf.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/strcasecmp.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/strptime.o
BIT_CGI_OBJS += CGI-BIN/Qdecoder/timegm.o
BIT_CGI_OBJS += Thread/ccgi.o
BIT_CGI_OBJS += Thread/curbit.o
BIT_CGI_OBJS += Utils/carraymsgdata.o
BIT_CGI_OBJS += Utils/cgpio.o
BIT_CGI_OBJS += Utils/clog.o
BIT_CGI_OBJS += Utils/cthread.o
BIT_CGI_OBJS += CGI-BIN/bit_cgi/main.o

# listallchannel.cgi
LISTALLCHANNEL_CGI_OBJS = CGI-BIN/Qdecoder/md5/md5c.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/mkstemp.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qArg.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qAwk.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qCount.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qDecoder.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qDownload.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qEncode.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qEnv.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qError.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qFile.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qHttpHeader.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qInternalCommon.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qInternalEntry.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qMisc.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qSed.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qSession.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qString.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qTime.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qValid.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qfDecoder.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/qsDecoder.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/snprintf.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/strcasecmp.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/strptime.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/Qdecoder/timegm.o
LISTALLCHANNEL_CGI_OBJS += CGI-BIN/listallchannel_cgi/main.o
LISTALLCHANNEL_CGI_OBJS += Anal/Collect/ccollectbank/ccollectbank.o
LISTALLCHANNEL_CGI_OBJS += Anal/MIDAS/RawFile.o
LISTALLCHANNEL_CGI_OBJS += System/csharedmemory.o    
LISTALLCHANNEL_CGI_OBJS += Utils/clog.o    
LISTALLCHANNEL_CGI_OBJS += System/csysconfig_cgi.o        
LISTALLCHANNEL_CGI_OBJS += Utils/ccommonutils_cgi.o    
LISTALLCHANNEL_CGI_OBJS += Anal/Collect/DataFile/DataFile_cgi.o

    

# INLCUDES 경로
INCLUDES = -I$(TMPDIR)/sysroots-components/aarch64/readline/usr/include
INCLUDES += -I$(TMPDIR)/sysroots-components/aarch64/ncurses/usr/include
INCLUDES += -I$(TMPDIR)/sysroots-components/aarch64/boost/usr/include
INCLUDES += -I$(TMPDIR)/sysroots-components/aarch64/sqlite3/usr/include


# LIBS 경로
LIBS = -L$(TMPDIR)/sysroots-components/aarch64/readline/usr/lib
LIBS += -L$(TMPDIR)/sysroots-components/aarch64/ncurses/lib
LIBS += -L$(TMPDIR)/sysroots-components/aarch64/ncurses/usr/lib
#LIBS += -L$(TMPDIR)/sysroots-components/aarch64/boost/usr/lib
LIBS += -L$(TMPDIR)/sysroots-components/aarch64/sqlite3/usr/lib

SRCS = $(APP_OBJS:.o=.cpp)

#LDLIBS = -pthread -lreadline -lncurses -lboost_thread -lboost_system -lsqlite3
LDLIBS = -pthread -lreadline -lncurses -lsqlite3

DEFINES += -D_POCKETSONATA_
DEFINES += -D_SQLITE_
DEFINES += -D__ZYNQ_BOARD__


CGI_DEFINES += -D_CGI_LIST_


all: build

build: $(APP) $(APP2) $(SYSTEM_CGI) $(UPLOAD_CGI) $(DOWNLOAD_CGI) $(FETCH_CGI) $(LISTALLCHANNEL_CGI)

$(APP): $(APP_OBJS)
	$(CXX) $(LDFLAGS) -o $@ $(APP_OBJS) $(LDLIBS) $(LIBS)
	
$(APP2): $(APP2_OBJS)
	$(CXX) $(LDFLAGS) -o $@ $(APP2_OBJS) $(LDLIBS) $(LIBS)	
	
$(SYSTEM_CGI): $(SYSTEM_CGI_OBJS)
	$(CXX) $(LDFLAGS) -o $@ $(SYSTEM_CGI_OBJS) $(LDLIBS) $(LIBS)
	
$(FETCH_CGI): $(FETCH_CGI_OBJS)
	$(CXX) $(LDFLAGS) -o $@ $(FETCH_CGI_OBJS) $(LDLIBS) $(LIBS)			
	
$(UPLOAD_CGI): $(UPLOAD_CGI_OBJS)
	$(CXX) $(LDFLAGS) -o $@ $(UPLOAD_CGI_OBJS) $(LDLIBS) $(LIBS)	

$(DOWNLOAD_CGI): $(DOWNLOAD_CGI_OBJS)
	$(CXX) $(LDFLAGS) -o $@ $(DOWNLOAD_CGI_OBJS) $(LDLIBS) $(LIBS)	
	
$(BIT_CGI): $(BIT_CGI_OBJS)
	$(CXX) $(LDFLAGS) -o $@ $(BIT_CGI_OBJS) $(LDLIBS) $(LIBS)		
	
$(LISTALLCHANNEL_CGI): $(LISTALLCHANNEL_CGI_OBJS)
	$(CXX) $(LDFLAGS) -o $@ $(LISTALLCHANNEL_CGI_OBJS) $(LDLIBS) $(LIBS)
	
	
# 기본 컴파일 방법들	
	
%.o: %.cpp
	$(CXX) $(CFLAGS) -c $< -o $@ $(INCLUDES) $(DEFINES) 
	
	
# CGI 구성하기 위한 컴파일 방법들		
	
System/csysconfig_cgi.o: System/csysconfig.cpp	
	$(CXX) $(CFLAGS) -c $< -o $@ $(INCLUDES) $(DEFINES) $(CGI_DEFINES) 
	
Utils/ccommonutils_cgi.o: Utils/ccommonutils.cpp	
	$(CXX) $(CFLAGS) -c $< -o $@ $(INCLUDES) $(DEFINES) $(CGI_DEFINES)   	
	
Anal/Collect/DataFile/DataFile_cgi.o: Anal/Collect/DataFile/DataFile.cpp	
	$(CXX) $(CFLAGS) -c $< -o $@ $(INCLUDES) $(DEFINES) $(CGI_DEFINES)   		


clean:
	$(RM) $(APP_OBJS) $(APP) $(SYSTEM_CGI) $(FETCH_CGI) $(UPLOAD_CGI) $(DOWNLOAD_CGI) $(BIT_CGI) $(LISTALLCHANNEL_CGI)
	
install:
	$(TARGETINST) -a "/dev/mmcblk0p1	/media/sdcard	auto	default,sync,noauto	0	0"	/etc/fstab	




