# 2020-08-26 오후 3:22:26

# CED/EOB 관련 테이블 코드 테이블을 삭제합니다.
DROP TABLE if exists "COHERENCY_CODE";
DROP TABLE if exists "CONTINUITY_CODE";
DROP TABLE if exists "MOP_CW_LEGACY_TYPE_CODE";
DROP TABLE if exists "MOP_CW_MOD_TYPE_CODE";
DROP TABLE if exists "PARAM_SET_ASSOC_TYPE_CODE";
DROP TABLE if exists "PATTERN_CODE";
DROP TABLE if exists "PLATFORM_CODE";
DROP TABLE if exists "POLARIZATION_CODE";
DROP TABLE if exists "PRI_LEGACY_TYPE_CODE";
DROP TABLE if exists "RF_LEGACY_TYPE_CODE";
DROP TABLE if exists "RF_MOP_TYPE_CODE";
DROP TABLE if exists "ROTATION_DIR_CODE";
DROP TABLE if exists "SCAN_TYPE_CODE";
DROP TABLE if exists "THREAT_STATUS_CODE";
DROP TABLE if exists "VALIDATION_CODE";
DROP TABLE if exists "COUNTRY";
DROP TABLE if exists "FUNCTION_CODES";

# CED/EOB 관련 테이블 코드 테이블을 생성합니다.
CREATE TABLE COHERENCY_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(25),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE CONTINUITY_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(25),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE MOP_CW_LEGACY_TYPE_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(25),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE MOP_CW_MOD_TYPE_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(25),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE PARAM_SET_ASSOC_TYPE_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(30),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE PATTERN_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(25),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE PLATFORM_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(25),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE POLARIZATION_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(50),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE PRI_LEGACY_TYPE_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(50),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE RF_LEGACY_TYPE_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(50),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE RF_MOP_TYPE_CODE
(
	RF_MOP_TYPE_CODE VARCHAR2(2) NOT NULL,
	SECLAB NUMBER NOT NULL,
	RF_MOP_TYPE_DEF VARCHAR2(30) NOT NULL,
	PRIMARY KEY (RF_MOP_TYPE_CODE)
);
CREATE TABLE ROTATION_DIR_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(25),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE SCAN_TYPE_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(25),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE THREAT_STATUS_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(25),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE VALIDATION_CODE
(
	CODE_VAL NUMBER NOT NULL,
	ABBREVIATION VARCHAR2(25),
	NAME VARCHAR2(100),
	PRIMARY KEY (CODE_VAL)
);
CREATE TABLE COUNTRY
(
  COUNTRY_CODE  VARCHAR2(2 ) NOT NULL,
  COUNTRY_NAME  VARCHAR2(80 ) NOT NULL,
  TRIGRAPH      VARCHAR2(3 ),
  SECLAB        INTEGER DEFAULT 0 NOT NULL,
  PRIMARY KEY (COUNTRY_CODE)
);
CREATE TABLE FUNCTION_CODES
(
  ABBREVIATION  VARCHAR2(20 ) NOT NULL,
  NAME  	VARCHAR2(45 ) NOT NULL,
  DESCRIPTION   CLOB,
  SYSTEM	INTEGER,
  SECLAB        INTEGER DEFAULT 0 NOT NULL,
  PRIMARY KEY (ABBREVIATION)
);

# CED/EOB 관련 테이블 코드 테이블에 데이터를 삽입합니다.
INSERT INTO COHERENCY_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (0, 'COHERENT', 'COHERENT');
INSERT INTO COHERENCY_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (1, 'NON_COHERENT', 'NON_COHERENT');
INSERT INTO COHERENCY_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (3, 'UNKNOWN', 'UNKNOWN');
INSERT INTO CONTINUITY_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (0, 'UNKNOWN', 'UNKNOWN');
INSERT INTO CONTINUITY_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (1, 'DISCRETE', 'DISCRETE');
INSERT INTO CONTINUITY_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (2, 'COUNTINUOUS', 'COUNTINUOUS');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (40, 'FMOP', 'FMOP');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (41, 'FMOP_LINEAR', 'FMOP_LINEAR');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (42, 'FMOP_NONLINEAR', 'FMOP_NONLINEAR');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (43, 'FMOP_STEPPED', 'FMOP_STEPPED');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (44, 'PMOP', 'PMOP');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (45, 'PMOP_BPSK', 'PMOP_BPSK');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (46, 'PMOP_QPSK', 'PMOP_QPSK');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (47, 'PMOP_MSK', 'PMOP_MSK');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (49, 'PMOP_POLY_TIME', 'PMOP_POLY_TIME');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (50, 'AMOP', 'AMOP');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (51, 'PCM', 'PCM');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (53, 'FM_TRIANGULAR', 'FM_TRIANGULAR');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (55, 'FM_SINUSOIDAL', 'FM_SINUSOIDAL');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (62, 'AM_TONES', 'AM_TONES');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (63, 'ON_OFF_KEYING', 'ON_OFF_KEYING');
INSERT INTO MOP_CW_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (64, 'OOK_SRW', 'OOK_SRW');
INSERT INTO MOP_CW_MOD_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (0, 'UNKNOWN', 'UNKNOWN');
INSERT INTO MOP_CW_MOD_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (1, 'FREQUENCY', 'FREQUENCY');
INSERT INTO MOP_CW_MOD_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (2, 'PHASE', 'PHASE');
INSERT INTO MOP_CW_MOD_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (3, 'AMPLITUDE', 'AMPLITUDE');
INSERT INTO MOP_CW_MOD_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (4, 'UNMODULATED', 'UNMODULATED');
INSERT INTO PARAM_SET_ASSOC_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (1, 'Simultaneous', 'Simultaneous');
INSERT INTO PARAM_SET_ASSOC_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (2, 'Sequential', 'Sequential');
INSERT INTO PARAM_SET_ASSOC_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (3, 'Independent-simultaneous', 'Independent-simultaneous');
INSERT INTO PATTERN_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (0, 'UNKNOWN', 'UNKNOWN');
INSERT INTO PATTERN_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (1, 'PATTERNED', 'PATTERNED');
INSERT INTO PATTERN_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (2, 'NON_PATTERNED', 'NON_PATTERNED');
INSERT INTO PATTERN_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (3, 'ADAPTIVE', 'ADAPTIVE');
INSERT INTO PATTERN_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (5, 'UNMODULATED', 'UNMODULATED');
INSERT INTO PLATFORM_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (0, 'UNKNOWN', 'UNKNOWN');
INSERT INTO PLATFORM_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (1, 'LAND', 'LAND');
INSERT INTO PLATFORM_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (2, 'SEA', 'SEA');
INSERT INTO PLATFORM_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (3, 'LAND_SEA_AND_AIR', 'LAND_SEA_AND_AIR');
INSERT INTO PLATFORM_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (4, 'COASTAL', 'COASTAL');
INSERT INTO PLATFORM_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (5, 'AIR', 'AIR');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (0, 'C', 'Diverse (Agile or adaptive). Capable of pulse-to-pulse agility.');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (1, 'D', 'Diverse.Option of operating with any of several polarizations.');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (2, 'G', 'Linear with no reference to plane (unknown whether H or V).');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (3, 'H', 'Linear - horizontal as compared with earth horizon or platform.');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (4, 'J', 'Circular, with right hand sense.');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (5, 'K', 'Circular, with left hand sense.');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (6, 'L', 'Circular, undetermined sense.');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (7, 'M', 'Elliptical.');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (8, 'R', 'Rotating.');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (9, 'S', 'Linear - slant, undetermined angle.');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (10, 'T', 'Linear - slant, right of vertical as compared with earth horizon or platform');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (11, 'U', 'Linear - slant, leeft of vertical as compared with earth horizon or platform');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (12, 'V', 'Linear - vertical as compared with earth horizon or platform');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (13, 'W', 'Unpolarized - modulated or spinning linear polarization');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (14, 'Y', 'Polarization fixed but type unknown');
INSERT INTO POLARIZATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (15, 'Z', 'Undetermined');
INSERT INTO PRI_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (20, 'PULSE_CONSTANT', 'PULSE_CONSTANT');
INSERT INTO PRI_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (21, 'STAGGER', 'STAGGER');
INSERT INTO PRI_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (22, 'JITTER', 'JITTER');
INSERT INTO PRI_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (23, 'DWELL_AND_SWITCH', 'DWELL_AND_SWITCH');
INSERT INTO PRI_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (24, 'PULSE_POSITION_MODULATION', 'PULSE_POSITION_MODULATION');
INSERT INTO PRI_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (25, 'PULSE_FREQUENCY_MODULATION', 'PULSE_FREQUENCY_MODULATION');
INSERT INTO PRI_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (26, 'PRI_SLIDING', 'PRI_SLIDING');
INSERT INTO PRI_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (27, 'PRI_PHASE_MODULATION_OR_SHIFTING', 'PRI_PHASE_MODULATION_OR_SHIFTING');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (0, 'RF_AGILE', 'RF_AGILE');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (1, 'RF_AGILE_PULSE_TO_PULSE', 'RF_AGILE_PULSE_TO_PULSE');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (2, 'RF_AGILE_GROUP_TO_GROUP', 'RF_AGILE_GROUP_TO_GROUP');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (3, 'RF_AGILE_SUB_PULSE', 'RF_AGILE_SUB_PULSE');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (4, 'MULTIPLE_RF', 'MULTIPLE_RF');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (5, 'MULTIPLE_RF_SIMULTANEOUS', 'MULTIPLE_RF_SIMULTANEOUS');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (6, 'MULTIPLE_RF_SEQUENTIAL', 'MULTIPLE_RF_SEQUENTIAL');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (7, 'LIMITED_RF_CHANGE_CAPABLE', 'LIMITED_RF_CHANGE_CAPABLE');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (8, 'RF_SWEEPING', 'RF_SWEEPING');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (9, 'RF_SWEEPING_LINEAR', 'RF_SWEEPING_LINEAR');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (10, 'RF_SWEEPING_SINUSOIDAL', 'RF_SWEEPING_SINUSOIDAL');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (11, 'RF_SWEEPING_TRIANGULAR', 'RF_SWEEPING_TRIANGULAR');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (12, 'RF_SLIDING', 'RF_SLIDING');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (13, 'ON_OFF_KEYED', 'ON_OFF_KEYED');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (14, 'CONSTANT_SINGLE_RF', 'CONSTANT_SINGLE_RF');
INSERT INTO RF_LEGACY_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (15, 'LINEAR_RF_STEPPING', 'LINEAR_RF_STEPPING');
INSERT INTO ROTATION_DIR_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (0, 'Counter Clockwise', 'Clockwise');
INSERT INTO ROTATION_DIR_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (1, 'Clockwise', 'Clockwise');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (0, 'A', 'Circular');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (1, 'B', 'Horizontal Sector (Bi-directional)');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (2, 'C', 'Vertical Sector (Bi-directional)');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (3, 'D', 'Non-Scanning');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (4, 'E', 'Irregular');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (5, 'F', 'Conical');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (6, 'G', 'Lobe Switching');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (7, 'H', 'Orthogonal or Interleaved Sectors');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (8, 'J', 'Raster');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (9, 'K', 'Spiral');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (10, 'L', 'Helical');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (11, 'O', 'Sector Uni or Bi-Directional');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (12, 'P', 'Agile Beam');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (13, 'R', 'Other Combination/Patterns');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (14, 'S', 'Vertical Sector (Uni-Directional)');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (15, 'T', 'Horizontal Sector (Uni-Directional)');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (16, 'U', 'Uni-Directional Sector (Plane Undertermined)');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (17, 'V', 'Bi-Directional Sector (Plane Undetermined)');
INSERT INTO SCAN_TYPE_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (18, 'Z', 'Undetermined');
INSERT INTO THREAT_STATUS_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (0, 'C', 'C');
INSERT INTO THREAT_STATUS_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (1, 'P', 'P');
INSERT INTO THREAT_STATUS_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (2, 'N', 'N');
INSERT INTO THREAT_STATUS_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (3, 'X', 'X');
INSERT INTO THREAT_STATUS_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (4, 'D', 'D');
INSERT INTO THREAT_STATUS_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (5, 'U', 'U');
INSERT INTO THREAT_STATUS_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (6, 'I', 'I');
INSERT INTO THREAT_STATUS_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (7, 'A', 'A');
INSERT INTO VALIDATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (0, 'UNVALIDATED', 'UNVALIDATED');
INSERT INTO VALIDATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (1, 'VALIDATED', 'VALIDATED');
INSERT INTO VALIDATION_CODE(CODE_VAL, ABBREVIATION, NAME) VALUES (2, 'POSTULATED', 'POSTULATED');
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AF', 'Afghanistan', 'AFG', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AX', 'Akrotiri', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AL', 'Albania', 'ALB', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AG', 'Algeria', 'DZA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AQ', 'American Samoa', 'ASM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AN', 'Andorra', 'AND', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AO', 'Angola', 'AGO', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AV', 'Anguilla', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AY', 'Antarctica', 'ATA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AC', 'Antigua and Barbuda', 'ATG', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AR', 'Argentina', 'ARG', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AM', 'Armenia', 'ARM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AA', 'Aruba', 'ABW', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AT', 'Ashmore and Cartier Islands', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AS', 'Australia', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AU', 'Austria', 'AUS', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AJ', 'Azerbaijan', 'AZE', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BF', 'Bahamas', 'BHS', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BA', 'Bahrain', 'BHR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('FQ', 'Baker Island', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BG', 'Bangladesh', 'BGD', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BB', 'Barbados', 'BRB', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BS', 'Bassas da India', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BO', 'Belarus', 'BLR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BE', 'Belgium', 'BEL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BH', 'Belize', 'BLZ', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BN', 'Benin', 'BEN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BD', 'Bermuda', 'BMU', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BT', 'Bhutan', 'BTN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BL', 'Bolivia', 'BOL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BK', 'Bosnia and Herzegovina', 'BIH', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BC', 'Botswana', 'BWA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BV', 'Bouvet Island', 'BVT', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BR', 'Brazil', 'BRA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('IO', 'British Indian Ocean Territory', 'IOT', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('VI', 'British Virgin Islands', 'VGB', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BX', 'Brunei', 'BRN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BU', 'Bulgaria', 'BGR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('UV', 'Burkina Faso', 'BFA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BM', 'Burma / Myanmar', 'MMR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BY', 'Burundi', 'BDI', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CB', 'Cambodia', 'KHM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CM', 'Cameroon', 'CMR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CA', 'Canada', 'CAN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CV', 'Cape Verde', 'CPV', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CJ', 'Cayman Islands', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CT', 'Central African Republic', 'CAF', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CD', 'Chad', 'TCD', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CI', 'Chile', 'CHL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('KT', 'Christmas Island', 'CXR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('IP', 'Clipperton Island', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CK', 'Cocos (Keeling) Islands', 'CCK', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CO', 'Colombia', 'COL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CN', 'Comoros', 'COM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CW', 'Cook Islands', 'COK', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CR', 'Coral Sea Islands', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CS', 'Costa Rica', 'CRI', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('IV', 'Cote d-lvoire', 'CIV', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('HR', 'Croatia', 'HRV', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CU', 'Cuba', 'CUB', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CY', 'Cyprus', 'CYP', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('EZ', 'Czech Republic', 'CZE', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CG', 'Democratic Republic of the Congo', 'COD', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('DA', 'Denmark', 'DNK', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('DX', 'Dhekelia', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('DJ', 'Djibouti', 'DJI', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('DO', 'Dominica', 'DMA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('DR', 'Dominican Republic', 'DOM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('EC', 'Ecuador', 'ECU', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('EG', 'Egypt', 'EGY', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('ES', 'El Salvador', 'SLV', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('EK', 'Equatorial Guinea', 'GNQ', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('ER', 'Eritrea', 'ERI', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('EN', 'Estonia', 'EST', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('ET', 'Ethiopia', 'ETH', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('EU', 'Europa Island', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('FK', 'Falkland Islands/Islas Malvinas', 'FLK', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('FO', 'Faroe Islands', 'FRO', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('FM', 'Federated States of Micronesia', 'FSM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('FJ', 'Fiji', 'FJI', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('FI', 'Finland', 'FIN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('FR', 'France', 'FRA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('FG', 'French Guiana', 'GUF', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('FP', 'French Polynesia', 'PYF', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('FS', 'French Southern Territories', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GB', 'Gabon', 'GAB', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GZ', 'Gaza Strip', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GG', 'Georgia', 'GEO', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GM', 'Germany', 'DEU', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GH', 'Ghana', 'GHA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GI', 'Gibraltar', 'GIB', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GO', 'Glorioso Islands', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GR', 'Greece', 'GRC', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GL', 'Greenland', 'GRL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GJ', 'Grenada', 'GRD', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GP', 'Guadeloupe', 'GLP', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GQ', 'Guam', 'GUM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GT', 'Guatemala', 'GTM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GK', 'Guernsey', 'GGY', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GV', 'Guinea', 'GIN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('PU', 'Guinea-Bissau', 'GNB', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GY', 'Guyana', 'GUY', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('HA', 'Haiti', 'HTI', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('HM', 'Heard Island and McDonald Islands', 'HMD', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('HO', 'Honduras', 'HND', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('HK', 'Hong Kong', 'HKG', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('HU', 'Hungary', 'HUN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('IC', 'Iceland', 'ISL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('IN', 'India', 'IND', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('ID', 'Indonesia', 'IDN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('IR', 'Iran', 'IRN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('IZ', 'Iraq', 'IRQ', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('IM', 'Isle of Man', 'IMN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('IS', 'Israel', 'ISR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('IT', 'Italy', 'ITA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('JM', 'Jamaica', 'JAM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('JN', 'Jan Mayen', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('JA', 'Japan', 'JPN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('JE', 'Jersey', 'JEY', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('JQ', 'Johnston Atoll', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('JO', 'Jordan', 'JOR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('JU', 'Juan de Nova Island', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('KZ', 'Kazakhstan', 'KAZ', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('KE', 'Kenya', 'KEN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('KQ', 'Kingman Reef', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('KR', 'Kiribati', 'KIR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('KU', 'Kuwait', 'KWT', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('KG', 'Kyrgyzstan', 'KGZ', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('LA', 'Laos', 'LAO', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('LG', 'Latvia', 'LVA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('LE', 'Lebanon', 'LBN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('LT', 'Lesotho', 'LSO', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('LI', 'Liberia', 'LBR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('LY', 'Libya', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('LS', 'Liechtenstein', 'LIE', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('LH', 'Lithuania', 'LTU', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('LU', 'Luxembourg', 'LUX', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MC', 'Macau', 'MAC', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MA', 'Madagascar', 'MDG', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MI', 'Malawi', 'MWI', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MY', 'Malaysia', 'MYS', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MV', 'Maldives', 'MDV', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('ML', 'Mali', 'MLI', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MT', 'Malta', 'MLT', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('RM', 'Marshall Islands', 'MHL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MB', 'Martinique', 'MTQ', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MR', 'Mauritania', 'MRT', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MP', 'Mauritius', 'MUS', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MF', 'Mayotte', 'MYT', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MX', 'Mexico', 'MEX', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MQ', 'Midway Islands', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MD', 'Moldova', 'MDA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MN', 'Monaco', 'MCO', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MG', 'Mongolia', 'MNG', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MJ', 'Montenegro', 'MNE', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MH', 'Montserrat', 'MSR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MO', 'Morocco', 'MAR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MZ', 'Mozambique', 'MOZ', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('WA', 'Namibia', 'NAM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NR', 'Nauru', 'NRU', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BQ', 'Navassa Island', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NP', 'Nepal', 'NPL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NL', 'Netherlands', 'NLD', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NT', 'Netherlands Antilles', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NC', 'New Caledonia', 'NCL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NZ', 'New Zealand', 'NZL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NU', 'Nicaragua', 'NIC', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NG', 'Niger', 'NER', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NI', 'Nigeria', 'NGA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NE', 'Niue', 'NIU', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NF', 'Norfolk Island', 'NFK', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('KN', 'North Korea', 'PRK', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CQ', 'Northern Mariana Islands', 'MNP', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NO', 'Norway', 'NOR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MU', 'Oman', 'OMN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('PK', 'Pakistan', 'PAK', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('PS', 'Palau', 'PLW', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('PM', 'Panama', 'PAN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('PP', 'Papua New Guinea', 'PNG', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('PF', 'Paracel Islands', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('PA', 'Paraguay', 'PRY', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CH', 'People-s Republic of China', 'CHN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('PE', 'Peru', 'PER', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('RP', 'Philippines', 'PHL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('PC', 'Pitcairn Islands', 'PCN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('PL', 'Poland', 'POL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('PO', 'Portugal', 'PRT', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('RQ', 'Puerto Rico', 'PRI', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('QA', 'Qatar', 'QAT', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TW', 'Republic of China (Taiwan)', 'TWN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('EI', 'Republic of Ireland', 'IRL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('MK', 'Republic of Macedonia', 'MKD', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('UG', 'Republic of Uganda', 'UGA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CF', 'Republic of the Congo', 'COG', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('RE', 'Reunion', 'REU', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('RO', 'Romania', 'ROU', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('RS', 'Russia', 'RUS', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('RW', 'Rwanda', 'RWA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SH', 'Saint Helena', 'SHN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SC', 'Saint Kitts and Nevis', 'KNA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('ST', 'Saint Lucia', 'LCA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SB', 'Saint Pierre and Miquelon', 'SPM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('VC', 'Saint Vincent and the Grenadines', 'VCT', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('WS', 'Samoa', 'WSM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SM', 'San Marino', 'SMR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TP', 'Sao Tome and Principe', 'STP', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SA', 'Saudi Arabia', 'SAU', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SG', 'Senegal', 'SEN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('RB', 'Serbia', 'SRB', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SE', 'Seychelles', 'SYC', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SL', 'Sierra Leone', 'SLE', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SN', 'Singapore', 'SGP', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('LO', 'Slovakia', 'SVK', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SI', 'Slovenia', 'SVN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('BP', 'Solomon Islands', 'SLB', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SO', 'Somalia', 'SOM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SF', 'South Africa', 'ZAF', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SX', 'South Georgia and the South Sandwich Islands', 'SGS', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('KS', 'South Korea', 'KOR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('OD', 'South Sudan', 'SSD', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SP', 'Spain', 'ESP', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('PG', 'Spratly Islands', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('CE', 'Sri Lanka', 'LKA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SU', 'Sudan', 'SDN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NS', 'Suriname', 'SUR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SV', 'Svalbard', 'SJM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('WZ', 'Swaziland', 'SWZ', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SW', 'Sweden', 'SWE', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SZ', 'Switzerland', 'CHE', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('SY', 'Syria', 'SYR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TI', 'Tajikistan', 'TJK', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TZ', 'Tanzania', 'TZA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TH', 'Thailand', 'THA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('GA', 'The Gambia', 'GMB', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TT', 'Timor-Leste/EastTimor', 'TLS', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TO', 'Togo', 'TGO', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TL', 'Tokelau', 'TKL', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TN', 'Tonga', 'TON', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TD', 'Trinidad and Tobago', 'TTO', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TE', 'Tromelin Island', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TS', 'Tunisia', 'TUN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TU', 'Turkey', 'TUR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TX', 'Turkmenistan', 'TKM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TK', 'Turks and Caicos Islands', 'TCA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('TV', 'Tuvalu', 'TUV', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('VQ', 'U.S. Virgin Islands', 'VIR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('UP', 'Ukraine', 'UKR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('AE', 'United Arab Emirates', 'ARE', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('UK', 'United Kingdom', 'GBR', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('US', 'United States', 'USA', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('UY', 'Uruguay', 'URY', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('UZ', 'Uzbekistan', 'UZB', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('NH', 'Vanuatu', 'VUT', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('VT', 'Vatican City', 'VAT', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('VE', 'Venezuela', 'VEN', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('VM', 'Vietnam', 'VNM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('WQ', 'Wake Island', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('WF', 'Wallis and Futuna', 'WLF', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('WE', 'West Bank', '', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('WI', 'Western Sahara', 'ESH', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('YM', 'Yemen', 'YEM', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('ZA', 'Zambia', 'ZMB', 0);
INSERT INTO COUNTRY(COUNTRY_CODE, COUNTRY_NAME, TRIGRAPH, SECLAB) VALUES ('ZI', 'Zimbabwe', 'ZWE', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('AA', 'Anti Aircraft Fire Control', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('AB', 'Airborne Search and Bomb', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('AI', 'Airborne Intercept', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('AL', 'Altimeter', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('AM', 'Airborne Recon Mapping', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('AT', 'Air Traffic Control', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('AV', 'Avian Control', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('BN', 'Beacon Transponder', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('BS', 'Battlefield Surveillance', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('CA', 'Controlled Approach G S', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('CI ', 'Controlled Intercept A G S', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('CS', 'Coastal Surveillance', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('DC', 'Decoy Mimic', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('DT', 'Data Transmission', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('ES', 'Earth Surveillance', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('EW', 'Early Warning', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('FC', 'Fire Control', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('GB', 'Gun Laying Beacon', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('GI', 'Ground I', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('GM', 'Ground Mapping', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('GT', 'Ground Traffic Control', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('HF', 'Height Finder', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('HS', 'Harbor Surveillance', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('IF', 'IFF Interrogator', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('IL', 'Instrument Landing System', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('IS', 'Ionospheric Sounding', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('IT', 'IFF Transponder', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('JB', 'Barrage Jamming', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('JC', 'Click Jamming', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('JD', 'Deceptive Jamming', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('JF', 'Frequency Swept Jamming', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('JG', 'Jamming  General', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('JN', 'Noise Jamming', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('JP', 'Pulsed Jamming', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('JR', 'Repeater Jamming', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('JS', 'Spot Noise Jamming', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('JT', 'Transponder Jamming', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('MA', 'Missile Acquisition', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('MC', 'Missile Control', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('MD', 'Missile Downlink', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('ME', 'Meteorological', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('MF', 'Multi Function', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('MG', 'Missile Guidance', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('MH', 'Missile Homing', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('MT', 'Missile Tracking', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('NA', 'Navigation General', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('ND', 'Navigation DME', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('NT', 'Navigation Terrain Following', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('NW', 'Navigation Weather Avoidance', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('PF', 'Proximity Fuse', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('RI', 'Instrumentation', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('RO', 'Range Only', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('RS', 'Radiosonde', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('SB', 'Sonobuoy', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('SP', 'Space', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('SS', 'Surface Search', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('ST', 'Shell Tracking', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('TA', 'Target Acquisition', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('TI', 'Target Illumination', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('TT', 'Target Tracking', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('TV', 'Television', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('UN', 'Unknown', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('VR', 'Video Remoting', '', '', 0);
INSERT INTO FUNCTION_CODES(ABBREVIATION, NAME, DESCRIPTION, SYSTEM, SECLAB) VALUES ('XP', 'Experimental or Trainer', '', '', 0);