/* --------------------------------------------------------------------------------------- 

	2022-11-24 
	
	최근 자료 남기고 오래된 데이터 삭제 - 임베디드에서 용량을 제한하기 위해서 사용

   --------------------------------------------------------------------------------------- */

DELETE FROM RAWDATA WHERE ROWID IN ( SELECT ROWID FROM RAWDATA ORDER BY ROWID DESC LIMIT -1 OFFSET 500 )      
DELETE FROM LOBDATA WHERE ROWID IN ( SELECT ROWID FROM LOBDATA ORDER BY ROWID DESC LIMIT -1 OFFSET 500 )   
DELETE FROM ABTDATA WHERE ROWID IN ( SELECT ROWID FROM ABTDATA ORDER BY ROWID DESC LIMIT -1 OFFSET 500 )
DELETE FROM AETDATA WHERE ROWID IN ( SELECT ROWID FROM AETDATA ORDER BY ROWID DESC LIMIT -1 OFFSET 500 )
DELETE FROM ELEMENT WHERE ROWID IN ( SELECT ROWID FROM ELEMENT ORDER BY ROWID DESC LIMIT -1 OFFSET 500 )
DELETE FROM POSITION WHERE ROWID IN ( SELECT ROWID FROM POSITION ORDER BY ROWID DESC LIMIT -1 OFFSET 500 )
   
   