/* m2wrsnmp.h - header for m2Lib Migration */

/*
 * Copyright (c) 2016 Wind River Systems, Inc.
 *
 * The right to copy, distribute, modify, or otherwise make use
 * of this software may be licensed only pursuant to the terms
 * of an applicable Wind River license agreement.
 */


/*
modification history
--------------------
17may16,chm  Port TSR defect fix forward from vxworks6.9 into vx7. (F6988)
*/

#ifndef _M2WRSNMP_H_
#define _M2WRSNMP_H_

#define LEAF_ifNumber	1
#define LEAF_ifIndex	1
#define MIN_ifIndex	1L
#define MAX_ifIndex	2147483647L
#define LEAF_ifDescr	2
#define MINSIZE_ifDescr	0L
#define MAXSIZE_ifDescr	255L
#define LEAF_ifType	3
#define VAL_ifType_other	1L
#define VAL_ifType_regular1822	2L
#define VAL_ifType_hdh1822	3L
#define VAL_ifType_ddnX25	4L
#define VAL_ifType_rfc877x25	5L
#define VAL_ifType_ethernetCsmacd	6L
#define VAL_ifType_iso88023Csmacd	7L
#define VAL_ifType_iso88024TokenBus	8L
#define VAL_ifType_iso88025TokenRing	9L
#define VAL_ifType_iso88026Man	10L
#define VAL_ifType_starLan	11L
#define VAL_ifType_proteon10Mbit	12L
#define VAL_ifType_proteon80Mbit	13L
#define VAL_ifType_hyperchannel	14L
#define VAL_ifType_fddi	15L
#define VAL_ifType_lapb	16L
#define VAL_ifType_sdlc	17L
#define VAL_ifType_ds1	18L
#define VAL_ifType_e1	19L
#define VAL_ifType_basicISDN	20L
#define VAL_ifType_primaryISDN	21L
#define VAL_ifType_propPointToPointSerial	22L
#define VAL_ifType_ppp	23L
#define VAL_ifType_softwareLoopback	24L
#define VAL_ifType_eon	25L
#define VAL_ifType_ethernet3Mbit	26L
#define VAL_ifType_nsip	27L
#define VAL_ifType_slip	28L
#define VAL_ifType_ultra	29L
#define VAL_ifType_ds3	30L
#define VAL_ifType_sip	31L
#define VAL_ifType_frameRelay	32L
#define VAL_ifType_rs232	33L
#define VAL_ifType_para	34L
#define VAL_ifType_arcnet	35L
#define VAL_ifType_arcnetPlus	36L
#define VAL_ifType_atm	37L
#define VAL_ifType_miox25	38L
#define VAL_ifType_sonet	39L
#define VAL_ifType_x25ple	40L
#define VAL_ifType_iso88022llc	41L
#define VAL_ifType_localTalk	42L
#define VAL_ifType_smdsDxi	43L
#define VAL_ifType_frameRelayService	44L
#define VAL_ifType_v35	45L
#define VAL_ifType_hssi	46L
#define VAL_ifType_hippi	47L
#define VAL_ifType_modem	48L
#define VAL_ifType_aal5	49L
#define VAL_ifType_sonetPath	50L
#define VAL_ifType_sonetVT	51L
#define VAL_ifType_smdsIcip	52L
#define VAL_ifType_propVirtual	53L
#define VAL_ifType_propMultiplexor	54L
#define LEAF_ifMtu	4
#define LEAF_ifSpeed	5
#define LEAF_ifPhysAddress	6
#define LEAF_ifAdminStatus	7
#define VAL_ifAdminStatus_up	1L
#define VAL_ifAdminStatus_down	2L
#define VAL_ifAdminStatus_testing	3L
#define LEAF_ifOperStatus	8
#define VAL_ifOperStatus_up	1L
#define VAL_ifOperStatus_down	2L
#define VAL_ifOperStatus_testing	3L
#define VAL_ifOperStatus_unknown	4L
#define VAL_ifOperStatus_dormant	5L
#define VAL_ifOperStatus_notPresent	6L
#define VAL_ifOperStatus_lowerLayerDown	7L
#define LEAF_ifLastChange	9
#define LEAF_ifInOctets	10
#define LEAF_ifInUcastPkts	11
#define LEAF_ifInDiscards	13
#define LEAF_ifInErrors	14
#define LEAF_ifInUnknownProtos	15
#define LEAF_ifOutOctets	16
#define LEAF_ifOutUcastPkts	17
#define LEAF_ifOutDiscards	19
#define LEAF_ifOutErrors	20
#define LEAF_ipForwarding	1
#define VAL_ipForwarding_forwarding	1L
#define VAL_ipForwarding_notForwarding	2L
#define LEAF_ipDefaultTTL	2
#define MIN_ipDefaultTTL	1L
#define MAX_ipDefaultTTL	255L
#define LEAF_ipReasmTimeout	13
#define LEAF_inetCidrRouteNumber	6
#define LEAF_inetCidrRouteDestType	1
#define VAL_inetCidrRouteDestType_unknown	0L
#define VAL_inetCidrRouteDestType_ipv4	1L
#define VAL_inetCidrRouteDestType_ipv6	2L
#define VAL_inetCidrRouteDestType_ipv4z	3L
#define VAL_inetCidrRouteDestType_ipv6z	4L
#define VAL_inetCidrRouteDestType_dns	16L
#define LEAF_inetCidrRouteDest	2
#define MINSIZE_inetCidrRouteDest	0L
#define MAXSIZE_inetCidrRouteDest	255L
#define LEAF_inetCidrRoutePfxLen	3
#define MIN_inetCidrRoutePfxLen	0L
#define MAX_inetCidrRoutePfxLen	2040L
#define LEAF_inetCidrRoutePolicy	4
#define LEAF_inetCidrRouteNextHopType	5
#define VAL_inetCidrRouteNextHopType_unknown	0L
#define VAL_inetCidrRouteNextHopType_ipv4	1L
#define VAL_inetCidrRouteNextHopType_ipv6	2L
#define VAL_inetCidrRouteNextHopType_ipv4z	3L
#define VAL_inetCidrRouteNextHopType_ipv6z	4L
#define VAL_inetCidrRouteNextHopType_dns	16L
#define LEAF_inetCidrRouteNextHop	6
#define MINSIZE_inetCidrRouteNextHop	0L
#define MAXSIZE_inetCidrRouteNextHop	255L
#define LEAF_inetCidrRouteIfIndex	7
#define MIN_inetCidrRouteIfIndex	0L
#define MAX_inetCidrRouteIfIndex	2147483647L
#define LEAF_inetCidrRouteType	8
#define VAL_inetCidrRouteType_other	1L
#define VAL_inetCidrRouteType_reject	2L
#define VAL_inetCidrRouteType_local	3L
#define VAL_inetCidrRouteType_remote	4L
#define VAL_inetCidrRouteType_blackhole	5L
#define LEAF_inetCidrRouteProto	9
#define VAL_inetCidrRouteProto_other	1L
#define VAL_inetCidrRouteProto_local	2L
#define VAL_inetCidrRouteProto_netmgmt	3L
#define VAL_inetCidrRouteProto_icmp	4L
#define VAL_inetCidrRouteProto_egp	5L
#define VAL_inetCidrRouteProto_ggp	6L
#define VAL_inetCidrRouteProto_hello	7L
#define VAL_inetCidrRouteProto_rip	8L
#define VAL_inetCidrRouteProto_isIs	9L
#define VAL_inetCidrRouteProto_esIs	10L
#define VAL_inetCidrRouteProto_ciscoIgrp	11L
#define VAL_inetCidrRouteProto_bbnSpfIgp	12L
#define VAL_inetCidrRouteProto_ospf	13L
#define VAL_inetCidrRouteProto_bgp	14L
#define VAL_inetCidrRouteProto_idpr	15L
#define VAL_inetCidrRouteProto_ciscoEigrp	16L
#define VAL_inetCidrRouteProto_dvmrp	17L
#define LEAF_inetCidrRouteAge	10
#define LEAF_inetCidrRouteNextHopAS	11
#define LEAF_inetCidrRouteMetric1	12
#define LEAF_inetCidrRouteMetric2	13
#define LEAF_inetCidrRouteMetric3	14
#define LEAF_inetCidrRouteMetric4	15
#define LEAF_inetCidrRouteMetric5	16
#define LEAF_inetCidrRouteStatus	17
#define VAL_inetCidrRouteStatus_active	1L
#define VAL_inetCidrRouteStatus_notInService	2L
#define VAL_inetCidrRouteStatus_notReady	3L
#define VAL_inetCidrRouteStatus_createAndGo	4L
#define VAL_inetCidrRouteStatus_createAndWait	5L
#define VAL_inetCidrRouteStatus_destroy	6L
#define LEAF_inetCidrRouteDiscards	8
#define LEAF_ipv6IpForwarding	25
#define VAL_ipv6IpForwarding_forwarding	1L
#define VAL_ipv6IpForwarding_notForwarding	2L
#define LEAF_ipv6IpDefaultHopLimit	26
#define MIN_ipv6IpDefaultHopLimit	0L
#define MAX_ipv6IpDefaultHopLimit	255L
#define LEAF_ipv4InterfaceTableLastChange	27
#define LEAF_ipv4InterfaceIfIndex	1
#define MIN_ipv4InterfaceIfIndex	1L
#define MAX_ipv4InterfaceIfIndex	2147483647L
#define LEAF_ipv4InterfaceReasmMaxSize	2
#define MIN_ipv4InterfaceReasmMaxSize	0L
#define MAX_ipv4InterfaceReasmMaxSize	65535L
#define LEAF_ipv4InterfaceEnableStatus	3
#define VAL_ipv4InterfaceEnableStatus_up	1L
#define VAL_ipv4InterfaceEnableStatus_down	2L
#define LEAF_ipv4InterfaceRetransmitTime	4
#define LEAF_ipv6InterfaceTableLastChange	29
#define LEAF_ipv6InterfaceIfIndex	1
#define MIN_ipv6InterfaceIfIndex	1L
#define MAX_ipv6InterfaceIfIndex	2147483647L
#define LEAF_ipv6InterfaceReasmMaxSize	2
#define MIN_ipv6InterfaceReasmMaxSize	1500L
#define MAX_ipv6InterfaceReasmMaxSize	65535L
#define LEAF_ipv6InterfaceIdentifier	3
#define MINSIZE_ipv6InterfaceIdentifier	0L
#define MAXSIZE_ipv6InterfaceIdentifier	8L
#define LEAF_ipv6InterfaceEnableStatus	5
#define VAL_ipv6InterfaceEnableStatus_up	1L
#define VAL_ipv6InterfaceEnableStatus_down	2L
#define LEAF_ipv6InterfaceReachableTime	6
#define LEAF_ipv6InterfaceRetransmitTime	7
#define LEAF_ipv6InterfaceForwarding	8
#define VAL_ipv6InterfaceForwarding_forwarding	1L
#define VAL_ipv6InterfaceForwarding_notForwarding	2L
#define LEAF_ipSystemStatsIPVersion	1
#define VAL_ipSystemStatsIPVersion_unknown	0L
#define VAL_ipSystemStatsIPVersion_ipv4	1L
#define VAL_ipSystemStatsIPVersion_ipv6	2L
#define LEAF_ipSystemStatsInReceives	3
#define LEAF_ipSystemStatsHCInReceives	4
#define LEAF_ipSystemStatsInOctets	5
#define LEAF_ipSystemStatsHCInOctets	6
#define LEAF_ipSystemStatsInHdrErrors	7
#define LEAF_ipSystemStatsInNoRoutes	8
#define LEAF_ipSystemStatsInAddrErrors	9
#define LEAF_ipSystemStatsInUnknownProtos	10
#define LEAF_ipSystemStatsInTruncatedPkts	11
#define LEAF_ipSystemStatsInForwDatagrams	12
#define LEAF_ipSystemStatsHCInForwDatagrams	13
#define LEAF_ipSystemStatsReasmReqds	14
#define LEAF_ipSystemStatsReasmOKs	15
#define LEAF_ipSystemStatsReasmFails	16
#define LEAF_ipSystemStatsInDiscards	17
#define LEAF_ipSystemStatsInDelivers	18
#define LEAF_ipSystemStatsHCInDelivers	19
#define LEAF_ipSystemStatsOutRequests	20
#define LEAF_ipSystemStatsHCOutRequests	21
#define LEAF_ipSystemStatsOutNoRoutes	22
#define LEAF_ipSystemStatsOutForwDatagrams	23
#define LEAF_ipSystemStatsHCOutForwDatagrams	24
#define LEAF_ipSystemStatsOutDiscards	25
#define LEAF_ipSystemStatsOutFragReqds	26
#define LEAF_ipSystemStatsOutFragOKs	27
#define LEAF_ipSystemStatsOutFragFails	28
#define LEAF_ipSystemStatsOutFragCreates	29
#define LEAF_ipSystemStatsOutTransmits	30
#define LEAF_ipSystemStatsHCOutTransmits	31
#define LEAF_ipSystemStatsOutOctets	32
#define LEAF_ipSystemStatsHCOutOctets	33
#define LEAF_ipSystemStatsInMcastPkts	34
#define LEAF_ipSystemStatsHCInMcastPkts	35
#define LEAF_ipSystemStatsInMcastOctets	36
#define LEAF_ipSystemStatsHCInMcastOctets	37
#define LEAF_ipSystemStatsOutMcastPkts	38
#define LEAF_ipSystemStatsHCOutMcastPkts	39
#define LEAF_ipSystemStatsOutMcastOctets	40
#define LEAF_ipSystemStatsHCOutMcastOctets	41
#define LEAF_ipSystemStatsInBcastPkts	42
#define LEAF_ipSystemStatsHCInBcastPkts	43
#define LEAF_ipSystemStatsOutBcastPkts	44
#define LEAF_ipSystemStatsHCOutBcastPkts	45
#define LEAF_ipSystemStatsDiscontinuityTime	46
#define LEAF_ipSystemStatsRefreshRate	47
#define LEAF_ipIfStatsTableLastChange	2
#define LEAF_ipIfStatsIPVersion	1
#define VAL_ipIfStatsIPVersion_unknown	0L
#define VAL_ipIfStatsIPVersion_ipv4	1L
#define VAL_ipIfStatsIPVersion_ipv6	2L
#define LEAF_ipIfStatsIfIndex	2
#define MIN_ipIfStatsIfIndex	1L
#define MAX_ipIfStatsIfIndex	2147483647L
#define LEAF_ipIfStatsInReceives	3
#define LEAF_ipIfStatsHCInReceives	4
#define LEAF_ipIfStatsInOctets	5
#define LEAF_ipIfStatsHCInOctets	6
#define LEAF_ipIfStatsInHdrErrors	7
#define LEAF_ipIfStatsInNoRoutes	8
#define LEAF_ipIfStatsInAddrErrors	9
#define LEAF_ipIfStatsInUnknownProtos	10
#define LEAF_ipIfStatsInTruncatedPkts	11
#define LEAF_ipIfStatsInForwDatagrams	12
#define LEAF_ipIfStatsHCInForwDatagrams	13
#define LEAF_ipIfStatsReasmReqds	14
#define LEAF_ipIfStatsReasmOKs	15
#define LEAF_ipIfStatsReasmFails	16
#define LEAF_ipIfStatsInDiscards	17
#define LEAF_ipIfStatsInDelivers	18
#define LEAF_ipIfStatsHCInDelivers	19
#define LEAF_ipIfStatsOutRequests	20
#define LEAF_ipIfStatsHCOutRequests	21
#define LEAF_ipIfStatsOutForwDatagrams	23
#define LEAF_ipIfStatsHCOutForwDatagrams	24
#define LEAF_ipIfStatsOutDiscards	25
#define LEAF_ipIfStatsOutFragReqds	26
#define LEAF_ipIfStatsOutFragOKs	27
#define LEAF_ipIfStatsOutFragFails	28
#define LEAF_ipIfStatsOutFragCreates	29
#define LEAF_ipIfStatsOutTransmits	30
#define LEAF_ipIfStatsHCOutTransmits	31
#define LEAF_ipIfStatsOutOctets	32
#define LEAF_ipIfStatsHCOutOctets	33
#define LEAF_ipIfStatsInMcastPkts	34
#define LEAF_ipIfStatsHCInMcastPkts	35
#define LEAF_ipIfStatsInMcastOctets	36
#define LEAF_ipIfStatsHCInMcastOctets	37
#define LEAF_ipIfStatsOutMcastPkts	38
#define LEAF_ipIfStatsHCOutMcastPkts	39
#define LEAF_ipIfStatsOutMcastOctets	40
#define LEAF_ipIfStatsHCOutMcastOctets	41
#define LEAF_ipIfStatsInBcastPkts	42
#define LEAF_ipIfStatsHCInBcastPkts	43
#define LEAF_ipIfStatsOutBcastPkts	44
#define LEAF_ipIfStatsHCOutBcastPkts	45
#define LEAF_ipIfStatsDiscontinuityTime	46
#define LEAF_ipIfStatsRefreshRate	47
#define LEAF_ipAddressPrefixIfIndex	1
#define MIN_ipAddressPrefixIfIndex	1L
#define MAX_ipAddressPrefixIfIndex	2147483647L
#define LEAF_ipAddressPrefixType	2
#define VAL_ipAddressPrefixType_unknown	0L
#define VAL_ipAddressPrefixType_ipv4	1L
#define VAL_ipAddressPrefixType_ipv6	2L
#define VAL_ipAddressPrefixType_ipv4z	3L
#define VAL_ipAddressPrefixType_ipv6z	4L
#define VAL_ipAddressPrefixType_dns	16L
#define LEAF_ipAddressPrefixPrefix	3
#define MINSIZE_ipAddressPrefixPrefix	0L
#define MAXSIZE_ipAddressPrefixPrefix	255L
#define LEAF_ipAddressPrefixLength	4
#define MIN_ipAddressPrefixLength	0L
#define MAX_ipAddressPrefixLength	2040L
#define LEAF_ipAddressPrefixOrigin	5
#define VAL_ipAddressPrefixOrigin_other	1L
#define VAL_ipAddressPrefixOrigin_manual	2L
#define VAL_ipAddressPrefixOrigin_wellknown	3L
#define VAL_ipAddressPrefixOrigin_dhcp	4L
#define VAL_ipAddressPrefixOrigin_routeradv	5L
#define LEAF_ipAddressPrefixOnLinkFlag	6
#define VAL_ipAddressPrefixOnLinkFlag_true	1L
#define VAL_ipAddressPrefixOnLinkFlag_false	2L
#define LEAF_ipAddressPrefixAutonomousFlag	7
#define VAL_ipAddressPrefixAutonomousFlag_true	1L
#define VAL_ipAddressPrefixAutonomousFlag_false	2L
#define LEAF_ipAddressPrefixAdvPreferredLifetime	8
#define LEAF_ipAddressPrefixAdvValidLifetime	9
#define LEAF_ipAddressSpinLock	33
#define MIN_ipAddressSpinLock	0L
#define MAX_ipAddressSpinLock	2147483647L
#define LEAF_ipAddressAddrType	1
#define VAL_ipAddressAddrType_unknown	0L
#define VAL_ipAddressAddrType_ipv4	1L
#define VAL_ipAddressAddrType_ipv6	2L
#define VAL_ipAddressAddrType_ipv4z	3L
#define VAL_ipAddressAddrType_ipv6z	4L
#define VAL_ipAddressAddrType_dns	16L
#define LEAF_ipAddressAddr	2
#define MINSIZE_ipAddressAddr	0L
#define MAXSIZE_ipAddressAddr	255L
#define LEAF_ipAddressIfIndex	3
#define MIN_ipAddressIfIndex	1L
#define MAX_ipAddressIfIndex	2147483647L
#define LEAF_ipAddressType	4
#define VAL_ipAddressType_unicast	1L
#define VAL_ipAddressType_anycast	2L
#define VAL_ipAddressType_broadcast	3L
#define LEAF_ipAddressPrefix	5
#define LEAF_ipAddressOrigin	6
#define VAL_ipAddressOrigin_other	1L
#define VAL_ipAddressOrigin_manual	2L
#define VAL_ipAddressOrigin_dhcp	4L
#define VAL_ipAddressOrigin_linklayer	5L
#define VAL_ipAddressOrigin_random	6L
#define LEAF_ipAddressStatus	7
#define VAL_ipAddressStatus_preferred	1L
#define VAL_ipAddressStatus_deprecated	2L
#define VAL_ipAddressStatus_invalid	3L
#define VAL_ipAddressStatus_inaccessible	4L
#define VAL_ipAddressStatus_unknown	5L
#define VAL_ipAddressStatus_tentative	6L
#define VAL_ipAddressStatus_duplicate	7L
#define VAL_ipAddressStatus_optimistic	8L
#define LEAF_ipAddressCreated	8
#define LEAF_ipAddressLastChanged	9
#define LEAF_ipAddressRowStatus	10
#define VAL_ipAddressRowStatus_active	1L
#define VAL_ipAddressRowStatus_notInService	2L
#define VAL_ipAddressRowStatus_notReady	3L
#define VAL_ipAddressRowStatus_createAndGo	4L
#define VAL_ipAddressRowStatus_createAndWait	5L
#define VAL_ipAddressRowStatus_destroy	6L
#define LEAF_ipAddressStorageType	11
#define VAL_ipAddressStorageType_other	1L
#define VAL_ipAddressStorageType_volatile	2L
#define VAL_ipAddressStorageType_nonVolatile	3L
#define VAL_ipAddressStorageType_permanent	4L
#define VAL_ipAddressStorageType_readOnly	5L
#define LEAF_ipNetToPhysicalIfIndex	1
#define MIN_ipNetToPhysicalIfIndex	1L
#define MAX_ipNetToPhysicalIfIndex	2147483647L
#define LEAF_ipNetToPhysicalNetAddressType	2
#define VAL_ipNetToPhysicalNetAddressType_unknown	0L
#define VAL_ipNetToPhysicalNetAddressType_ipv4	1L
#define VAL_ipNetToPhysicalNetAddressType_ipv6	2L
#define VAL_ipNetToPhysicalNetAddressType_ipv4z	3L
#define VAL_ipNetToPhysicalNetAddressType_ipv6z	4L
#define VAL_ipNetToPhysicalNetAddressType_dns	16L
#define LEAF_ipNetToPhysicalNetAddress	3
#define MINSIZE_ipNetToPhysicalNetAddress	0L
#define MAXSIZE_ipNetToPhysicalNetAddress	255L
#define LEAF_ipNetToPhysicalPhysAddress	4
#define MINSIZE_ipNetToPhysicalPhysAddress	0L
#define MAXSIZE_ipNetToPhysicalPhysAddress	65535L
#define LEAF_ipNetToPhysicalLastUpdated	5
#define LEAF_ipNetToPhysicalType	6
#define VAL_ipNetToPhysicalType_other	1L
#define VAL_ipNetToPhysicalType_invalid	2L
#define VAL_ipNetToPhysicalType_dynamic	3L
#define VAL_ipNetToPhysicalType_static	4L
#define VAL_ipNetToPhysicalType_local	5L
#define LEAF_ipNetToPhysicalState	7
#define VAL_ipNetToPhysicalState_reachable	1L
#define VAL_ipNetToPhysicalState_stale	2L
#define VAL_ipNetToPhysicalState_delay	3L
#define VAL_ipNetToPhysicalState_probe	4L
#define VAL_ipNetToPhysicalState_invalid	5L
#define VAL_ipNetToPhysicalState_unknown	6L
#define VAL_ipNetToPhysicalState_incomplete	7L
#define LEAF_ipNetToPhysicalRowStatus	8
#define VAL_ipNetToPhysicalRowStatus_active	1L
#define VAL_ipNetToPhysicalRowStatus_notInService	2L
#define VAL_ipNetToPhysicalRowStatus_notReady	3L
#define VAL_ipNetToPhysicalRowStatus_createAndGo	4L
#define VAL_ipNetToPhysicalRowStatus_createAndWait	5L
#define VAL_ipNetToPhysicalRowStatus_destroy	6L
#define LEAF_ipv6ScopeZoneIndexIfIndex	1
#define MIN_ipv6ScopeZoneIndexIfIndex	1L
#define MAX_ipv6ScopeZoneIndexIfIndex	2147483647L
#define LEAF_ipv6ScopeZoneIndexLinkLocal	2
#define LEAF_ipv6ScopeZoneIndex3	3
#define LEAF_ipv6ScopeZoneIndexAdminLocal	4
#define LEAF_ipv6ScopeZoneIndexSiteLocal	5
#define LEAF_ipv6ScopeZoneIndex6	6
#define LEAF_ipv6ScopeZoneIndex7	7
#define LEAF_ipv6ScopeZoneIndexOrganizationLocal	8
#define LEAF_ipv6ScopeZoneIndex9	9
#define LEAF_ipv6ScopeZoneIndexA	10
#define LEAF_ipv6ScopeZoneIndexB	11
#define LEAF_ipv6ScopeZoneIndexC	12
#define LEAF_ipv6ScopeZoneIndexD	13
#define LEAF_ipDefaultRouterAddressType	1
#define VAL_ipDefaultRouterAddressType_unknown	0L
#define VAL_ipDefaultRouterAddressType_ipv4	1L
#define VAL_ipDefaultRouterAddressType_ipv6	2L
#define VAL_ipDefaultRouterAddressType_ipv4z	3L
#define VAL_ipDefaultRouterAddressType_ipv6z	4L
#define VAL_ipDefaultRouterAddressType_dns	16L
#define LEAF_ipDefaultRouterAddress	2
#define MINSIZE_ipDefaultRouterAddress	0L
#define MAXSIZE_ipDefaultRouterAddress	255L
#define LEAF_ipDefaultRouterIfIndex	3
#define MIN_ipDefaultRouterIfIndex	1L
#define MAX_ipDefaultRouterIfIndex	2147483647L
#define LEAF_ipDefaultRouterLifetime	4
#define MIN_ipDefaultRouterLifetime	0L
#define MAX_ipDefaultRouterLifetime	65535L
#define LEAF_ipDefaultRouterPreference	5
#define VAL_ipDefaultRouterPreference_reserved	-2L
#define VAL_ipDefaultRouterPreference_low	-1L
#define VAL_ipDefaultRouterPreference_medium	0L
#define VAL_ipDefaultRouterPreference_high	1L
#define LEAF_ipv6RouterAdvertSpinLock	38
#define MIN_ipv6RouterAdvertSpinLock	0L
#define MAX_ipv6RouterAdvertSpinLock	2147483647L
#define LEAF_ipv6RouterAdvertIfIndex	1
#define MIN_ipv6RouterAdvertIfIndex	1L
#define MAX_ipv6RouterAdvertIfIndex	2147483647L
#define LEAF_ipv6RouterAdvertSendAdverts	2
#define VAL_ipv6RouterAdvertSendAdverts_true	1L
#define VAL_ipv6RouterAdvertSendAdverts_false	2L
#define LEAF_ipv6RouterAdvertMaxInterval	3
#define MIN_ipv6RouterAdvertMaxInterval	4L
#define MAX_ipv6RouterAdvertMaxInterval	1800L
#define LEAF_ipv6RouterAdvertMinInterval	4
#define MIN_ipv6RouterAdvertMinInterval	3L
#define MAX_ipv6RouterAdvertMinInterval	1350L
#define LEAF_ipv6RouterAdvertManagedFlag	5
#define VAL_ipv6RouterAdvertManagedFlag_true	1L
#define VAL_ipv6RouterAdvertManagedFlag_false	2L
#define LEAF_ipv6RouterAdvertOtherConfigFlag	6
#define VAL_ipv6RouterAdvertOtherConfigFlag_true	1L
#define VAL_ipv6RouterAdvertOtherConfigFlag_false	2L
#define LEAF_ipv6RouterAdvertLinkMTU	7
#define LEAF_ipv6RouterAdvertReachableTime	8
#define MIN_ipv6RouterAdvertReachableTime	0L
#define MAX_ipv6RouterAdvertReachableTime	3600000L
#define LEAF_ipv6RouterAdvertRetransmitTime	9
#define LEAF_ipv6RouterAdvertCurHopLimit	10
#define MIN_ipv6RouterAdvertCurHopLimit	0L
#define MAX_ipv6RouterAdvertCurHopLimit	255L
#define LEAF_ipv6RouterAdvertDefaultLifetime	11
#define MIN_ipv6RouterAdvertDefaultLifetime_1	0L
#define MAX_ipv6RouterAdvertDefaultLifetime_1	0L
#define MIN_ipv6RouterAdvertDefaultLifetime_2	4L
#define MAX_ipv6RouterAdvertDefaultLifetime_2	9000L
#define LEAF_ipv6RouterAdvertRowStatus	12
#define VAL_ipv6RouterAdvertRowStatus_active	1L
#define VAL_ipv6RouterAdvertRowStatus_notInService	2L
#define VAL_ipv6RouterAdvertRowStatus_notReady	3L
#define VAL_ipv6RouterAdvertRowStatus_createAndGo	4L
#define VAL_ipv6RouterAdvertRowStatus_createAndWait	5L
#define VAL_ipv6RouterAdvertRowStatus_destroy	6L
#define LEAF_icmpStatsIPVersion	1
#define VAL_icmpStatsIPVersion_unknown	0L
#define VAL_icmpStatsIPVersion_ipv4	1L
#define VAL_icmpStatsIPVersion_ipv6	2L
#define LEAF_icmpStatsInMsgs	2
#define LEAF_icmpStatsInErrors	3
#define LEAF_icmpStatsOutMsgs	4
#define LEAF_icmpStatsOutErrors	5
#define LEAF_icmpMsgStatsIPVersion	1
#define VAL_icmpMsgStatsIPVersion_unknown	0L
#define VAL_icmpMsgStatsIPVersion_ipv4	1L
#define VAL_icmpMsgStatsIPVersion_ipv6	2L
#define LEAF_icmpMsgStatsType	2
#define MIN_icmpMsgStatsType	0L
#define MAX_icmpMsgStatsType	255L
#define LEAF_icmpMsgStatsInPkts	3
#define LEAF_icmpMsgStatsOutPkts	4
#define LEAF_tcpRtoAlgorithm	1
#define VAL_tcpRtoAlgorithm_other	1L
#define VAL_tcpRtoAlgorithm_constant	2L
#define VAL_tcpRtoAlgorithm_rsre	3L
#define VAL_tcpRtoAlgorithm_vanj	4L
#define VAL_tcpRtoAlgorithm_rfc2988	5L
#define LEAF_tcpRtoMin	2
#define MIN_tcpRtoMin	0L
#define MAX_tcpRtoMin	2147483647L
#define LEAF_tcpRtoMax	3
#define MIN_tcpRtoMax	0L
#define MAX_tcpRtoMax	2147483647L
#define LEAF_tcpMaxConn	4
#define MIN_tcpMaxConn	-1L
#define MAX_tcpMaxConn	2147483647L
#define LEAF_tcpActiveOpens	5
#define LEAF_tcpPassiveOpens	6
#define LEAF_tcpAttemptFails	7
#define LEAF_tcpEstabResets	8
#define LEAF_tcpCurrEstab	9
#define LEAF_tcpInSegs	10
#define LEAF_tcpOutSegs	11
#define LEAF_tcpRetransSegs	12
#define LEAF_tcpInErrs	14
#define LEAF_tcpOutRsts	15
#define LEAF_tcpConnectionLocalAddressType	1
#define VAL_tcpConnectionLocalAddressType_unknown	0L
#define VAL_tcpConnectionLocalAddressType_ipv4	1L
#define VAL_tcpConnectionLocalAddressType_ipv6	2L
#define VAL_tcpConnectionLocalAddressType_ipv4z	3L
#define VAL_tcpConnectionLocalAddressType_ipv6z	4L
#define VAL_tcpConnectionLocalAddressType_dns	16L
#define LEAF_tcpConnectionLocalAddress	2
#define MINSIZE_tcpConnectionLocalAddress	0L
#define MAXSIZE_tcpConnectionLocalAddress	255L
#define LEAF_tcpConnectionLocalPort	3
#define MIN_tcpConnectionLocalPort	0L
#define MAX_tcpConnectionLocalPort	65535L
#define LEAF_tcpConnectionRemAddressType	4
#define VAL_tcpConnectionRemAddressType_unknown	0L
#define VAL_tcpConnectionRemAddressType_ipv4	1L
#define VAL_tcpConnectionRemAddressType_ipv6	2L
#define VAL_tcpConnectionRemAddressType_ipv4z	3L
#define VAL_tcpConnectionRemAddressType_ipv6z	4L
#define VAL_tcpConnectionRemAddressType_dns	16L
#define LEAF_tcpConnectionRemAddress	5
#define MINSIZE_tcpConnectionRemAddress	0L
#define MAXSIZE_tcpConnectionRemAddress	255L
#define LEAF_tcpConnectionRemPort	6
#define MIN_tcpConnectionRemPort	0L
#define MAX_tcpConnectionRemPort	65535L
#define LEAF_tcpConnectionState	7
#define VAL_tcpConnectionState_closed	1L
#define VAL_tcpConnectionState_listen	2L
#define VAL_tcpConnectionState_synSent	3L
#define VAL_tcpConnectionState_synReceived	4L
#define VAL_tcpConnectionState_established	5L
#define VAL_tcpConnectionState_finWait1	6L
#define VAL_tcpConnectionState_finWait2	7L
#define VAL_tcpConnectionState_closeWait	8L
#define VAL_tcpConnectionState_lastAck	9L
#define VAL_tcpConnectionState_closing	10L
#define VAL_tcpConnectionState_timeWait	11L
#define VAL_tcpConnectionState_deleteTCB	12L
#define LEAF_tcpConnectionProcess	8
#define LEAF_tcpListenerLocalAddressType	1
#define VAL_tcpListenerLocalAddressType_unknown	0L
#define VAL_tcpListenerLocalAddressType_ipv4	1L
#define VAL_tcpListenerLocalAddressType_ipv6	2L
#define VAL_tcpListenerLocalAddressType_ipv4z	3L
#define VAL_tcpListenerLocalAddressType_ipv6z	4L
#define VAL_tcpListenerLocalAddressType_dns	16L
#define LEAF_tcpListenerLocalAddress	2
#define MINSIZE_tcpListenerLocalAddress	0L
#define MAXSIZE_tcpListenerLocalAddress	255L
#define LEAF_tcpListenerLocalPort	3
#define MIN_tcpListenerLocalPort	0L
#define MAX_tcpListenerLocalPort	65535L
#define LEAF_tcpListenerProcess	4
#define LEAF_udpInDatagrams	1
#define LEAF_udpNoPorts	2
#define LEAF_udpInErrors	3
#define LEAF_udpOutDatagrams	4
#define LEAF_udpEndpointLocalAddressType	1
#define VAL_udpEndpointLocalAddressType_unknown	0L
#define VAL_udpEndpointLocalAddressType_ipv4	1L
#define VAL_udpEndpointLocalAddressType_ipv6	2L
#define VAL_udpEndpointLocalAddressType_ipv4z	3L
#define VAL_udpEndpointLocalAddressType_ipv6z	4L
#define VAL_udpEndpointLocalAddressType_dns	16L
#define LEAF_udpEndpointLocalAddress	2
#define MINSIZE_udpEndpointLocalAddress	0L
#define MAXSIZE_udpEndpointLocalAddress	255L
#define LEAF_udpEndpointLocalPort	3
#define MIN_udpEndpointLocalPort	0L
#define MAX_udpEndpointLocalPort	65535L
#define LEAF_udpEndpointRemoteAddressType	4
#define VAL_udpEndpointRemoteAddressType_unknown	0L
#define VAL_udpEndpointRemoteAddressType_ipv4	1L
#define VAL_udpEndpointRemoteAddressType_ipv6	2L
#define VAL_udpEndpointRemoteAddressType_ipv4z	3L
#define VAL_udpEndpointRemoteAddressType_ipv6z	4L
#define VAL_udpEndpointRemoteAddressType_dns	16L
#define LEAF_udpEndpointRemoteAddress	5
#define MINSIZE_udpEndpointRemoteAddress	0L
#define MAXSIZE_udpEndpointRemoteAddress	255L
#define LEAF_udpEndpointRemotePort	6
#define MIN_udpEndpointRemotePort	0L
#define MAX_udpEndpointRemotePort	65535L
#define LEAF_udpEndpointInstance	7
#define MIN_udpEndpointInstance	1L
#define MAX_udpEndpointInstance	4294967295L
#define LEAF_udpEndpointProcess	8
#define LEAF_snmpInPkts	1
#define LEAF_snmpOutPkts	2
#define LEAF_snmpInBadVersions	3
#define LEAF_snmpInBadCommunityNames	4
#define LEAF_snmpInBadCommunityUses	5
#define LEAF_snmpInASNParseErrs	6
#define LEAF_snmpInTooBigs	8
#define LEAF_snmpInNoSuchNames	9
#define LEAF_snmpInBadValues	10
#define LEAF_snmpInReadOnlys	11
#define LEAF_snmpInGenErrs	12
#define LEAF_snmpInTotalReqVars	13
#define LEAF_snmpInTotalSetVars	14
#define LEAF_snmpInGetRequests	15
#define LEAF_snmpInGetNexts	16
#define LEAF_snmpInSetRequests	17
#define LEAF_snmpInGetResponses	18
#define LEAF_snmpInTraps	19
#define LEAF_snmpOutTooBigs	20
#define LEAF_snmpOutNoSuchNames	21
#define LEAF_snmpOutBadValues	22
#define LEAF_snmpOutGenErrs	24
#define LEAF_snmpOutGetRequests	25
#define LEAF_snmpOutGetNexts	26
#define LEAF_snmpOutSetRequests	27
#define LEAF_snmpOutGetResponses	28
#define LEAF_snmpOutTraps	29
#define LEAF_snmpEnableAuthenTraps	30
#define VAL_snmpEnableAuthenTraps_enabled	1L
#define VAL_snmpEnableAuthenTraps_disabled	2L
#define LEAF_snmpSilentDrops	31
#define LEAF_snmpProxyDrops	32
#define LEAF_ifName	1
#define MINSIZE_ifName	0L
#define MAXSIZE_ifName	255L
#define LEAF_ifInMulticastPkts	2
#define LEAF_ifInBroadcastPkts	3
#define LEAF_ifOutMulticastPkts	4
#define LEAF_ifOutBroadcastPkts	5
#define LEAF_ifLinkUpDownTrapEnable	14
#define VAL_ifLinkUpDownTrapEnable_enabled	1L
#define VAL_ifLinkUpDownTrapEnable_disabled	2L
#define LEAF_ifHighSpeed	15
#define LEAF_ifPromiscuousMode	16
#define VAL_ifPromiscuousMode_true	1L
#define VAL_ifPromiscuousMode_false	2L
#define LEAF_ifConnectorPresent	17
#define VAL_ifConnectorPresent_true	1L
#define VAL_ifConnectorPresent_false	2L
#define LEAF_ifAlias	18
#define MINSIZE_ifAlias	0L
#define MAXSIZE_ifAlias	64L
#define LEAF_ifCounterDiscontinuityTime	19
#define LEAF_ifTableLastChange	5
#define LEAF_snmpTrapOID	1
#define LEAF_snmpTrapEnterprise	3
#define LEAF_snmpSetSerialNo	1
#define MIN_snmpSetSerialNo	0L
#define MAX_snmpSetSerialNo	2147483647L


#endif
