
# this file is automatically generated by mk/krnl/rules.binlayer.mk
# build of binary layer PPC_PPCMATH
 
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	

	
__BUILD_FB_IDS += _top_PPC_PPCMATH_src

BUILD : _binlayer_build_PPC_PPCMATH_src_

_binlayer_build_PPC_PPCMATH_src_ :
	+ cd D:/vxWorks7/vxworks-7/pkgs/os/arch/ppc-1.3.1.5/ppc_math_bin_PPCE6500_diab_smp/src && D:/vxWorks7/vxworks-7/host/binutils/x86-win32/bin/make _mk VSBL_NAME=PPC_PPCMATH CPU=PPCE6500 TOOL=diab TOOL_VERSION=diab_5_9_6_1 _CC_VERSION=diab_5_9_6_5 VSB_DIR=D:/VirtualBoxVMs/Git/ZPocketSonata1/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild __BIN_LAYER=D:/vxWorks7/vxworks-7/pkgs/os/arch/ppc-1.3.1.5/ppc_math_bin_PPCE6500_diab_smp _FB_ID=_top_PPC_PPCMATH_src BUILD_ALL_OBJS=TRUE 

	
	

	
	
	

	

	
__DIR_TARGETS += $(__DIR_TARGETS_PPC_PPCMATH)

__DIR_TARGETS_PPC_PPCMATH += 

