

__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_CPU = PPCE6500
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_VSB_DATAMODEL = ILP32
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_SMP = y
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_FP = hard
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_ENDIAN = big
 
__VSB_CHANGE_TO_CLEAN_WRS_CONFIG_CORE_KERNEL_1_2_5_1 = y

