
ifndef __HEADER_ACCESS_BDM_SATA_INCLUDED
__HEADER_ACCESS_BDM_SATA_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BDM_SATA = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/BDM_SATA),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BDM_SATA))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/BDM_SATA
endif
endif

endif

endif

