
ifndef __HEADER_ACCESS_SYSCALLS_CUSTOM_INCLUDED
__HEADER_ACCESS_SYSCALLS_CUSTOM_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_SYSCALLS_CUSTOM = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/SYSCALLS_CUSTOM),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), SYSCALLS_CUSTOM))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/SYSCALLS_CUSTOM
endif
endif

endif

endif

