
ifndef __HEADER_ACCESS_BDM_NFTL_INCLUDED
__HEADER_ACCESS_BDM_NFTL_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BDM_NFTL = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/BDM_NFTL),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BDM_NFTL))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/BDM_NFTL
endif
endif

endif

endif

