
ifndef __HEADER_ACCESS_LANG_LIB_TOOL_TOOLSRC_GNU_USER_INCLUDED
__HEADER_ACCESS_LANG_LIB_TOOL_TOOLSRC_GNU_USER_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_LANG_LIB_TOOL_TOOLSRC_GNU_USER = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/LANG_LIB_TOOL_TOOLSRC_GNU_USER),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), LANG_LIB_TOOL_TOOLSRC_GNU_USER))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/LANG_LIB_TOOL_TOOLSRC_GNU_USER
endif
endif

endif

endif

