
ifndef __HEADER_ACCESS_FSAPI_USR_INCLUDED
__HEADER_ACCESS_FSAPI_USR_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_FSAPI_USR = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FSAPI_USR),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), FSAPI_USR))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FSAPI_USR
endif
endif

endif

endif

