
ifndef __HEADER_ACCESS_LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL_INCLUDED
__HEADER_ACCESS_LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL
endif
endif

endif

endif

