
ifndef __HEADER_ACCESS_FS_DOSFS_INCLUDED
__HEADER_ACCESS_FS_DOSFS_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_FS_DOSFS = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FS_DOSFS),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), FS_DOSFS))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FS_DOSFS
endif
endif

endif

endif

