
ifndef __HEADER_ACCESS_PPC_DRV_INCLUDED
__HEADER_ACCESS_PPC_DRV_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_PPC_DRV = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/PPC_DRV),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), PPC_DRV))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/PPC_DRV
endif
endif

endif

endif

