
ifndef __HEADER_ACCESS_LIBDL_7X_INCLUDED
__HEADER_ACCESS_LIBDL_7X_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_LIBDL_7X = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/LIBDL_7X),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), LIBDL_7X))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/LIBDL_7X
endif
endif

endif

endif

