
ifndef __HEADER_ACCESS_LANG_LIB_TOOL_TOOLSRC_GNU_INCLUDED
__HEADER_ACCESS_LANG_LIB_TOOL_TOOLSRC_GNU_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_LANG_LIB_TOOL_TOOLSRC_GNU = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/LANG_LIB_TOOL_TOOLSRC_GNU),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), LANG_LIB_TOOL_TOOLSRC_GNU))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/LANG_LIB_TOOL_TOOLSRC_GNU
endif
endif

endif

endif

