
ifndef __HEADER_ACCESS_LANG_LIB_TOOL_TOOLSRC_COMMON_INCLUDED
__HEADER_ACCESS_LANG_LIB_TOOL_TOOLSRC_COMMON_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_LANG_LIB_TOOL_TOOLSRC_COMMON = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/LANG_LIB_TOOL_TOOLSRC_COMMON),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), LANG_LIB_TOOL_TOOLSRC_COMMON))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/LANG_LIB_TOOL_TOOLSRC_COMMON
endif
endif

endif

endif

