
ifndef __HEADER_ACCESS_IPNET_NTP_INCLUDED
__HEADER_ACCESS_IPNET_NTP_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_IPNET_NTP = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET_NTP),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), IPNET_NTP))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET_NTP
endif
endif

endif

endif

