
ifndef __HEADER_ACCESS_PPC_KERNEL_INCLUDED
__HEADER_ACCESS_PPC_KERNEL_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_PPC_KERNEL = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/PPC_KERNEL),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), PPC_KERNEL))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/PPC_KERNEL
endif
endif

endif

endif

