
ifndef __HEADER_ACCESS_IPNET_AAA_INCLUDED
__HEADER_ACCESS_IPNET_AAA_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_IPNET_AAA = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET_AAA),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), IPNET_AAA))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET_AAA
endif
endif

endif

endif

