
ifndef __HEADER_ACCESS_FS_ROMFS_INCLUDED
__HEADER_ACCESS_FS_ROMFS_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_FS_ROMFS = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FS_ROMFS),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), FS_ROMFS))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FS_ROMFS
endif
endif

endif

endif

