
ifndef __HEADER_ACCESS_IPNET_PPP_INCLUDED
__HEADER_ACCESS_IPNET_PPP_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_IPNET_PPP = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET_PPP),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), IPNET_PPP))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET_PPP
endif
endif

endif

endif

