
ifndef __HEADER_ACCESS_VXBUS_BUSLIB_INCLUDED
__HEADER_ACCESS_VXBUS_BUSLIB_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_VXBUS_BUSLIB = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/VXBUS_BUSLIB),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), VXBUS_BUSLIB))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/VXBUS_BUSLIB
endif
endif

endif

endif

