
ifndef __HEADER_ACCESS_IPNET_FTP_INCLUDED
__HEADER_ACCESS_IPNET_FTP_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_IPNET_FTP = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET_FTP),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), IPNET_FTP))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/IPNET_FTP
endif
endif

endif

endif

