
ifndef __HEADER_ACCESS_FS_DEVFS_INCLUDED
__HEADER_ACCESS_FS_DEVFS_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_FS_DEVFS = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FS_DEVFS),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), FS_DEVFS))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FS_DEVFS
endif
endif

endif

endif

