
ifndef __HEADER_ACCESS_LIBDL_INCLUDED
__HEADER_ACCESS_LIBDL_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_LIBDL = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/LIBDL),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), LIBDL))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/LIBDL
endif
endif

endif

endif

