
ifndef __HEADER_ACCESS_RUNTIME_ANALYSIS_INCLUDED
__HEADER_ACCESS_RUNTIME_ANALYSIS_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_RUNTIME_ANALYSIS = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/RUNTIME_ANALYSIS),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), RUNTIME_ANALYSIS))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/RUNTIME_ANALYSIS
endif
endif

endif

endif

