
ifndef __HEADER_ACCESS_FS_CORE_INCLUDED
__HEADER_ACCESS_FS_CORE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_FS_CORE = 



ifneq ($(wildcard $(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FS_CORE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), FS_CORE))
VSBL_LKH += $(OPTION_INCLUDE_DIR)$(VSB_KERNEL_PROTECTED_INCLUDE_DIR)/FS_CORE
endif
endif

endif

endif

