
ifndef __HEADER_ACCESS_LANG_LIB_CPLUS_CPLUS_USER_2011_INCLUDED
__HEADER_ACCESS_LANG_LIB_CPLUS_CPLUS_USER_2011_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_LANG_LIB_CPLUS_CPLUS_USER_2011 = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/LANG_LIB_CPLUS_CPLUS_USER_2011),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), LANG_LIB_CPLUS_CPLUS_USER_2011))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/LANG_LIB_CPLUS_CPLUS_USER_2011
endif
endif

endif

endif

