
ifndef __HEADER_ACCESS_JOBQUEUE_INCLUDED
__HEADER_ACCESS_JOBQUEUE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_JOBQUEUE = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/JOBQUEUE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), JOBQUEUE))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/JOBQUEUE
endif
endif

endif

endif

