
ifndef __HEADER_ACCESS_DEBUG_AGENT_INCLUDED
__HEADER_ACCESS_DEBUG_AGENT_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_DEBUG_AGENT = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/DEBUG_AGENT),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), DEBUG_AGENT))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/DEBUG_AGENT
endif
endif

endif

endif

