
ifndef __HEADER_ACCESS_BDM_NVRAM_INCLUDED
__HEADER_ACCESS_BDM_NVRAM_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BDM_NVRAM = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/BDM_NVRAM),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BDM_NVRAM))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/BDM_NVRAM
endif
endif

endif

endif

