
ifndef __HEADER_ACCESS_VXBUS_CORE_INCLUDED
__HEADER_ACCESS_VXBUS_CORE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_VXBUS_CORE = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/VXBUS_CORE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), VXBUS_CORE))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/VXBUS_CORE
endif
endif

endif

endif

