
ifndef __HEADER_ACCESS_BDM_TFFS_DRIVER_INCLUDED
__HEADER_ACCESS_BDM_TFFS_DRIVER_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BDM_TFFS_DRIVER = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/BDM_TFFS_DRIVER),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BDM_TFFS_DRIVER))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/BDM_TFFS_DRIVER
endif
endif

endif

endif

