
ifndef __HEADER_ACCESS_MY_QSPI_FLASH_LAYER_INCLUDED
__HEADER_ACCESS_MY_QSPI_FLASH_LAYER_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_MY_QSPI_FLASH_LAYER = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/MY_QSPI_FLASH_LAYER),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), MY_QSPI_FLASH_LAYER))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/MY_QSPI_FLASH_LAYER
endif
endif

endif

endif

