
ifndef __HEADER_ACCESS_BOOTAPP_INCLUDED
__HEADER_ACCESS_BOOTAPP_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_BOOTAPP = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/BOOTAPP),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), BOOTAPP))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/BOOTAPP
endif
endif

endif

endif

