
ifndef __HEADER_ACCESS_STACKTRACE_INCLUDED
__HEADER_ACCESS_STACKTRACE_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_STACKTRACE = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/STACKTRACE),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), STACKTRACE))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/STACKTRACE
endif
endif

endif

endif

