
ifndef __HEADER_ACCESS_IPNET_TFTP_INCLUDED
__HEADER_ACCESS_IPNET_TFTP_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_IPNET_TFTP = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/IPNET_TFTP),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), IPNET_TFTP))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/IPNET_TFTP
endif
endif

endif

endif

