
ifndef __HEADER_ACCESS_SYSTEMVIEWER_INCLUDED
__HEADER_ACCESS_SYSTEMVIEWER_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_SYSTEMVIEWER = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/SYSTEMVIEWER),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), SYSTEMVIEWER))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/SYSTEMVIEWER
endif
endif

endif

endif

