
ifndef __HEADER_ACCESS_FSAPI_UTIL_INCLUDED
__HEADER_ACCESS_FSAPI_UTIL_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_FSAPI_UTIL = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/FSAPI_UTIL),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), FSAPI_UTIL))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/FSAPI_UTIL
endif
endif

endif

endif

