
ifndef __HEADER_ACCESS_SEC_HASH_INCLUDED
__HEADER_ACCESS_SEC_HASH_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_SEC_HASH = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/SEC_HASH),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), SEC_HASH))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/SEC_HASH
endif
endif

endif

endif

