
ifndef __HEADER_ACCESS_LOADER_INCLUDED
__HEADER_ACCESS_LOADER_INCLUDED = TRUE





__SUBSCRIBE_ACCESS_LOADER = 



ifneq ($(wildcard $(VSB_USER_PROTECTED_INCLUDE_DIR)/LOADER),)

ifneq ($(VSBL_NAME),)
ifeq ($(VSBL_NAME),$(filter $(VSBL_NAME), LOADER))
VSBL_LUH += $(OPTION_INCLUDE_DIR)$(VSB_USER_PROTECTED_INCLUDE_DIR)/LOADER
endif
endif

endif

endif

