
#
# This file is automatically generated by mk/krnl/defs.fastlibgen.mk .
#
# build configuration :
#	VSB : D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild
#	CPU : PPCE6500
#	TOOL : diab
#	FP : hard
# 	ENDIAN : big
#	LIB_DIR_TAG = 
#	LIBDIRBASE = krnl/PPCE6500/common
#	LIBDIRBASE = krnl/$(CPU)$(CPU_OPTION_SUFFIX)/$(TOOL_COMMON_DIR)$(LIB_DIR_TAG)$(MINOR_OPTION_SUFFIX)






LIBOBJS = $(LIBOBJS_tcfagent)

# DEP_OBJS = (DEP_OBJS)

 
LIBOBJS_krnl_PPCE6500_common_tcfagent_kernel_top_DEBUG_AGENT_hostfs_src_diab =  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/objtcfagent/hostFsLib.o  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/objtcfagent/hostFsLib.o 

arcmdfile_krnl_PPCE6500_common_tcfagent : $(LIBOBJS_krnl_PPCE6500_common_tcfagent_kernel_top_DEBUG_AGENT_hostfs_src_diab)

LIBOBJS_krnl_PPCE6500_common_tcfagent_DEBUG_AGENT += $(LIBOBJS_krnl_PPCE6500_common_tcfagent_kernel_top_DEBUG_AGENT_hostfs_src_diab)

LIBOBJS_krnl_PPCE6500_common_tcfagent += $(LIBOBJS_krnl_PPCE6500_common_tcfagent_kernel_top_DEBUG_AGENT_hostfs_src_diab)

__OBJS_TO_CLEAN_DEBUG_AGENT += $(LIBOBJS_krnl_PPCE6500_common_tcfagent_kernel_top_DEBUG_AGENT_hostfs_src_diab) $(LIBOBJS_krnl_PPCE6500_common_tcfagent_kernel_top_DEBUG_AGENT_hostfs_src_diab:.o=.d)

ifndef _DONEBASE_LIB_krnl_PPCE6500_common_tcfagent

_DONEBASE_LIB_krnl_PPCE6500_common_tcfagent = TRUE

# LIBBASES += tcfagent

__LIBS_TO_BUILD += krnl_PPCE6500_common_tcfagent

__LIBS_TO_BUILD_DEBUG_AGENT += krnl_PPCE6500_common_tcfagent

__BUILT_LIBS += krnl_PPCE6500_common_tcfagent

__LIB_krnl_PPCE6500_common_tcfagent = D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/libtcfagent$(OPT).a


D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/objtcfagent :
	$(MKDIR) $@


lib : D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/libtcfagent$(OPT).a  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/libtcfagent.cdf

# need to pass the lib.a file twice to D:/vxWorks7/compilers/diab-5.9.6.5/WIN32/bin/ddump -Ng to workaround ddump problem
D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/libtcfagent.nm : D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/libtcfagent$(OPT).a
	$(if $(wildcard $<),cd D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common && $(NM) libtcfagent$(OPT).a libtcfagent$(OPT).a > $@, $(info skipping $@ : non existant $<))

D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/libtcfagent.cdf : D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/libtcfagent.nm 
	$(if $(wildcard $<),$(LIB2CDF) -i $< -a libtcfagent.a -o $@, $(info skipping $@ : non existant $<))

arcmdfiles : arcmdfile_krnl_PPCE6500_common_tcfagent

arcmdfile_krnl_PPCE6500_common_tcfagent :
	$(file >$@,$(call uniq,$(LIBOBJS_krnl_PPCE6500_common_tcfagent)))
	@echo created $@

D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/libtcfagent$(OPT).a : arcmdfile_krnl_PPCE6500_common_tcfagent
	D:/vxWorks7/compilers/diab-5.9.6.5/WIN32/bin/dar crusv $@ @arcmdfile_krnl_PPCE6500_common_tcfagent


clean _layer_clean_DEBUG_AGENT : _clean_LIB_BASE_krnl_PPCE6500_common_tcfagent

_clean_LIB_BASE_krnl_PPCE6500_common_tcfagent :
	rm -f D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/libtcfagent$(OPT).a


endif

ifndef _DONEBASE_LIB_DEBUG_AGENT_krnl_PPCE6500_common_tcfagent

_DONEBASE_LIB_DEBUG_AGENT_krnl_PPCE6500_common_tcfagent = TRUE

lib : D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/layerDEBUG_AGENT_libtcfagent.cdf

D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/layerDEBUG_AGENT_libtcfagent.cdf :  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/libtcfagent$(OPT).a
	$(file >$@, $(call __tmpl_layercdf,DEBUG_AGENT,libtcfagent.a,$(LIBOBJS_krnl_PPCE6500_common_tcfagent)))

endif


D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/PPCE6500/common/libtcfagent$(OPT).a : $(LIBOBJS_krnl_PPCE6500_common_tcfagent)




 

################
# rules defined locally in Makefile
##



################

objs : $(LIBOBJS)
 
# this is the end of the file 
