
#
# This file is automatically generated by mk/krnl/defs.fastlibgen.mk .
#
# build configuration :
#	VSB : D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild
#	CPU : PPCE6500
#	TOOL : diab
#	FP : hard
# 	ENDIAN : big
#	LIB_DIR_TAG = 
#	LIBDIRBASE = krnl/diab
#	LIBDIRBASE = krnl/$(TOOL_SPECIFIC_DIR)$(LIB_DIR_TAG)$(MINOR_OPTION_SUFFIX)






LIBOBJS = $(LIBOBJS_cplus)

# DEP_OBJS = (DEP_OBJS)

 
LIBOBJS_krnl_diab_cplus_kernel_top_LANG_LIB_CPLUS_CPLUS_KERNEL_src_diab_rts_demangler =  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/objcplus/cplusDemStyle.o  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/objcplus/cplusDem.o  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/objcplus/cplusDemStub.o  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/objcplus/etoa_decode.o  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/objcplus/demangler.o  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/objcplus/cplusDemStyle.o  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/objcplus/cplusDem.o  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/objcplus/cplusDemStub.o  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/objcplus/etoa_decode.o  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/objcplus/demangler.o 

arcmdfile_krnl_diab_cplus : $(LIBOBJS_krnl_diab_cplus_kernel_top_LANG_LIB_CPLUS_CPLUS_KERNEL_src_diab_rts_demangler)

LIBOBJS_krnl_diab_cplus_LANG_LIB_CPLUS_CPLUS_KERNEL += $(LIBOBJS_krnl_diab_cplus_kernel_top_LANG_LIB_CPLUS_CPLUS_KERNEL_src_diab_rts_demangler)

LIBOBJS_krnl_diab_cplus += $(LIBOBJS_krnl_diab_cplus_kernel_top_LANG_LIB_CPLUS_CPLUS_KERNEL_src_diab_rts_demangler)

__OBJS_TO_CLEAN_LANG_LIB_CPLUS_CPLUS_KERNEL += $(LIBOBJS_krnl_diab_cplus_kernel_top_LANG_LIB_CPLUS_CPLUS_KERNEL_src_diab_rts_demangler) $(LIBOBJS_krnl_diab_cplus_kernel_top_LANG_LIB_CPLUS_CPLUS_KERNEL_src_diab_rts_demangler:.o=.d)

ifndef _DONEBASE_LIB_krnl_diab_cplus

_DONEBASE_LIB_krnl_diab_cplus = TRUE

# LIBBASES += cplus

__LIBS_TO_BUILD += krnl_diab_cplus

__LIBS_TO_BUILD_LANG_LIB_CPLUS_CPLUS_KERNEL += krnl_diab_cplus

__BUILT_LIBS += krnl_diab_cplus

__LIB_krnl_diab_cplus = D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/libcplus$(OPT).a


D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/objcplus :
	$(MKDIR) $@


lib : D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/libcplus$(OPT).a  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/libcplus.cdf

# need to pass the lib.a file twice to D:/vxWorks7/compilers/diab-5.9.6.5/WIN32/bin/ddump -Ng to workaround ddump problem
D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/libcplus.nm : D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/libcplus$(OPT).a
	$(if $(wildcard $<),cd D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab && $(NM) libcplus$(OPT).a libcplus$(OPT).a > $@, $(info skipping $@ : non existant $<))

D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/libcplus.cdf : D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/libcplus.nm 
	$(if $(wildcard $<),$(LIB2CDF) -i $< -a libcplus.a -o $@, $(info skipping $@ : non existant $<))

arcmdfiles : arcmdfile_krnl_diab_cplus

arcmdfile_krnl_diab_cplus :
	$(file >$@,$(call uniq,$(LIBOBJS_krnl_diab_cplus)))
	@echo created $@

D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/libcplus$(OPT).a : arcmdfile_krnl_diab_cplus
	D:/vxWorks7/compilers/diab-5.9.6.5/WIN32/bin/dar crusv $@ @arcmdfile_krnl_diab_cplus


clean _layer_clean_LANG_LIB_CPLUS_CPLUS_KERNEL : _clean_LIB_BASE_krnl_diab_cplus

_clean_LIB_BASE_krnl_diab_cplus :
	rm -f D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/libcplus$(OPT).a


endif

ifndef _DONEBASE_LIB_LANG_LIB_CPLUS_CPLUS_KERNEL_krnl_diab_cplus

_DONEBASE_LIB_LANG_LIB_CPLUS_CPLUS_KERNEL_krnl_diab_cplus = TRUE

lib : D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/layerLANG_LIB_CPLUS_CPLUS_KERNEL_libcplus.cdf

D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/layerLANG_LIB_CPLUS_CPLUS_KERNEL_libcplus.cdf :  D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/libcplus$(OPT).a
	$(file >$@, $(call __tmpl_layercdf,LANG_LIB_CPLUS_CPLUS_KERNEL,libcplus.a,$(LIBOBJS_krnl_diab_cplus)))

endif


D:/VirtualBoxVMs/Git/ZPocketSonataT/project-spec/meta-user/recipes-apps/apppocketsonata/VxWorksSpace/VSourceBuild/krnl/diab/libcplus$(OPT).a : $(LIBOBJS_krnl_diab_cplus)




 

################
# rules defined locally in Makefile
##



################

objs : $(LIBOBJS)
 
# this is the end of the file 
