# Automatically generated file: do not edit

##########################
# DSI_DSI_KERNEL Section
##########################


ifdef _WRS_CONFIG_DSI_DSI_KERNEL
VSBL_DSI_DSI_KERNEL_SRC = 
VSBL_DSI_DSI_KERNEL_DEPEND = 

ifdef _WRS_CONFIG_DSI_1_0_0_1_DSI_KERNEL_1_0_0_7
VSBL_DSI_DSI_KERNEL_SRC += DSI_DSI_KERNEL
VSBL_DSI_DSI_KERNEL_DEPEND += IPNET_COREIP
VSBL_DSI_DSI_KERNEL_DEPEND += TIPC_TIPC_KERNEL
DSI_DSI_KERNEL_FASTBUILD = YES
VSBL_DSI_DSI_KERNEL_PATH = $(WIND_BASE)/pkgs/ipc/dsi-1.0.0.1/dsi_kernel-1.0.0.7
VSBL_DSI_DSI_KERNEL_VERSION = DSI_1_0_0_1_DSI_KERNEL_1_0_0_7
endif
endif

