# Automatically generated file: do not edit

##########################
# VXBUS_VXTEST Section
##########################


ifdef _WRS_CONFIG_VXBUS_VXTEST
VSBL_VXBUS_VXTEST_SRC = 
VSBL_VXBUS_VXTEST_DEPEND = 

ifdef _WRS_CONFIG_VXBUS_1_0_5_0_CORE_1_0_8_4_VXTEST_1_0_0_2
VSBL_VXBUS_VXTEST_SRC += VXBUS_VXTEST
VSBL_VXBUS_VXTEST_DEPEND += CORE_KERNEL_VXTEST
VXBUS_VXTEST_FASTBUILD = YES
VSBL_VXBUS_VXTEST_PATH = $(WIND_BASE)/pkgs/os/drv/vxbus-1.0.5.0/core-1.0.8.4/vxTest
VSBL_VXBUS_VXTEST_VERSION = VXBUS_1_0_5_0_CORE_1_0_8_4_VXTEST_1_0_0_2
endif
endif

