# Automatically generated file: do not edit

##########################
# LANG_LIB_LIBC_LIBC_USER Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_LIBC_LIBC_USER
VSBL_LANG_LIB_LIBC_LIBC_USER_SRC = 
VSBL_LANG_LIB_LIBC_LIBC_USER_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_LIBC_1_0_0_1_LIBC_USER_1_0_6_6
ifdef _WRS_CONFIG_LANG_LIB_LIBC_VXTEST_USER
VSBL_LANG_LIB_LIBC_LIBC_USER_SRC += LANG_LIB_LIBC_VXTEST_USER
endif
VSBL_LANG_LIB_LIBC_LIBC_USER_SRC += LANG_LIB_LIBC_LIBC_USER
VSBL_LANG_LIB_LIBC_LIBC_USER_DEPEND += SYSCALLS_VXWORKS
VSBL_LANG_LIB_LIBC_LIBC_USER_DEPEND += CORE_USER
VSBL_LANG_LIB_LIBC_LIBC_USER_DEPEND += CORE_USER
LANG_LIB_LIBC_LIBC_USER_FASTBUILD = YES
VSBL_LANG_LIB_LIBC_LIBC_USER_PATH = $(WIND_BASE)/pkgs/os/lang-lib/libc-1.0.0.1/libc-usr-1.0.6.6
VSBL_LANG_LIB_LIBC_LIBC_USER_VERSION = LANG_LIB_LIBC_1_0_0_1_LIBC_USER_1_0_6_6
endif
endif

