# Automatically generated file: do not edit

##########################
# IPNET_IPHWCRYPTO Section
##########################


ifdef _WRS_CONFIG_IPNET_IPHWCRYPTO
VSBL_IPNET_IPHWCRYPTO_SRC = 
VSBL_IPNET_IPHWCRYPTO_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_CRYPTO_1_0_0_10_IPHWCRYPTO_1_0_0_3
VSBL_IPNET_IPHWCRYPTO_SRC += IPNET_IPHWCRYPTO
VSBL_IPNET_IPHWCRYPTO_DEPEND += IPNET_IPCRYPTO
IPNET_IPHWCRYPTO_FASTBUILD = YES
VSBL_IPNET_IPHWCRYPTO_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/crypto-1.0.0.10/iphwcrypto
VSBL_IPNET_IPHWCRYPTO_VERSION = IPNET_1_1_1_2_CRYPTO_1_0_0_10_IPHWCRYPTO_1_0_0_3
endif
endif

