# Automatically generated file: do not edit

##########################
# FBDEV_FSLDCUFB Section
##########################


ifdef _WRS_CONFIG_FBDEV_FSLDCUFB
VSBL_FBDEV_FSLDCUFB_SRC = 
VSBL_FBDEV_FSLDCUFB_DEPEND = 

ifdef _WRS_CONFIG_FBDEV_1_0_0_2_FSLDCUFB_1_0_2_2
VSBL_FBDEV_FSLDCUFB_SRC += FBDEV_FSLDCUFB
VSBL_FBDEV_FSLDCUFB_DEPEND += FBDEV_COMMON
FBDEV_FSLDCUFB_FASTBUILD = YES
VSBL_FBDEV_FSLDCUFB_PATH = $(WIND_BASE)/pkgs/ui/fbdev-1.0.0.2/fsldcu-1.0.2.2
VSBL_FBDEV_FSLDCUFB_VERSION = FBDEV_1_0_0_2_FSLDCUFB_1_0_2_2
endif
endif

