# Automatically generated file: do not edit

##########################
# IPNET_IPSECIKE Section
##########################


ifdef _WRS_CONFIG_IPNET_IPSECIKE
VSBL_IPNET_IPSECIKE_SRC = 
VSBL_IPNET_IPSECIKE_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_IPSECIKE_1_0_1_13
ifdef _WRS_CONFIG_IPNET_IKE
VSBL_IPNET_IPSECIKE_SRC += IPNET_IKE
endif
ifdef _WRS_CONFIG_IPNET_IPSEC
VSBL_IPNET_IPSECIKE_SRC += IPNET_IPSEC
endif
VSBL_IPNET_IPSECIKE_SRC += IPNET_IPSECIKE
VSBL_IPNET_IPSECIKE_DEPEND += IPNET_COREIP
IPNET_IPSECIKE_FASTBUILD = YES
IPNET_IPSECIKE_FRIEND = GDOI
VSBL_IPNET_IPSECIKE_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/ipsecike-1.0.1.13
VSBL_IPNET_IPSECIKE_VERSION = IPNET_1_1_1_2_IPSECIKE_1_0_1_13
endif
endif

