# Automatically generated file: do not edit

##########################
# CORE_SAFETY Section
##########################


ifdef _WRS_CONFIG_CORE_SAFETY
VSBL_CORE_SAFETY_SRC = 
VSBL_CORE_SAFETY_DEPEND = 

ifdef _WRS_CONFIG_CORE_SAFETY_1_0_5_1
VSBL_CORE_SAFETY_SRC += CORE_SAFETY
VSBL_CORE_SAFETY_DEPEND += CORE_KERNEL
VSBL_CORE_SAFETY_DEPEND += CORE_KERNEL
VSBL_CORE_SAFETY_DEPEND += CORE_KERNEL
VSBL_CORE_SAFETY_DEPEND += CORE_RTP
VSBL_CORE_SAFETY_DEPEND += CORE_RTP
VSBL_CORE_SAFETY_DEPEND += CORE_KERNEL
CORE_SAFETY_FASTBUILD = YES
VSBL_CORE_SAFETY_PATH = $(WIND_BASE)/pkgs/os/core/safety-1.0.5.1
VSBL_CORE_SAFETY_VERSION = CORE_SAFETY_1_0_5_1
endif
endif

