# Automatically generated file: do not edit

##########################
# RASTER_MESA Section
##########################


ifdef _WRS_CONFIG_RASTER_MESA
VSBL_RASTER_MESA_SRC = 
VSBL_RASTER_MESA_DEPEND = 

ifdef _WRS_CONFIG_RASTER_1_0_0_2_MESA_13_0_3_0
VSBL_RASTER_MESA_SRC += RASTER_MESA
VSBL_RASTER_MESA_DEPEND += RASTER_COMMON
VSBL_RASTER_MESA_DEPEND += KHRONOS
VSBL_RASTER_MESA_DEPEND += XML
VSBL_RASTER_MESA_DEPEND += FBDEV_COMMON
ifdef _WRS_CONFIG_GPUDEV_LIBDRM
VSBL_RASTER_MESA_DEPEND += GPUDEV_LIBDRM
endif
ifdef _WRS_CONFIG_ARCH_i86*
VSBL_RASTER_MESA_DEPEND += GPUDEV_LIBDRM
endif
VSBL_RASTER_MESA_DEPEND += LANG_LIB_LIBC_LIBC_KERNEL
RASTER_MESA_FASTBUILD = YES
VSBL_RASTER_MESA_PATH = $(WIND_BASE)/pkgs/ui/raster-1.0.0.2/mesa-13.0.3.0
VSBL_RASTER_MESA_VERSION = RASTER_1_0_0_2_MESA_13_0_3_0
endif
endif

