# Automatically generated file: do not edit

##########################
# FS_CDROMFS Section
##########################


ifdef _WRS_CONFIG_FS_CDROMFS
VSBL_FS_CDROMFS_SRC = 
VSBL_FS_CDROMFS_DEPEND = 

ifdef _WRS_CONFIG_FS_1_0_0_2_CDROMFS_1_0_1_1
VSBL_FS_CDROMFS_SRC += FS_CDROMFS
VSBL_FS_CDROMFS_DEPEND += BDM_XBD
VSBL_FS_CDROMFS_DEPEND += ERF
VSBL_FS_CDROMFS_DEPEND += FS_COMMON
VSBL_FS_CDROMFS_DEPEND += UTF
VSBL_FS_CDROMFS_DEPEND += CORE_IO
FS_CDROMFS_FASTBUILD = YES
VSBL_FS_CDROMFS_PATH = $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/cdromfs-1.0.1.1
VSBL_FS_CDROMFS_VERSION = FS_1_0_0_2_CDROMFS_1_0_1_1
endif
endif

