# Automatically generated file: do not edit

##########################
# SYSTEMVIEWER_AGENT Section
##########################


ifdef _WRS_CONFIG_SYSTEMVIEWER_AGENT
VSBL_SYSTEMVIEWER_AGENT_SRC = 
VSBL_SYSTEMVIEWER_AGENT_DEPEND = 

ifdef _WRS_CONFIG_SYSTEMVIEWER_AGENT_1_0_0_12
VSBL_SYSTEMVIEWER_AGENT_SRC += SYSTEMVIEWER_AGENT
VSBL_SYSTEMVIEWER_AGENT_DEPEND += DEBUG_AGENT
VSBL_SYSTEMVIEWER_AGENT_DEPEND += SYSTEMVIEWER
SYSTEMVIEWER_AGENT_FASTBUILD = YES
VSBL_SYSTEMVIEWER_AGENT_PATH = $(WIND_BASE)/pkgs/rttools/systemviewer-1.0.0.12
VSBL_SYSTEMVIEWER_AGENT_VERSION = SYSTEMVIEWER_AGENT_1_0_0_12
endif
endif

