# Automatically generated file: do not edit

##########################
# VXBUS_DRV Section
##########################


ifdef _WRS_CONFIG_VXBUS_DRV
VSBL_VXBUS_DRV_SRC = 
VSBL_VXBUS_DRV_DEPEND = 

ifdef _WRS_CONFIG_VXBUS_1_0_5_0_DRV_1_2_7_1
VSBL_VXBUS_DRV_SRC += VXBUS_DRV
VSBL_VXBUS_DRV_DEPEND += VXBUS_SUBSYSTEM
VSBL_VXBUS_DRV_DEPEND += VXBUS_SUBSYSTEM
VSBL_VXBUS_DRV_DEPEND += VXBUS_BUSLIB
VSBL_VXBUS_DRV_DEPEND += VXBUS_CORE
VSBL_VXBUS_DRV_DEPEND += VXBUS_CORE
VSBL_VXBUS_DRV_DEPEND += CORE_KERNEL
ifdef _WRS_CONFIG_INTEL
VSBL_VXBUS_DRV_DEPEND += PSL
endif
ifdef _WRS_CONFIG_INTEL*
endif
ifdef _WRS_CONFIG_INTEL
VSBL_VXBUS_DRV_DEPEND += PSL
endif
ifdef _WRS_CONFIG_INTEL*
endif
VSBL_VXBUS_DRV_DEPEND += VXBUS_SUBSYSTEM
VSBL_VXBUS_DRV_DEPEND += VXBUS_SUBSYSTEM
VSBL_VXBUS_DRV_DEPEND += VXBUS_CORE
VXBUS_DRV_FASTBUILD = YES
VSBL_VXBUS_DRV_PATH = $(WIND_BASE)/pkgs/os/drv/vxbus-1.0.5.0/drv-1.2.7.1
VSBL_VXBUS_DRV_VERSION = VXBUS_1_0_5_0_DRV_1_2_7_1
endif
endif

