# Automatically generated file: do not edit

##########################
# IPNET Section
##########################


ifdef _WRS_CONFIG_IPNET
VSBL_IPNET_SRC = 
VSBL_IPNET_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2
ifdef _WRS_CONFIG_IPNET_AAA
VSBL_IPNET_SRC += IPNET_AAA
endif
ifdef _WRS_CONFIG_IPNET_DIAMETER
VSBL_IPNET_SRC += IPNET_DIAMETER
endif
ifdef _WRS_CONFIG_IPNET_RADIUS
VSBL_IPNET_SRC += IPNET_RADIUS
endif
ifdef _WRS_CONFIG_IPNET_DHCPC
VSBL_IPNET_SRC += IPNET_DHCPC
endif
ifdef _WRS_CONFIG_IPNET_DHCPC6
VSBL_IPNET_SRC += IPNET_DHCPC6
endif
ifdef _WRS_CONFIG_IPNET_DHCPR
VSBL_IPNET_SRC += IPNET_DHCPR
endif
ifdef _WRS_CONFIG_IPNET_DHCPS
VSBL_IPNET_SRC += IPNET_DHCPS
endif
ifdef _WRS_CONFIG_IPNET_DHCPS6
VSBL_IPNET_SRC += IPNET_DHCPS6
endif
ifdef _WRS_CONFIG_IPNET_DNSC
VSBL_IPNET_SRC += IPNET_DNSC
endif
ifdef _WRS_CONFIG_IPNET_FTP
VSBL_IPNET_SRC += IPNET_FTP
endif
ifdef _WRS_CONFIG_IPNET_NTP
VSBL_IPNET_SRC += IPNET_NTP
endif
ifdef _WRS_CONFIG_IPNET_PTP
VSBL_IPNET_SRC += IPNET_PTP
endif
ifdef _WRS_CONFIG_IPNET_SNTP
VSBL_IPNET_SRC += IPNET_SNTP
endif
ifdef _WRS_CONFIG_IPNET_TFTP
VSBL_IPNET_SRC += IPNET_TFTP
endif
ifdef _WRS_CONFIG_IPNET_COREIP
VSBL_IPNET_SRC += IPNET_COREIP
endif
ifdef _WRS_CONFIG_IPNET_CRYPTO
VSBL_IPNET_SRC += IPNET_CRYPTO
endif
ifdef _WRS_CONFIG_IPNET_IPCRYPTO
VSBL_IPNET_SRC += IPNET_IPCRYPTO
endif
ifdef _WRS_CONFIG_IPNET_IPFREESCALE
VSBL_IPNET_SRC += IPNET_IPFREESCALE
endif
ifdef _WRS_CONFIG_IPNET_IPHWCRYPTO
VSBL_IPNET_SRC += IPNET_IPHWCRYPTO
endif
ifdef _WRS_CONFIG_IPNET_EAP
VSBL_IPNET_SRC += IPNET_EAP
endif
ifdef _WRS_CONFIG_IPNET_FIREWALL
VSBL_IPNET_SRC += IPNET_FIREWALL
endif
ifdef _WRS_CONFIG_IPNET_IPSECIKE
VSBL_IPNET_SRC += IPNET_IPSECIKE
endif
ifdef _WRS_CONFIG_IPNET_IKE
VSBL_IPNET_SRC += IPNET_IKE
endif
ifdef _WRS_CONFIG_IPNET_IPSEC
VSBL_IPNET_SRC += IPNET_IPSEC
endif
ifdef _WRS_CONFIG_IPNET_LINKPROTO
VSBL_IPNET_SRC += IPNET_LINKPROTO
endif
ifdef _WRS_CONFIG_IPNET_BRIDGE
VSBL_IPNET_SRC += IPNET_BRIDGE
endif
ifdef _WRS_CONFIG_IPNET_L2TP
VSBL_IPNET_SRC += IPNET_L2TP
endif
ifdef _WRS_CONFIG_IPNET_PPP
VSBL_IPNET_SRC += IPNET_PPP
endif
ifdef _WRS_CONFIG_IPNET_ROHC
VSBL_IPNET_SRC += IPNET_ROHC
endif
ifdef _WRS_CONFIG_IPNET_MOBILITY
VSBL_IPNET_SRC += IPNET_MOBILITY
endif
ifdef _WRS_CONFIG_IPNET_8021X
VSBL_IPNET_SRC += IPNET_8021X
endif
ifdef _WRS_CONFIG_IPNET_DOT1X
VSBL_IPNET_SRC += IPNET_DOT1X
endif
ifdef _WRS_CONFIG_IPNET_WLANMLME
VSBL_IPNET_SRC += IPNET_WLANMLME
endif
ifdef _WRS_CONFIG_IPNET_WLAN
VSBL_IPNET_SRC += IPNET_WLAN
endif
ifdef _WRS_CONFIG_IPNET_WPS
VSBL_IPNET_SRC += IPNET_WPS
endif
ifdef _WRS_CONFIG_IPNET_QOS
VSBL_IPNET_SRC += IPNET_QOS
endif
ifdef _WRS_CONFIG_IPNET_ROUTEPROTO
VSBL_IPNET_SRC += IPNET_ROUTEPROTO
endif
ifdef _WRS_CONFIG_IPNET_RIPNG
VSBL_IPNET_SRC += IPNET_RIPNG
endif
ifdef _WRS_CONFIG_IPNET_RIP
VSBL_IPNET_SRC += IPNET_RIP
endif
ifdef _WRS_CONFIG_IPNET_SSH
VSBL_IPNET_SRC += IPNET_SSH
endif
ifdef _WRS_CONFIG_IPNET_SSL
VSBL_IPNET_SRC += IPNET_SSL
endif
ifdef _WRS_CONFIG_IPNET_TSN
VSBL_IPNET_SRC += IPNET_TSN
endif
ifdef _WRS_CONFIG_IPNET_CLOCK
VSBL_IPNET_SRC += IPNET_CLOCK
endif
ifdef _WRS_CONFIG_IPNET_QAVQBV
VSBL_IPNET_SRC += IPNET_QAVQBV
endif
ifdef _WRS_CONFIG_IPNET_STREAM
VSBL_IPNET_SRC += IPNET_STREAM
endif
ifdef _WRS_CONFIG_IPNET_USRSPACE
VSBL_IPNET_SRC += IPNET_USRSPACE
endif
ifdef _WRS_CONFIG_IPNET_VRRP
VSBL_IPNET_SRC += IPNET_VRRP
endif
VSBL_IPNET_SRC += IPNET
VSBL_IPNET_DEPEND += NET_BASE
IPNET_FASTBUILD = YES
VSBL_IPNET_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2
VSBL_IPNET_VERSION = IPNET_1_1_1_2
endif
endif

