# Automatically generated file: do not edit

##########################
# LANG_LIB_LIBC Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_LIBC
VSBL_LANG_LIB_LIBC_SRC = 
VSBL_LANG_LIB_LIBC_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_LIBC_1_0_0_1
ifdef _WRS_CONFIG_LANG_LIB_LIBC_LIBC_BOOT
VSBL_LANG_LIB_LIBC_SRC += LANG_LIB_LIBC_LIBC_BOOT
endif
ifdef _WRS_CONFIG_LANG_LIB_LIBC_LIBC_KERNEL
VSBL_LANG_LIB_LIBC_SRC += LANG_LIB_LIBC_LIBC_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_LIBC_VXTEST_KERNEL
VSBL_LANG_LIB_LIBC_SRC += LANG_LIB_LIBC_VXTEST_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_LIBC_LIBC_USER
VSBL_LANG_LIB_LIBC_SRC += LANG_LIB_LIBC_LIBC_USER
endif
ifdef _WRS_CONFIG_LANG_LIB_LIBC_VXTEST_USER
VSBL_LANG_LIB_LIBC_SRC += LANG_LIB_LIBC_VXTEST_USER
endif
VSBL_LANG_LIB_LIBC_SRC += LANG_LIB_LIBC
LANG_LIB_LIBC_FASTBUILD = YES
VSBL_LANG_LIB_LIBC_PATH = $(WIND_BASE)/pkgs/os/lang-lib/libc-1.0.0.1
VSBL_LANG_LIB_LIBC_VERSION = LANG_LIB_LIBC_1_0_0_1
endif
endif

