# Automatically generated file: do not edit

##########################
# IPNET_ROUTEPROTO Section
##########################


ifdef _WRS_CONFIG_IPNET_ROUTEPROTO
VSBL_IPNET_ROUTEPROTO_SRC = 
VSBL_IPNET_ROUTEPROTO_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_ROUTEPROTO_1_0_1_6
ifdef _WRS_CONFIG_IPNET_RIP
VSBL_IPNET_ROUTEPROTO_SRC += IPNET_RIP
endif
ifdef _WRS_CONFIG_IPNET_RIPNG
VSBL_IPNET_ROUTEPROTO_SRC += IPNET_RIPNG
endif
VSBL_IPNET_ROUTEPROTO_SRC += IPNET_ROUTEPROTO
VSBL_IPNET_ROUTEPROTO_DEPEND += IPNET_COREIP
IPNET_ROUTEPROTO_FASTBUILD = YES
VSBL_IPNET_ROUTEPROTO_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/routeproto-1.0.1.6
VSBL_IPNET_ROUTEPROTO_VERSION = IPNET_1_1_1_2_ROUTEPROTO_1_0_1_6
endif
endif

