# Automatically generated file: do not edit

##########################
# CORE_USER Section
##########################


ifdef _WRS_CONFIG_CORE_USER
VSBL_CORE_USER_SRC = 
VSBL_CORE_USER_DEPEND = 

ifdef _WRS_CONFIG_CORE_USER_1_2_5_1
ifdef _WRS_CONFIG_CORE_USER_APPS
VSBL_CORE_USER_SRC += CORE_USER_APPS
endif
VSBL_CORE_USER_SRC += CORE_USER
VSBL_CORE_USER_DEPEND += CORE_KERNEL
VSBL_CORE_USER_DEPEND += CORE_KERNEL
VSBL_CORE_USER_DEPEND += CORE_KERNEL
VSBL_CORE_USER_DEPEND += CORE_KERNEL
VSBL_CORE_USER_DEPEND += CORE_KERNEL
VSBL_CORE_USER_DEPEND += CORE_KERNEL
VSBL_CORE_USER_DEPEND += SYSCALLS_VXWORKS
VSBL_CORE_USER_DEPEND += SYSCALLS_VXWORKS
VSBL_CORE_USER_DEPEND += CORE_KERNEL
VSBL_CORE_USER_DEPEND += CORE_KERNEL
VSBL_CORE_USER_DEPEND += SYSCALLS_VXWORKS
VSBL_CORE_USER_DEPEND += CORE_KERNEL
VSBL_CORE_USER_DEPEND += CORE_RTP
VSBL_CORE_USER_DEPEND += CORE_KERNEL
CORE_USER_FASTBUILD = YES
VSBL_CORE_USER_PATH = $(WIND_BASE)/pkgs/os/core/user-1.2.5.1
VSBL_CORE_USER_VERSION = CORE_USER_1_2_5_1
endif
endif

