# Automatically generated file: do not edit

##########################
# TIPC_TIPC_KERNEL Section
##########################


ifdef _WRS_CONFIG_TIPC_TIPC_KERNEL
VSBL_TIPC_TIPC_KERNEL_SRC = 
VSBL_TIPC_TIPC_KERNEL_DEPEND = 

ifdef _WRS_CONFIG_TIPC_1_0_0_1_TIPC_KERNEL_1_0_0_11
VSBL_TIPC_TIPC_KERNEL_SRC += TIPC_TIPC_KERNEL
VSBL_TIPC_TIPC_KERNEL_DEPEND += IPNET_COREIP
TIPC_TIPC_KERNEL_FASTBUILD = YES
VSBL_TIPC_TIPC_KERNEL_PATH = $(WIND_BASE)/pkgs/ipc/tipc-1.0.0.1/tipc_kernel-1.0.0.11
VSBL_TIPC_TIPC_KERNEL_VERSION = TIPC_1_0_0_1_TIPC_KERNEL_1_0_0_11
endif
endif

