# Automatically generated file: do not edit

##########################
# WEBCLI_COMMON Section
##########################


ifdef _WRS_CONFIG_WEBCLI_COMMON
VSBL_WEBCLI_COMMON_SRC = 
VSBL_WEBCLI_COMMON_DEPEND = 

ifdef _WRS_CONFIG_WEBCLI_1_0_0_3_COMMON_1_0_3_5
VSBL_WEBCLI_COMMON_SRC += WEBCLI_COMMON
VSBL_WEBCLI_COMMON_DEPEND += IPNET_COREIP
ifdef _WRS_CONFIG_SEC_CRYPTO
VSBL_WEBCLI_COMMON_DEPEND += SEC_CRYPTO
endif
ifdef _WRS_CONFIG_SEC_CRYPTO*
VSBL_WEBCLI_COMMON_DEPEND += SEC_CRYPTO
endif
WEBCLI_COMMON_FASTBUILD = YES
VSBL_WEBCLI_COMMON_PATH = $(WIND_BASE)/pkgs/app/webcli-1.0.0.3/common-1.0.3.5
VSBL_WEBCLI_COMMON_VERSION = WEBCLI_1_0_0_3_COMMON_1_0_3_5
endif
endif

