# Automatically generated file: do not edit

##########################
# SDMMC_TIMMCHS Section
##########################


ifdef _WRS_CONFIG_SDMMC_TIMMCHS
VSBL_SDMMC_TIMMCHS_SRC = 
VSBL_SDMMC_TIMMCHS_DEPEND = 

ifdef _WRS_CONFIG_SDMMC_1_0_1_3_HOST_1_0_0_4_TIMMCHS_1_1_1_1
VSBL_SDMMC_TIMMCHS_SRC += SDMMC_TIMMCHS
VSBL_SDMMC_TIMMCHS_DEPEND += ERF
VSBL_SDMMC_TIMMCHS_DEPEND += SDMMC_CORE
VSBL_SDMMC_TIMMCHS_DEPEND += VXBUS_BUSLIB
SDMMC_TIMMCHS_FASTBUILD = YES
VSBL_SDMMC_TIMMCHS_PATH = $(WIND_BASE)/pkgs/connectivity/sdmmc-1.0.1.3/host/timmchs-1.1.1.1
VSBL_SDMMC_TIMMCHS_VERSION = SDMMC_1_0_1_3_HOST_1_0_0_4_TIMMCHS_1_1_1_1
endif
endif

