# Automatically generated file: do not edit

##########################
# SDMMC_STORAGE Section
##########################


ifdef _WRS_CONFIG_SDMMC_STORAGE
VSBL_SDMMC_STORAGE_SRC = 
VSBL_SDMMC_STORAGE_DEPEND = 

ifdef _WRS_CONFIG_SDMMC_1_0_1_3_DEVICE_1_0_0_2_STORAGE_1_0_2_1
VSBL_SDMMC_STORAGE_SRC += SDMMC_STORAGE
VSBL_SDMMC_STORAGE_DEPEND += BDM_XBD
VSBL_SDMMC_STORAGE_DEPEND += ERF
VSBL_SDMMC_STORAGE_DEPEND += SDMMC_CORE
SDMMC_STORAGE_FASTBUILD = YES
VSBL_SDMMC_STORAGE_PATH = $(WIND_BASE)/pkgs/connectivity/sdmmc-1.0.1.3/device/storage-1.0.2.1
VSBL_SDMMC_STORAGE_VERSION = SDMMC_1_0_1_3_DEVICE_1_0_0_2_STORAGE_1_0_2_1
endif
endif

