# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_LLVM_1_0_1_2_TOOLSRC_LLVM_KERNEL_1_0_0_1
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL_SRC += LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL
LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_llvm-1.0.1.2/kernel
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_LLVM_1_0_1_2_TOOLSRC_LLVM_KERNEL_1_0_0_1
endif
endif

