# Automatically generated file: do not edit

##########################
# FS_COMMON Section
##########################


ifdef _WRS_CONFIG_FS_COMMON
VSBL_FS_COMMON_SRC = 
VSBL_FS_COMMON_DEPEND = 

ifdef _WRS_CONFIG_FS_1_0_0_2_CORE_1_0_0_2_COMMON_1_1_3_0
VSBL_FS_COMMON_SRC += FS_COMMON
VSBL_FS_COMMON_DEPEND += BDM_XBD
VSBL_FS_COMMON_DEPEND += ERF
VSBL_FS_COMMON_DEPEND += CORE_IO
VSBL_FS_COMMON_DEPEND += CORE_IO
FS_COMMON_FASTBUILD = YES
VSBL_FS_COMMON_PATH = $(WIND_BASE)/pkgs/storage/fs-1.0.0.2/core/common-1.1.3.0
VSBL_FS_COMMON_VERSION = FS_1_0_0_2_CORE_1_0_0_2_COMMON_1_1_3_0
endif
endif

