# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_LLVM_USER Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_LLVM_USER
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_USER_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_USER_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_LLVM_1_0_1_2_TOOLSRC_LLVM_USER_1_0_0_0
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_USER_SRC += LANG_LIB_TOOL_TOOLSRC_LLVM_USER
LANG_LIB_TOOL_TOOLSRC_LLVM_USER_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_USER_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_llvm-1.0.1.2/usr
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_USER_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_LLVM_1_0_1_2_TOOLSRC_LLVM_USER_1_0_0_0
endif
endif

