# Automatically generated file: do not edit

##########################
# LANG_LIB_LIBC_LIBC_BOOT Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_LIBC_LIBC_BOOT
VSBL_LANG_LIB_LIBC_LIBC_BOOT_SRC = 
VSBL_LANG_LIB_LIBC_LIBC_BOOT_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_LIBC_1_0_0_1_LIBC_BOOT_1_0_0_3
VSBL_LANG_LIB_LIBC_LIBC_BOOT_SRC += LANG_LIB_LIBC_LIBC_BOOT
LANG_LIB_LIBC_LIBC_BOOT_FASTBUILD = YES
VSBL_LANG_LIB_LIBC_LIBC_BOOT_PATH = $(WIND_BASE)/pkgs/os/lang-lib/libc-1.0.0.1/libc-boot-1.0.0.3
VSBL_LANG_LIB_LIBC_LIBC_BOOT_VERSION = LANG_LIB_LIBC_1_0_0_1_LIBC_BOOT_1_0_0_3
endif
endif

