# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_ICC_20_0_0_5_TOOLSRC_ICC_KERNEL_20_0_0_3
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL_SRC += LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL
LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_icc-20.0.0.5/kernel
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_ICC_20_0_0_5_TOOLSRC_ICC_KERNEL_20_0_0_3
endif
endif

