# Automatically generated file: do not edit

##########################
# EVDEV_VXSIM_PTR Section
##########################


ifdef _WRS_CONFIG_EVDEV_VXSIM_PTR
VSBL_EVDEV_VXSIM_PTR_SRC = 
VSBL_EVDEV_VXSIM_PTR_DEPEND = 

ifdef _WRS_CONFIG_EVDEV_1_0_0_3_DRV_1_0_0_1_VXSIM_PTR_1_0_1_1
VSBL_EVDEV_VXSIM_PTR_SRC += EVDEV_VXSIM_PTR
VSBL_EVDEV_VXSIM_PTR_DEPEND += FBDEV_VXSIMFB
EVDEV_VXSIM_PTR_FASTBUILD = YES
VSBL_EVDEV_VXSIM_PTR_PATH = $(WIND_BASE)/pkgs/ui/evdev-1.0.0.3/drv/vxSimPtr-1.0.1.1
VSBL_EVDEV_VXSIM_PTR_VERSION = EVDEV_1_0_0_3_DRV_1_0_0_1_VXSIM_PTR_1_0_1_1
endif
endif

