# Automatically generated file: do not edit

##########################
# RASTER_MESA_DEMOS Section
##########################


ifdef _WRS_CONFIG_RASTER_MESA_DEMOS
VSBL_RASTER_MESA_DEMOS_SRC = 
VSBL_RASTER_MESA_DEMOS_DEPEND = 

ifdef _WRS_CONFIG_RASTER_1_0_0_2_MESA_DEMOS_1_0_4_1
VSBL_RASTER_MESA_DEMOS_SRC += RASTER_MESA_DEMOS
VSBL_RASTER_MESA_DEMOS_DEPEND += RASTER_MESA
RASTER_MESA_DEMOS_FASTBUILD = YES
VSBL_RASTER_MESA_DEMOS_PATH = $(WIND_BASE)/pkgs/ui/raster-1.0.0.2/mesa_demos-1.0.4.1
VSBL_RASTER_MESA_DEMOS_VERSION = RASTER_1_0_0_2_MESA_DEMOS_1_0_4_1
endif
endif

