# Automatically generated file: do not edit

##########################
# IPNET_STREAM Section
##########################


ifdef _WRS_CONFIG_IPNET_STREAM
VSBL_IPNET_STREAM_SRC = 
VSBL_IPNET_STREAM_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_TSN_1_0_3_0_STREAM_1_0_2_0
VSBL_IPNET_STREAM_SRC += IPNET_STREAM
VSBL_IPNET_STREAM_DEPEND += END_LIB
VSBL_IPNET_STREAM_DEPEND += END
VSBL_IPNET_STREAM_DEPEND += IPNET_COREIP
VSBL_IPNET_STREAM_DEPEND += SOCKET
VSBL_IPNET_STREAM_DEPEND += NET_BASE
IPNET_STREAM_FASTBUILD = YES
VSBL_IPNET_STREAM_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/tsn-1.0.3.0/stream
VSBL_IPNET_STREAM_VERSION = IPNET_1_1_1_2_TSN_1_0_3_0_STREAM_1_0_2_0
endif
endif

