# Automatically generated file: do not edit

##########################
# END_DRV Section
##########################


ifdef _WRS_CONFIG_END_DRV
VSBL_END_DRV_SRC = 
VSBL_END_DRV_DEPEND = 

ifdef _WRS_CONFIG_END_1_2_8_0_DRV_1_2_8_0
VSBL_END_DRV_SRC += END_DRV
VSBL_END_DRV_DEPEND += END_LIB
VSBL_END_DRV_DEPEND += VXBUS_BUSLIB
VSBL_END_DRV_DEPEND += CORE_KERNEL
VSBL_END_DRV_DEPEND += VXBUS_BUSLIB
VSBL_END_DRV_DEPEND += VXBUS_SUBSYSTEM
VSBL_END_DRV_DEPEND += VXBUS_CORE
VSBL_END_DRV_DEPEND += VXBUS_CORE
END_DRV_FASTBUILD = YES
VSBL_END_DRV_PATH = $(WIND_BASE)/pkgs/net/end-1.2.8.0/drv
VSBL_END_DRV_VERSION = END_1_2_8_0_DRV_1_2_8_0
endif
endif

