# Automatically generated file: do not edit

##########################
# PSL Section
##########################


ifdef _WRS_CONFIG_PSL
VSBL_PSL_SRC = 
VSBL_PSL_DEPEND = 

ifdef _WRS_CONFIG_FSL_IMX_1_3_3_1
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += FDT
VSBL_PSL_DEPEND += JOBQUEUE
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += VXBUS_SUBSYSTEM
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += VXBUS_CORE
VSBL_PSL_DEPEND += BOARDLIB
VSBL_PSL_DEPEND += ARM_KERNEL
ifdef _WRS_CONFIG_ARM_ARMV7A
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7A*
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7A
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7A*
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7M
VSBL_PSL_DEPEND += ARM_ARMV7M
endif
ifdef _WRS_CONFIG_ARM_ARMV7M*
VSBL_PSL_DEPEND += ARM_ARMV7M
endif
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/fsl_imx-1.3.3.1
VSBL_PSL_VERSION = FSL_IMX_1_3_3_1
endif

ifdef _WRS_CONFIG_FSL_KINETIS_1_0_4_0
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += FDT
VSBL_PSL_DEPEND += BOARDLIB
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += ARM_KERNEL
ifdef _WRS_CONFIG_ARM_ARMV7M
VSBL_PSL_DEPEND += ARM_ARMV7M
endif
ifdef _WRS_CONFIG_ARM_ARMV7M*
VSBL_PSL_DEPEND += ARM_ARMV7M
endif
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/fsl_kinetis-1.0.4.0
VSBL_PSL_VERSION = FSL_KINETIS_1_0_4_0
endif

ifdef _WRS_CONFIG_FSL_PQ2_1_0_1_4
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += FDT
VSBL_PSL_DEPEND += PPC
VSBL_PSL_DEPEND += VXBUS
VSBL_PSL_DEPEND += BOARDLIB
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/fsl_pq2-1.0.1.4
VSBL_PSL_VERSION = FSL_PQ2_1_0_1_4
endif

ifdef _WRS_CONFIG_FSL_QORIQ_1_2_0_2
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += CORE_KERNEL
ifdef _WRS_CONFIG_ARM
VSBL_PSL_DEPEND += ARM
endif
ifdef _WRS_CONFIG_ARM_KERNEL
VSBL_PSL_DEPEND += ARM_KERNEL
endif
ifndef _WRS_CONFIG_PPC_BASE
VSBL_PSL_DEPEND += PPC_BASE
endif
ifdef _WRS_CONFIG_ARM_ARMV7A
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7A*
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
VSBL_PSL_DEPEND += FDT
VSBL_PSL_DEPEND += FDT
VSBL_PSL_DEPEND += BOARDLIB
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += VXBUS_CORE
VSBL_PSL_DEPEND += VXBUS_SUBSYSTEM
ifdef _WRS_CONFIG_END
VSBL_PSL_DEPEND += END
endif
ifdef _WRS_CONFIG_END*
VSBL_PSL_DEPEND += END
endif
VSBL_PSL_DEPEND += VXBUS_CORE
VSBL_PSL_DEPEND += VXBUS_BUSLIB
ifdef _WRS_CONFIG_PPC_E500
VSBL_PSL_DEPEND += PPC_E500
endif
ifdef _WRS_CONFIG_PPC_E500*
VSBL_PSL_DEPEND += PPC_E500
endif
ifdef _WRS_CONFIG_FDT
VSBL_PSL_DEPEND += FDT
endif
ifdef _WRS_CONFIG_PPC_E500*
VSBL_PSL_DEPEND += FDT
endif
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/fsl_qoriq-1.2.0.2
VSBL_PSL_VERSION = FSL_QORIQ_1_2_0_2
endif

ifdef _WRS_CONFIG_FSL_VYBRID_1_0_3_1
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += FDT
VSBL_PSL_DEPEND += VXBUS
VSBL_PSL_DEPEND += BOARDLIB
VSBL_PSL_DEPEND += ARM_KERNEL
ifdef _WRS_CONFIG_ARM_ARMV7A
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7A*
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7M
VSBL_PSL_DEPEND += ARM_ARMV7M
endif
ifdef _WRS_CONFIG_ARM_ARMV7M*
VSBL_PSL_DEPEND += ARM_ARMV7M
endif
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/fsl_vybrid-1.0.3.1
VSBL_PSL_VERSION = FSL_VYBRID_1_0_3_1
endif

ifdef _WRS_CONFIG_INTEL_1_1_1_3
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += BOARDLIB
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += VXBUS_SUBSYSTEM
VSBL_PSL_DEPEND += VXBUS_SUBSYSTEM
VSBL_PSL_DEPEND += VXBUS_CORE
VSBL_PSL_DEPEND += VXBUS_SUBSYSTEM
VSBL_PSL_DEPEND += CORE_IO
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/intel-1.1.1.3
VSBL_PSL_VERSION = INTEL_1_1_1_3
endif

ifdef _WRS_CONFIG_ITL_COMMON_1_0_5_1
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += VXBUS_CORE
VSBL_PSL_DEPEND += VXBUS_CORE
VSBL_PSL_DEPEND += VXBUS_SUBSYSTEM
VSBL_PSL_DEPEND += VXBUS_SUBSYSTEM
VSBL_PSL_DEPEND += VXBUS_SUBSYSTEM
VSBL_PSL_DEPEND += VXBUS_SUBSYSTEM
VSBL_PSL_DEPEND += BOARDLIB
VSBL_PSL_DEPEND += BOARDLIB
VSBL_PSL_DEPEND += IA
VSBL_PSL_DEPEND += IA_KERNEL
VSBL_PSL_DEPEND += IA_KERNEL
VSBL_PSL_DEPEND += IA_KERNEL
VSBL_PSL_DEPEND += IA_KERNEL
VSBL_PSL_DEPEND += IA_KERNEL
VSBL_PSL_DEPEND += CORE_IO
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += VXBUS_CORE
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/itl_core_psl/itl_common-1.0.5.1
VSBL_PSL_VERSION = ITL_COMMON_1_0_5_1
endif

ifdef _WRS_CONFIG_QSP_1_1_2_1
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += FDT
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += BOARDLIB
ifdef _WRS_CONFIG_ARM
VSBL_PSL_DEPEND += ARM
endif
ifdef _WRS_CONFIG_ARM*
VSBL_PSL_DEPEND += ARM
endif
ifdef _WRS_CONFIG_ARM_ARMV7A
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7A*
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV8A
VSBL_PSL_DEPEND += ARM_ARMV8A
endif
ifdef _WRS_CONFIG_ARM_ARMV8A*
VSBL_PSL_DEPEND += ARM_ARMV8A
endif
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/qsp-1.1.2.1
VSBL_PSL_VERSION = QSP_1_1_2_1
endif

ifdef _WRS_CONFIG_TI_AM3XXX_1_1_4_3_CTXA8_1_0_0_2
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += TI_AM3XXX
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/ti_am3xxx-1.1.4.3/sitara_ctxa8
VSBL_PSL_VERSION = TI_AM3XXX_1_1_4_3_CTXA8_1_0_0_2
endif

ifdef _WRS_CONFIG_TI_AM3XXX_1_1_4_3_CTXA9_1_0_0_3
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += TI_AM3XXX
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/ti_am3xxx-1.1.4.3/sitara_ctxa9
VSBL_PSL_VERSION = TI_AM3XXX_1_1_4_3_CTXA9_1_0_0_3
endif

ifdef _WRS_CONFIG_TI_KEYSTONE_1_1_3_1
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += FDT
VSBL_PSL_DEPEND += JOBQUEUE
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += VXBUS_CORE
VSBL_PSL_DEPEND += BOARDLIB
VSBL_PSL_DEPEND += ARM_KERNEL
ifdef _WRS_CONFIG_ARM_ARMV7A
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7A*
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/ti_keystone-1.1.3.1
VSBL_PSL_VERSION = TI_KEYSTONE_1_1_3_1
endif

ifdef _WRS_CONFIG_TI_SITARA_1_0_4_2
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += FDT
VSBL_PSL_DEPEND += VXBUS_SUBSYSTEM
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += BOARDLIB
VSBL_PSL_DEPEND += ARM_KERNEL
ifdef _WRS_CONFIG_ARM_ARMV7A
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7A*
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7M
VSBL_PSL_DEPEND += ARM_ARMV7M
endif
ifdef _WRS_CONFIG_ARM_ARMV7M*
VSBL_PSL_DEPEND += ARM_ARMV7M
endif
VSBL_PSL_DEPEND += VXBUS_BUSLIB
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/ti_sitara-1.0.4.2
VSBL_PSL_VERSION = TI_SITARA_1_0_4_2
endif

ifdef _WRS_CONFIG_XEN_1_0_0_1
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += FDT
VSBL_PSL_DEPEND += VXBUS_BUSLIB
ifdef _WRS_CONFIG_ARM_KERNEL
VSBL_PSL_DEPEND += ARM_KERNEL
endif
ifdef _WRS_CONFIG_ARM_KERNEL*
VSBL_PSL_DEPEND += ARM_KERNEL
endif
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/xen-1.0.0.1
VSBL_PSL_VERSION = XEN_1_0_0_1
endif

ifdef _WRS_CONFIG_XLNX_ZYNQ_1_1_7_0
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += FDT
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += VXBUS_CORE
VSBL_PSL_DEPEND += BOARDLIB
VSBL_PSL_DEPEND += ARM_KERNEL
ifdef _WRS_CONFIG_ARM_ARMV7A
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7A*
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV8A
VSBL_PSL_DEPEND += ARM_ARMV8A
endif
ifdef _WRS_CONFIG_ARM_ARMV8A*
VSBL_PSL_DEPEND += ARM_ARMV8A
endif
VSBL_PSL_DEPEND += VXBUS_BUSLIB
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/xlnx_zynq-1.1.7.0
VSBL_PSL_VERSION = XLNX_ZYNQ_1_1_7_0
endif

ifdef _WRS_CONFIG_ALT_SOC_1_0_4_2
VSBL_PSL_SRC += PSL
VSBL_PSL_DEPEND += CORE_KERNEL
VSBL_PSL_DEPEND += FDT
VSBL_PSL_DEPEND += BOARDLIB
VSBL_PSL_DEPEND += VXBUS_BUSLIB
VSBL_PSL_DEPEND += ARM_KERNEL
ifdef _WRS_CONFIG_ARM_ARMV7A
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
ifdef _WRS_CONFIG_ARM_ARMV7A*
VSBL_PSL_DEPEND += ARM_ARMV7A
endif
PSL_FASTBUILD = YES
VSBL_PSL_PATH = $(WIND_BASE)/pkgs/os/platform/alt_soc-1.0.4.2
VSBL_PSL_VERSION = ALT_SOC_1_0_4_2
endif
endif

