# Automatically generated file: do not edit

##########################
# LANG_LIB_CPLUS_CPLUS_KERNEL Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_CPLUS_CPLUS_KERNEL
VSBL_LANG_LIB_CPLUS_CPLUS_KERNEL_SRC = 
VSBL_LANG_LIB_CPLUS_CPLUS_KERNEL_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_CPLUS_1_0_0_1_CPLUS_KERNEL_1_0_0_6
VSBL_LANG_LIB_CPLUS_CPLUS_KERNEL_SRC += LANG_LIB_CPLUS_CPLUS_KERNEL
LANG_LIB_CPLUS_CPLUS_KERNEL_FASTBUILD = YES
VSBL_LANG_LIB_CPLUS_CPLUS_KERNEL_PATH = $(WIND_BASE)/pkgs/os/lang-lib/cplus-1.0.0.1/cplus-kernel-1.0.0.6
VSBL_LANG_LIB_CPLUS_CPLUS_KERNEL_VERSION = LANG_LIB_CPLUS_1_0_0_1_CPLUS_KERNEL_1_0_0_6
endif
endif

