# Automatically generated file: do not edit

##########################
# WEBCLI_MIBWAY Section
##########################


ifdef _WRS_CONFIG_WEBCLI_MIBWAY
VSBL_WEBCLI_MIBWAY_SRC = 
VSBL_WEBCLI_MIBWAY_DEPEND = 

ifdef _WRS_CONFIG_WEBCLI_1_0_0_3_MIBWAY_1_0_0_4
VSBL_WEBCLI_MIBWAY_SRC += WEBCLI_MIBWAY
VSBL_WEBCLI_MIBWAY_DEPEND += SNMP_ENGINE
VSBL_WEBCLI_MIBWAY_DEPEND += WEBCLI_COMMON
WEBCLI_MIBWAY_FASTBUILD = YES
VSBL_WEBCLI_MIBWAY_PATH = $(WIND_BASE)/pkgs/app/webcli-1.0.0.3/mibway-1.0.0.4
VSBL_WEBCLI_MIBWAY_VERSION = WEBCLI_1_0_0_3_MIBWAY_1_0_0_4
endif
endif

