# Automatically generated file: do not edit

##########################
# GPUDEV_LIBDRM Section
##########################


ifdef _WRS_CONFIG_GPUDEV_LIBDRM
VSBL_GPUDEV_LIBDRM_SRC = 
VSBL_GPUDEV_LIBDRM_DEPEND = 

ifdef _WRS_CONFIG_GPUDEV_1_0_0_2_LIBDRM_2_4_74_0
VSBL_GPUDEV_LIBDRM_SRC += GPUDEV_LIBDRM
VSBL_GPUDEV_LIBDRM_DEPEND += GPUDEV_COMMON
GPUDEV_LIBDRM_FASTBUILD = YES
VSBL_GPUDEV_LIBDRM_PATH = $(WIND_BASE)/pkgs/ui/gpudev-1.0.0.2/libdrm-2.4.74.0
VSBL_GPUDEV_LIBDRM_VERSION = GPUDEV_1_0_0_2_LIBDRM_2_4_74_0
endif
endif

