# Automatically generated file: do not edit

##########################
# AUDIO_FSL_SSI Section
##########################


ifdef _WRS_CONFIG_AUDIO_FSL_SSI
VSBL_AUDIO_FSL_SSI_SRC = 
VSBL_AUDIO_FSL_SSI_DEPEND = 

ifdef _WRS_CONFIG_AUDIO_1_0_0_2_DRV_1_0_0_1_FSL_SSI_1_0_1_3
VSBL_AUDIO_FSL_SSI_SRC += AUDIO_FSL_SSI
VSBL_AUDIO_FSL_SSI_DEPEND += FDT
VSBL_AUDIO_FSL_SSI_DEPEND += VXBUS_BUSLIB
VSBL_AUDIO_FSL_SSI_DEPEND += VXBUS_CORE
VSBL_AUDIO_FSL_SSI_DEPEND += VXBUS_SUBSYSTEM
AUDIO_FSL_SSI_FASTBUILD = YES
VSBL_AUDIO_FSL_SSI_PATH = $(WIND_BASE)/pkgs/ui/audio-1.0.0.2/drv/fslssi-1.0.1.3
VSBL_AUDIO_FSL_SSI_VERSION = AUDIO_1_0_0_2_DRV_1_0_0_1_FSL_SSI_1_0_1_3
endif
endif

