# Automatically generated file: do not edit

##########################
# BOARDLIB_VXTEST Section
##########################


ifdef _WRS_CONFIG_BOARDLIB_VXTEST
VSBL_BOARDLIB_VXTEST_SRC = 
VSBL_BOARDLIB_VXTEST_DEPEND = 

ifdef _WRS_CONFIG_BOARDLIB_1_1_1_3_VXTEST_1_0_1_0
VSBL_BOARDLIB_VXTEST_SRC += BOARDLIB_VXTEST
VSBL_BOARDLIB_VXTEST_DEPEND += CORE_KERNEL_VXTEST
BOARDLIB_VXTEST_FASTBUILD = YES
VSBL_BOARDLIB_VXTEST_PATH = $(WIND_BASE)/pkgs/os/utils/boardlib-1.1.1.3/vxTest
VSBL_BOARDLIB_VXTEST_VERSION = BOARDLIB_1_1_1_3_VXTEST_1_0_1_0
endif
endif

