# Automatically generated file: do not edit

##########################
# GPUDEV_LIBDRM_DEMOS Section
##########################


ifdef _WRS_CONFIG_GPUDEV_LIBDRM_DEMOS
VSBL_GPUDEV_LIBDRM_DEMOS_SRC = 
VSBL_GPUDEV_LIBDRM_DEMOS_DEPEND = 

ifdef _WRS_CONFIG_GPUDEV_1_0_0_2_LIBDRM_DEMOS_1_0_2_1
VSBL_GPUDEV_LIBDRM_DEMOS_SRC += GPUDEV_LIBDRM_DEMOS
VSBL_GPUDEV_LIBDRM_DEMOS_DEPEND += FBDEV_COMMON
VSBL_GPUDEV_LIBDRM_DEMOS_DEPEND += GPUDEV_LIBDRM
GPUDEV_LIBDRM_DEMOS_FASTBUILD = YES
VSBL_GPUDEV_LIBDRM_DEMOS_PATH = $(WIND_BASE)/pkgs/ui/gpudev-1.0.0.2/libdrm_demos-1.0.2.1
VSBL_GPUDEV_LIBDRM_DEMOS_VERSION = GPUDEV_1_0_0_2_LIBDRM_DEMOS_1_0_2_1
endif
endif

