# Automatically generated file: do not edit

##########################
# SYSTEMVIEWER Section
##########################


ifdef _WRS_CONFIG_SYSTEMVIEWER
VSBL_SYSTEMVIEWER_SRC = 
VSBL_SYSTEMVIEWER_DEPEND = 

ifdef _WRS_CONFIG_SYSTEMVIEWER_1_0_3_0
VSBL_SYSTEMVIEWER_SRC += SYSTEMVIEWER
VSBL_SYSTEMVIEWER_DEPEND += RBUFF
VSBL_SYSTEMVIEWER_DEPEND += CORE_KERNEL
SYSTEMVIEWER_FASTBUILD = YES
VSBL_SYSTEMVIEWER_PATH = $(WIND_BASE)/pkgs/os/debug/event-1.0.3.0
VSBL_SYSTEMVIEWER_VERSION = SYSTEMVIEWER_1_0_3_0
endif
endif

