# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_GNU_20_0_2_6_TOOLSRC_GNU_KERNEL_20_0_0_6
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL_SRC += LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL
LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_gnu-20.0.2.6/kernel
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_GNU_20_0_2_6_TOOLSRC_GNU_KERNEL_20_0_0_6
endif
endif

