# Automatically generated file: do not edit

##########################
# IPNET_WPS Section
##########################


ifdef _WRS_CONFIG_IPNET_WPS
VSBL_IPNET_WPS_SRC = 
VSBL_IPNET_WPS_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_MOBILITY_1_0_1_0_WPS_1_0_1_0
VSBL_IPNET_WPS_SRC += IPNET_WPS
VSBL_IPNET_WPS_DEPEND += IPNET_8021X
VSBL_IPNET_WPS_DEPEND += IPNET_COREIP
VSBL_IPNET_WPS_DEPEND += IPNET_EAP
VSBL_IPNET_WPS_DEPEND += IPNET_WLAN
IPNET_WPS_FASTBUILD = YES
VSBL_IPNET_WPS_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/mobility-1.0.1.0/wps
VSBL_IPNET_WPS_VERSION = IPNET_1_1_1_2_MOBILITY_1_0_1_0_WPS_1_0_1_0
endif
endif

