# Automatically generated file: do not edit

##########################
# OSTOOLS_VXTEST Section
##########################


ifdef _WRS_CONFIG_OSTOOLS_VXTEST
VSBL_OSTOOLS_VXTEST_SRC = 
VSBL_OSTOOLS_VXTEST_DEPEND = 

ifdef _WRS_CONFIG_OSTOOLS_1_0_3_1_VXTEST_1_0_0_1
VSBL_OSTOOLS_VXTEST_SRC += OSTOOLS_VXTEST
VSBL_OSTOOLS_VXTEST_DEPEND += CORE_KERNEL_VXTEST
OSTOOLS_VXTEST_FASTBUILD = YES
VSBL_OSTOOLS_VXTEST_PATH = $(WIND_BASE)/pkgs/os/utils/ostools-1.0.3.1/vxTest
VSBL_OSTOOLS_VXTEST_VERSION = OSTOOLS_1_0_3_1_VXTEST_1_0_0_1
endif
endif

