# Automatically generated file: do not edit

##########################
# FBDEV_TILCDCFB Section
##########################


ifdef _WRS_CONFIG_FBDEV_TILCDCFB
VSBL_FBDEV_TILCDCFB_SRC = 
VSBL_FBDEV_TILCDCFB_DEPEND = 

ifdef _WRS_CONFIG_FBDEV_1_0_0_2_TILCDCFB_1_0_4_0
VSBL_FBDEV_TILCDCFB_SRC += FBDEV_TILCDCFB
VSBL_FBDEV_TILCDCFB_DEPEND += FBDEV_COMMON
FBDEV_TILCDCFB_FASTBUILD = YES
VSBL_FBDEV_TILCDCFB_PATH = $(WIND_BASE)/pkgs/ui/fbdev-1.0.0.2/tilcdc-1.0.4.0
VSBL_FBDEV_TILCDCFB_VERSION = FBDEV_1_0_0_2_TILCDCFB_1_0_4_0
endif
endif

