# Automatically generated file: do not edit

##########################
# WEBCLI_WEBCLIDEMO Section
##########################


ifdef _WRS_CONFIG_WEBCLI_WEBCLIDEMO
VSBL_WEBCLI_WEBCLIDEMO_SRC = 
VSBL_WEBCLI_WEBCLIDEMO_DEPEND = 

ifdef _WRS_CONFIG_WEBCLI_1_0_0_3_WEBCLIDEMO_1_0_1_7
VSBL_WEBCLI_WEBCLIDEMO_SRC += WEBCLI_WEBCLIDEMO
VSBL_WEBCLI_WEBCLIDEMO_DEPEND += FS_DOSFS
VSBL_WEBCLI_WEBCLIDEMO_DEPEND += OPENSSL
VSBL_WEBCLI_WEBCLIDEMO_DEPEND += WEBCLI_BACKPLANE
VSBL_WEBCLI_WEBCLIDEMO_DEPEND += WEBCLI_MIBWAY
VSBL_WEBCLI_WEBCLIDEMO_DEPEND += WEBCLI_COMMON
VSBL_WEBCLI_WEBCLIDEMO_DEPEND += WEBCLI_HTTP
VSBL_WEBCLI_WEBCLIDEMO_DEPEND += WEBCLI_CLI
VSBL_WEBCLI_WEBCLIDEMO_DEPEND += OPENSSL
WEBCLI_WEBCLIDEMO_FASTBUILD = YES
VSBL_WEBCLI_WEBCLIDEMO_PATH = $(WIND_BASE)/pkgs/app/webcli-1.0.0.3/webclidemo-1.0.1.7
VSBL_WEBCLI_WEBCLIDEMO_VERSION = WEBCLI_1_0_0_3_WEBCLIDEMO_1_0_1_7
endif
endif

