# Automatically generated file: do not edit

##########################
# WEBCLI_WEBDEMO Section
##########################


ifdef _WRS_CONFIG_WEBCLI_WEBDEMO
VSBL_WEBCLI_WEBDEMO_SRC = 
VSBL_WEBCLI_WEBDEMO_DEPEND = 

ifdef _WRS_CONFIG_WEBCLI_1_0_0_3_WEBDEMO_1_0_1_10
VSBL_WEBCLI_WEBDEMO_SRC += WEBCLI_WEBDEMO
VSBL_WEBCLI_WEBDEMO_DEPEND += FS_DOSFS
VSBL_WEBCLI_WEBDEMO_DEPEND += WEBCLI_BACKPLANE
VSBL_WEBCLI_WEBDEMO_DEPEND += WEBCLI_CURL
VSBL_WEBCLI_WEBDEMO_DEPEND += WEBCLI_MIBWAY
VSBL_WEBCLI_WEBDEMO_DEPEND += WEBCLI_COMMON
VSBL_WEBCLI_WEBDEMO_DEPEND += WEBCLI_HTTP
VSBL_WEBCLI_WEBDEMO_DEPEND += OPENSSL
WEBCLI_WEBDEMO_FASTBUILD = YES
VSBL_WEBCLI_WEBDEMO_PATH = $(WIND_BASE)/pkgs/app/webcli-1.0.0.3/webdemo-1.0.1.10
VSBL_WEBCLI_WEBDEMO_VERSION = WEBCLI_1_0_0_3_WEBDEMO_1_0_1_10
endif
endif

