# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_GNU_USER Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_GNU_USER
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_USER_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_USER_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_GNU_20_0_2_6_TOOLSRC_GNU_USER_4_3_3_2
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_USER_SRC += LANG_LIB_TOOL_TOOLSRC_GNU_USER
LANG_LIB_TOOL_TOOLSRC_GNU_USER_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_USER_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_gnu-20.0.2.6/usr
VSBL_LANG_LIB_TOOL_TOOLSRC_GNU_USER_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_GNU_20_0_2_6_TOOLSRC_GNU_USER_4_3_3_2
endif
endif

