# Automatically generated file: do not edit

##########################
# FBDEV Section
##########################


ifdef _WRS_CONFIG_FBDEV
VSBL_FBDEV_SRC = 
VSBL_FBDEV_DEPEND = 

ifdef _WRS_CONFIG_FBDEV_1_0_0_2
ifdef _WRS_CONFIG_FBDEV_COMMON
VSBL_FBDEV_SRC += FBDEV_COMMON
endif
ifdef _WRS_CONFIG_FBDEV_DEMOS
VSBL_FBDEV_SRC += FBDEV_DEMOS
endif
ifdef _WRS_CONFIG_FBDEV_FSLDCUFB
VSBL_FBDEV_SRC += FBDEV_FSLDCUFB
endif
ifdef _WRS_CONFIG_FBDEV_FSLIPUFB
VSBL_FBDEV_SRC += FBDEV_FSLIPUFB
endif
ifdef _WRS_CONFIG_FBDEV_ITLGCFB
VSBL_FBDEV_SRC += FBDEV_ITLGCFB
endif
ifdef _WRS_CONFIG_FBDEV_ITLGMCFB
VSBL_FBDEV_SRC += FBDEV_ITLGMCFB
endif
ifdef _WRS_CONFIG_FBDEV_SAMPLEFB
VSBL_FBDEV_SRC += FBDEV_SAMPLEFB
endif
ifdef _WRS_CONFIG_FBDEV_TILCDCFB
VSBL_FBDEV_SRC += FBDEV_TILCDCFB
endif
ifdef _WRS_CONFIG_FBDEV_VXSIMFB
VSBL_FBDEV_SRC += FBDEV_VXSIMFB
endif
ifdef _WRS_CONFIG_FBDEV_XLNXLCVCFB
VSBL_FBDEV_SRC += FBDEV_XLNXLCVCFB
endif
VSBL_FBDEV_SRC += FBDEV
FBDEV_FASTBUILD = YES
VSBL_FBDEV_PATH = $(WIND_BASE)/pkgs/ui/fbdev-1.0.0.2
VSBL_FBDEV_VERSION = FBDEV_1_0_0_2
endif
endif

