# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_LLVM Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_LLVM
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_LLVM_1_0_1_2
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_SRC += LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_LLVM_USER
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_SRC += LANG_LIB_TOOL_TOOLSRC_LLVM_USER
endif
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_SRC += LANG_LIB_TOOL_TOOLSRC_LLVM
LANG_LIB_TOOL_TOOLSRC_LLVM_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_llvm-1.0.1.2
VSBL_LANG_LIB_TOOL_TOOLSRC_LLVM_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_LLVM_1_0_1_2
endif
endif

