# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL
VSBL_LANG_LIB_TOOL_SRC = 
VSBL_LANG_LIB_TOOL_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_COMMON
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_COMMON
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_COMMON_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_COMMON_USER
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_COMMON_USER
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_CERT
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_CERT
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_DIAB
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_DIAB
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_DIAB_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_DIAB_USER
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_DIAB_USER
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_GNU
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_GNU
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_GNU_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_GNU_USER
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_GNU_USER
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_ICC
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_ICC
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_ICC_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_ICC_USER
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_ICC_USER
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_LLVM
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_LLVM
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_LLVM_KERNEL
endif
ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_LLVM_USER
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL_TOOLSRC_LLVM_USER
endif
VSBL_LANG_LIB_TOOL_SRC += LANG_LIB_TOOL
LANG_LIB_TOOL_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3
VSBL_LANG_LIB_TOOL_VERSION = LANG_LIB_TOOL_1_0_0_3
endif
endif

