# Automatically generated file: do not edit

##########################
# TILCON_KERNEL Section
##########################


ifdef _WRS_CONFIG_TILCON_KERNEL
VSBL_TILCON_KERNEL_SRC = 
VSBL_TILCON_KERNEL_DEPEND = 

ifdef _WRS_CONFIG_TILCON_7_0_0_1_KERNEL_7_2_1_6
VSBL_TILCON_KERNEL_SRC += TILCON_KERNEL
VSBL_TILCON_KERNEL_DEPEND += EVDEV_LIB
VSBL_TILCON_KERNEL_DEPEND += FBDEV_COMMON
VSBL_TILCON_KERNEL_DEPEND += FONT_FREETYPE2
VSBL_TILCON_KERNEL_DEPEND += IMAGE_JPEG
VSBL_TILCON_KERNEL_DEPEND += IMAGE_PNG
VSBL_TILCON_KERNEL_DEPEND += KHRONOS
TILCON_KERNEL_FASTBUILD = YES
VSBL_TILCON_KERNEL_PATH = $(WIND_BASE)/pkgs/ui/tilcon-7.0.0.1/kernel-7.2.1.6
VSBL_TILCON_KERNEL_VERSION = TILCON_7_0_0_1_KERNEL_7_2_1_6
endif
endif

