# Automatically generated file: do not edit

##########################
# IPNET_WLANMLME Section
##########################


ifdef _WRS_CONFIG_IPNET_WLANMLME
VSBL_IPNET_WLANMLME_SRC = 
VSBL_IPNET_WLANMLME_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_MOBILITY_1_0_1_0_WLANMLME_1_0_1_0
VSBL_IPNET_WLANMLME_SRC += IPNET_WLANMLME
VSBL_IPNET_WLANMLME_DEPEND += END_LIB
VSBL_IPNET_WLANMLME_DEPEND += IPNET_COREIP
VSBL_IPNET_WLANMLME_DEPEND += VXBUS_LEGACY
IPNET_WLANMLME_FASTBUILD = YES
VSBL_IPNET_WLANMLME_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/mobility-1.0.1.0/wlanmlme
VSBL_IPNET_WLANMLME_VERSION = IPNET_1_1_1_2_MOBILITY_1_0_1_0_WLANMLME_1_0_1_0
endif
endif

