# Automatically generated file: do not edit

##########################
# ARM_ARMV7M Section
##########################


ifdef _WRS_CONFIG_ARM_ARMV7M
VSBL_ARM_ARMV7M_SRC = 
VSBL_ARM_ARMV7M_DEPEND = 

ifdef _WRS_CONFIG_ARM_1_1_10_2_KERNEL_1_0_13_2_ARMV7M_1_0_2_1
VSBL_ARM_ARMV7M_SRC += ARM_ARMV7M
VSBL_ARM_ARMV7M_DEPEND += CORE_KERNEL
VSBL_ARM_ARMV7M_DEPEND += CORE_KERNEL
VSBL_ARM_ARMV7M_DEPEND += ARM_ARMBASE
ARM_ARMV7M_FASTBUILD = YES
VSBL_ARM_ARMV7M_PATH = $(WIND_BASE)/pkgs/os/arch/arm-1.1.10.2/kernel/armv7m
VSBL_ARM_ARMV7M_VERSION = ARM_1_1_10_2_KERNEL_1_0_13_2_ARMV7M_1_0_2_1
endif
endif

