# Automatically generated file: do not edit

##########################
# IPNET_IKE Section
##########################


ifdef _WRS_CONFIG_IPNET_IKE
VSBL_IPNET_IKE_SRC = 
VSBL_IPNET_IKE_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_IPSECIKE_1_0_1_13_IKE_1_0_0_14
VSBL_IPNET_IKE_SRC += IPNET_IKE
VSBL_IPNET_IKE_DEPEND += IPNET_COREIP
VSBL_IPNET_IKE_DEPEND += OPENSSL
VSBL_IPNET_IKE_DEPEND += SEC_HASH
VSBL_IPNET_IKE_DEPEND += SEC_CRYPTO
IPNET_IKE_FASTBUILD = YES
IPNET_IKE_FRIEND = GDOI
VSBL_IPNET_IKE_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/ipsecike-1.0.1.13/ike
VSBL_IPNET_IKE_VERSION = IPNET_1_1_1_2_IPSECIKE_1_0_1_13_IKE_1_0_0_14
endif
endif

