# Automatically generated file: do not edit

##########################
# AUDIO_TI_MCASP Section
##########################


ifdef _WRS_CONFIG_AUDIO_TI_MCASP
VSBL_AUDIO_TI_MCASP_SRC = 
VSBL_AUDIO_TI_MCASP_DEPEND = 

ifdef _WRS_CONFIG_AUDIO_1_0_0_2_DRV_1_0_0_1_TI_MCASP_1_0_1_3
VSBL_AUDIO_TI_MCASP_SRC += AUDIO_TI_MCASP
VSBL_AUDIO_TI_MCASP_DEPEND += FDT
VSBL_AUDIO_TI_MCASP_DEPEND += VXBUS_BUSLIB
VSBL_AUDIO_TI_MCASP_DEPEND += VXBUS_CORE
VSBL_AUDIO_TI_MCASP_DEPEND += VXBUS_SUBSYSTEM
AUDIO_TI_MCASP_FASTBUILD = YES
VSBL_AUDIO_TI_MCASP_PATH = $(WIND_BASE)/pkgs/ui/audio-1.0.0.2/drv/timcasp-1.0.1.3
VSBL_AUDIO_TI_MCASP_VERSION = AUDIO_1_0_0_2_DRV_1_0_0_1_TI_MCASP_1_0_1_3
endif
endif

