# Automatically generated file: do not edit

##########################
# TIPC Section
##########################


ifdef _WRS_CONFIG_TIPC
VSBL_TIPC_SRC = 
VSBL_TIPC_DEPEND = 

ifdef _WRS_CONFIG_TIPC_1_0_0_1
ifdef _WRS_CONFIG_TIPC_TIPC_KERNEL_INVENTORYSIM_DEMO
VSBL_TIPC_SRC += TIPC_TIPC_KERNEL_INVENTORYSIM_DEMO
endif
ifdef _WRS_CONFIG_TIPC_TIPC_KERNEL_TESTSUIT_DEMO
VSBL_TIPC_SRC += TIPC_TIPC_KERNEL_TESTSUIT_DEMO
endif
ifdef _WRS_CONFIG_TIPC_TIPC_KERNEL
VSBL_TIPC_SRC += TIPC_TIPC_KERNEL
endif
ifdef _WRS_CONFIG_TIPC_TIPC_USER
VSBL_TIPC_SRC += TIPC_TIPC_USER
endif
VSBL_TIPC_SRC += TIPC
TIPC_FASTBUILD = YES
VSBL_TIPC_PATH = $(WIND_BASE)/pkgs/ipc/tipc-1.0.0.1
VSBL_TIPC_VERSION = TIPC_1_0_0_1
endif
endif

