# Automatically generated file: do not edit

##########################
# EVDEV_DRV Section
##########################


ifdef _WRS_CONFIG_EVDEV_DRV
VSBL_EVDEV_DRV_SRC = 
VSBL_EVDEV_DRV_DEPEND = 

ifdef _WRS_CONFIG_EVDEV_1_0_0_3_DRV_1_0_0_1
ifdef _WRS_CONFIG_EVDEV_EETI_EXC7200_TS
VSBL_EVDEV_DRV_SRC += EVDEV_EETI_EXC7200_TS
endif
ifdef _WRS_CONFIG_EVDEV_FSL_CRTOUCH_TS
VSBL_EVDEV_DRV_SRC += EVDEV_FSL_CRTOUCH_TS
endif
ifdef _WRS_CONFIG_EVDEV_FT_5X06_TS
VSBL_EVDEV_DRV_SRC += EVDEV_FT_5X06_TS
endif
ifdef _WRS_CONFIG_EVDEV_TI_AM335X_TS
VSBL_EVDEV_DRV_SRC += EVDEV_TI_AM335X_TS
endif
ifdef _WRS_CONFIG_EVDEV_TI_TSC2004_TS
VSBL_EVDEV_DRV_SRC += EVDEV_TI_TSC2004_TS
endif
ifdef _WRS_CONFIG_EVDEV_VIRTUAL_KBD
VSBL_EVDEV_DRV_SRC += EVDEV_VIRTUAL_KBD
endif
ifdef _WRS_CONFIG_EVDEV_VIRTUAL_PTR
VSBL_EVDEV_DRV_SRC += EVDEV_VIRTUAL_PTR
endif
ifdef _WRS_CONFIG_EVDEV_VXSIM_KBD
VSBL_EVDEV_DRV_SRC += EVDEV_VXSIM_KBD
endif
ifdef _WRS_CONFIG_EVDEV_VXSIM_PTR
VSBL_EVDEV_DRV_SRC += EVDEV_VXSIM_PTR
endif
VSBL_EVDEV_DRV_SRC += EVDEV_DRV
VSBL_EVDEV_DRV_DEPEND += EVDEV_LIB
EVDEV_DRV_FASTBUILD = YES
VSBL_EVDEV_DRV_PATH = $(WIND_BASE)/pkgs/ui/evdev-1.0.0.3/drv
VSBL_EVDEV_DRV_VERSION = EVDEV_1_0_0_3_DRV_1_0_0_1
endif
endif

