# Automatically generated file: do not edit

##########################
# GSOAP_CORE Section
##########################


ifdef _WRS_CONFIG_GSOAP_CORE
VSBL_GSOAP_CORE_SRC = 
VSBL_GSOAP_CORE_DEPEND = 

ifdef _WRS_CONFIG_GSOAP_2_8_15_1_CORE_2_8_15_6
VSBL_GSOAP_CORE_SRC += GSOAP_CORE
VSBL_GSOAP_CORE_DEPEND += IPNET_COREIP
VSBL_GSOAP_CORE_DEPEND += OPENSSL
VSBL_GSOAP_CORE_DEPEND += ZLIB
ifdef _WRS_CONFIG_SEC_CRYPTO
VSBL_GSOAP_CORE_DEPEND += SEC_CRYPTO
endif
ifdef _WRS_CONFIG_SEC_CRYPTO*
VSBL_GSOAP_CORE_DEPEND += SEC_CRYPTO
endif
GSOAP_CORE_FASTBUILD = YES
VSBL_GSOAP_CORE_PATH = $(WIND_BASE)/pkgs/app/gsoap-2.8.15.1/core-2.8.15.6
VSBL_GSOAP_CORE_VERSION = GSOAP_2_8_15_1_CORE_2_8_15_6
endif
endif

