# Automatically generated file: do not edit

##########################
# STOP_MODE_DEBUG_AGENT Section
##########################


ifdef _WRS_CONFIG_STOP_MODE_DEBUG_AGENT
VSBL_STOP_MODE_DEBUG_AGENT_SRC = 
VSBL_STOP_MODE_DEBUG_AGENT_DEPEND = 

ifdef _WRS_CONFIG_STOP_MODE_DEBUG_AGENT_2_0_4_4
VSBL_STOP_MODE_DEBUG_AGENT_SRC += STOP_MODE_DEBUG_AGENT
VSBL_STOP_MODE_DEBUG_AGENT_DEPEND += VXDBG
VSBL_STOP_MODE_DEBUG_AGENT_DEPEND += CORE_KERNEL
ifdef _WRS_CONFIG_LOADER
VSBL_STOP_MODE_DEBUG_AGENT_DEPEND += LOADER
endif
ifdef _WRS_CONFIG_LOADER*
VSBL_STOP_MODE_DEBUG_AGENT_DEPEND += LOADER
endif
ifdef _WRS_CONFIG_CORE_RTP
VSBL_STOP_MODE_DEBUG_AGENT_DEPEND += CORE_RTP
endif
ifdef _WRS_CONFIG_CORE_RTP*
VSBL_STOP_MODE_DEBUG_AGENT_DEPEND += CORE_RTP
endif
VSBL_STOP_MODE_DEBUG_AGENT_DEPEND += CORE_KERNEL
ifdef _WRS_CONFIG_ARM_ARMV7M
VSBL_STOP_MODE_DEBUG_AGENT_DEPEND += ARM_ARMV7M
endif
ifdef _WRS_CONFIG_CPU_ARMARCH7M*
VSBL_STOP_MODE_DEBUG_AGENT_DEPEND += ARM_ARMV7M
endif
STOP_MODE_DEBUG_AGENT_FASTBUILD = YES
VSBL_STOP_MODE_DEBUG_AGENT_PATH = $(WIND_BASE)/pkgs/rttools/stopmode-2.0.4.4
VSBL_STOP_MODE_DEBUG_AGENT_VERSION = STOP_MODE_DEBUG_AGENT_2_0_4_4
endif
endif

