# Automatically generated file: do not edit

##########################
# RASTER_SDL_DEMOS Section
##########################


ifdef _WRS_CONFIG_RASTER_SDL_DEMOS
VSBL_RASTER_SDL_DEMOS_SRC = 
VSBL_RASTER_SDL_DEMOS_DEPEND = 

ifdef _WRS_CONFIG_RASTER_1_0_0_2_SDL_DEMOS_1_0_1_0
VSBL_RASTER_SDL_DEMOS_SRC += RASTER_SDL_DEMOS
VSBL_RASTER_SDL_DEMOS_DEPEND += RASTER_SDL
RASTER_SDL_DEMOS_FASTBUILD = YES
VSBL_RASTER_SDL_DEMOS_PATH = $(WIND_BASE)/pkgs/ui/raster-1.0.0.2/sdl_demos-1.0.1.0
VSBL_RASTER_SDL_DEMOS_VERSION = RASTER_1_0_0_2_SDL_DEMOS_1_0_1_0
endif
endif

