# Automatically generated file: do not edit

##########################
# USB_TOUCHSCREEN Section
##########################


ifdef _WRS_CONFIG_USB_TOUCHSCREEN
VSBL_USB_TOUCHSCREEN_SRC = 
VSBL_USB_TOUCHSCREEN_DEPEND = 

ifdef _WRS_CONFIG_USB_1_1_0_6_HOST_1_0_0_4_CLASS_1_0_0_3_TOUCHSCREEN_1_0_0_4
VSBL_USB_TOUCHSCREEN_SRC += USB_TOUCHSCREEN
VSBL_USB_TOUCHSCREEN_DEPEND += EVDEV_LIB
VSBL_USB_TOUCHSCREEN_DEPEND += USB_HID
USB_TOUCHSCREEN_FASTBUILD = YES
VSBL_USB_TOUCHSCREEN_PATH = $(WIND_BASE)/pkgs/connectivity/usb-1.1.0.6/host/class/touchscreen-1.0.0.4
VSBL_USB_TOUCHSCREEN_VERSION = USB_1_1_0_6_HOST_1_0_0_4_CLASS_1_0_0_3_TOUCHSCREEN_1_0_0_4
endif
endif

