# Automatically generated file: do not edit

##########################
# LANG_LIB_CPLUS_CPLUS_USER Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_CPLUS_CPLUS_USER
VSBL_LANG_LIB_CPLUS_CPLUS_USER_SRC = 
VSBL_LANG_LIB_CPLUS_CPLUS_USER_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_CPLUS_1_0_0_1_CPLUS_USER_1_0_3_6
VSBL_LANG_LIB_CPLUS_CPLUS_USER_SRC += LANG_LIB_CPLUS_CPLUS_USER
LANG_LIB_CPLUS_CPLUS_USER_FASTBUILD = YES
VSBL_LANG_LIB_CPLUS_CPLUS_USER_PATH = $(WIND_BASE)/pkgs/os/lang-lib/cplus-1.0.0.1/cplus-usr-1.0.3.6
VSBL_LANG_LIB_CPLUS_CPLUS_USER_VERSION = LANG_LIB_CPLUS_1_0_0_1_CPLUS_USER_1_0_3_6
endif
endif

