# Automatically generated file: do not edit

##########################
# IPNET_RADIUS Section
##########################


ifdef _WRS_CONFIG_IPNET_RADIUS
VSBL_IPNET_RADIUS_SRC = 
VSBL_IPNET_RADIUS_DEPEND = 

ifdef _WRS_CONFIG_IPNET_1_1_1_2_AAA_1_0_1_10_RADIUS_1_0_0_6
VSBL_IPNET_RADIUS_SRC += IPNET_RADIUS
VSBL_IPNET_RADIUS_DEPEND += IPNET_COREIP
VSBL_IPNET_RADIUS_DEPEND += SEC_HASH
IPNET_RADIUS_FASTBUILD = YES
VSBL_IPNET_RADIUS_PATH = $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/aaa-1.0.1.10/radius
VSBL_IPNET_RADIUS_VERSION = IPNET_1_1_1_2_AAA_1_0_1_10_RADIUS_1_0_0_6
endif
endif

