# Automatically generated file: do not edit

##########################
# WEBCLI_CLIDEMO Section
##########################


ifdef _WRS_CONFIG_WEBCLI_CLIDEMO
VSBL_WEBCLI_CLIDEMO_SRC = 
VSBL_WEBCLI_CLIDEMO_DEPEND = 

ifdef _WRS_CONFIG_WEBCLI_1_0_0_3_CLIDEMO_1_0_1_4
VSBL_WEBCLI_CLIDEMO_SRC += WEBCLI_CLIDEMO
VSBL_WEBCLI_CLIDEMO_DEPEND += SHELL
VSBL_WEBCLI_CLIDEMO_DEPEND += WEBCLI_BACKPLANE
VSBL_WEBCLI_CLIDEMO_DEPEND += WEBCLI_MIBWAY
VSBL_WEBCLI_CLIDEMO_DEPEND += WEBCLI_COMMON
VSBL_WEBCLI_CLIDEMO_DEPEND += WEBCLI_CLI
WEBCLI_CLIDEMO_FASTBUILD = YES
VSBL_WEBCLI_CLIDEMO_PATH = $(WIND_BASE)/pkgs/app/webcli-1.0.0.3/clidemo-1.0.1.4
VSBL_WEBCLI_CLIDEMO_VERSION = WEBCLI_1_0_0_3_CLIDEMO_1_0_1_4
endif
endif

