# Automatically generated file: do not edit

##########################
# BOARDLIB Section
##########################


ifdef _WRS_CONFIG_BOARDLIB
VSBL_BOARDLIB_SRC = 
VSBL_BOARDLIB_DEPEND = 

ifdef _WRS_CONFIG_BOARDLIB_1_1_1_3
ifdef _WRS_CONFIG_BOARDLIB_VXTEST
VSBL_BOARDLIB_SRC += BOARDLIB_VXTEST
endif
VSBL_BOARDLIB_SRC += BOARDLIB
ifdef _WRS_CONFIG_PPC_KERNEL
VSBL_BOARDLIB_DEPEND += PPC_KERNEL
endif
ifdef _WRS_CONFIG_ARCH_ppc*
VSBL_BOARDLIB_DEPEND += PPC_KERNEL
endif
VSBL_BOARDLIB_DEPEND += CORE_KERNEL
ifdef _WRS_CONFIG_SHELL
VSBL_BOARDLIB_DEPEND += SHELL
endif
ifdef _WRS_CONFIG_SHELL*
VSBL_BOARDLIB_DEPEND += SHELL
endif
BOARDLIB_FASTBUILD = YES
VSBL_BOARDLIB_PATH = $(WIND_BASE)/pkgs/os/utils/boardlib-1.1.1.3
VSBL_BOARDLIB_VERSION = BOARDLIB_1_1_1_3
endif
endif

