# Automatically generated file: do not edit

##########################
# FBDEV_ITLGCFB Section
##########################


ifdef _WRS_CONFIG_FBDEV_ITLGCFB
VSBL_FBDEV_ITLGCFB_SRC = 
VSBL_FBDEV_ITLGCFB_DEPEND = 

ifdef _WRS_CONFIG_FBDEV_1_0_0_2_ITLGCFB_1_0_4_0
VSBL_FBDEV_ITLGCFB_SRC += FBDEV_ITLGCFB
VSBL_FBDEV_ITLGCFB_DEPEND += FBDEV_COMMON
FBDEV_ITLGCFB_FASTBUILD = YES
VSBL_FBDEV_ITLGCFB_PATH = $(WIND_BASE)/pkgs/ui/fbdev-1.0.0.2/itlgc-1.0.4.0
VSBL_FBDEV_ITLGCFB_VERSION = FBDEV_1_0_0_2_ITLGCFB_1_0_4_0
endif
endif

