# Automatically generated file: do not edit

##########################
# LANG_LIB_TOOL_TOOLSRC_ICC_USER Section
##########################


ifdef _WRS_CONFIG_LANG_LIB_TOOL_TOOLSRC_ICC_USER
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_USER_SRC = 
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_USER_DEPEND = 

ifdef _WRS_CONFIG_LANG_LIB_TOOL_1_0_0_3_TOOLSRC_ICC_20_0_0_5_TOOLSRC_ICC_USER_14_0_0_2
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_USER_SRC += LANG_LIB_TOOL_TOOLSRC_ICC_USER
LANG_LIB_TOOL_TOOLSRC_ICC_USER_FASTBUILD = YES
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_USER_PATH = $(WIND_BASE)/pkgs/os/lang-lib/tool-1.0.0.3/toolsrc_icc-20.0.0.5/usr
VSBL_LANG_LIB_TOOL_TOOLSRC_ICC_USER_VERSION = LANG_LIB_TOOL_1_0_0_3_TOOLSRC_ICC_20_0_0_5_TOOLSRC_ICC_USER_14_0_0_2
endif
endif

