# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_BDM_NFTL  {}
set _VSB_LAYER_CDFPATH_BDM_NFTL [concat  $_VSB_LAYER_CDFPATH_BDM_NFTL D:/vxWorks7/vxworks-7/pkgs/storage/bdm-1.0.1.3/flash/nftl-1.1.0.3/cdf]
