# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_PSL  {}
set _VSB_LAYER_CDFPATH_PSL [concat  $_VSB_LAYER_CDFPATH_PSL D:/vxWorks7/vxworks-7/pkgs/os/platform/fsl_qoriq-1.2.0.2/cdf]
