# this file is automatically generated by mk/krnl/rules.layers.mk
set _VSB_LAYER_CDFPATH_VIP_PROFILES  {}
set _VSB_LAYER_CDFPATH_VIP_PROFILES [concat  $_VSB_LAYER_CDFPATH_VIP_PROFILES D:/vxWorks7/vxworks-7/pkgs/vip_profiles/profiles]
