

/* this file is automatically generated */


Layer Layer::IPNET_PPP {
}




/*********************************
 Component INCLUDE_IPPPP 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Component	INCLUDE_IPPPP {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Component INCLUDE_IPPPPOE 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Component	INCLUDE_IPPPPOE {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Component INCLUDE_IPPPPMP 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Component	INCLUDE_IPPPPMP {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Component INCLUDE_IPPPP_VJCOMP 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Component	INCLUDE_IPPPP_VJCOMP {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Component INCLUDE_IPPPP_CMD 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Component	INCLUDE_IPPPP_CMD {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Component INCLUDE_IPPPP_INTERFACE_CONFIG 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Component	INCLUDE_IPPPP_INTERFACE_CONFIG {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Component INCLUDE_IPPPP_USERS_CONFIG 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Component	INCLUDE_IPPPP_USERS_CONFIG {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Folder FOLDER_NET_PPP 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Folder	FOLDER_NET_PPP {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Layer Layer::IPNET_PPP 
 original object sources located at 
 $(VSB_DIR) 
**********************************/
Layer	Layer::IPNET_PPP {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(VSB_DIR)}
}


/*********************************
 Parameter PPP_DEFAULT_BAUDRATE 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_DEFAULT_BAUDRATE {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_RUNMODE 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_RUNMODE {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_FLAGS 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_FLAGS {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_AUTH_MODES 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_AUTH_MODES {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_LCP_MRU 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_LCP_MRU {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_LCP_MTU 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_LCP_MTU {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_LCP_ECHO_REQ_INTERVAL 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_LCP_ECHO_REQ_INTERVAL {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_LCP_ECHO_REQ_FAILURE 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_LCP_ECHO_REQ_FAILURE {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IPCP_IPV4_ADDRESS 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IPCP_IPV4_ADDRESS {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IPCP_PEER_IPV4_ADDRESS 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IPCP_PEER_IPV4_ADDRESS {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IPCP_PEER_IPV4_POOL_NAME 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IPCP_PEER_IPV4_POOL_NAME {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IPCP_PEER_IPV4_ADDRESS_POOL 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IPCP_PEER_IPV4_ADDRESS_POOL {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_USERNAME 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_USERNAME {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_PASSWD 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_PASSWD {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IPCP_PRIMARY_DNS_ADDRESS 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IPCP_PRIMARY_DNS_ADDRESS {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IPCP_SECONDARY_DNS_ADDRESS 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IPCP_SECONDARY_DNS_ADDRESS {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IPCP_PRIMARY_NBNS_ADDRESS 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IPCP_PRIMARY_NBNS_ADDRESS {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IPCP_SECONDARY_NBNS_ADDRESS 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IPCP_SECONDARY_NBNS_ADDRESS {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_L2TP_LNS_ADDRESS_DEFAULT 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_L2TP_LNS_ADDRESS_DEFAULT {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_INSTALL_CALLBACK_HOOK 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_INSTALL_CALLBACK_HOOK {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_ACTION_CALLBACK_HOOK 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_ACTION_CALLBACK_HOOK {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_LCP_CLOSE_IF_NO_NCP_OPENED 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_LCP_CLOSE_IF_NO_NCP_OPENED {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_TASK_PRIORITY 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_TASK_PRIORITY {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_DEBUG_ENABLE 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_DEBUG_ENABLE {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_DEFAULT_BAUDRATE_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_DEFAULT_BAUDRATE_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_RUNMODE_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_RUNMODE_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_FLAGS_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_FLAGS_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_AUTH_MODES_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_AUTH_MODES_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_USERNAME 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_USERNAME {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_PASSWD 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_PASSWD {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_LCP_MRU_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_LCP_MRU_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_LCP_MTU_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_LCP_MTU_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_LCP_ECHO_REQ_INTERVAL_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_LCP_ECHO_REQ_INTERVAL_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_LCP_ECHO_REQ_FAILURE_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_LCP_ECHO_REQ_FAILURE_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_IPCP_IPV4_ADDRESS_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_IPCP_IPV4_ADDRESS_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_IPCP_PEER_IPV4_ADDRESS_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_IPCP_PEER_IPV4_ADDRESS_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_IPCP_PEER_IPV4_ADDRESS_POOL_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_IPCP_PEER_IPV4_ADDRESS_POOL_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_IPCP_PRIMARY_DNS_ADDRESS_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_IPCP_PRIMARY_DNS_ADDRESS_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_IF_IPCP_SECONDARY_DNS_ADDRESS_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_IF_IPCP_SECONDARY_DNS_ADDRESS_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_USERS_LCP_ECHO_REQ_INTERVAL_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_USERS_LCP_ECHO_REQ_INTERVAL_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_USERS_IPCP_IPV4_ADDRESS_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_USERS_IPCP_IPV4_ADDRESS_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_USERS_IPCP_PEER_IPV4_ADDRESS_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_USERS_IPCP_PEER_IPV4_ADDRESS_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_USERS_IPCP_PEER_IPV4_ADDRESS_POOL_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_USERS_IPCP_PEER_IPV4_ADDRESS_POOL_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_USERS_IPCP_PRIMARY_DNS_ADDRESS_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_USERS_IPCP_PRIMARY_DNS_ADDRESS_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPP_USERS_IPCP_SECONDARY_DNS_ADDRESS_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPP_USERS_IPCP_SECONDARY_DNS_ADDRESS_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPOE_SERVER 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPOE_SERVER {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPOE_SECRET_NAME 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPOE_SECRET_NAME {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPOE_MAX_SESSIONS 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPOE_MAX_SESSIONS {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPOE_MAX_ETH_SESSIONS 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPOE_MAX_ETH_SESSIONS {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPOE_AC_NAME 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPOE_AC_NAME {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPOE_SERVICE_NAME 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPOE_SERVICE_NAME {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPOE_IF_MAX_ETH_SESSIONS_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPOE_IF_MAX_ETH_SESSIONS_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPOE_IF_SERVICE_NAME_LIST 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPOE_IF_SERVICE_NAME_LIST {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPMP_ENABLE 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPMP_ENABLE {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPMP_MRRU 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPMP_MRRU {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPMP_SSN 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPMP_SSN {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPMP_FRAG_DISABLE 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPMP_FRAG_DISABLE {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPMP_PPPOE_LINKS 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPMP_PPPOE_LINKS {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Parameter PPPVJC_ENABLE 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Parameter	PPPVJC_ENABLE {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}


/*********************************
 Selection SELECT_IPPPP_OPTIONAL_CONFIG 
 original object sources located at 
 $(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf 
**********************************/
Selection	SELECT_IPPPP_OPTIONAL_CONFIG {
		LAYER += Layer::IPNET_PPP
		LAYER_SOURCE		{$(WIND_BASE)/pkgs/net/ipnet-1.1.1.2/linkproto/ppp-1.2.1.4/cdf/02comp_ipnet_ppp.cdf}
}
