/* Copyright (c) 2014-2016 Wind River Systems, Inc.
 *
 * The right to copy, distribute, modify or otherwise make use
 * of this software may be licensed only pursuant to the terms
 * of an applicable Wind River license agreement.
 */

/* This file has been autogenerated by cafe-type2h(1). */

#ifndef CAFE_TYPE2H_PERF_MEM_EVENTS_TYPE_autogenerated_h
#define CAFE_TYPE2H_PERF_MEM_EVENTS_TYPE_autogenerated_h

#include <cafe/autogenerated/cafe.type.h>

#ifdef __cplusplus
extern "C" {
#endif

#define category_perf_mem_metrics_VT_DEF "N[category.perf_mem_metrics,,n[cafe.METRIC_CATEGORY,\"perf_mem_metrics\",\"Memory Metrics (Perf)\"]]"
#define category_perf_mem_metrics_VT_REF "t[category.perf_mem_metrics]"
#define category_perf_mem_metrics_VT_NAT "n[category.perf_mem_metrics]"

#define perf_mem_heap_VT_DEF "S[perf_mem.heap,v[size,Q,n[cafe.SUM_METRIC_CLASS]n[category.perf_mem_metrics]n[cafe.LABEL,\"Heap Size\"]]]"
#define perf_mem_heap_VT_REF "t[perf_mem.heap]"

#define perf_mem_mmap_VT_DEF "S[perf_mem.mmap,v[size,Q,n[cafe.SUM_METRIC_CLASS]n[category.perf_mem_metrics]n[cafe.LABEL,\"MMap Size\"]]]"
#define perf_mem_mmap_VT_REF "t[perf_mem.mmap]"

#define PERF_MEM_EVENTS_TYPE_ALL_VT_DEFS \
	category_perf_mem_metrics_VT_DEF \
	perf_mem_heap_VT_DEF \
	perf_mem_mmap_VT_DEF \

struct perf_mem_heap {
	unsigned long long size;
};

struct perf_mem_mmap {
	unsigned long long size;
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
