 
/* this file is generated by defs.fastlibgen.mk __tmpl_layercd */

Layer Layer::STOP_MODE_DEBUG_AGENT {

LIBRARIES += libstopmode.a

OBJECTS libstopmode.a::smaArchLib.o libstopmode.a::smaArchLib.o libstopmode.a::smaLib.o libstopmode.a::smaProtocolLib.o libstopmode.a::smaSerialLib.o libstopmode.a::smaVmLib.o libstopmode.a::smaRtpLib.o libstopmode.a::smaMbufLib.o libstopmode.a::smaEndLib.o libstopmode.a::smaEndPktDrv.o libstopmode.a::smaUdpLib.o libstopmode.a::smaLib.o libstopmode.a::smaProtocolLib.o libstopmode.a::smaSerialLib.o libstopmode.a::smaVmLib.o libstopmode.a::smaRtpLib.o libstopmode.a::smaMbufLib.o libstopmode.a::smaEndLib.o libstopmode.a::smaEndPktDrv.o libstopmode.a::smaUdpLib.o

}


ObjectFile libstopmode.a::smaArchLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaArchLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaProtocolLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaSerialLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaVmLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaRtpLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaMbufLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaEndLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaEndPktDrv.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaUdpLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaProtocolLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaSerialLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaVmLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaRtpLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaMbufLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaEndLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaEndPktDrv.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}
 
ObjectFile libstopmode.a::smaUdpLib.o { 
	PATH krnl/PPCE6500/common/objstopmode/
}



