 
/* this file is generated by defs.fastlibgen.mk __tmpl_layercd */

Layer Layer::CORE_KERNEL {

LIBRARIES += libsplDbg.a

OBJECTS libsplDbg.a::kernelLockLib.o libsplDbg.a::spinLockIsrNdLib.o libsplDbg.a::spinLockSmpDbgLib.o

}


ObjectFile libsplDbg.a::kernelLockLib.o { 
	PATH krnl/PPCE6500/common/objsplDbg/
}
 
ObjectFile libsplDbg.a::spinLockIsrNdLib.o { 
	PATH krnl/PPCE6500/common/objsplDbg/
}
 
ObjectFile libsplDbg.a::spinLockSmpDbgLib.o { 
	PATH krnl/PPCE6500/common/objsplDbg/
}



